### ISSUE TITLE
Steng ned det gamle diff-store løpet

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-issue-tracker#1004]
Oppdatering av timeseries har allerede blitt fjerna fra [fdk-reports-bff](https://github.com/Informasjonsforvaltning/fdk-reports-bff/commit/492c8cd8dfb462aaa1f257e1eb87587015ca04dd)
Men løpet som bygger opp diff-store kjører fortsatt, uten at det brukes til noe. For å stenge ned:

- [x] Steng ned fdk-rdf-postman + arkiver [repoet](https://github.com/Informasjonsforvaltning/fdk-rdf-postman)
- [x] Steng ned alle variantene av diff-writer og query-cache + arkiver [rdf-diff-store](https://github.com/Informasjonsforvaltning/rdf-diff-store)
- [x] Steng ned gitea og fjern fra [fdk-infra](https://github.com/Informasjonsforvaltning/fdk-infra)
- [x] Undersøk om [rdf-prettifier](https://github.com/Informasjonsforvaltning/rdf-prettifier) brukes av andre deler av fdk, hvis ikke kan også den stenges ned + arkiveres

**Comment by valosnah** [comment]
Alt stengt ned og fjernet
