### ISSUE TITLE
BUG: knapp til registreringsløsning i demo lenker til portal

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#1008]
### Nåværende oppførsel
knapp til registreringsløsning i demo lenker til portal

![image](https://github.com/user-attachments/assets/9897a013-cacf-491c-b9fb-3f57c45a8424)

### Forventet oppførsel
Forventer at den lenker til innloggingssiden for registreringsløsning i demo. 

### Hvordan reprodusere?
Gå til https://demo.fellesdatakatalog.digdir.no/publishing
Velg Logg inn for å registrere

**Comment by jeffreiffers** [comment]
Feilen skyldes at vi mangler konfigurasjon i appen for at demo ikke bruker kustomize deployment. Endrer workflowen...
