### ISSUE TITLE
BUG: Kun en frarådet term og tillatt term vises i portalen selv om det er lagt til flere

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#1012]
### Nåværende oppførsel

Hvis man legger til flere frarådede termer og tillatte termer så vises kun en frarådet term og en tilltatt term på data.norge. På detaljesiden til begrepet i registreringsløsningen så vises alle de registrerte frarådede og tillatte termene. Og hvis det er lagt inn frarådet term/tillatt term på flere språk så vises det en term per språk, og det er de samme termene som vises selv om brukeren endrer språk i portalen.

Eks. - https://staging.fellesdatakatalog.digdir.no/concepts/b9e14ca3-7170-3f2b-a270-1cd02ef326e8
Fra reg.løsning:
![image](https://github.com/user-attachments/assets/97590a42-ecbf-4b1b-bb1d-f1b807d11169)
![image](https://github.com/user-attachments/assets/7bcd2484-be2a-45c4-b59b-805cc2c1319a)
![image](https://github.com/user-attachments/assets/816be260-a1b2-41ed-a6e0-3d509e0fbd49)

Fra portalen:
![image](https://github.com/user-attachments/assets/11881858-d2b7-4ae2-914e-9ba31e25d60a)
![image](https://github.com/user-attachments/assets/840190c0-6826-4803-a888-928875fadf38)
![image](https://github.com/user-attachments/assets/f4a2535a-333f-483f-8af5-e7c0f785e341)

### Forventet oppførsel

Alle frarådede og tillatte termer skal vises.
Frarådet og tillatt term skal vises for valgt språk i portalen.

**Comment by NilsOveTen** [comment]
Det ser ut til å være en feil som oppstår i rdf-parser, må fikse der og så la parser-service jobbe seg gjennom alle begrep etterpå

**Comment by NilsOveTen** [comment]
Koden antar at det bare er en variant per språk, når det er flere så overskriver den det den har lest inn fra før.

````
skos:hiddenLabel   "home"@en , "hjem"@nb , "swine path"@en , "krypinn"@nb , "tilfluktstad"@nn , "svinesti"@nb , "mancave"@en , "heim"@nn;
````

Av disse har det derfor blitt lagt til en tilfeldig av `home`, `swine path` og `mancave` for engelsk osv, uten noen garanti for at det som blir valgt for hvert språk er en oversettelse av hverandre.

Jeg fjerner alt av forsøk på å legge verdiene til som oversettelser av hverandre, siden det ikke er informasjon vi faktisk har. Usikker på hvordan det vil se ut i portal, men ser ikke noen annen mulighet med hvordan de er definert i skos-ap-no
