### ISSUE TITLE
BUG: Catalog-view-API'et henter ikke ut relasjoner til interne begrep

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#1018]
### Nåværende oppførsel

Catalog-view-API'et henter ikke ut relasjoner til interne begrep. Dette gjelder relasjonene:
- internSeOgså
- internBegrepsRelasjon
- InternErstattesAv

Eks. på interne relasjoner:
![image](https://github.com/user-attachments/assets/0041f2a8-deea-4f16-9886-8715906af8f1)

### Forventet oppførsel

At API'et henter relasjoner til interne begrep slik den den gjør for publiserte begrep.

### Hvordan reprodusere?

Test: https://catalog-view.api.staging.fellesdatakatalog.digdir.no/catalogs/991825827/concepts

Begrep «Anbefalt term 1» har relasjoner til publiserte begrep og begrep «Anbefalt term 2» har relasjoner til upublisert begrep.

**Comment by NilsOveTen** [comment]
@KurtStian Når vi lagrer interne relasjoner så lagrer vi id, ikke uri. Den blir transformert til uri ved produksjon av RDF.

Skal vi beholde kun id eller transformere til uri her i catalog-view-api?

**Comment by KurtStian** [comment]
@NilsOve Tenker at det kan være lurt å transfomere til URI-er slik at relasjonene blir likt behandlet/har lik oppbyggning uavhengig om de kun er til interne begrep eller til publiserte begrep. 
Er usikker på hvilken tjeneste som bør transformere til URI. Kan det være behov for URI-er på disse relasjonene andre steder enn i catalog-view-api?

**Comment by NilsOveTen** [comment]
Vi må skrive om en del logikk internt i concept-catalog om den skal bruke uri i stedet for id. Vi bør nok se nærmere på hvordan den håndterer alle relasjoner, kanskje redusere antall felt m.m.

Men bør vente med den type refaktorering til vi kun må forholde oss til 1 frontend
