### ISSUE TITLE
Informasjonsmodellelementer mangler begrepsreferanser i strukturvisning

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#102]
Kan ikke finne igjen noen begreper i strukturvisning. Denne modellen https://staging.fellesdatakatalog.digdir.no/informationmodels/60ecfff8-9ea3-41ee-92cc-7e791d73dac0 skal ha 20 begrep (dct:subject), f. eks Sivilstand

**Comment by azaxarov** [comment]
@shenluna @lillelars 
Fikset i https://github.com/Informasjonsforvaltning/fdk-portal/pull/676

**Comment by lillelars** [comment]
Denne er nå fikset og prodsatt. Testet i prod, i chrome. Lukker saken
