### ISSUE TITLE
FDK-metadata bør skjules fra rdf-visningene av informasjonsmodeller

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-issue-tracker#104]
- [x] Opprette endepunkt på høsteren som svarer med den høstede modellen, uten fdk-metadta
- [x] Oppdatere fdk-fulltext-search
- [x] Oppdatere fdk-harvest-bff

**Comment by lillelars** [comment]
.. og da vises ikke dette lenger heller. Lukker saken.
