### ISSUE TITLE
Bytte logo på altinn innlogging

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#106]
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/5b0667f3-dc07-47d1-89da-05cbe997cf09)

Link til logo: https://web.tresorit.com/l/VE3Vs#glUQIt5Pz5gOWZmeY40Nug&3CbmUZplwBliarino6VMmB2nkqhiWgUZ&Mqk5dNWe0CQrRJ4SfzV7y9IkiRs1F6LM&viewer=mPi6NzFWOLYjRqlEzE15NZ4aureIzKL2

**Comment by valosnah** [comment]
Bestilling sendt til servicedesk

**Comment by valosnah** [comment]
Mottatt melding om endring. Bekreftet på plass i staging og prod.

(tok litt tid før jeg fikk den opp i staging, så bare en brukket bildelenke. Vet ikke om det var cache-problematikk eller at servicedesk var litt raske med å fortelle meg at logoen var lagt inn)

**Comment by shenluna** [comment]
Verifisert i staging og prod.
