### ISSUE TITLE
Feil tall på rapportsiden - infomodeller

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#108]
Det vises feil tall (mye færre enn det faktisk er) for informasjonsmodeller på rapportsiden.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/b314b105-94a6-44b1-9a2b-a99cfb262398)

**Comment by shenluna** [comment]
Testet i staging og verifisert i prod
