### ISSUE TITLE
Spesialiserer (arv) ligger feil på infomodellen

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#110]
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/infomodel/detail-structure-default.html
(se struktur objekttype ->Leveranse)

Slik er det nå:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/4df88df1-9112-4882-bdd3-c619bfdc103a)

**Comment by shenluna** [comment]
Testet i staging (https://staging.fellesdatakatalog.digdir.no/informationmodels/60ecfff8-9ea3-41ee-92cc-7e791d73dac0)
![image](https://user-images.githubusercontent.com/73637969/102980738-4be0a300-4508-11eb-9b27-27789c62e127.png)
