### ISSUE TITLE
Implementere concepts for rot-nivå på informasjonsmodeller

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#112]

**Comment by lillelars** [comment]
@ToHelland får du testet denne? har vi et eksempel på dette?

**Comment by ToHelland** [comment]
@lillelars @shenluna Har et eksempel i staging: https://staging.fellesdatakatalog.digdir.no/informationmodels/90096759-a1e5-376a-a7e4-0e964266d3fc, er basert på følgende fil https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/SKDModellkatalog.ttl​​​​​​​.

**Comment by shenluna** [comment]
Testet og verifisert av Tore i staging
