### ISSUE TITLE
Metadata-kvalitet: 0 i Interoperabilitet sjølv om dcat:mediaType er oppgitt.

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#114]
Scorer 0 på Interoparbilitet sjølv om dcat:mediaType er fylt ut med gyldig iana type.
Eksempel: https://data.norge.no/organizations/971040238/datasets/ac43bcb0-1f19-4431-9473-edd775a0e450

Eksempel: https://data.norge.no/datasets/ac43bcb0-1f19-4431-9473-edd775a0e450
Turtle frå distribusjon
```
<https://kartkatalog.geonorge.no/Metadata/uuid/be676da7-4339-4f1c-8932-0fbb3cee9f2b/GML>
        a                dcat:Distribution ;
        dct:description  "Nedlastning gjennom Geonorge-portalen ved bruk av handlevognsfunksjonalitet" ;
        dct:format       "GML" ;
        dct:license      <https://creativecommons.org/licenses/by/4.0/> ;
        dct:title        "Geonorge nedlastning"@no ;
        adms:status      <http://purl.org/adms/status/onGoing> ;
        dcat:accessURL   <https://kartkatalog.geonorge.no/metadata/uuid/be676da7-4339-4f1c-8932-0fbb3cee9f2b> ;
        dcat:mediaType   <https://www.iana.org/assignments/media-types/application/gml+xml> .
```
Hypotese:
Dette kan skje fordi vi sjekker på `dct:format` (som forøvrig burde hatt range dct:MediaType), og at vi ikkje sjekker at distribusjon har `dcat:mediaType`.

Ref https://data.norge.no/specification/dcat-ap-no/#Distribusjon-format

**Comment by lillelars** [comment]
Denne fungerer i prod nå. Testet med kartverket sine datasett på metadatakvalitetssiden.
