### ISSUE TITLE
Performance forbedring av parsing

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#115]
iblioteket vi bruker for å gjøre mappingen til rdf tar nå 20 sekunder, økt med 10 siden støtte for model properties.

Bør oppdateres til:

- [ ] Kun 1 «stor» request per oppdatering, resten vil da hentes ut av cache og kjøretiden er da < 1 sekund

- [ ] Den store requesten er Redusert med 30%

**Comment by shenluna** [comment]
Lagt til caching, parsing går raskere enn tidligere
