### ISSUE TITLE
Felles modellkatalog - feil format på dct:subject

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#119]
I dag leses kun begrepsreferanser i FMK (dct:subject) med range anyURI. Dette var noe som ble benyttet tidligere, men i ModellDCAT-AP-NO er range klassen skos:Concept.

I fellesmodellene er verdiene til dct:subject på denne formen:
![image](https://user-images.githubusercontent.com/17720749/102355917-ceb7aa00-3fac-11eb-9f2f-c879946d015d.png)

Dette burde være:
dct:subject  <http://begrepskatalogen/begrep/88804c45-ff43-11e6-9d97-005056825ca0>, siden skos:Concept er en klasse.

Når jeg endrer dette i testmodellene og høster det til staging-miljøet, forsvinner imidlertid teksten som hentes fra begrepskatalogen. Dette må endres.

**Comment by NilsOveTen** [comment]
@ToHelland @lillelars 
Hvilken testmodell har blitt oppdatert? Vi har behov for et faktisk eksempel hvis vi skal se næremere på dette.

**Comment by ToHelland** [comment]
@NilsOveTen Denne filen inneholder noen dct:subject med riktig format , men de fleste som en anyURI, https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/model-catalogTestModellDCAT.ttl

**Comment by NilsOveTen** [comment]
@ToHelland Fungerer det om du endrer fra `modelldcatno:subject` til `dct:subject`?

**Comment by ToHelland** [comment]
Forhåpentligvis😁. Har tatt juleferie nå, så får ikke testet det nå.

________________________________
Fra: NilsOveTen <notifications@github.com>
Sendt: Monday, December 21, 2020 8:07:05 AM
Til: Informasjonsforvaltning/fdk-issue-tracker <fdk-issue-tracker@noreply.github.com>
Kopi: Helland, Tore <tore.helland@digdir.no>; Mention <mention@noreply.github.com>
Emne: Re: [Informasjonsforvaltning/fdk-issue-tracker] Felles modellkatalog - feil format på dct:subject (#119)


@ToHelland<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FToHelland&data=04%7C01%7C%7C1a6aeaed136d43c2406a08d8a57f0723%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637441312285608345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5kxXU4%2FzpnvSZZ3TW2tDjG1WfLe3Ofl4%2B9J1uxpIShA%3D&reserved=0> Fungerer det om du endrer fra modelldcatno:subject til dct:subject?

**Comment by lillelars** [comment]
@ToHelland Fikk du testet dette noengang?

**Comment by ToHelland** [comment]
Har nå endret fra modelldcatno:subject til dct:subject. Har testet, men det er kun begrepsreferanser på anyURI-format som vises.

**Comment by ToHelland** [comment]
Se https://staging.fellesdatakatalog.digdir.no/informationmodels/60ecfff8-9ea3-41ee-92cc-7e791d73dac0, her er noen  dct:subject med riktig format , mens noen med anyURI.

**Comment by lillelars** [comment]
Denne er nå testet og dette er godkjent av Tore. Lukker saken.
