### ISSUE TITLE
rss/atom skal fungere for nye datasett under "datasett"-fanen

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#12]
Hvis dette ikke fungerer må vi skrive om tjenestene :) 

knyttet til dataset-api og gammel ES.

- [ ] endre output fra fulltext-search for å støtte formater

- [ ] skriv om tjenesten til å hente data fra korrekt sted

**Comment by lillelars** [comment]
@azaxarov mangler selve ikonene for RSS/Atom før denne kan godkjennes.

**Comment by valosnah** [comment]
Har prodsatt riktig ruting i fdk-nginx-search

**Comment by shenluna** [comment]
Testet i staging og prod
