### ISSUE TITLE
format vises som full url i portal

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#120]
Formatene skal vises på MIME-type. Nå vises hele url'en

Mulig at denne er relatert til #117 

Etter at Kartverket har retta opp i dct:format på dct:Distribution slik at denne er i henhold til dcat-ap-no, vises format/mediatypes som fulle url, ref skjermdump:
![image](https://user-images.githubusercontent.com/1702357/102483075-81970f00-4064-11eb-80f4-7b11a94720a6.png)

Døme: https://data.norge.no/datasets/bc7b3a1a-20e3-4aaf-baef-02e095c45245

I rdf ser dømet slik ut:
```
<https://kartkatalog.geonorge.no/Metadata/uuid/036b361e-ffb1-45b5-8791-6ccd2065f3e8/GML>
        a                dcat:Distribution ;
        dct:description  "Nedlastning gjennom Geonorge-portalen ved bruk av handlevognsfunksjonalitet" ;
        dct:format       <https://www.iana.org/assignments/media-types/application/gml+xml> ;
        dct:license      <http://data.norge.no/nlod/no/1.0> ;
        dct:title        "Geonorge nedlastning"@no ;
        adms:status      <http://purl.org/adms/status/completed> ;
        dcat:accessURL   <https://kartkatalog.geonorge.no/metadata/uuid/036b361e-ffb1-45b5-8791-6ccd2065f3e8> .
```
Forventning er at mediatypen skal visast i "kortform": GML

**Comment by shenluna** [comment]
Testet i staging 
![image](https://user-images.githubusercontent.com/73637969/103546042-b4ce0080-4ea2-11eb-8800-adaf624cf12d.png)
