### ISSUE TITLE
Brukkede bilde-lenker i about-registration

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#123]
https://data.norge.no/publishing/about-registration

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/eec2f5fd-4521-4b12-9788-b95ba0b41be0)

**Comment by oyvindis** [comment]
Denne ser ut til å være løst.

**Comment by shenluna** [comment]
Ingen brukkede lenker lenger, lukker saken
