### ISSUE TITLE
Implementere et /endpoints-endpoint (DSOP)

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#13]
I dag er dette et filter for service type på datatjenester i gammel API-harvester.

- [ ] Koden kan (potensielt) brukes as-is, men må legges et annet sted.

- [ ] Fjerne referanser til utfasede tjenester (api/apis gjenstår, denne kan ikke fjernes før DSOP håndteres av noe annet enn api-harvester)

- [ ] kontrakttester

**Comment by shenluna** [comment]
Verifisert i staging, demo og prod
