### ISSUE TITLE
Legg til 'Brukt i informasjonsmodell'

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#130]
Behov: https://github.com/Informasjonsforvaltning/behov/issues/535

- [ ] "Utvide standarden" - med tenkt felt https://data.norge.no/specification/dcat-ap-no/#Datasett-iSamsvarMed
- [ ] Luna legger inn i endepunktet
- [ ] Utvikler henter fra endepunktet

**Comment by lillelars** [comment]
@stigbd hvordan gjør vi dette? Skal vi bare "utvide standarden" på egen hånd?

**Comment by stigbd** [comment]
Kvifor tenker de at vi må "utvide standarden". Range for dct:conformsTo er dct:Standard. En modelldcatno:InformationModel er sub-klasse av dct:Standard. Så dette er støtta rett ut av boksen.

Men mulig eg misforstår. Tittel på issue gir litt lite å gå på. Dette inngår kanskje i eit heilt anna epic?

**Comment by lillelars** [comment]
@stigbd Skjer detn oe mer her?

**Comment by stigbd** [comment]
Vi hadde eit møte på dette med Espen og Kurt Stian. Resulterte i enighet om intensjon og konsept, men det gjenstår litt eksplisitt spesifisering av korleis vi implementerer dette i modellane.

**Comment by shenluna** [comment]
Lukker denne saken da det per dags dato ikke er mulig med tanke på dagens spesifikasjon.
