### ISSUE TITLE
Oppdatere design

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#132]
- [ ] Kontaktpunkt (cv:hasContactPoint)
- [ ] Hjemmel (cv:hasLegalResource)
- [ ] Avgrensning (dct:spatial)
- [ ] Saksbehandlingsregler (cpsv:follows)
- [ ] Tjenestekanal (hasChannel)
- [ ] Behandlingstid (processingTime)
- [ ] Gebyr (hasCost)

**Comment by oyvindis** [comment]
Designoppgave for Lene, gjort.
