### ISSUE TITLE
Oppdatere design på detaljsiden

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#135]
- [ ] 'Begreper brukt i tjenester'

Se design her: https://www.figma.com/proto/N5yRmXN2WW6sv6J3ILiav7/Detail?node-id=294%3A0&viewport=-10772%2C57%2C0.924018383026123&scaling=min-zoom

**Comment by oyvindis** [comment]
Venter foreløpig oppdatert design av detaljside-template før denne kan påbegynnes, endring gjelder alle detaljsider.

**Comment by lillelars** [comment]
@oyvindis @shenluna venter vi fortsatt på design her? hva mangler?

**Comment by oyvindis** [comment]
@lillelars Jeg ser ikke at designet er endret siden sist, men jeg sjekker med Lene.

**Comment by shenluna** [comment]
Testet i staging
![image](https://user-images.githubusercontent.com/73637969/105705086-fb49d480-5f0f-11eb-9857-3920965b234a.png)
