### ISSUE TITLE
Oppfølging av dataservices som er lastet opp via fil - vises ikke i portal lenger

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#14]
Vi må følge opp hver enkelt virksomhet og høre om de har spesifikasjonsfilen i stedet.

https://teams.microsoft.com/l/file/7da0ab62-20f2-4331-9085-e2c53bdc884b?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=xlsx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FFDKUtviklingsteam%2FDelte%2520dokumenter%2FGeneral%2FListe%2520over%2520apier%2520opplastet%2520via%2520fil.xlsx&serviceName=recent

**Comment by joebrreg** [comment]
Jeg har tatt kontakt med virksomhetene det gjelder.
