### ISSUE TITLE
Begrep fra NAV mangler ansvarlig

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#145]
case: https://data.norge.no/concepts?orgPath=MISSING

Alle begrepene til NAV ser bra ut med hensyn på publisher i NAV sitt endepunkt:
```
curl -H "Accept:text/turtle" https://data.nav.no/digdir-api/terms
```

**Comment by joachim-me** [comment]
Lukkes. Ikke lenger tilfelle.
