### ISSUE TITLE
Fikse "sist endret" tidspunkt i dataset-catalog

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#146]
Alle/tilnærmet alle datasett i registreringsløsningen viser "sist endret dato som 13.01, da ETL ble kjørt.
(Dette fordi ETL'en gjorde en liten oppdatering på datasettene)

Har de opprinnelige tidspunktene tilgjengelig i ETL-podden, ekstraherer disse og må kjøre en liten ETL via et midlertidig endepunkt

**Comment by valosnah** [comment]
ETL via midlertidig endepunkt utført. Nils Ove reverter endepunktet

**Comment by shenluna** [comment]
Testet i staging og demo.
