### ISSUE TITLE
[datatjenestekatalog] Import av api-spec seier "successfully imported", men ingen av feltene blir pre-utfylt

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#147]
Case:
> Vi har problemer med å få lastet opp API dokumentasjonen og knytte dette sammen med det nye datasettet vi har publisert om kompensasjonsordningen for næringslivet.
Utviklerne våre får beskjed om at alt er Successfully opplastet, men ingenting blir preutfylt i tjenesten. Lenken de prøver å legge inn er:
https://data.brreg.no/kompensasjonsordning/api/open-api/v3/docs

opnenAPI-spesifikasjonen er ikkje gyldig, for den manglar obligatorisk felt "info->version". Så det kan vere eit issue. I så fall bør vi ikkje melde `Successfully imported specification from https://data.brreg.no/kompensasjonsordning/api/open-api/v3/docs`

**Comment by shenluna** [comment]
Testet i staging, registrering gir nå feilmelding når den ikke klarer å importere.
