### ISSUE TITLE
[datasettkatalog] Feltet "Sist oppdatert" under "Opphav og ferskhet" lar seg ikkje slette

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#148]
Brønnøysundregistrene melder:
> På selve datasett registreringen ser vi at datoen "Sist oppdatert" under "Opphav og ferskhet" ikke lar seg slette…
Ref https://data.norge.no/datasets/7aa53892-ef52-33d5-8dd6-f46044be37db

Eg har tilsynelatande greidd å gjenskape denne i demo på følgande datasett:
https://registrering.demo.fellesdatakatalog.digdir.no/catalogs/910244132/datasets/79942913-d16b-4271-8d0a-c60a93445109

Eg sletter dato, og den er borte. Men når eg går inn på datasettet på nytt, er datoen stadig i feltet.

**Comment by shenluna** [comment]
Testet i staging
