### ISSUE TITLE
Implementere nytt design for admin-gui

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#152]
- [x] Vise orgName

- [x] Utvide auth m/ orgnavn? evnt kan vi samle orgnr og lage en request mot 

- [x] Legge til undertittel "datasettkatalog", "begrepskatalog", "informasjonsmodellkatalog" osv på de ulike datatypene

- [x] Gjøre om admin-siden til bokmål

- [x] Endre tekst "Data type" til "Content type" både i endepunktsboksen og popup-boksen

- [x] Filter for katalogtyper

- [x] Søk for organisasjon

- [x] hjørnene skal avrundes til 5px

Se design:
https://eggedosis.github.io/fdk-design/redirects/register/admin/start-default-desktop.html

**Comment by shenluna** [comment]
Testet i staging
