### ISSUE TITLE
schema objects modeller - mangler noen egenskaper

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#153]
- [x] Feil multiplisitet på noen egenskaper

- [x] Støtte for kombinering av schemas

- [x] Støtte for `description`

- [x] Støtte for codeList/ codeElements

- [ ] Refaktorering

- [ ] finskrive kode

- [ ] sjekke tester

**Comment by lillelars** [comment]
@matsjs hørte du snakket med Tore - så opprettet en issue på dette :) Forstod det slik at du har fått en liste fra Tore.

**Comment by shenluna** [comment]
Testes gjennom unit tester i backend, det er opprettet egne saker for frontend
