### ISSUE TITLE
fdk-x-harvester må sende melding når høsting av endpunkt feiler

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#154]
I dag må vi "manuelt" gå inn i gcp for undersøke resultatet av en høste-event. Dette er tungvindt og introduserer store forsinkelser når vi skal varsle endpunkts-eigar (virksomheten).

Vi må implementere løsning der melding blir sendt (feks til rabbitMQ kø) når høsting feiler. Så kan vi monitorere denne køen, og etter kvart etablere mekanismer for å automatisk håndtere disse meldingene.

**Comment by valosnah** [comment]
Så lenge feil logges noenlunde likt i alle høsterne, kan jeg sette opp en metric som lager en alert, som vi kan få i gcp_dev_alerts/gcp_prod_alerts

Får det nok også til om de ikke er helt uniforme

**Comment by stigbd** [comment]
> Så lenge feil logges noenlunde likt i alle høsterne, kan jeg sette opp en metric som lager en alert, som vi kan få i gcp_dev_alerts/gcp_prod_alerts

Det er et fint suplement til feature eg beskriver. Eg tenker at vi må gjere begge deler.

**Comment by KurtStian** [comment]
I tillegg må det i legges til opplysninger i administrasjonsløsningen for data-sources (https://admin.fellesdatakatalog.digdir.no/data-sources) som viser tidspunkt for når en datakilde sist ble høstet slik at katalogeieren selv kan sjekke når en høsting er foretatt. Det må også synliggjøres hvis en høsting har feilet med opplysninger om tidspunkt og tilgang til feillogg.

**Comment by joachim-me** [comment]
Lukkes. Det er mulig å se høstetidspunkt i admin-løsningen.
