### ISSUE TITLE
Datasett-detaljsiden får sporadisk "Something went wrong"-feil

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#157]
Av og til når man følger en direktelink til et datasett, får man opp "Something went wrong"
Dette kan gjenskapes på følgende måte: 

- Åpne et datasett
![image.png](https://images.zenhubusercontent.com/5da70fe359191331a197eae1/67fb74b5-3289-4a46-9b6a-001061dfc2cd)

- Refresh siden til du får feilen.
![image.png](https://images.zenhubusercontent.com/5da70fe359191331a197eae1/9ecd0348-12df-4440-8dca-a1c9c8d959c0)

Mistanken er at et asynkront kall i noen tilfeller blir ferdig før et annet, og ikke takler dette.

**Comment by valosnah** [comment]
Dette ser ikke ut til å være tilfellet for de andre datatypene.
Det kan være de ikke bruker aynkrone kall, eller at det er er mindre sannsynlig å trigge rekkefølgen som feiler.

**Comment by shenluna** [comment]
Testet i staging, klarer ikke lenger å reprodusere feilen

**Comment by stigbd** [comment]
Reprodusert i prod no ved å trykke på https://data.norge.no/datasets/b91b1e95-5a48-49e8-9411-0fc00a65142c:

![image](https://user-images.githubusercontent.com/1702357/107340120-a97f7d80-6abd-11eb-8b87-5fd7d2b1a2cb.png)

**Comment by azaxarov** [comment]
Portal har vel ikke blitt prodsatt?

**Comment by shenluna** [comment]
Prodsatt og verifisert :)
