### ISSUE TITLE
Lage DCAT-AP-NO 2 endepunkt for DSOP API'er

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#16]
- [x] Lage endepunktet

- [x] eksponere /endpoints ut til ny tjeneste

**Comment by NilsOveTen** [comment]
DSOP API'ene er tilgjengelige som DCAT-AP-NO 2 fra tjenesten `dataservice-publisher` og `/endpoints` er flyttet til `fdk-api-endpoints`
