### ISSUE TITLE
Tilpasse detaljesiden for hendelser

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#164]
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/scenario/detail-default-d.html

**Comment by shenluna** [comment]
Denne trenger å få mappet opp type med dct:type, hendelsestype med cv:BusinessEvent eller cv:LifeEvent, og relasjoner med dct:relation for å kunne vise disse delene i frontend.

![image](https://user-images.githubusercontent.com/73637969/107959737-10140800-6fa4-11eb-9999-8a899b155eef.png)

**Comment by shenluna** [comment]
Testet i stag
