### ISSUE TITLE
utvide admin api med filter for ulike endepunkter

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#168]
- [ ] UTFORSKE og ESTIMERE hvor lang tid denne oppgaven tar

- [ ] utvide api'et med en filtrering på api/datasett/informasjonsmodell og begreper i admin
- [ ] Vise en slik filtrering 

- [ ] Tester??

**Comment by jeffreiffers** [comment]
Saken lukkes. Filter har blitt implementert i frontend.
