### ISSUE TITLE
Datasettregistrering - blank registreringsside

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#169]
Feil i datasettkatalogregistrering Skatt. Jeg får gjenskapt feilen som superbruker:
"I datasettregisterløsningen så ser det ut til at jeg kommer greit inn på alle datasett bortsett fra ett. Det heter Restanser (https://registrering.fellesdatakatalog.digdir.no/catalogs/974761076/datasets/27b01149-aa7a-4948-ab11-46c89595cf96 ) Da er siden bare hvit og viser ingenting. Har fått andre også til å teste, så det er ikke bare hos meg. Hva kan det være?"

Hans Olavs undersøkelser:
Ser det samme med min superbruker.
Når det gjelder datasettet, ser jeg dette i konsollen:
https://fdk-project.slack.com/files/UP26H7VKM/F01M15YSBFF/image.png

Sjekket ut datasettet i mongodb.
Eneste jeg kan se annerledes fra et par andre tilfeldige datasett, er at dette ikke har "issued" og "modified"
Kan det være dette som gjør at det ikke kan vises av guiet?

**Comment by matsjs** [comment]
Kan testes med denne: https://registrering.staging.fellesdatakatalog.digdir.no/catalogs/974761076/datasets/27b01149-aa7a-4948-ab11-46c89595cf96

**Comment by shenluna** [comment]
Testet i staging med lenke oppgitt av Mats i kommentar over
