### ISSUE TITLE
Oppdatere kotlin-api til å bruke java15

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-issue-tracker#173]
Java15:
- [x] fdk-public-service-harvester
- [x] fdk-event-harvester
- [x] fdk-informationmodel-harvester
- [x] fdk-dataset-harvester
- [x] fdk-dataservice-harvester
- [x] fdk-concept-harvester
- [x] organization-catalogue
- [x] dataset-catalog
- [x] user-api
- [x] terms-and-conditions

**Comment by lillelars** [comment]
Ferdigstilt. Lukker saken.
