### ISSUE TITLE
Lenken "Last ned distribusjon" virker ikke på enkelte datasett

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#175]
Se f.eks. datasett:

- https://data.norge.no/datasets/d2379e8a-fc4c-4f8b-be73-dd1a5c580619
- https://data.norge.no/datasets/2cd616e2-4029-466a-a53b-6c7de0422512

Download-lenken til disse datasettene er registrert med http i stedet for https, og redirekt fungere ikke når man bruker lenken/knappen. Ved å høyreklikke og velge "åpne linken i en ny fane" så får man lastet ned distribusjonen da nettleser følger redirekt. Mange datasett kan ha denne feilen.

**Comment by stigbd** [comment]
Øystein skriver: http er ikkje lenger støtta. redirect til https fungerte fint heilt til chrome rulla ut ei oppdatering for nokre veker sidan
Her ville eg køyrt ein søk og erstattjobb i databasen for å spyle ut alle http://hotell* lenkjer og erstatte dei med https

**Comment by KurtStian** [comment]
@stigbd Hva er status på denne?

**Comment by valosnah** [comment]
Jeg ser det også brukes http på accessURL, license og conformsTo.
Skal vi gjøre noe med disse også, eller kun downloadUrl?

**Comment by KurtStian** [comment]
Jeg mener at alle http://hotell* lenker skal oppdaterers til https.

**Comment by valosnah** [comment]
ETL kjørt, klar til å verifiseres i prod etter høsting kl 12:05

**Comment by KurtStian** [comment]
Har testet i produksjon og alle lenkene som tidligere begynte med http://hotell*, begynner nå med https://hotell*.
