### ISSUE TITLE
Samle alle relasjoner "som peker på meg"

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#178]
Se design datasett:
https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-default.html

![image](https://user-images.githubusercontent.com/39513382/108345402-81d79600-71de-11eb-9041-a3b284bd008a.png)

- [x] Alle relasjoner i portal som peker på et datasett skal vises på datasettet og lenke til dataen som eier relasjonen

- [x] Alle relasjoner i portal som peker på en datatjeneste skal vises på datatjenesten og lenke til dataen som eier relasjonen

- [x] Alle relasjoner i portal som peker på et begrep skal vises på begrepet og lenke til dataen som eier relasjonen

- [x] Alle relasjoner i portal som peker på en informasjonsmodell skal vises på modellen og lenke til dataen som eier relasjonen

- [x] Alle relasjoner i portal som peker på en public service skal vises på tjenesten og lenke til dataen som eier relasjonen

- [x] Alle relasjoner i portal som peker på en hendelse skal vises på hendelsen og lenkes til dataen som eier relasjonen

- [ ] Legge til ekstra relasjonsinformasjon der dette finnes

- [ ] Fjerne dupliserte relasjonsfelt

**Comment by shenluna** [comment]
https://data.norge.no/public-services/31249174-df02-3746-9d61-59fc61b4c5f9
![image](https://user-images.githubusercontent.com/73637969/109934865-41dbdd00-7ccd-11eb-8817-f10b80789175.png)

https://www.demo.fellesdatakatalog.digdir.no/informationmodels/e25c93b4-e01d-3724-9301-72bd44b49cbc
![image](https://user-images.githubusercontent.com/73637969/109935004-6afc6d80-7ccd-11eb-8e34-fd5cf914d4d9.png)

**Comment by shenluna** [comment]
Testet og verifisert OK
