### ISSUE TITLE
Innhold blir avvist i felt «Lenke til databehandleravtale»

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#183]
1.	Innhold blir åpenbart men stille avvist i felt «Lenke til databehandleravtale»
a.	Enkle lenker aksepteres. For eksempel «https://elements.mattilsynet.no/elements/rm/MATTILSYNET_ELEMENTS/»
b.	Den virkelige lenken blir ikke lagret slik at feltet står åpent når man kommer tilbake til etter å ha vært ute av posten. For eksempel «https://elements.mattilsynet.no/elements/rm/MATTILSYNET_ELEMENTS/#nav=/cases/12942123/registryEntries/15709157/view/documents/17031214/preview
c.	Bruker har bekreftet feilen i posten bruker hos oss har meldt til meg. Jeg har bekreftet tilsvarende i andre poster. Posten er https://registrering-protokoll.fellesdatakatalog.digdir.no/985399077/records/e95245ac-17da-49e8-ac33-2ea8d358fae4     
d.	Bruker har bekreftet feilen i demo. 
e.	Bruker har forsøkt litt forskjellig og funnet mange eksempler på at feltet ikke blir laget.
f.	Bruker har funnet «unntak fra feilen» i registreringene sine da andre poster åpenbart har klart å lagre sin lenkeadresse i feltet: «https://elements.mattilsynet.no/elements/rm/MATTILSYNET_ELEMENTS#nav=/ephorte/-1013/-602/14949861/view/documents/15967532/preview» (https://registrering-protokoll.fellesdatakatalog.digdir.no/985399077/records/bda23ba4-10d0-462d-9fd7-f796b98dd475) og en annen oppføring har «https://elements.mattilsynet.no/elements/rm/MATTILSYNET_ELEMENTS#nav=/cases/13599887/registryEntries/14973134/view/documents» og noen andre har klart dette også.

**Comment by joebrreg** [comment]
@shenluna Kan du se på denne ?

**Comment by shenluna** [comment]
Fikset, og testet i staging
