### ISSUE TITLE
Hendelsestype vises som næring og innbygger

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#188]
Se design her: https://www.figma.com/proto/N5yRmXN2WW6sv6J3ILiav7/Detail?node-id=1241%3A12409&viewport=-1873%2C48%2C0.25&scaling=min-zoom 

Alle cv:LifeEvent skal vises som 'Innbygger' og alle cv:BusinessEvent skal vises som 'Næring'

**Comment by oyvindis** [comment]
Jeg misforstod kommentaren i issue #164 da, der var det angitt cv:BusinessEvent eller cv:LifeEvent. Men det går kjapt å lage en label for dette. @shenluna har du forslag hva tilsvarende labels blir på engelsk?

**Comment by shenluna** [comment]
Testet i staging

**Comment by shenluna** [comment]
Verifisert i prod
