### ISSUE TITLE
Bug i visning av formater på ikonene

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#190]
- [ ] Forslag til hva vi gjør med ikoner der vi har korrekt IANA type, men vi ikke har ikonet for det - felles ikon?
- [ ] Forslag til hva vi gjør med ikoner der vi IKKE har korrekt IANA type - vise ikon for N/A ?

- [ ] Visning av "generelt ukjent-ikon" når det finnes korrekt IANA type, men vi ikke har det ikonet
https://drive.google.com/file/d/1pKdLG0JLDI0GIUk8CaSlXupNbOXTB4Ml/view

- [ ] 

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/ea900275-da56-4d63-8645-c2371c312b48)

**Comment by jeffreiffers** [comment]
Forslag:

- Vi viser riktig ikon for alle IANA typer men også typer som XML,JSON,CSV, etc. siden disse typer er såpass standardisert
- Typer som ikke er IANA typer skal også vises riktig i sammendraget
- Distribusjoner som ikke er IANA typer skal vises med dårligere metadatakvalitet
