### ISSUE TITLE
Filter for format/mediatypes - distribusjoner til datasett

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#192]
Opprette et filter for formater / mediatype på distribusjoner til datasett.
Vise topp 5 (topp 10 etter ekspandering) 

- [ ] gruppering av lignende formater som: text/xml application/xml xml, json application/json osv
- [ ] utvide ES med grupperinger? utvide rdfParser med logikken her

**Comment by shenluna** [comment]
Testet OK i staging

**Comment by shenluna** [comment]
Verifisert i prod
