### ISSUE TITLE
Ikke mulig å trykke tilbake når man har fått feilmelding

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#196]
Når man har fått en feilmelding, feks something went wrong blir man ikke tatt tilbake når man trykker på 'tilbake'-knappen

![2021-03-01_10-43-08.gif](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/e0d310ea-0c30-4faa-927e-8db4ea3a9476)

**Comment by lillelars** [comment]
Ser ut til å ha forsvunnet etter tiltakene rundt "something went wrong" feilene. Lukker saken.
