### ISSUE TITLE
feil i datasettkatalog: får ikke vist datasettbeskrivelse i portal i produksjon

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#198]
Får ikke vist datasettbeskrivelse for Enhetsregisteret i produksjon (https://data.norge.no/datasets/68d08f28-a16d-4fab-a953-ed4ab08ce2e2 ) . Får feilmelding "Something went wrong":
![image](https://user-images.githubusercontent.com/32771488/109482770-b66d0c80-7a7e-11eb-85d6-3b2da7a58be1.png)

**Comment by lillelars** [comment]
Løst av fdk-metadata-quality-service#28

**Comment by RogerSOlsen** [comment]
@lillelars @shenluna : Feilen oppstår fortsatt etter at den ble lukket
