### ISSUE TITLE
Kommuner med nytt orgnr.

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#202]
Noen kommuner har etter 01.01.2020 fått nytt orgnr., vi ønsker å flytte datasett tilhørende disse kommunene til nytt orgnr. 

- [x] Ålesund kommune (942 953 119 til 920 415 288)
- [x] Molde kommune (944 020 977 til 921 221 967)
- [x] Sogndal kommune (936 401 651 til 922 121 893)

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/99367970-4bb8-48e2-96e1-d565cc7b16b9)

**Comment by valosnah** [comment]
Fjernet gammel katalog, og lagt inn datasettene på respektive nye.

**Comment by shenluna** [comment]
Verifisert i prod
