### ISSUE TITLE
feil: felt "Kilder til personopplysningene" og "System i virksomheten som behandler personopplysningene" utvider seg ikke når tekststreng blir for lang

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#204]
felt "Kilder til personopplysningene" og System i virksomheten som behandler personopplysningene" utvider seg ikke når tekststreng er lenger enn vinduet gir plass til:

![image](https://user-images.githubusercontent.com/32771488/109929677-076f4180-7cc7-11eb-8c53-8491f8db1a4e.png)

og System i virksomheten som behandler personopplysningene"
![image](https://user-images.githubusercontent.com/32771488/109930277-c3c90780-7cc7-11eb-9cab-c4599407e69d.png)

slik vi kan i feltet "Planlagte tidsfrister for sletting"
![image](https://user-images.githubusercontent.com/32771488/109929771-240b7980-7cc7-11eb-8f10-d2cbbeb2f2d4.png)

**Comment by shenluna** [comment]
Testet i staging og verifisert i demo
