### ISSUE TITLE
Seksjon for "andre som relaterer til meg" bør være lenger ned

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#205]
Denne seksjonen er minst viktig og bør ligge under de relasjonene som eies av datasettet/begrepet/datatjenesten bruker står på.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/c42d4317-1c79-4b0b-90fc-45fc732549a9)

**Comment by matsjs** [comment]
https://github.com/Informasjonsforvaltning/fdk-portal/pull/816

**Comment by shenluna** [comment]
Denne er nå helt i bunn, bør flyttes opp over 'Kontaktinformasjon'

**Comment by matsjs** [comment]
https://github.com/Informasjonsforvaltning/fdk-portal/pull/823

**Comment by shenluna** [comment]
Testet OK i staging
