### ISSUE TITLE
metadatakvalitet har forsvunnet?

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#206]
I prod:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/c3fa2edf-1e49-404d-bdbb-4341793a85b7)

**Comment by valosnah** [comment]
![image](https://user-images.githubusercontent.com/8625716/109936891-ab102000-7cce-11eb-9d3a-5f8a1a48b666.png)

**Comment by lillelars** [comment]
Lukker saken. Fungerer igjen.
