### ISSUE TITLE
Mulig å hente rdf uten fdk-metadata fra alle høsterene

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-issue-tracker#209]
- [x] fdk-public-service-harvester
- [x] fdk-event-harvester
- [x] fdk-informationmodel-harvester
- [x] fdk-dataset-harvester
- [x] fdk-dataservice-harvester
- [x] fdk-concept-harvester
- [x] fdk-fulltext-search
- [x] fdk-harvester-bff

**Comment by shenluna** [comment]
Testet OK
