### ISSUE TITLE
Kvalitetsfelter vises ikke lenger

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#213]
- [ ] Hypotese om at årsaken er at vi må fikse tripplene i registreringsløsningen

Kvalitetsfelter vises ikke lenger på detaljsidene til datasett. Datasettet Enhetsregisteret skal ha disse: https://data.norge.no/datasets/68d08f28-a16d-4fab-a953-ed4ab08ce2e2

Se design: https://www.figma.com/proto/N5yRmXN2WW6sv6J3ILiav7/Detail?node-id=1%3A561&viewport=399%2C203%2C0.5&scaling=min-zoom

![image](https://user-images.githubusercontent.com/39513382/111283607-983b0b00-863f-11eb-9aef-335f11aed232.png)

Det er disse feltene jeg savner:

<http://www.w3.org/ns/dqv#hasQualityAnnotation>
                [ a             <http://www.w3.org/ns/dqv#QualityAnnotation> ;
                  <http://www.w3.org/ns/dqv#inDimension>
                          <iso:Accuracy> ;
                  prov:hasBody  [ rdf:value  "Nøyaktigheten avhenger av at den enkelte virksomhet rapporterer endringer til Enhetsregisteret, jfr. https://lovdata.no/lov/1994-06-03-15/§15.   \n "@nb ]
                ] ;
        <http://www.w3.org/ns/dqv#hasQualityAnnotation>
                [ a             <http://www.w3.org/ns/dqv#QualityAnnotation> ;
                  <http://www.w3.org/ns/dqv#inDimension>
                          <iso:Completeness> ;
                  prov:hasBody  [] 
                ] ;
        <http://www.w3.org/ns/dqv#hasQualityAnnotation>
                [ a             <http://www.w3.org/ns/dqv#QualityAnnotation> ;
                  <http://www.w3.org/ns/dqv#inDimension>
                          <iso:Availability> ;
                  prov:hasBody  [ rdf:value  "Offentlige aktører og foretak som har konsesjon for å drive kredittopplysningsforetak har tilgang på fødselsnummer. Andre private aktører har bare tilgang til fødselsdato. "@nb ]
                ] ;
        <http://www.w3.org/ns/dqv#hasQualityAnnotation>
                [ a             <http://www.w3.org/ns/dqv#QualityAnnotation> ;
                  <http://www.w3.org/ns/dqv#inDimension>
                          <iso:Currentness> ;
                  prov:hasBody  [ rdf:value  "Antall ansatte oppdateres ca. den 10. hver måned. \nMVA oppdateres en gang i døgnet.\nDaglig oppdatering fra Folkeregisteret og Matrikkelen."@nb ]
                ] ;
        <http://www.w3.org/ns/dqv#hasQualityAnnotation>
                [ a             <http://www.w3.org/ns/dqv#QualityAnnotation> ;
                  <http://www.w3.org/ns/dqv#inDimension>
                          <iso:Relevance> ;
                  prov:hasBody  [ rdf:value  "- Velegnet for gjenbruk, pre-utfylling og kontroll av opplysninger.                                              \n\n- §22 i Lov om Enhetsregisteret; Sammenstilling av opplysninger om person kan bare gis når det gjelder personens registrerte tilknytning til næringsvirksomhet."@nb ]
                ] .

**Comment by shenluna** [comment]
Kvalitetsfeltene blir fremdeles ikke vist i frontend. Eks https://www.staging.fellesdatakatalog.digdir.no/datasets/07f83b95-92fe-31a1-84c8-225057a78f8a
![image](https://user-images.githubusercontent.com/73637969/111635059-65d40e00-87f7-11eb-9b00-ba241542719e.png)
