### ISSUE TITLE
Utvide feltet "Cost" for detaljeside på tjenester 

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#214]
Relatert til:
https://github.com/Informasjonsforvaltning/behov/issues/445

Se design: https://eggedosis.github.io/fdk-design/redirects/portal/service/detail-default.html

Se f.eks tjenesten: https://data.norge.no/public-services/6ce4e524-3226-3591-ad99-c026705d4259

Et Gebyr-felt "Cost" skal bestå av Valuta, verdi og en beskrivelse.

<http://public-service-publisher.fellesdatakatalog.digdir.no/cost/1> a cv:Cost ;
  dct:identifier "1" ;
  cv:value 5570 ;
  cv:currency <http://publications.europa.eu/resource/authority/currency/NOK> ;
  dct:description "Nyregistrering - Aksjeselskap, Allmennaksjeselskap, Boligbyggelag/borretslag, Kommandittselskap: elektronisk kr 5570,-" ;
  cv:isDefinedBy <http://public-service-publisher.fellesdatakatalog.digdir.no/public-organisation/1> ;
  cv:ifAccessedThrough <http://public-service-publisher.fellesdatakatalog.digdir.no/channel/1> ;

**Comment by shenluna** [comment]
Testet OK i staging
