### ISSUE TITLE
Validering fra admin

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#215]
Ved klikk på validering fra admin blir man sendt til validatoren, men katalogen blir ikke validert
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/22ab7aa8-1b5d-4b08-8ed2-b56c1435b0a4)

**Comment by lillelars** [comment]
Ferdig testet i prod. Lukker saken.
