### ISSUE TITLE
Feil redirect hvis feil oppstår i pålogging

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#216]
Hvis man timer ut, eller en annen ukjent feil oppstår ifbm pålogging, blir man omdirigert til den gamle brreg-url'en.
Usikkert om dette er feil i SSO, eller konfig i ID-porten.

Også usikker på om dette er et issue i prod, eller bare staging.

Feil har oppstått, og jeg trykker på "Tilbake-knappen"
![image.png](https://images.zenhubusercontent.com/5da70fe359191331a197eae1/4c2859cf-b280-4922-adc3-95cb37a05667)

![image.png](https://images.zenhubusercontent.com/5da70fe359191331a197eae1/f0a25b89-e006-4efd-88af-cf8c7d25154f)

**Comment by valosnah** [comment]
Kan fremprovoseres ved å la ID-porten påloggingen time ut mens den venter på input.
Bekreftet at feilen fortsatt eksisterer i staging, prod virker fint (og har sannsynligvis alltid gjort det).

Mail sendt til servicedesk ang oidc-klienten som brukes med idportens testmiljø ver2

**Comment by valosnah** [comment]
Fått tilbakemelding fra servicedesk, og url'en er nå fikset.

(Men burde kanskje denne URL'en vært til registreringsløsningen, ikke portalen?)

**Comment by shenluna** [comment]
Enig at det tilbake-knappen burde gå til registreringsløsningen, får du rettet opp? @valosnah

**Comment by valosnah** [comment]
Bestilt endring til /publishing , dette ble utført i morges og skal nå være klart.

**Comment by shenluna** [comment]
Testet og verifisert at tilbake-knappen går til registreringsløsningen, lukker dermed saken
