### ISSUE TITLE
Berike trippler som beskriver registrert organisasjon

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#217]
@lillelars commented on [Fri Mar 12 2021](https://github.com/Informasjonsforvaltning/fdk-organization-bff/issues/44)

For alle dct:publisher legg til trippler som beskriver registrert organisasjon (rov:RegisteredOrganization) inn i SPARQL service sin tripple store

Prioritere virksomhetssiden datasett

**Comment by NilsOveTen** [comment]
Verifisert i prod
