### ISSUE TITLE
Støtte for markdown i portal

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#218]
Ønsker at dette skal hvertfall være mulig for detaljesidene i løsningen. Støttes på datatjeneste-detaljeside nå - dette skal fungere for alle de andre detaljesidene også.

- [x] Støtte markdown på detaljeside begrep. Minimum for feltet beskrivelse

- [x] Støtte markdown datasettdetaljeside. Minimum: beskrivelse og formål

- [x] Støtte markdown informasjonsmodeller. Minimum: beskrivelse 

- [x] Støtte markdown tjeneste og hendelser. Minimum: beskrivelse 

- [ ] Støtte markdown ut fra registreringsløsning. Hvis jeg skriver det markdown i registreringsløsningen skal det rendres korrekt ut i portal. Altså ikke slik:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/2236a272-1b54-4ea1-9678-8a6893a42a1b)

**Comment by shenluna** [comment]
Det er flere markdown elementer som ikke vises blant annet lister og tabeller. Se https://www.staging.fellesdatakatalog.digdir.no/datasets/07f83b95-92fe-31a1-84c8-225057a78f8a
![image](https://user-images.githubusercontent.com/73637969/112449883-1d1ad880-8d54-11eb-8b62-142f33600269.png)

**Comment by shenluna** [comment]
Testet og verifsert, Det er kun lagt til støttet for enkelte markdown elementer. Elementene nevnt i kommentaren over er ikke implementert og vil evt bli tatt med ved behov.
