### ISSUE TITLE
Søk i innholdsleverandører (datasett registrering)

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#219]
Får ikke treff ved søk på deler av organisasjonsnummer.

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/d5ab3be6-a86b-4138-b40a-9377ace8dc74)
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/2571a2d7-7ea6-4c63-b6d0-89f2150af7bf)

Ikke mulig å slette innhold i tekstboks når alt er markert
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/6398e26d-a2ff-4581-b514-060674737a02)

**Comment by frederik-ronnevig** [comment]
### ANALYSE

Tjenesten gjør kall til enhetsregisteret utelukkende på organisasjonsnavn

Enhetsregisteret har støtte for søk på: 

- navn
- navn+organisasjonsnummer (konjuksjon)
- organisasjonsnummer

ref.  https://data.brreg.no/enhetsregisteret/api/docs/index.html

Per dags dato gjøres to kall for hver inntasting i søkeføltet:

enheter?navn=
underenheter?navn=

Man kunne lagt til et kall direkte på organisasjonsnummer også. Ulempen er at tjenesten til enhetsregisteret ikke støtter organisasjonsnumre som ikke er et helt tall på 9 siffer. 

For å gjennomføre både søk på organisasjonsnummer eller navn så må altså hele organisasjonsnummeret tastes inn før en organisasjon kan poppe opp. 

En løsning kunne vært å endre navnet på tekstfeltet til å kun søke på navn. Deretter kunne man ha et eget felt ved siden av for søk på organisasjonsnummer. Mulig at dette UX-messig vil være mer informativt overfor brukeren i stedet for et felt der man søker både på navn og eller må taste inn et komplett organisasjonsnummer for å få treff. 

Uansett må teksten som vises til brukeren endres.

**Comment by lillelars** [comment]
@LeneSundsbo Vi trenger forslag til ny tekst her

**Comment by lillelars** [comment]
"Søk på navn eller skriv inn organisasjonsnummer"

**Comment by LeneSundsbo** [comment]
Da foreslår jeg følgende:

<img width="936" alt="Screenshot 2021-04-23 at 15 11 44" src="https://user-images.githubusercontent.com/25385497/115876196-4f4c5280-a446-11eb-8b00-71504e3cdc4b.png">

**Comment by shenluna** [comment]
Nå står det "Søk på organisasjon", ønske om å endre det til Lenes forslag "Søk på organisasjonsnavn eller oppgi organisasjonsnummer"

**Comment by shenluna** [comment]
Testet Ok
