### ISSUE TITLE
500-respons i fdk-nginx-search

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#220]
Hvis man går mot api/apis, forventes det at requestet inneholder mer.
Nginxen prøver å skrive om pathen fra api/apis( * ) til ( * ).
Dette blir da null. 

- [x] Legge inn sjekk på at pathen har innhold etter api/apis
- [x] Legge inn at api/apis uten innhold blir omdirigert til api/dataservices

**Comment by shenluna** [comment]
Testet og verifisert
