### ISSUE TITLE
'Relaterte tjenester' vises uten innhold

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#221]
En tjeneste som ikke har andre tjenester som relaterer til den viser en tom boks. Denne bør kun vises hvis den har innhold.

Eks. https://www.staging.fellesdatakatalog.digdir.no/public-services/d5d0c07c-c14f-3741-9aa3-126960958cf0

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/616decfd-3140-4983-ac32-29e26366d428)

**Comment by oyvindis** [comment]
Kan du reteste denne @shenluna , tror den skal være løst allerede.

**Comment by shenluna** [comment]
@oyvindis Du har rett, ser ut som om den allerede er løst.
Jeg lukker saken :)
