### ISSUE TITLE
Something went wrong.... AGAIN

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#224]
Når MOD header står på:
Virksomhetssiden -> Velg SVV

**Comment by azaxarov** [comment]
Litt info om feilen:

Feilen skjer her: https://github.com/Informasjonsforvaltning/fdk-portal/blob/b7f64d64cacd0d742633e1b9f320637449ee2560/src/components/with-organization/redux/saga.ts#L32

Årsaken til feilen er at vi har lite streng sjekk på responsen fra organisation catalogue APIet. Med header "Accept: text/turtle", får vi tilbake en streng (Turtle versjon av organisation's objektet) i stedet for objektet.

![Screenshot 2021-03-18 at 11.20.11.png](https://images.zenhubusercontent.com/5d402ba1ca7b4e0001322ad3/bd6578ca-943d-4874-abca-469cc9eb2927)
![Screenshot 2021-03-18 at 11.20.26.png](https://images.zenhubusercontent.com/5d402ba1ca7b4e0001322ad3/6fb45324-5fbd-40a5-ae9c-e8b793b17be3)

**Comment by shenluna** [comment]
Testet i staging, får nå en tom virksomhetsside
![image](https://user-images.githubusercontent.com/73637969/112118243-72bc7d00-8bbc-11eb-8e71-4e5f670bed7e.png)
