### ISSUE TITLE
from-parameteret har ingen effekt i datasett-katalogen

### ISSUE THREAD

**Issue by stiang** [Informasjonsforvaltning/fdk-issue-tracker#23]
Jeg prøver å bruke API-et for å hente ut de ulike datasettene i Felles Datakatalog, som beskrevet her:

https://fellesdatakatalog.brreg.no/datasets/ea9e2aa7-880c-4387-888e-77446acab279

Ifølge beskrivelsen skal man kunne angi `from=N` for å starte på et gitt treff, sånn at man skal kunne hente ut alle datasettene ved å gjøre flere spørringer, men det virker ikke som `from`-parameteret har noen effekt - jeg får alltid samme resultat. Her er kommandoene jeg kjører:

```
$ curl -sH 'Accept: application/json' 'https://fellesdatakatalog.brreg.no/datasets?size=100' | jq 'del(.took)' | shasum
501dee5e95735a115264a02dda996ab87ca7bfd2  -

$ curl -sH 'Accept: application/json' 'https://fellesdatakatalog.brreg.no/datasets?size=100&from=123' | jq 'del(.took)' | shasum
501dee5e95735a115264a02dda996ab87ca7bfd2  -
```

Har jeg misforstått hvordan dette skal gjøres eller er dette en feil? Finnes det evt. noen alternative måter å hente ut hele katalogen på?

**Comment by lillelars** [comment]
@stigbd kan vi lukke denne?

**Comment by stigbd** [comment]
Ja.
