### ISSUE TITLE
Strukturvisning av informasjonsmodeller - identifikatorer (IRI) vises ikke på modell, modellelementer eller egenskaper.

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#231]
Se trådskisse, https://www.figma.com/proto/nrqaa1JB8pY6pBvUBxp1EV/Detail-infomodel?node-id=979%3A6665&viewport=-13757%2C425%2C1.2490730285644531&scaling=min-zoom.

IRI'en til modellen skal vises Identifikatorer:
![image](https://user-images.githubusercontent.com/17720749/112142188-8c6abe00-8bd6-11eb-9ff6-99b09c74a689.png)

Identifikatorer til modellelementer, egenskaper og kodeelementer skal vises under "Se detaljer":
![image](https://user-images.githubusercontent.com/17720749/112142366-c9cf4b80-8bd6-11eb-9636-42dc7dfc2d2a.png)

**Comment by matsjs** [comment]
Vanskelig å estimere - må undersøkes mer
