### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - kodelister mangler kode

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#233]
Kodeelementer til kodelister høstes ikke, se f.eks. https://data.norge.no/informationmodels/1029338d-215b-3fe9-8821-7c5553c7653b:
![image](https://user-images.githubusercontent.com/17720749/112146629-19644600-8bdc-11eb-90ca-4d8fefcfda84.png)

Dette er en kjent feil. Utfordringen ligger i at kodeelementer i ModellDCAT-AP-NO peker til kodeliste og ikke omvendt og eksisterer dermed ikke i en modell.

I møte 23.03.2021 ble det nevnt at en løsning på dette er at man kan lage inverse relasjoner til  skos:inScheme.

**Comment by matsjs** [comment]
Wont fix til vi får inverse relasjoner/ en annen snedig løsning

**Comment by matsjs** [comment]
Mulig snedig løsning er å lage flere grafer direkte i RDF-lib og så kombinere de før serialisering til RDF. Under arbeid.
