### ISSUE TITLE
Fjerne alle altinn modellene fra prod

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#234]
Joachim har slått av høstingen av Altinn-xsd'er for informasjonsmodellene fra Altinn.
Nå gjenstår det å fjerne modellene fra prod.

**Comment by valosnah** [comment]
ETL kjørt i alle tre miljø

**Comment by valosnah** [comment]
Har også fjernet applikasjonen altinn-model-publisher fra alle tre miljøene, og fjernet hosten fra ingressen

**Comment by shenluna** [comment]
Alle modellene er fjernet fra prod
