### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - enkeltype i tillegg til kodeliste

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#235]
ModellDCAT-AP_NO åpner for at et attributt både kan ha en kodeliste og en enkeltype som type. En kodeliste (enum) vil i Json være definert innenfor et skjema, f.eks. integer eller string. Det bør derfor opprette en enkeltype i tillegg til kodeliste for attributtet.
Eksempel, se https://data.norge.no/informationmodels/1029338d-215b-3fe9-8821-7c5553c7653b:

En egenskap viser til et string-skjema hvor det er definert en enum:
![image](https://user-images.githubusercontent.com/17720749/112150538-81b52680-8be0-11eb-9559-93d274308b62.png)

Her skal attributtet type for objekttypen PostalAddress ha både string og AddressType som type:
![image](https://user-images.githubusercontent.com/17720749/112151016-056f1300-8be1-11eb-8765-e598d7ef0d8f.png)

**Comment by matsjs** [comment]
Hvorfor skal denne også ha string? Antar at `AddressType` er et subset av string, så alt som gjelder for string vil ikke gjelde her.
Videre usikker på om modellcatno støtter flere typer på samme entitet. Her må da muligens portal, model-publisher og modelldcatno oppdateres.

**Comment by ToHelland** [comment]
ModellDCAT-AP-NO tillater å knytte ett attributt til både en CodeList og SimpleType. SimpleType spesifiserer da hvilket format kodeelementene er på (CodeElement), f.eks. string eller integer. Men jeg ser en utfordring for hvordan vi presenterer dette og kanskje hvordan det skal forstås (også i Metamodellen). For dette er ikke en union, men som nevnt en spesifisering av kodeelement-formatet.

**Comment by frederik-ronnevig** [comment]
Litt usikker på svaret her. Det blir vel kanskje et spørsmål om hva som er tiltenkt bruk av modellen. Men dersom det er ting som må utvides/endres så kan jeg selvfølgelig gjøre dette...

**Comment by ToHelland** [comment]
Jeg tar en diskusjonen med gruppen som jobber med ModellDCAT-AP-NO om dette, så dette kan avvente.

**Comment by ToHelland** [comment]
@matsjs @frederik-ronnevig Har diskutert dette med gruppen som arbeider med ModellDCAT-AP-NO. Vi ble enig at dette lett kan misforstås, og at man derfor tar bort mulighet for at et attributt både kan ha en SimpleType og CodeList som type. Lukker derfor issuet.
