### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - global definerte Json Schema-skjemaer som tilsvarer enkeltyper høstes ikke 

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#236]
Global definerte skjemaer som skal mappes til enkeltyper (modelldcatno:SimpleTypes) høstes ikke.

Eksempel:
![image](https://user-images.githubusercontent.com/17720749/112151918-0a809200-8be2-11eb-9e08-c5df2e2ddaf6.png)

![image](https://user-images.githubusercontent.com/17720749/112152260-664b1b00-8be2-11eb-849a-6c3e044ce991.png)

Det skal her opprettes en enkeltype (modelldcatno:SimpleType) CountryCode som arver enkeltype string. Verdirestriksjonene legges inn på CountryCode. CountryCode skal legges som type til attributtet country.

Hvordan dette mappes er beskrevet i følgende dokument:
https://teams.microsoft.com/l/file/92D96EE8-500D-4100-9EEB-41E227DE9F70?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1%2FDelte%20dokumenter%2FModellkatalog%2FJsonS2ModellDCAT.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1&serviceName=teams&threadId=19:1d63088cc0e1451cb991a9ccd9d8ada6@thread.skype&groupId=937040ec-fca4-412c-97ff-28d0f60c75a3

Det er også laget eksempler på dette.

**Comment by matsjs** [comment]
@NilsOveTen vet du noe om dette?

**Comment by shenluna** [comment]
Mangler arv, som blir løst i denne saken https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/265
Lukker dermed denne.
