### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - typer og multiplisitet vises ikke for enkelte komposisjoner

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#238]
Se f.eks https://data.norge.no/informationmodels/1029338d-215b-3fe9-8821-7c5553c7653b:
 
![image](https://user-images.githubusercontent.com/17720749/112163395-4705bb00-8bed-11eb-8a26-c6aa21088542.png)

Henger trolig sammen med issue #230.

**Comment by shenluna** [comment]
Testet og verifisert av Tore, lukker saken
