### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - enkelte typer til attributter vises ikke

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#239]
Se https://data.norge.no/informationmodels/46727d30-e074-359f-9600-ee9afd99f4f3.

![image](https://user-images.githubusercontent.com/17720749/112165180-cd6ecc80-8bee-11eb-88e0-20d3b30c0ab2.png)

Gjelder flere attributter.

Siden jeg ikke får tilgang til endepunktbeskrivelsen for API'et, kan jeg ikke finne ut hvilken typen dette skal være.

**Comment by ToHelland** [comment]
Er relatert til issue #240, se kommentarer på dette. Det er mulig at API-beskrivelsen som modellen bygger på skal slettes. I så fall utgår issuet.

**Comment by lillelars** [comment]
Denne lukker vi ettersom tilgang til endepunktsbeskrivelsen ikke finnes.
