### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner -egenskaper på objekttype vises ikke

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#240]
Se følgende modell https://data.norge.no/informationmodels/46727d30-e074-359f-9600-ee9afd99f4f3, eBevis Production.

Klassen EvidenceStatus mangler innhold. Det kan være realiteten, men får ikke sjekket opp om den skal inneholde noe siden jeg ikke får tilgang til endepunktbeskrivelse:
![image](https://user-images.githubusercontent.com/17720749/112167847-1162d100-8bf1-11eb-824e-5af4d7af2080.png)

**Comment by matsjs** [comment]
Muligens feil i datakilde - endepunktsbeskrivelse gir 404

**Comment by ToHelland** [comment]
@stigbd Forsto du Stig hadde vært i kontakt med API-eier om 404 feil?

**Comment by stigbd** [comment]
Ja. Erlend Oksvoll skulle visstnok flytte api-beskrivelsen frå brreg til Digitaliseringsdirektoratet. Usikker på status.

**Comment by ToHelland** [comment]
Jeg sendte en e-post til Erlend for å få en status.

**Comment by ToHelland** [comment]
@stigbd Fikk beskjed om at dette skyldes nok at ebevis.no ikke finnes lenger og at
ebevis-oppføringen egentlig kan slettes fra BR på api-katalogen. Erlend oppretter den på nytt under digdir. Skal det opprettes et issue for å slette API-beskrivelsen?

**Comment by stigbd** [comment]
Å slette eksisterende API-beskrivelse for eBevis er det kun tilbyder som kan gjere, i dette tilfellet REGISTERENHETEN I BRØNNØYSUND, ref https://data.norge.no/dataservices/3059ed22-3a6f-388e-9cff-507e240566a7

**Comment by joebrreg** [comment]
Kan ikke gjenskape denne lenger. E-bevis oppføringen er slettet.
