### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - ikke høstet modeller for alle API'er

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#241]
Det er ikke alle modeller som det er høstet et modellinnhold for:

Se f.eks.:

- Åpne Data fra Enhetsregisteret - API Dokumentasjon, https://data.norge.no/dataservices/5d521611-91da-4b4c-839e-ed7ca14f9251
- Information Model - National Data Directory Organization Catalogue, https://data.norge.no/informationmodels/27f78768-7d04-307c-baac-947b8002a932
- Nøkkeltall fra årsregnskapet, https://data.norge.no/dataservices?format=application%2Fjson&orgPath=%2FSTAT
- SGregister - Register over foretak med sentral godkjenning, https://data.norge.no/dataservices/c443ab25-ae23-3b67-b6b3-3782c08f4d46

**Comment by ToHelland** [comment]
Ser at for Åpne Data fra Enhetsregisteret er objektene i Json S-filen ikke definert som objekt-skjemaer. En regel kan være at hvis skjematype ikke er definert, men skjema inneholder properties, så er det en objekttype.

**Comment by ToHelland** [comment]
For meg ser det ut som om 90% av alle modellene ikke presenterer modellinnhold.

**Comment by matsjs** [comment]
**Fikset**
* Nøkkeltall fra årsregisteret: Her mappes ikke svar-elementet fordi det er lokalt definert, fikset.
* Åpne Data fra Enhetsregisteret: Ble ikke mappet pga manglende typespesifisering. Fikset.

**Fikses ikke**
* SG-register: Mappes ikke på grunn av ugyldig JSON (JSON5)
* National Data Directory Organization Catalogue: Blir tom da ingen GET-requests svarer med faktiske modell-elementer.
