### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - angi modelltyper

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#242]
Det skal angis at disse modellene er fysiske modeller.

Informasjonsmodellklassen (ModellDCAT-AP-NO) skal ha dct:type med verdi <https://data.norge.no/vocabulary/modelldcatno#physicalModel>. 

Dette skal også vises i portalen (skal vises som Fysisk modell, ikke Konstruksjonsmodell som i skissen):
![image](https://user-images.githubusercontent.com/17720749/112179256-d1085080-8bfa-11eb-9414-c681d8d85adf.png)

Gjelder alle modeller høstet fra Open API Specification.

**Comment by matsjs** [comment]
@stigbd @frederik-ronnevig Dette er ikke tillatt med modellcatno nå, hva tenker dere om dette?

**Comment by ToHelland** [comment]
Ser at type vises, men bare IRI'en, 
![image](https://user-images.githubusercontent.com/17720749/113822148-5d7b4d00-977d-11eb-84ff-ed47e7becf6f.png). Ønsker at norsk label skal vises, Fysisk informasjonsmodell.
