### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - prefiks

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#243]
Følgende prefiks er benyttet:
@prefix ns1:   for <https://data.norge.no/vocabulary/modelldcatno#> 

Her bør man bruke samme prefiks som i ModellDCAT-AP-NO, modelldcatno:

Det gjør det enklere for de med kjennskap til ModellDCAT-AP-NO å lese de ulike RDF-serialiseringene.

**Comment by matsjs** [comment]
@frederik-ronnevig settes namespace prefiks i modellcatno?

**Comment by frederik-ronnevig** [comment]
Hei @matsjs , ja namespace-prefikset settes i modelldcatno. Det som settes der er:

```https://data.norge.no/vocabulary/modelldcatno#```

**Comment by matsjs** [comment]
Er det da også mulig å endre prefiksen der fra `ns1` til `modellcatno`? @frederik-ronnevig

**Comment by frederik-ronnevig** [comment]
Hvor er det at prefiksen settes til ns1 i stedet for modelldatno? Jeg tror dette er en RDFlib-sak men det skjer bare når noe printes til konsoll i forbindelse med feilmelding. 

Vi har også metoder for dump_diff som gir noe slikt:

```
@prefix dct: <http://purl.org/dc/terms/> .
@prefix modelldcatno: <https://data.norge.no/vocabulary/modelldcatno#> .
<http://example.com/informationmodels/1> a modelldcatno:InformationModel ;
    dct:title "Title 1"@en,
        "Tittel 1"@nb .
```

**Comment by frederik-ronnevig** [comment]
Dette er nok ikke noe med modelldcatno, men RDFLib i stedet for eksempel vil denne metoden gi riktig ouput:

```
    for _l in g.serialize(format="turtle").splitlines():
        if _l:
            print(_l.decode())
```

**Comment by matsjs** [comment]
> Dette er nok ikke noe med modelldcatno, men RDFLib i stedet for eksempel vil denne metoden gi riktig ouput:
> 
> ```
>     for _l in g.serialize(format="turtle").splitlines():
>         if _l:
>             print(_l.decode())
> ```

Var dette noe vi kunne gjøre på vår ende?
