### ISSUE TITLE
Metrics og varsel til Slack - cloud-logging

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#244]
- [x] Opprette metric for staging, demo, prod
- [x] Opprette meldingsvarsel til Slack ved feil

**Comment by valosnah** [comment]
Opprettet metric for errors i alle miljø (med varsel til Slack for prod og demo)
Opprettet metric for warnings i prod og demo

**Comment by shenluna** [comment]
Når man klikker på varslene som blir sendt til Slack får man opp en side man ikke har tilgang til.

Se på mulighetene for å få lenke direkte til loggene som utløser varslene eller at flere får tilgang til monitoreringssiden.
![image](https://user-images.githubusercontent.com/73637969/113867499-e9f23380-97ae-11eb-9bd4-eeb86c52691f.png)

**Comment by valosnah** [comment]
Gitt tilgang til Monitoring-viewer. 
Legger til fremgangsmåte for å nå loggen via URL'en i slackmeldingen

**Comment by shenluna** [comment]
Testet og verifisert
