### ISSUE TITLE
Feil i totalt antall datasettbeskrivelser når man er på siden til en virksomhet

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#246]
Når man står på siden [Virksomheter](https://data.norge.no/organizations) vises antall datasettbeskrivelser for hver virksomhet. Hvis man klikker seg inn på en virksomhet så er stemmer ikke antall totale datasettbeskrivelser med det som stod på forrige side.

Eksempel Arbeids- og velferdsetaten (NAV):
På siden Virksomheter fremgår det at etaten har 46 datasett:
![image](https://user-images.githubusercontent.com/43232700/112338635-3de51e80-8cbf-11eb-863a-3af424327b5c.png)
Men når man har gått inn på siden til etaten så står det at de kun har 8 datasett:
![image](https://user-images.githubusercontent.com/43232700/112338743-548b7580-8cbf-11eb-884f-084ac6d43beb.png)

Og hvis man klikker på datasettikonet eller antallet datasett (8), så kommer man til søkesiden til FDK som er filtert på etaten som eier. Og der fremgår det at etaten har 46 datasett.
![image](https://user-images.githubusercontent.com/43232700/112340085-86510c00-8cc0-11eb-8be3-6e9064aa412e.png)

Se også: https://github.com/Informasjonsforvaltning/behov/issues/566#issuecomment-805913686

**Comment by stigbd** [comment]
Dette er kjent feil, og blir løyst av https://github.com/Informasjonsforvaltning/fdk-organization-bff/issues/42
