### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - mangler type på attributt i modell (Helse Uføreopplysninger)

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#249]
Se modell https://data.norge.no/informationmodels/c23f625f-a654-3462-805e-74408cb5367a

![image](https://user-images.githubusercontent.com/17720749/112602268-bc52d500-8e13-11eb-8954-3f41c26c233a.png)

Json Schema:
![image](https://user-images.githubusercontent.com/17720749/112602610-3420ff80-8e14-11eb-8db0-3d932f323206.png)

Som det framgår av endepunktsbeskrivelsen, skal attributtet forsteVirkningstidspunkt ha en modelldcatno:SimpleType date.

**Comment by ToHelland** [comment]
@matsjs @lillelars Fant en feil til, denne bør prioriteres med de andre issuene med prioritet 1.

**Comment by ToHelland** [comment]
Ser at dette gjelder flere modeller, Informasjonsmodell - Helse Medlemskapsunntak, https://data.norge.no/informationmodels/db536c33-7db0-321f-a9ab-44226a0a640a. Virker som om dette gjelder Json-properties hvor det er oppgitt et format. F.eks.:
unntakId:
          type: integer
          description: Den funksjonelle ID'en til et medlemskapsunntak.
          format: int64

Her skal int64 bli SimpleType.

**Comment by matsjs** [comment]
Fellesnevner her er at filene er i `.yaml` og ikke `.json`, tror dette kan være problemet @ToHelland

**Comment by ToHelland** [comment]
@matsjs Kan vi likevel lese dem maskinelt?
