### ISSUE TITLE
Håndtere X-Real-IP i trafikken fra data.norge.no

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#25]
All trafikk som kommer via data.norge.no blir kun loggført med IP'en til data.norge-loadbalanceren. Dette gjør at vi ikke ser hvilke IP'er som står bak evt ondsinnet trafikk.
Data.norge.no sender IP'en i "X-Real-IP". Må fikse slik at GCP-loggen kan plukke det opp.

- [ ] ~~Det ser ut som det skal gå an å implementere dette direkte i GCP.~~
- [ ] Kan kreve en liten modifikasjon i fdk-nginx-search

Ved nærmere undersøkelser, virker det ikke som dette er helt enkelt.
Vi kan fikse dette på nginx-nivå, men da behandler vi bare kall som slippes inn av cloud armor. Det er mest interessant med de som blir stoppet, og det ser ikke ut som Stackdriver støtter dette enda

**Comment by lillelars** [comment]
@valosnah hva gjør vi med dette issuet? Kan vi lukke det med konklusjonen din over?

**Comment by valosnah** [comment]
Det er en ganske nødvendig fiks, da vi ikke kan se reell IP bak uønsket trafikk som kommer via data.norge.no, som gir oss restriksjoner på hvilke midler vi kan bruke i tilfeller der cloud armor ikke vil virke. 
Vil anbefale å holde denne åpen til det er løst. Skal undersøke om det er noen planlagte oppdateringer som vil fikse dette, evt undersøke på nytt om det kan løses på et annet vis. Blir også løst om vi tar over kontrollen til domenet.

**Comment by valosnah** [comment]
Avhengig av https://github.com/Informasjonsforvaltning/static-rdf-server/issues/51

**Comment by valosnah** [comment]
GCP håndterer nå trafikk fra data.norge.no direkte, og håndtering av x-real-ip er derfor ikke nødvendig. Lukker.
