### ISSUE TITLE
Virksomhetssiden skalerer dårlig til mobiltelefon

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#251]
Oppdagde litt tilfeldig at virksomhetssiden skalerer dårlig til mobiltelefon. Er det noko vi kan gjere for å forbedre dette?
![image](https://user-images.githubusercontent.com/1702357/112811986-e3f8a600-907c-11eb-8078-fa69938e37a4.png)

**Comment by stigbd** [comment]
Eksempel: https://data.norge.no/organizations/991825827

**Comment by lillelars** [comment]
Funker nå i staging.
