### ISSUE TITLE
Opprette dokumentasjon for bruk av digdir-cloud-functions

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#252]
- [x] Hvordan logge seg på
- [x] Hvordan opprette cloud function
- [x] Se oversikt over cloud functions
- [x] Bruke log-metrics

**Comment by valosnah** [comment]
Dokument opprettet i Teams

**Comment by shenluna** [comment]
Dokumentasjon finnes på IT-infrastruktur/Oppskrifter
