### ISSUE TITLE
Integrasjon NodeBB diskusjoner i portalen/katalog

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-issue-tracker#257]
Se design (nederst på siden):
https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-default.html

- [x] Datasett detaljesiden

- [x]  API detaljeside

- [x] Begreps detaljeside

- [x] Infomodeller detaljeside

- [x] Tjenester og hendelser detaljeside

- [x] Finne tråder der detaljsiden er lenket til

**Comment by shenluna** [comment]
Det ser ut til å fungere bra! Men vi trenger å fikse litt på logikken så samme emne ikke vises flere ganger hvis url-en blir nevnt flere ganger, eks https://www.staging.fellesdatakatalog.digdir.no/dataservices/87a057f1-7546-3d7e-88e0-45b4bc4659cd

![image](https://user-images.githubusercontent.com/73637969/121681547-40376780-cabb-11eb-8c73-f6b69ca2c100.png)

**Comment by shenluna** [comment]
Testet og verifisert, allerede prodsatt
