### ISSUE TITLE
Registrerte Datasett vises ikke ut i portal

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#26]
@lillelars commented on [Wed Aug 19 2020](https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/36)

**NB! Kan avvente med denne til vi ser om ny kode rundt rabbit vil håndtere dette.**

Datasettene har blitt registrert og høstet korrekt, men likevel vises de ikke ut i produksjon før Nils Ove måtte manuelt trigge en ingest i fulltext. 

Vi må finne ut hvor problemet her ligger og løse det. Gjelder både Demo og Prod.

**Comment by lillelars** [comment]
@valosnah @NilsOveTen kan vi lukke denne?

**Comment by NilsOveTen** [comment]
Ja, kan vi ikke det. Merker dere noe problem med at datasett ikke dukker opp i portal?

**Comment by valosnah** [comment]
@lillelars Tenker den kan lukkes. Har vel ikke hatt noen issues med datasett siden koden meldingsopplegget ble oppdatert?

**Comment by valosnah** [comment]
Skulle foreslå å stenge denne, men vi har vel fortsatt sett noen tilfeller (iallefall i staging) der manuell trigging av høsting ikke viser nye/oppdaterte datasett i portal. Det hjelper som regel å trigge en reindeksering i fulltext-search, men det burde kanskje undersøkes nærmere hvorfor dette skjer @lillelars

**Comment by lillelars** [comment]
Lukker denne. Forsøker å beskrive situasjonen neste gang det skjer og utforske da.
