### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - lokale definerte typer skal ikke ha egne navn 

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#263]
Gjelder lokal definerte datatyper, så sant de ikke er definert med egne navn. Hvis den skulle ha et navn (som er mulig, men jeg ikke har sett eksempel på, følger den den samme mappingen som globalt definerte typer.

Se f.eks. modell https://data.norge.no/informationmodels/aebc7bfc-7c4c-3848-adb7-f1f1b9239182

Json Schema:
![image](https://user-images.githubusercontent.com/17720749/113991038-5b36f280-9852-11eb-920b-72308750fe8f.png)

Egenskapen streetName mappes til et attributt. Nå opprettes det i FDK en type StreetName som får verdirestriksjonene minLength (som ikke vises)/maxLength:
![image](https://user-images.githubusercontent.com/17720749/113992357-a998c100-9853-11eb-9836-0cf6bab759fd.png)

Her skal dette ikke opprettes en enkeltype (ModellDCAT-AP-NO) StreetName for attributtet streetName, men en string med verdirestriksjoner for min/maxLength. Hvis string har ulike verdirestriksjoner, så blir det en ny instans av string. Du vil med andre ord få mange string-enkelttyper, men det er det som blir mest semantisk riktig.

**Comment by ToHelland** [comment]
Se eksempler i følgende dokument: https://teams.microsoft.com/l/file/92D96EE8-500D-4100-9EEB-41E227DE9F70?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1%2FDelte%20dokumenter%2FModellkatalog%2FJsonS2ModellDCAT.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1&serviceName=teams&threadId=19:1d63088cc0e1451cb991a9ccd9d8ada6@thread.skype&groupId=937040ec-fca4-412c-97ff-28d0f60c75a3

**Comment by joebrreg** [comment]
Testet ok.
