### ISSUE TITLE
Høsting av modeller fra API-spesifikasjoner - modelldcatno:SimpleType basert på Json-datatyper og formater, skal ha liten forbokstav

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#264]
Json datatyper og formater skrives med liten forbokstaver, f.eks. string, boolean, date-time". Når disse mappes til modelldcatno:SimpleType, skal de ha liten forbokstav og **ikke** stor som nå. 

Dette fordi at ulike datatypesett har ulike konvensjoner for dette. F.eks. UML sine datatyper skrives med store forbokstaver. Dette vil være med å tydeliggjøre hvilket datatypesett det gjelder.

NB! Der det er definert globale typer med egne navn, får SimpleType tittelen etter måten det er skrevet på. F.eks. 
![image](https://user-images.githubusercontent.com/17720749/113995038-2d53ad00-9856-11eb-9e3e-42302cb97359.png)

Siden Amount her er skrevet med stor forbokstav, vil SimpleType ha tittel "Amount".

**Comment by joebrreg** [comment]
Fungerer likt i FDK og Swagger Editor. Lukker denne.
