### ISSUE TITLE
Mangler hjelpetekst i API-katalog i feltet "Kan alle få tilgang"

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#267]
I feltet "Kan alle få tilgang" i registreringsløsning for API-katalog er det en ufullstendig setning i hjelpetekst:

![image](https://user-images.githubusercontent.com/32771488/114519579-d62c4e80-9c40-11eb-8ad7-8dbe394e1c31.png)

**Comment by terjesyl** [comment]
Har du forslag til hva som bør stå her @joachim-me ? Eventuelt om det er nødvendig med hjelpetekst i det hele tatt?

**Comment by joachim-me** [comment]
@terjesyl Vi kan fjerne hjelpeteksten her i første omgang.
