### ISSUE TITLE
Opprette cache(redis) for dcat-ap-no-validator-service

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#268]
dcat-ap-no-validator-cache:
- [x] Resirkulere publishers-cache repoet til dcat-ap-no-validator-cache
- [x] Endre workflow
- [x] Endre helm-template
- [x] Sette opp/endre GCP-secrets
- [x] Sette opp nye disker
- [x] Deploy staging
- [x] Deploy prod/demo

dcat-ap-no-validator-service:
- [x] Legge til redis-miljøvariabler i dcat-ap-no-validator-service helm-template

Opprydning ift publishers-cache:
- [x] Slette gamle disker
- [x] Slette gamle containers/services

**Comment by shenluna** [comment]
Testet ok
