### ISSUE TITLE
[epic] Etabler monitoreringsløsning for FDK

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#271]
Ta for eksempel utgangspunkt i TICK-stack eksempelet her: https://github.com/Informasjonsforvaltning/example-monitoring

Målet er i første omgang å monitorere logger, men vi kan etterkvart bygge ut og samle inn andre metrikker:
- responstider
- antall requests
- ...

**Comment by valosnah** [comment]
Lukkes, se https://github.com/Informasjonsforvaltning/fdk-monitoring-services
