### ISSUE TITLE
BETA tag for tjeneste detaljeside vises feil

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#272]
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/service/detail-default.html

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/a69a95c5-201e-4067-ae1a-2853dfd535eb)

**Comment by shenluna** [comment]
Testet i staging

**Comment by shenluna** [comment]
Verifisert
