### ISSUE TITLE
Oppdatere forside Transportportal.no

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#273]
SVV ønsker å oppdatere forsiden på https://data.transportportal.no/datasets

NB! Behold lenkene i topmeny som de er (IKKE følg designet her)!

- [x] Oppdatere header og banner

- [x] Oppdatere FOOTER

- [x] endre tekst

- [x] Legge til logoer

- [x] Oppdatere mobilvisning

Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/transport/search-default-alt-2.html
DESIGN MOBIL:
https://eggedosis.github.io/fdk-design/redirects/portal/transport/search-default-m.html

Logoer:
https://drive.google.com/drive/folders/1GGId6DrGJtAOqj0DkEKnZczRKuFl2zEX?usp=sharing

**Comment by oyvindis** [comment]
NB! Når det gjelder test, det er noen feil i skissene for desktop og mobil. Tror ikke alle skissene er oppdatert, men avklaringer er gjort med Lene.

Header: Farge og bakgrunnsfarge er endret.

Banner: oppdatert med logoer og tekst

Footer: oppdatert med bakgrunnsfarge og lenker.

Oppdatert mobilvisning.

**Comment by shenluna** [comment]
Testet i staging

**Comment by shenluna** [comment]
Verifisert
