### ISSUE TITLE
Endre sparql-endepunkt (backend)

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#279]
- [x] Bestille DNS for sparql.fellesdatakatalog.digdir.no
- [x] Se til at avhengige tjenester (org-bff, metadata-quality-service (m.fl?) får peker til ny adresse

**Comment by stigbd** [comment]
Løses i #275

**Comment by shenluna** [comment]
Testet og verifisert
