### ISSUE TITLE
Presentasjon av Publiseringsportal

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#28]
Hentet fra behov: https://github.com/Informasjonsforvaltning/behov/issues/515

Se design: https://eggedosis.github.io/fdk-design/redirects/register/portal/start-default.html

Som bruker av registreringsløsningene til data.norge.no
Når jeg går til Registreringsportalen
Ønsker jeg å få en god presentasjon av hvordan jeg kommer i gang
og hvordan jeg registrerer meg som bruker.
Slik at jeg får publisert mine dataset/dataservices/begreper i data.norge.no

Relatert til epos: #514

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Akseptansekriterier:

Her må vi vise lenke til både admin løsning og registreringsløsning

-------------------------------
- [x] What link to use for logging in to registration?
Prod: 
https://registrering.fellesdatakatalog.digdir.no/

(https://sso.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/auth?client_id=fdk-registration-public&redirect_uri=https%3A%2F%2Fregistrering.fellesdatakatalog.digdir.no%2F&state=f5374b50-2e02-44be-89b2-9f6ee7266d2d&response_mode=fragment&response_type=code&scope=openid&nonce=96dc1402-6e41-44f8-b7fb-2b63c4b2b14c)

Staging:
https://registrering.staging.fellesdatakatalog.digdir.no/

(https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/auth?client_id=fdk-registration-public&redirect_uri=https%3A%2F%2Fregistrering.staging.fellesdatakatalog.digdir.no%2F&state=7566a94c-6a0f-4e69-8368-487b1550cb3c&response_mode=fragment&response_type=code&scope=openid&nonce=3e850122-453d-4ec2-8782-762f0a8ac577)

Demo:
https://registrering.demo.fellesdatakatalog.digdir.no/

(https://sso.demo.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/auth?client_id=fdk-registration-public&redirect_uri=https%3A%2F%2Fregistrering.demo.fellesdatakatalog.digdir.no%2F&state=969f9707-28ac-46a1-8264-a6a9b642d9ce&response_mode=fragment&response_type=code&scope=openid&nonce=cb2d2480-a936-4d87-879b-a38314b5d221)

- [x] What link to use for logging in to harvesting?
Prod:
https://admin.fellesdatakatalog.digdir.no/

Demo:
https://admin.demo.fellesdatakatalog.digdir.no/

Staging:
https://admin.staging.fellesdatakatalog.digdir.no/

- [x] What link to use for more information about registration?
https://data.norge.no/about-registration
(Men denne er knyttet mot ID'er fra CMS'et - men det går kanskje greit?)

- [x] What link to use for more information about harvesting?
Kan opprette dummy-lenke så lenge som f.eks:
https://data.norge.no/about-harvesting 

- [x] CMS ID'er til informasjonsside:

Bokmål:
"id": "5e4d7251-1327-4cc1-8c91-2d0947fd75c4",
"title": "Hjelp til å høste dataendepunkter",

Nynorsk:
"id": "ba6aac2b-57ad-4961-934f-1456f8d55da9",
"title": "Hjelp til å høste dataendepunkter (nynorsk)",

Engelsk: 
"title": "Help to harvest data endpoints
"id": "ae3b550d-7e75-4b47-b85c-18300aada1b4"

- [x] How do we handle information section titles that may overflow beyond one line?
Hvor er dette et problem? Kan vi ikke kolonnestyre det - hvertfall for større skjermer i første omgang. Vi bestemmer all informasjon som skal være på denne siden så vi bør kunne tilpasse alt slik vi ønsker.. Er det mobilskjerm som blir utfordrende her?

- [x] Undertittel (se design):
"Vi arbeider for "ONCE ONLY" - prinsippet. Felles datakatalog tilbyr virksomheter å dele data via dataportalen. Dette kan gjøres både ved høsting av egne kataloger og ved å benytte Felles datakatalog sin registreringsløsning."

- [x] TITTEL / TEKST / LENKER for information section paragraphs:

Tittel:
"Hjelp til å komme i gang med registrering" <-- NB! Denne tittelen bør være en lenke til CMS siden https://data.norge.no/about-registration

Tekst: 
"Registreringsløsningen kan benyttes av alle brukere som ønsker å publisere datainnhold til dataportalen på vegne av sin virksomhet."

Lenker: 
- "Innlogging med ID-porten/Altinn" (https://data.norge.no/about-registration <- men scrollet til tittelen "Innlogging med ID-porten/Altinn" )
- "Innlogging med Felles brukerhåndtering" (https://data.norge.no/about-registration <- men scrollet til tittelen "Innlogging med Felles brukerhåndtering" )

Tittel:
"Nyttig å vite om datasettbeskrivelser" <-- NB: Denne tittelen skal være en lenke hit: https://data.norge.no/guidance

Tekst:
"Før du går i gang med å publisere data til Felles Datakatalog kan det være lurt å ta en titt på lenkene under:"

Lenker:
- "Standard for beskrive datasett: https://informasjonsforvaltning.github.io/dcat-ap-no/ "
- "Veiledning for registrering av data: https://doc.difi.no/data/veileder-apne-data/ "
- "Norsk lisens for offentlig data: https://data.norge.no/nlod/no/ "

UTGÅR SE OPPDATERT SKISSE
Tittel:
"Tidligere brukere av data.norge.no"

UTGÅR SE OPPDATERT SKISSE 
Tekst:
Tidligere brukere av data.norge.no kan benytte registreringsløsningen på lik linje som før.

UTGÅR SE OPPDATERT SKISSE 
Lenke:
- For å komme til profilsiden din går du til https://user.difi.no

- [x] What texts do we use in information sections links?
Se forrige punkt. 

- [x] Where do we expose the publication portal?
https://data.norge.no/publishing

- [x] Bruksvilkår menypunkt:

Bokmål:
id": "ff7b4cde-7299-4212-98d7-13dd01a090a1
"title": "Bruksvilkår",

Engelsk:
"id": "679c4c6c-4a46-4033-86bd-2bd425e14af8",
"title": "Terms of use",

Nynorsk:
"id": "20e549e1-f251-47ed-b712-1e320c613bf1",
"title": "Bruksvilkår - nynorsk",

- [x]  NAP:
UPDATE: Vi beholder NAP as is. Vi trenger ikke gjøre noe endringer her.

**Comment by azaxarov** [comment]
@lillelars og @joebrreg , kanskje dere kan svare på noen av spørsmålene jeg la til på issuet?

**Comment by lillelars** [comment]
Da er dette prodsatt!! :D Testet i edge, firefox og chrome - i staging og demo. Lukker saken.
