### ISSUE TITLE
Begrense hva brukere kan legge ut på profilen sin

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#280]
- [ ] Fjerne alt unødvendig som bruker kan registrere om seg selv.

Personopplysning | Kilde | Kan endres i Community
-- | -- | --
Fullt navn | Felles brukerhåndtering | Nei
E-post | Felles brukerhåndtering | Nei
Brukernavn | Generert i Community - basert på e-post | Ja
Virksomhet | Valgfri brukeropplsyning (ny tittel på 'Om meg') | Ja
Stillingstittel | Valgfri brukeropplysning (ny tittel på 'Om meg') | Ja

**Comment by shenluna** [comment]
Testet OK
![image](https://user-images.githubusercontent.com/73637969/117417458-a8be8200-af1a-11eb-8a46-424a04c60258.png)
