### ISSUE TITLE
Informasjonsmodeller - feil i e-postadresse under Kontaktinformasjon

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#285]
Se følgende modell i demo-miljøet: https://demo.fellesdatakatalog.digdir.no/informationmodels/7d51c3f5-94a0-3e79-bb57-e11c799abc19

E-posten vises som en URL ved at det ved høsting automatisk har blitt lagt til 
"http://example.com/".

![image](https://user-images.githubusercontent.com/17720749/115865313-700dab80-a438-11eb-9013-2d51157fbeb3.png)

Slik er den beskrevet i filen som høstes:
![image](https://user-images.githubusercontent.com/17720749/115864661-79e2df00-a437-11eb-8018-55ee9ca4ec9a.png)

Vet ikke om dette er spesifikt for demo-miljøet eller om det også gjelder prod.

**Comment by oyvindis** [comment]
Her er det testdata for modellen som har skapt noen problemer.

Det har opprinnelig stått feil mailadresse i modellen. Deretter er id-uri endret i etterkant og modellen tolkes da som en ny modell av vår høster. Den gamle vil fortsette å eksistere.

Så feilen er ikke relatert til noen tjenester, lukker saken.

**Comment by ToHelland** [comment]
Skulle stått mailto: før e-post i Turtle-filen?

**Comment by oyvindis** [comment]
Nei, i Turtle-filen må det kun stå mail-adressen, som det gjør nå. Så dette feltet vises riktig i alle andre modeller jeg har sjekket på.
