### ISSUE TITLE
Informasjonsmodeller - egenskapen prof:isProfileOf vises ikke.

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#287]
Informasjonsmodell-klassen (modelldcatno:InformationModel) kan ha egenskapen prof:isProfileOf med range dct:Standard. Se ModellDCAT-AP-NO, https://data.norge.no/specification/modelldcat-ap-no/#Informasjonsmodell-erProfilAv. Dette støttes av 1.1-versjonen av ModellDCAT-AP-NO.

Pr i dag vises ikke dette i portalvisningen. Det er laget trådskisser for dette (Alternativ representasjon av format):
![image](https://user-images.githubusercontent.com/17720749/115867233-19ee3780-a43b-11eb-9756-5dc4f4595cf3.png)

For eksempel, se:
https://demo.fellesdatakatalog.digdir.no/informationmodels/7d51c3f5-94a0-3e79-bb57-e11c799abc19

**Comment by shenluna** [comment]
Testet OK

**Comment by ToHelland** [comment]
Ser ikke ut som om det stemme med det som er høstet. Jeg skal lage et komplett eksempel.

**Comment by shenluna** [comment]
Verifisert i demo https://demo.fellesdatakatalog.digdir.no/informationmodels/7d51c3f5-94a0-3e79-bb57-e11c799abc19
![image](https://user-images.githubusercontent.com/73637969/118811543-6b101080-b8ad-11eb-85d2-2079d3e8434a.png)
