### ISSUE TITLE
Informasjonsmodeller - egenskapen dct:conformsTo vises ikke i portalen.

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#288]
Informasjonsmodell-klassen (modelldcatno:InformationModel) kan ha egenskapen dct:conformsTo med range dct:Standard. Se ModellDCAT-AP-NO, https://data.norge.no/specification/modelldcat-ap-no/#Informasjonsmodell-iSamsvarMed. Dette støttes av 1.1-versjonen av ModellDCAT-AP-NO.

Pr i dag vises ikke dette i portalvisningen. Det er laget trådskisser for dette (Alternativ representasjon av format):
![image](https://user-images.githubusercontent.com/17720749/115867854-e3fd8300-a43b-11eb-8999-aca5302d0e4d.png)

**Comment by shenluna** [comment]
Vises nå i staging, trenger å få oppdatert formateringen av blandt annet url. Dette blir løst i #287 
![image](https://user-images.githubusercontent.com/73637969/117667182-edf5e480-b1a4-11eb-8018-4139e94027c8.png)

**Comment by shenluna** [comment]
Testet OK

**Comment by ToHelland** [comment]
Ser ikke ut som om det stemme med det som er høstet. Jeg skal lage et komplett eksempel.
