### ISSUE TITLE
Informasjonsmodeller - dcat:theme, EU-vokabular vises ikke i portalvisningen

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#290]
Se modell, https://demo.fellesdatakatalog.digdir.no/informationmodels/7d51c3f5-94a0-3e79-bb57-e11c799abc19.

Los-temaer vises i dag for informasjonsmodeller, men ikke hvis dette er EU-vokabular:
![image](https://user-images.githubusercontent.com/17720749/115870570-b581a700-a43f-11eb-9805-cb8181c7640e.png)

**Comment by oyvindis** [comment]
Vi må se om vår referansedata vår må utvides? Jeg ser ikke at vi har referansen fra dette vokabularet i 'los' eller 'themes'.

**Comment by ToHelland** [comment]
Det refereres til dette vokabularet i DCAT-AP-NO, https://data.norge.no/specification/dcat-ap-no/#Skal-brukes-for-theme

**Comment by stigbd** [comment]
@ToHelland Eg greier ikkje å sjå at  vokabularet som denne peiker på er i henold til dcat-ap-no. http://data.europa.eu/una/com-web-presence/c33e404a44
Eg greier heller ikkje å finne noko fornuftig i enden av lenka, men det kan vere brukarfeil.

**Comment by ToHelland** [comment]
@stigbd Her er det vel jeg som har oppgitt feil URI, er litt vanskelig å finne fram i vokabularene til SSB. I DCAT-AP-NO vises det til  EuroVoc for dcat:theme https://data.norge.no/specification/dcat-ap-no/#Skal-brukes-for-theme. Spørsmålet er om URI'en skulle være http://eurovoc.europa.eu/4256. Statistics. Dette ligger under kategorien Economics -->economic analysis i EuroVoc.

**Comment by ToHelland** [comment]
Riktig URL for temaet skal være http://eurovoc.europa.eu/4256 og ikke  http://data.europa.eu/una/com-web-presence/c33e404a44. Jeg oppdaterer eksemplet.

**Comment by ToHelland** [comment]
@jeffreiffers Jeg har nå lagt inn http://eurovoc.europa.eu/4256  i testfilen http://eurovoc.europa.eu/4256  og https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/modelldcatno_Test2FlereEksempler.ttl. Endepunktene for disse skal være registrert i staging-miljøet.
