### ISSUE TITLE
Informasjonsmodeller - identifikator for informasjonsmodeller vises ikke i henhold til trådskisse

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#291]
I dag vises ikke identifikatorene til modellene i henhold til trådskisse. Nå vises kun dct:identifier for informasjonsmodell-klassen.

I henhold til trådskissen skal også IRI'en til modellen vises:
![image](https://user-images.githubusercontent.com/17720749/115871077-5f613380-a440-11eb-8b9f-7ca02bf08016.png)

**Comment by oyvindis** [comment]
@ToHelland 
Det som vises som "Identifikator" i dag er iri/uri.

Da legger vi inn så "Angitt identifikator" er den som peker mot dct:identifier?

**Comment by ToHelland** [comment]
@oyvindis Ja, angitt identifikator er dct:identifier.

Der det står "identifikator" i trådskissen, skal URI'en vises.

**Comment by oyvindis** [comment]
Den er grei, jeg retter og skiller uri/iri og dct:identifier på to ulike felt også i visningen.
Det var litt blandet sammen fra før i portalvisningen.

**Comment by shenluna** [comment]
Vises nå i staging, se feks https://www.staging.fellesdatakatalog.digdir.no/informationmodels/6feff2b7-c7e5-3bde-99bf-9e5ae5cd6be8
![image](https://user-images.githubusercontent.com/73637969/117790222-6f9f4e00-b249-11eb-843d-cf5c791513d1.png)

**Comment by shenluna** [comment]
Verifisert i demo
https://demo.fellesdatakatalog.digdir.no/informationmodels/7d51c3f5-94a0-3e79-bb57-e11c799abc19
