### ISSUE TITLE
Informasjonsmodeller - dct:temporal vises ikke i portalen

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#292]
Se f.eks. https://data.norge.no/informationmodels/8bfa055a-9b0c-40df-a7c2-2e58173eb2e0, og en av RDF-serialiseringen av modellen.
Modeller har opplysninger om dct:temporal, men dette vises ikke i portalvisningen.

Trådskisse:
![image](https://user-images.githubusercontent.com/17720749/115872844-90426800-a442-11eb-8473-131d3783b05e.png)

**Comment by shenluna** [comment]
Testet OK. dct:temporal vises blant annet her https://www.staging.fellesdatakatalog.digdir.no/informationmodels/bcbe6738-85f6-388c-afcc-ef1fafd7cc45

**Comment by shenluna** [comment]
Verifisert i demo
f.eks https://demo.fellesdatakatalog.digdir.no/informationmodels/d1115536-2fd6-4bde-be29-240bad171a3b
