### ISSUE TITLE
NAP - virksomheter, feil tall på antall datasettbeskrivelser

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#301]
Viser 2, men ved klikk får jeg bare opp 1?

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/a48cddbd-f9af-445f-8e72-313d2117007d)

**Comment by shenluna** [comment]
Samme gjelder data.norge
https://github.com/Informasjonsforvaltning/fdk-portal/issues/881

**Comment by NilsOveTen** [comment]
Problemet for NAP-siden er at frontend ikke inkluderer filteret i spørringen
den sender en spørringen: `https://organization-bff.fellesdatakatalog.digdir.no/organizationcatalogs/972417866`
spørringen skal være: `https://organization-bff.fellesdatakatalog.digdir.no/organizationcatalogs/972417866?filter=transportportal`

**Comment by azaxarov** [comment]
Issue moved to [Informasjonsforvaltning/fdk-portal #884](https://github.com/Informasjonsforvaltning/fdk-portal/issues/884) via [**ZenHub**](https://www.zenhub.com/)
