### ISSUE TITLE
NAP - metadatakvalitet mangler filter

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#302]
Gå via transportportal, inn på virksomheter og klikk på metadatakvalitet...:

![image](https://user-images.githubusercontent.com/39513382/116857964-f034cd80-abfd-11eb-8182-7c286fc211a5.png)

**Comment by azaxarov** [comment]
Metadata ser ut til å fungere som forventet med lokal oppsett, men den klarer ikke oppdage nye triplene knyttet til Transportportal.

**Comment by azaxarov** [comment]
Det var da et problem med deployment rekkefølgen i staging. Problemet er nå løst ved å deploye siste versjon av master til staging miljø.

**Comment by shenluna** [comment]
Verifisert at Metadatakvalitet for NAP fungerer, men gjennomsnittet får feil verdi, dette blir løst i https://github.com/Informasjonsforvaltning/fdk-organization-bff/issues/65
Lukker dermed denne saken.
