### ISSUE TITLE
Tall på Datatjenester - virksomhetside

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#304]
I første omgang skal vi ha tallene: 
- [x] Antall Datatjenester
- [x] Antall nye siste uken

Altså utgår tall om Metadatakvalitet, Autoritativitet og Åpne API'er

Se design: 
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/6c4a2c43-f557-4bdf-8061-49a79ff0211a)

**Comment by shenluna** [comment]
Testet OK
