### ISSUE TITLE
Ulik antall formater på rapportside og filter

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#305]
Disse to bør være samme tall!

Hvorfor er disse to tallene ulike - OG hva er korrekt?:
1) 
![image](https://user-images.githubusercontent.com/39513382/116976341-49196a00-acc1-11eb-919e-decfe14e2749.png)

2) ![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/5f6bc5fb-b3a9-41a9-8536-6bf2b9d08f08)

**Comment by jeffreiffers** [comment]
Saken lukkes siden feilen er rettet ved å bruke new-reference-data
