### ISSUE TITLE
Tall på ulike formater - datasett er forskjellig på filter og rapportside

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#306]
Disse to sidene bør vise samme antall formater:

Hva er korrekt?!

1) ![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/36eb6eb7-a810-452f-a9af-613301e29a36)

2) ![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/1d844359-0699-4a49-af52-02fbf221448e)

**Comment by jeffreiffers** [comment]
Saken lukkes siden der er løst ved å bruke new-reference-data
