### ISSUE TITLE
Tall på Informasjonsmodeller - virksomhetside 

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#307]
Design: @LeneSundsbo 

Vi skal utvide virksomhetssiden med tall på:
- [ ] Antall informasjonsmodeller
- [ ] Antall nye siste uken

**Comment by NilsOveTen** [comment]
Løst av https://github.com/Informasjonsforvaltning/fdk-organization-bff/pull/69 og https://github.com/Informasjonsforvaltning/fdk-portal/pull/909
