### ISSUE TITLE
Utvide virksomhetssiden med tall for Begreper og informasjosnmodeller

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#309]
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/report/organizations.html

- [x] Utvide med tall for begreper
- [x] Utvide med tall for infomodeller
- [x] Legge på ikoner over 

Søkeside på virksomheter skal nå utvides med tall på begreper og infomodeller:
![image](https://user-images.githubusercontent.com/39513382/116972216-fd63c200-acba-11eb-9809-180ac8eb63c3.png)

**Comment by shenluna** [comment]
Sorteringsmulighetene til de forskjellige katalogene ser ikke til å fungere, den sorterer stigende, men ikke synkende. I tillegg vises det ingen begreper eller informasjonsmodeller for virksomheter som har dette.

![image](https://user-images.githubusercontent.com/73637969/118604720-c7900480-b7b5-11eb-9cb6-c8cc8e5183b2.png)
![image](https://user-images.githubusercontent.com/73637969/118604821-e42c3c80-b7b5-11eb-903a-49d581121f47.png)

**Comment by shenluna** [comment]
Testet OK
