### ISSUE TITLE
Begreper - sammenligningsfunksjonalitet virker ikke lenger

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#318]
Testet i STAGING:

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/dca825ef-827d-4b8d-be59-253a1fa4972c)

**Comment by shenluna** [comment]
Testet OK, fungerer som i dagens prod, fremdeles noen feil med sammenligning som løses i andre issues
