### ISSUE TITLE
Portal klarer ikke last inn /concepts etter man har vært på sammenlikningssiden

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#319]
Hvis man sammenligner begreper, og så forsøker å åpne /concepts igjen, får man 404

![image.png](https://images.zenhubusercontent.com/5da70fe359191331a197eae1/0c156a2b-2dc4-4daa-a8e4-ff6b5504fe2d)
![image.png](https://images.zenhubusercontent.com/5da70fe359191331a197eae1/4ac1cce1-2189-41e6-a419-0312e19bdff3)

Frontend_alerts varsler om "Cannot read property 'id' of undefined"

**Comment by shenluna** [comment]
I tillegg blir det lagt ved et tomt begrep i sammenligning, feks:
![image](https://user-images.githubusercontent.com/73637969/117943721-bb66fb80-b30c-11eb-88c9-8e881def3253.png)

**Comment by shenluna** [comment]
Testet OK i staging

**Comment by shenluna** [comment]
Verifisert OK
