### ISSUE TITLE
Begrepsregistrering: Egendefinert blir ikkje med inn ved import frå csv

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#321]
Brønnøysundregistrene forsøker å importere eit sett av begreper. Nokre har "egendefinert" i forhold til kilde. Dette blir ikkje satt på begrepet ved import. Feltet er tomt.

**Comment by NilsOveTen** [comment]
Kravet er nå at det er definert en uri for at parsing skal godta kildeBeskrivelse. Hva er oppførselen vi vil ha?

1. Det er ok at kildeuri alltid må være definert
2. Parsing skal aldri kreve at en uri er definert
3. Parsing skal kun godta at uri ikke er definert om "Forhold til kilde" har verdien "Egendefinert"

**Comment by stigbd** [comment]
Vi går for (3).

**Comment by marittor** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mto/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mto/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



anbefaltTerm:nb | definisjon:nb | forholdtilkilde | kilde | merknad:nb | fagområde:nb | bruksområde:nb | eksempel:nb | tillattTerm:nb | frarådetTerm:nb |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
tildaenhet | virksomhet som føres tilsyn med, og som eier/driver eller har råderett   over et kontrollobjekt, og/eller har et juridisk ansvar for å etterleve et   krav knyttet til et kontrollobjekt | egendefinert | En tildaenhet består av et organisasjonsnummer. Virksomheten som er   gjenstand for tilsyn er ofte en underenhet. Når en ansvarlig aktør utgjør en   virksomhet, identifiseres denne ved et organisasjonsnummer. | Tilsyn | Datadelingstjenesten Tilda |   |   |  
tilsyn utført av | den tilsynsmyndigheten som har utført et tilsyn | egendefinert | Det skal alltid oppgis et organisasjonsnummer for å utlede hvem som har   utført et gitt tilsyn, selv om dette er en lovfestet tilsynsmyndighet som har   utført tilsynet. | Tilsyn | Datadelingstjenesten Tilda |   |   |  
ansvarlig tilsynsmyndighet | tilsynsmyndigheten som står ansvarlig for et tilsyn, selv om denne ikke   nødvendigvis utførte tilsynet | egendefinert | Tilsynsmyndigheten identifiseres ved et organisasjonsnummer. | Tilsyn | Datadelingstjenesten Tilda |   |   |  
tilsynsegenskaper | informasjon som beskriver bakgrunn og egenskaper vedrørende et tilsyn | egendefinert |   | Tilsyn | Datadelingstjenesten Tilda |   |   |  
intern tilsynsid | en spesifikk og intern ID hos tilsynsmyndigheten som kan brukes som   referanse for å identifisere hvilket tilsyn det er snakk om | egendefinert | Tilsyns ID-nummeret er litt forskjellig fra tilsynsmyndighet til   tilsynsmyndighet, men kan bli brukt som referanse og delt blant flere etater   når de har koordinerte og utførte tilsyn på samme sted til samme tid. | Tilsyn | Datadelingstjenesten Tilda | tilsynsid\|tilsynsnummer\|saksnummer\|oppgavenummer
storulykkevirksomhet | ethvert privat eller offentlig foretak hvor farlige kjemikalier   forekommer, og der mengden kjemikalier er lik eller større enn til enhver tid   gjeldende grenseverdier, herunder foretak som ikke sysselsetter arbeidstaker | basertPaaKilde | Storulykkeforskriften § 3. Forskrift   3. juni 2016 nr. 569 om tiltak for å forebygge og begrense konsekvensene av   storulykker i virksomheter der farlige kjemikalier forekommer. Tilgjengelig   fra https://lovdata.no/dokument/SF/forskrift/2016-06-03-569 | Tilsyn | Datadelingstjenesten Tilda | storulykkeobjekt |   |  



</body>

</html>

**Comment by marittor** [comment]
basertPaaKilde kom fint inn altså, men ikke egendefinert
