### ISSUE TITLE
feil i datasettkatalog: får ikke registret tilgangsnivå /hjelpetekst mangler tekstbryting

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#324]
Det er ikke mulig å velge tilgangsnivå i datasettkatalogen og hjelpetekstene mangler tekstbryting.

![image](https://user-images.githubusercontent.com/32771488/117633799-a9efe900-b17e-11eb-8c00-6ed0479a05d4.png)

**Comment by joebrreg** [comment]
Angående issue "feil i datasettkatalog: får ikke registret tilgangsnivå /hjelpetekst mangler tekstbryting #324": jeg får valgt tilgangsnivå inne i registreringsbildet når jeg klikker der hvor det skulle vært radioknapper , men jeg får ikke lagret endring på tilgangsnivå, for eksempel å gå fra "Offentlig" til "Begrenset offentlighet", eller motsatt.

**Comment by KurtStian** [comment]
Relatert til/dublett: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/323

**Comment by KurtStian** [comment]
Kanskje kan denne også være relatert: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/322

**Comment by marittor** [comment]
@RogerSOlsen Tusen takk for fyldig og beroligende svar :) Jeg skal melde dette videre til prosjektet jeg er med i.

**Comment by RogerSOlsen** [comment]
> @RogerSOlsen Tusen takk for fyldig og beroligende svar :) Jeg skal melde dette videre til prosjektet jeg er med i.

Beklager at dette har tatt tid. Jeg varsler deg når løsningen er klar for bruk igjen

**Comment by RogerSOlsen** [comment]
@marittor Da skal feilen være rettet. Kan du for sikkerhets skyld sjekke om dette virker slik det skal i de datasettbeskrivelsene dere oppdaget feilen i? mvh Roger

**Comment by marittor** [comment]
@RogerSOlsen - De er tilbake nå, det er supert! Takk skal dere ha!
