### ISSUE TITLE
Informasjonsmodeller - begreper vises ikke på informasjonsmodell

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#325]
Det er mulig å legge på begreper på klassen Informasjonsmodell (modelldcatno:InformationModel) ved bruk av egenskapen dct:subject. Disse vises ikke i portalvisningen.

Se modell https://demo.fellesdatakatalog.digdir.no/informationmodels/7d51c3f5-94a0-3e79-bb57-e11c799abc19.

Begreper på informasjonsmodell skal vises slik iht. trådskisse:
![image](https://user-images.githubusercontent.com/17720749/117780886-5645d400-b240-11eb-95b0-6c6ab607d18e.png)

Dette er i samsvar med hvordan begrepene vises på datasett.

**Comment by ToHelland** [comment]
Satte den på deg @oyvindis, regner dette har med front end å gjøre.

**Comment by ToHelland** [comment]
Dette ser ut som om dette er implementert feil. Informasjonsmodeller kan referere til begreper på to måter - fra modellelementene og egenskapene og fra modellen i seg selv, begge ved bruk av dct:subject.  Her virker det som om man under "Begreper brukt i modellen" lister opp begrepene som det pekes på fra modellelementer og egenskaper, siden jeg kan ikke se at det finnes noen dct:subject i instansen av modelldcatno:InformationModel. Det blir feil. Kun begreper som det refereres til fra InformationModel-instansen skal vises under "Begreper brukt om modellen".

Grunnen til at noen av begrepene ikke vises, kan være at demo- og stagingmiljøet ikke får tilgang til begreper registrert i registreringsløsningen i FDK. Det har vi erfart tidligere.

Et eksempel på en modell som har dct:subject på modelldcatno:InformationModel: https://demo.fellesdatakatalog.digdir.no/informationmodels/77ff9ff4-c6d7-3f84-91bd-c76bd6fad381. Men jeg ser at disse begrepene er registrert i registreringsløsningen i FDK og ikke høstet, så de vil nok ikke vises i demo- eller stagingmiljøet. Jeg kan lage noen eksempler i testmodellene vi har.

**Comment by ToHelland** [comment]
@shenluna Se kommentar ovenfor.  Jeg har nå lagt inn dct:subject på modelldcatno:Informationmodel-instanser for følgende testfiler:

https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/modelldcatno_Test2FlereEksempler.ttl
https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/model-catalogTestModellDCAT.ttl

De fleste begrepene er blitt registrert i registreringsløsningen for begreper i FDK, så det er mulig at disse ikke vil vises i staging/demo-miljøet. Men et par av dem er høstet fra en annen etat og skal kunne vises. Dette er:
Sivilstand
<http://begrepskatalogen/begrep/88804c58-ff43-11e6-9d97-005056825ca0>
Personnavn
<http://begrepskatalogen/begrep/88804c45-ff43-11e6-9d97-005056825ca0>

De andre begrepene bør dukke opp i prod.

**Comment by ToHelland** [comment]
@shenluna Testet. OK.

**Comment by shenluna** [comment]
Verifisert av Tore, lukker saken.
