### ISSUE TITLE
endre navn på valg under Generer rapport

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#33]
"Alle behandlingsoversikter" endres til "Behandlingsoversikt".
"Obligatoriske felt" endres til "Protokoll". 

![image](https://user-images.githubusercontent.com/32771488/95419616-45478400-093a-11eb-9ee0-a301b9c06970.png)

**Comment by lillelars** [comment]
Denne er fikset. Testet i demo, i chrome. Lukker saken.
