### ISSUE TITLE
Oppdatere høsteendepunkt ved autogenerering av datakilden concept-catalog i data-source

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#331]
For at URL-ene som går mot registreringsløsningen skal være bygget opp på en mer "standard" måte og at hver URL kun skal peke til en begrepskatalog, må URL som brukes ved autogenerering av datakilden concept-catalog i høsteløsningen endres slik at den også inneholder organisasjonsnummeret til eier av den spesifikke begrepskatalogen:

fra: https://registrering-begrep-api.fellesdatakatalog.digdir.no/collections

til: https://concept-catalog.fellesdatakatalog.digdir.no/collections?publisher=<orgNummer>

**Comment by NilsOveTen** [comment]
Skal være løst av https://github.com/Informasjonsforvaltning/concept-catalog/issues/3

**Comment by KurtStian** [comment]
@NilsOveTen 
Ut fra det jeg kan se i datasource, ser det ut som saken ikke er løst. Den 8/6 oppdaterte jeg navn på datakilde og URI til Næringslivets Sikkerhetsorganisasjon. Den 10/6 publiserte de et begrep og da ble det automatisk opprettet en dublett av denne datakilden - slik den så ut før jeg oppdaterte den (altså med gammet navn (automatically generated..) og URI):
![image](https://user-images.githubusercontent.com/43232700/121651817-51707c00-ca9b-11eb-96d1-6610e749932a.png)

**Comment by NilsOveTen** [comment]
@KurtStian 
`https://concept-catalog.fellesdatakatalog.digdir.no` og `https://registrering-begrep-api.fellesdatakatalog.digdir.no` er ekvivalente slik ingressen er satt opp, `concept-catalog` skal ta over etterhvert, men det vil kreve en større jobb (ETL) å ta hensyn til alle følgene den endringen har. Så enn så lenge kommer apiet til å bruke `registrering-begrep-api`. Det bør uansett være et eget issue.

Issuet jeg viser til endrer apiet slik at `/collections/960478150` blir korrekt path for å hente turtle for en enkel skos:Collection. `/collection?publisher=960478150` vil gi alle skos:Collection, siden parameteren `publisher` ikke finnes.

**Comment by shenluna** [comment]
@KurtStian Kan denne lukkes? Se svaret fra Nils Ove

**Comment by KurtStian** [comment]
@shenluna 
Har spurt Stig om denne da jeg ikke i utgangspunktet er enig om at den er løst så lenge URL-en ikke er endret til det som står på saken (og som var avklart med Stig). Men har ikke fått svar. Skal purre.

**Comment by stigbd** [comment]
No fungerer i alle fall :
```
curl -H "Accept: text/turtle" https://concept-catalog.fellesdatakatalog.digdir.no/collections/960478150
```
Så dermed foreslår eg at det er denne som skal brukast for høsting av alle begreps-collections for ein organisasjon.

**Comment by KurtStian** [comment]
OK, enig med Stig. Siden en begrepssamling i SKOS-standarden er definert som skos:Collection kan høsteendepunktet ved autogenerering av datakilden til concept-catalog være: 
**https://concept-catalog.fellesdatakatalog.digdir.no/collections/<orgNummer**

(Så kan man jo alltids diskutere om det da egentlig burde hete collection-catalog i stedet for concept-catalog 😋)

**Comment by shenluna** [comment]
Da lukker jeg denne saken utfra kommentarene som er skrevet. Ref. det Nils Ove skriver om at https://concept-catalog.fellesdatakatalog.digdir.no og https://registrering-begrep-api.fellesdatakatalog.digdir.no er ekvivalente. Overgang til concept-catalog tar vi i et eget issue.
