### ISSUE TITLE
manglende hjelpetekst i registreringsløsning for "Kan alle få tilgang"?

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#346]
Under "Kan alle få tilgang?" i bolken "Tilgang" i Datatjenestekatalogen, er hjelpeteksten ufullstendig:

![image](https://user-images.githubusercontent.com/32771488/120186851-59672b00-c214-11eb-964f-1cae3e8664d0.png)

**Comment by KurtStian** [comment]
Denne er dublett til [267](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/267)

**Comment by RogerSOlsen** [comment]
Lukkes fordi dette er en dublett av 267
