### ISSUE TITLE
Feil i summering over antall behandlingsaktiviteter i registreringsløsningen for en organisasjon

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#354]
For Mattilsynet står det at det finnes 10 behandlingsaktiviteter, men når man åpner behandlingsoversiktkatalogen så ser man at det finnes 83 godkjente behandlingsaktiviteter (per 1/6) samt mange med status "utkast".

![image](https://user-images.githubusercontent.com/43232700/120295117-2467e080-c2c7-11eb-9415-1a28c63e1a77.png)
![image](https://user-images.githubusercontent.com/43232700/120295454-6db83000-c2c7-11eb-9d4e-158acad3bc9d.png)

**Comment by KurtStian** [comment]
Jeg har testet på Mattilsynet og der kommer det nå riktig antall (126 per 3/6). (Tok ut alle behandlingsaktivitetene i et regnearket og kunne så se antall rader.)

**Comment by KurtStian** [comment]
@shenluna Skal jeg bare lukke denne saken siden den er testet OK i prod?

**Comment by shenluna** [comment]
@KurtStian Ja det må du gjerne gjøre. Veldig fint at du har fått testet det og at det ser bra ut :)
