### ISSUE TITLE
Lage CMS for driftsmeldinger

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#356]

**Comment by stigbd** [comment]
Her bør vi gjenbruke eksisterande cms. Vi kan også opprette egene dokument-typer for dette.

**Comment by shenluna** [comment]
Det er blitt opprettet et dokument type med navn service messages for driftsmeldinger
![image](https://user-images.githubusercontent.com/73637969/132180965-ba6143f5-b8d5-4bdb-b248-edd1c6e93bcb.png)
