### ISSUE TITLE
Feil justering av kolonneoverskriften "Sist endret" på oversiktsiden til datasettkatalog i registreringsløsningen

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#364]
Kolonneoverskriften "Sist endret" er høyrejustert mens datoen er venstrejustert. I tillegg er de andre overskriftenten i tabellen venstrejustert.

Eks.: 
![image](https://user-images.githubusercontent.com/43232700/121179513-23532800-c860-11eb-8c9c-17c16ea72d5d.png)

**Comment by joachim-me** [comment]
Ikke lenger aktuell. Ny løsning underveis.
