### ISSUE TITLE
Lag eksempel på sparql-spørring til bruk i data.norge.no/sparql

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#369]
Lag eksempel på sparql-spørring som tar ut alle datasett med følgende informasjon:

- Tittel/navn på datasett
- Beskrivelse
- Eier av datasett
- Dato for publisert og/eller sist endret
- Lenke til datasett på data.norge.no

**Comment by stigbd** [comment]
Ta kontakt med @KurtStian som vidareformidlar denne til brukar som har stilt spørsmål.

**Comment by NilsOveTen** [comment]
> Dato for publisert og/eller sist endret

publisert / sist endret i fdk eller publisert / sist endret fra der vi høster fra?

**Comment by KurtStian** [comment]
@NilsOveTen 

Angående: 

Dato for publisert og/eller sist endret
publisert / sist endret i fdk eller publisert / sist endret fra der vi høster fra?

---

Dato publisert i FDK 
Eks.:
![image](https://user-images.githubusercontent.com/43232700/122898218-fd8f4e00-d34a-11eb-88d2-13b1507f7cb5.png)

Når det gjelder sist endret, tenkte jeg i utgangspunktet på "Sist endret/oppdatert i FDK". 

Visste ikke at vi også hadde egen dato for når det ble sist endret fra der vi høster fra. Men blir ikke ofte disse datoene lik hvis det er kontinuerlig høsting?

**Comment by NilsOveTen** [comment]
```
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?fdkURI ?eier ?publisert ?sistEndret
FROM <https://datasets.fellesdatakatalog.digdir.no>
WHERE {{
    ?dataset a dcat:Dataset .
    ?fdkURI foaf:primaryTopic ?dataset .
    ?fdkURI a dcat:CatalogRecord .
    ?fdkURI dct:issued ?publisert .
    ?fdkURI dct:modified ?sistEndret .
    ?catalog dcat:dataset ?dataset .
    OPTIONAL {{ ?dataset dct:publisher ?datasetPublisher . }}
    OPTIONAL {{ ?catalog dct:publisher ?catalogPublisher . }}
    BIND ( IF( EXISTS {{ ?dataset dct:publisher ?datasetPublisher . }},
        ?datasetPublisher, ?catalogPublisher ) AS ?publisher ) .
    OPTIONAL {{ ?publisher dct:identifier ?eier . }}
}}
```
Tittel og beskrivelse har flere språk-alternativer på mange datasett, så de vil få ett utslag pr språk og gi inntrykk av at det er flere datasett enn hva det faktisk er. Kan eventuelt prøve å legge på en lang if-else på å kun plukke ett språk pr datasett, men er det vil ta lang tid og er strengt tatt usikker på om det er mulig.

**Comment by KurtStian** [comment]
@NilsOveTen 
Mangler tittel og beskrivelse.
Lenken kan ikke nås (403)
På eier kommer det org.nr, og det er sikkert greit. Er det enkelt å heller vise navnet på enheten i stedet for org.nr.?

![image](https://user-images.githubusercontent.com/43232700/122906208-33840080-d352-11eb-885e-be7f2f6b6e1f.png)

**Comment by NilsOveTen** [comment]
@KurtStian 
> Mangler tittel og beskrivelse.
Som jeg sa ovenfor. Tittel og beskrivelse har flere språk, så det vil resultere i flere treff per datasett. Det vil da se ut som at det er flere datasett enn hva det faktisk er.

> Lenken kan ikke nås (403)
Hvilken lenke er det som ikke kan nås?

> På eier kommer det org.nr, og det er sikkert greit. Er det enkelt å heller vise navnet på enheten i stedet for org.nr.?
Kan legge til det offisielt registrerte navnet, siden det ikke finnes flere språkalternativer. Men med prefLabel vil vi få samme problem som for tittel for datasettet, vil få flere treff per organisasjon

**Comment by NilsOveTen** [comment]
Med offisielt registrert navn i stedet for orgnr:
```
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?fdkURI ?eier ?publisert ?sistEndret
FROM <https://datasets.fellesdatakatalog.digdir.no>
WHERE {{
    ?dataset a dcat:Dataset .
    ?fdkURI foaf:primaryTopic ?dataset .
    ?fdkURI a dcat:CatalogRecord .
    ?fdkURI dct:issued ?publisert .
    ?fdkURI dct:modified ?sistEndret .
    ?catalog dcat:dataset ?dataset .
    OPTIONAL {{ ?dataset dct:publisher ?datasetPublisher . }}
    OPTIONAL {{ ?catalog dct:publisher ?catalogPublisher . }}
    BIND ( IF( EXISTS {{ ?dataset dct:publisher ?datasetPublisher . }},
        ?datasetPublisher, ?catalogPublisher ) AS ?publisher ) .
    OPTIONAL {{ ?publisher rov:legalName ?eier . }}
}}
```
Med både orgnr og offisielt registrert navn:
```
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?fdkURI ?eier ?eierOrgNr ?publisert ?sistEndret
FROM <https://datasets.fellesdatakatalog.digdir.no>
WHERE {{
    ?dataset a dcat:Dataset .
    ?fdkURI foaf:primaryTopic ?dataset .
    ?fdkURI a dcat:CatalogRecord .
    ?fdkURI dct:issued ?publisert .
    ?fdkURI dct:modified ?sistEndret .
    ?catalog dcat:dataset ?dataset .
    OPTIONAL {{ ?dataset dct:publisher ?datasetPublisher . }}
    OPTIONAL {{ ?catalog dct:publisher ?catalogPublisher . }}
    BIND ( IF( EXISTS {{ ?dataset dct:publisher ?datasetPublisher . }},
        ?datasetPublisher, ?catalogPublisher ) AS ?publisher ) .
    OPTIONAL {{ ?publisher rov:legalName ?eier . }}
    OPTIONAL {{ ?publisher dct:identifier ?eierOrgNr . }}
}}
```

**Comment by KurtStian** [comment]
@NilsOveTen 
Ønsker tittel og beskrivelse, ellers så gir ikke spørringen så mye mening. Helst med kun bokmål. men hvis dette medfører mye jobb får man i første omgang akseptere at samme datasett kommer flere ganger. Er det da mulig å ta ut språk slik at bruker kan sortere/filtrere?

Lenken som hentes ut ved spørring (den som bruker skal bruke for finne datasettet i data.norge.no (portalen) :
![image](https://user-images.githubusercontent.com/43232700/122909650-b22e6d00-d355-11eb-83f4-12b331ba0dcb.png)

"Med både orgnr og offisielt registrert navn:" - denne er fin :-)

**Comment by NilsOveTen** [comment]
@KurtStian 
Ah, det er jo selvfølgelig lenke til portal dere vil ha. Det der er en lenke til rdf-data. Den er dog helt åpen, litt usikker på hvordan du fikk 403.
Portal er uansett ikke noe rdf-dataene vet noe om, jeg kan prøve å bygge opp en portal-uri ut fra id. Skal se på det i morgen.

Skal også fikse noen spørringer m. div alternativer ang. tittel og beskrivelse i morgen.

**Comment by KurtStian** [comment]
@NilsOveTen 
Måtte være noe grums som hang igjen i nettleser. Da jeg slettet nettleserdata fikk jeg lenken til å fungere. Men som du skriver er det lenke til datasettet i portalen jeg ønsker :-)

Supert om du kan få sett på dette i morgen slik at jeg får svart ut saken på servicedesken.

**Comment by jeffreiffers** [comment]
`PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?portalUri ?eier ?eierOrgNr ?publisert ?sistEndret
FROM <https://datasets.fellesdatakatalog.digdir.no>
WHERE {{
    ?dataset a dcat:Dataset .   
    ?fdkURI foaf:primaryTopic ?dataset .
    ?fdkURI a dcat:CatalogRecord .
    ?fdkURI dct:issued ?publisert .
    ?fdkURI dct:modified ?sistEndret .
    ?catalog dcat:dataset ?dataset .
    OPTIONAL {{ ?dataset dct:publisher ?datasetPublisher . }}
    OPTIONAL {{ ?catalog dct:publisher ?catalogPublisher . }}
    BIND ( IF( EXISTS {{ ?dataset dct:publisher ?datasetPublisher . }},
        ?datasetPublisher, ?catalogPublisher ) AS ?publisher ) .
    BIND ( replace(str(?fdkURI), "datasets.fellesdatakatalog.digdir.no", "data.norge.no") as ?portalUri ) .
    OPTIONAL {{ ?publisher rov:legalName ?eier . }}
    OPTIONAL {{ ?publisher dct:identifier ?eierOrgNr . }}
}}`

**Comment by KurtStian** [comment]
@jeffreiffers 
![image](https://user-images.githubusercontent.com/43232700/122935593-c2077a80-d370-11eb-9a9a-08186b1a2c5d.png)

**Comment by jeffreiffers** [comment]
![image](https://user-images.githubusercontent.com/430997/122936184-3f32ef80-d371-11eb-9ef2-bd501f34b954.png)

**Comment by jeffreiffers** [comment]
https://data.norge.no/sparql#query=PREFIX%20rov%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fregorg%23%3E%0APREFIX%20dct%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX%20dcat%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0A%0ASELECT%20DISTINCT%20%3FportalUri%20%3Feier%20%3FeierOrgNr%20%3Fpublisert%20%3FsistEndret%0AFROM%20%3Chttps%3A%2F%2Fdatasets.fellesdatakatalog.digdir.no%3E%0AWHERE%20%7B%7B%0A%20%20%20%20%3Fdataset%20a%20dcat%3ADataset%20.%20%20%20%0A%20%20%20%20%3FfdkURI%20foaf%3AprimaryTopic%20%3Fdataset%20.%0A%20%20%20%20%3FfdkURI%20a%20dcat%3ACatalogRecord%20.%0A%20%20%20%20%3FfdkURI%20dct%3Aissued%20%3Fpublisert%20.%0A%20%20%20%20%3FfdkURI%20dct%3Amodified%20%3FsistEndret%20.%0A%20%20%20%20%3Fcatalog%20dcat%3Adataset%20%3Fdataset%20.%0A%20%20%20%20OPTIONAL%20%7B%7B%20%3Fdataset%20dct%3Apublisher%20%3FdatasetPublisher%20.%20%7D%7D%0A%20%20%20%20OPTIONAL%20%7B%7B%20%3Fcatalog%20dct%3Apublisher%20%3FcatalogPublisher%20.%20%7D%7D%0A%20%20%20%20BIND%20(%20IF(%20EXISTS%20%7B%7B%20%3Fdataset%20dct%3Apublisher%20%3FdatasetPublisher%20.%20%7D%7D%2C%0A%20%20%20%20%20%20%20%20%3FdatasetPublisher%2C%20%3FcatalogPublisher%20)%20AS%20%3Fpublisher%20)%20.%0A%20%20%20%20BIND%20(%20replace(str(%3FfdkURI)%2C%20%22datasets.fellesdatakatalog.digdir.no%22%2C%20%22data.norge.no%22)%20as%20%3FportalUri%20)%20.%0A%20%20%20%20OPTIONAL%20%7B%7B%20%3Fpublisher%20rov%3AlegalName%20%3Feier%20.%20%7D%7D%0A%20%20%20%20OPTIONAL%20%7B%7B%20%3Fpublisher%20dct%3Aidentifier%20%3FeierOrgNr%20.%20%7D%7D%0A%7D%7D&endpoint=https%3A%2F%2Fsparql.fellesdatakatalog.digdir.no&requestMethod=POST&tabTitle=Query&headers=%7B%7D&contentTypeConstruct=application%2Fn-triples%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table

**Comment by NilsOveTen** [comment]
Bra greier @jeffreiffers :+1: 

@KurtStian 
Du kan endre språk ved å endre `nb` i de siste to linjene, vanlige alternativer er `no`, `nn` og `en`. Du kan og fjerne de to linjene med `FILTER (lang...` for å få alle datasett med alle språkalternativer.

De aller fleste datasettene bruker enten `nb` eller `no`, så du vil finne det meste vha de to. Men det er noe overlapp. 

Skal jeg sette opp disse spørringene eller er du i mål?

**Comment by KurtStian** [comment]
@NilsOveTen 
Får du lenkene til å fungere? Jeg får denne:
![image](https://user-images.githubusercontent.com/43232700/123048006-39cfb680-d3fe-11eb-8d7d-d636b59904c3.png)

**Comment by jeffreiffers** [comment]
Ser ut at data.norge.no domenet er nede. Vi sjekker med drift.

**Comment by KurtStian** [comment]
@jeffreiffers  Er oppe igjen nå :-)

**Comment by jeffreiffers** [comment]
Supert! :)

**Comment by KurtStian** [comment]
@NilsOveTen 
I spørringen med filter på 'nb' får man 823 treff. Ideelt bør det være minst 1572 siden det er det som kommer opp som antall datasett på data.norge.no. Hvordan endrer man     
FILTER (lang(?title) = 'nb')
    FILTER (lang(?description) = 'nb')
  
 slik at man får med nynorsk eller engelsk - regner med at man får treff nærmere antallet 1572 da.

Når det gjelder språk så skriver du at det finnes språkformene no, nb, nn og en for disse feltene. Stemmer dette?
 
Ideelt skulle det ha vært slik at man fikk ut alle de 1572 datasettene (p.t.), med filtrering på hvilke språk som vises. Finnes det bokmål så vises dette, hvis ikke sjekkes det om det finnes nynorsk og ev. viser dette og hvis ikke dette finnes vises det engelsk. Men jeg antar at dette er mye jobb å få til slik at vi kan nok leve med denne spørringen.

**Comment by NilsOveTen** [comment]
Du kan fjerne filterene, da vil du få alle datasett med alle språkversjoner:
```
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?portalUri ?title ?description ?eier ?eierOrgNr ?publisert ?sistEndret
FROM <https://datasets.fellesdatakatalog.digdir.no>
WHERE {{
    ?dataset a dcat:Dataset .   
    ?fdkURI foaf:primaryTopic ?dataset .
    ?fdkURI a dcat:CatalogRecord .
    ?fdkURI dct:issued ?publisert .
    ?fdkURI dct:modified ?sistEndret .
    ?catalog dcat:dataset ?dataset .
    OPTIONAL {{ ?dataset dct:title ?title . }}
    OPTIONAL {{ ?dataset dct:description ?description . }}
    OPTIONAL {{ ?dataset dct:publisher ?datasetPublisher . }}
    OPTIONAL {{ ?catalog dct:publisher ?catalogPublisher . }}
    BIND ( IF( EXISTS {{ ?dataset dct:publisher ?datasetPublisher . }},
        ?datasetPublisher, ?catalogPublisher ) AS ?publisher ) .
    BIND ( replace(str(?fdkURI), "datasets.fellesdatakatalog.digdir.no", "data.norge.no") as ?portalUri ) .
    OPTIONAL {{ ?publisher rov:legalName ?eier . }}
    OPTIONAL {{ ?publisher dct:identifier ?eierOrgNr . }}
}}
```

**Comment by NilsOveTen** [comment]
Jeg regner med at det er mulig å legge til en rekke if-else greier ang språk, slik at vi alltid bare en versjon av hvert datasett.. Men er usikker på hvordan, så det vil uansett ta lang tid å knote meg frem til noe som fungerer, og kan ikke love at det faktisk er mulig.

**Comment by KurtStian** [comment]
@NilsOveTen  
Ja, jeg fikk med at jeg kan fjerne filteret for språk. Men du skrev samtidig:
 "_De aller fleste datasettene bruker enten nb eller no, så du vil finne det meste vha de to. Men det er noe overlapp._"

Hvordan får man med begge disse i samme spørring? Altså at man får de datasettene som har språk 'no' og 'nb', samt de som har både 'no' og 'nb' (ev. det samme for 'nb' og 'nn')

Stemmer det at det finnes språkformene 'no', 'nb', 'nn' og 'en' for disse feltene. 
(jf. _@KurtStian
Du kan endre språk ved å endre nb i de siste to linjene, vanlige alternativer er no, nn og en. Du kan og fjerne de to linjene med FILTER (lang... for å få alle datasett med alle språkalternativer.

De aller fleste datasettene bruker enten nb eller no, så du vil finne det meste vha de to. Men det er noe overlapp._

**Comment by NilsOveTen** [comment]
Ah, ja. Du kan legge til en `OR` i filteret:
```
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?portalUri ?title ?description ?eier ?eierOrgNr ?publisert ?sistEndret
FROM <https://datasets.fellesdatakatalog.digdir.no>
WHERE {{
    ?dataset a dcat:Dataset .   
    ?fdkURI foaf:primaryTopic ?dataset .
    ?fdkURI a dcat:CatalogRecord .
    ?fdkURI dct:issued ?publisert .
    ?fdkURI dct:modified ?sistEndret .
    ?catalog dcat:dataset ?dataset .
    ?dataset dct:title ?title .
    ?dataset dct:description ?description .
    OPTIONAL {{ ?dataset dct:publisher ?datasetPublisher . }}
    OPTIONAL {{ ?catalog dct:publisher ?catalogPublisher . }}
    BIND ( IF( EXISTS {{ ?dataset dct:publisher ?datasetPublisher . }},
        ?datasetPublisher, ?catalogPublisher ) AS ?publisher ) .
    BIND ( replace(str(?fdkURI), "datasets.fellesdatakatalog.digdir.no", "data.norge.no") as ?portalUri ) .
    OPTIONAL {{ ?publisher rov:legalName ?eier . }}
    OPTIONAL {{ ?publisher dct:identifier ?eierOrgNr . }}
 	FILTER (lang(?title) = 'nb' || lang(?title) = 'no')
    FILTER (lang(?description) = 'nb' || lang(?title) = 'no')
}}
```

**Comment by NilsOveTen** [comment]
Det er litt færre og det er sikkert noen få datasett som kommer dobbelt, men den er nok det nærmeste vi kommer uten mye knoting.

**Comment by KurtStian** [comment]
@NilsOveTen Tror vi er ganske nær. Kommer ut 1570 datasett og i følge data.norge er det 1572 datasett. Selvfølgelig kan det vel være at det fremdeles kommer datasett som er dobbelt slik at vi mangler flere enn 2 datasett, men dette er bra :-)

**Comment by NilsOveTen** [comment]
@KurtStian 
Det var en skrivefeil i forrige, henter `title@no` i stedet for description
Og ko i tillegg på at det sikkert er greit å ta med de som ikke har definert språk i det hele tatt. Får da 1573:
```
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?portalUri ?title ?description ?eier ?eierOrgNr ?publisert ?sistEndret
FROM <https://datasets.fellesdatakatalog.digdir.no>
WHERE {{
    ?dataset a dcat:Dataset .   
    ?fdkURI foaf:primaryTopic ?dataset .
    ?fdkURI a dcat:CatalogRecord .
    ?fdkURI dct:issued ?publisert .
    ?fdkURI dct:modified ?sistEndret .
    ?catalog dcat:dataset ?dataset .
    ?dataset dct:title ?title .
    ?dataset dct:description ?description .
    OPTIONAL {{ ?dataset dct:publisher ?datasetPublisher . }}
    OPTIONAL {{ ?catalog dct:publisher ?catalogPublisher . }}
    BIND ( IF( EXISTS {{ ?dataset dct:publisher ?datasetPublisher . }},
        ?datasetPublisher, ?catalogPublisher ) AS ?publisher ) .
    BIND ( replace(str(?fdkURI), "datasets.fellesdatakatalog.digdir.no", "data.norge.no") as ?portalUri ) .
    OPTIONAL {{ ?publisher rov:legalName ?eier . }}
    OPTIONAL {{ ?publisher dct:identifier ?eierOrgNr . }}
    FILTER (lang(?title) = 'nb' || lang(?title) = 'no' || lang(?title) = '')
    FILTER (lang(?description) = 'nb' || lang(?description) = 'no' || lang(?description) = '')
}}
```

**Comment by KurtStian** [comment]
Saken er nå besvart i HPSM. Kommer også til å legge ut eksemplet på wikiområdet til kanalen "Servicedesk".
Takk for hjelpen @NilsOveTen  og @jeffreiffers 😊
