### ISSUE TITLE
Informasjonsmodeller - lenke for alternative formater (dct:hasFormat) virker ikke

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#372]
Gjelder modeller generert på bakgrunn av Open API-spesifikasjoner og egenskapen for alternative formater (dct:hasFormat).

Se f.eks. 
![image](https://user-images.githubusercontent.com/17720749/123617961-0af37f00-d808-11eb-897c-a655ca256e60.png)

De samme gjelder for egenskapen "i samsvar med" (dct:conformsTo). Jeg vet ikke hvorfor det er lagt inn en URL her og hva den er ment å peke på (er ikke etterspurt fra behovssiden). I tillegg vises Versjon for egenskapen uten at den har noen verdi. Hvis versjon på "i samsvar med" ikke har noen verdi, skal ikke Versjon vises. 
![image](https://user-images.githubusercontent.com/17720749/123618895-e9df5e00-d808-11eb-9c28-6d12ebdef838.png)

Gjelder modell: https://data.norge.no/informationmodels/14a8758e-d467-3dbf-8a90-64b6914cc45f

Det som gikk på dct:conformsTo er nå lagt i et eget issue, #375

**Comment by stigbd** [comment]
Dette issuet bør splittes i to. Eitt som går på "alternativ representasjon", og eitt som går på conformsTo.

Kommentar til conformsTo: dette api-et er i samsvar med standard bank-api spesifikasjon frå bits. Det er kritisk informasjon for blant anna DSOP-kontroll, og er publisert av oss. Sjå feks her:
https://data.norge.no/dataservices/d26e8d82-ac60-3dab-a333-71f619539710

Her vises conformsTo som "Tjenestetype".

**Comment by ToHelland** [comment]
@stigbd Ja, vi kan splitte det opp. Vedrørende conformsTo. Siden lenken ikke førte meg noen sted, var jeg usikker på hva man refererer til. Men her må være obs på hvordan man peker. Det spesielle med modellene vi har høstet fra Open API specification, er jo at dette  er en bottom up tilnærming. På den andre siden knytter vi jo informasjonsmodeller til API ved å si at datatjenesten (API'et) er conformTo informasjonsmodellen. Får vi da en sirkelreferanse?

**Comment by ToHelland** [comment]
Jeg har nå  laget et eget issue for dct:conformsTO, se #375

**Comment by matsjs** [comment]
Vi ser at det er utfordringer knyttet til URI'er. Foreslår et kort møte mellom @ToHelland, @stigbd og meg.

**Comment by ToHelland** [comment]
@shenluna Dette er nå riktig:-)

**Comment by shenluna** [comment]
Testet og verifisert av Tore, lukker saken
