### ISSUE TITLE
E-postadressen i bunnteksten til Datalandsbyen er ikke satt opp riktig

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#373]
E-postadressen er satt opp som en HTML-lenke i stedet for HTML e-postkobling (mailto).

Får denne meldingen/siden når jeg klikker på e-postadressen:

![image](https://user-images.githubusercontent.com/43232700/123928093-d7daf800-d98d-11eb-99ff-dc32033e96c7.png)

**Comment by shenluna** [comment]
Testet OK
