### ISSUE TITLE
Avvik i antall begreper - fane i Begrepskatalog vs. Rapport

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/fdk-issue-tracker#376]
I oversikten over kataloger i Felles datakatalog portal vises et annet antall begreper enn under menyen Verktøy/Rapporter.
(Det virker som om oppdateringen på rapportsiden er forsinket)

**Comment by KurtStian** [comment]
Det er også avvik i antallet for API og Informasjonsmodell. Når man sjekker for API og Informasjonsmodell så kan det se ut som at siste oppdatering er rundt 26. mai.

**Comment by NilsOveTen** [comment]
Det er fdk-reports-bff feiler, har startet på en større refaktorering. Epic her: https://github.com/Informasjonsforvaltning/fdk-reports-bff/issues/71

Skal dog få forbedret tallene før hele refaktoreringen er ferdig.

API fungerer egentlig, men har ikke blitt oppdatert fordi den ventet på at begrep skulle oppdateres. Så det skal bli bedre etter denne: https://github.com/Informasjonsforvaltning/fdk-reports-bff/issues/70

Informasjonsmodeller og begrep er de største feilene, her har fdk-reports-bff avhengighet til utdaterte kall. Har issue for disse her: https://github.com/Informasjonsforvaltning/fdk-reports-bff/issues/73 og https://github.com/Informasjonsforvaltning/fdk-reports-bff/issues/68

**Comment by shenluna** [comment]
Tallene for informasjonsmodeller er det fremdeles avvik på. Dette løses i https://github.com/Informasjonsforvaltning/fdk-informationmodel-harvester/issues/80

**Comment by shenluna** [comment]
Testet og verifisert OK
