### ISSUE TITLE
begreper mangler i datasettbeskrivelsen "Enhetsregisteret"

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#377]
Datasettbeskrivelsen "Enhetsregisteret" hadde tidligere mange begreper tilknyttet. Nå mangler alle unntatt ett. 
Brønnøysundregistrene har meldt at de ikke har fjernet begrepene i datasettbeskrivelsen. 

Litt historikk i tilfelle det har betydning for feilsøking:

Datasettbeskrivelsen ble avpublisert av BR 27.04.2021. 
BR melder 29/4 at de ikke får publisert på nytt. 
Jeg svarte 29/4 at feltet «Tilgangslenke» for distribusjon 4 «Sektorkoder» ikke var fylt ut. Tilgangslenke er et obligatorisk felt
Jeg kontaktet BR 21/5 og etterlyste datasettbeskrivelsen i portalen. Fikk svar samme dag om at den nå var publisert.
Jeg oppdaget 25/5 at datasettbeskrivelsen som tidligere hadde mange begreper, nå var tilknyttet kun ett begrep og kontaktet BR for å spørre om dette var riktig.
Fikk svar 2/6 om  at de ikke gjort noen endringer i forhold til begreper. De hadde kun endret datasettbeskrivelsens tilgangsnivå til offentlig.

Slik jeg forstår det, har BR også opplevd andre problemer med knytting mellom datasettbeskrivelser og begreper i denne perioden.

**Comment by joachim-me** [comment]
@RogerSOlsen Er dette fortsatt tilfelle?

**Comment by RogerSOlsen** [comment]
Vi ikke har kunnet gjenskape registreringen slik den var før begrepene forsvant. Datasetteier er oppfordret til å registrere knytning til begreper på nytt. Saken er derfor lukket
