### ISSUE TITLE
Mulig feil knyttet til "search all" i portalen

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#379]
Hva kan være årsaken til denne feilmeldingen?
Frontend-alerts: 
https://fdk-project.slack.com/archives/C01SEH2JVNW/p1625556143000500
![image](https://user-images.githubusercontent.com/43232700/124568336-16b4f600-de45-11eb-9853-dad5e4061bd7.png)

Fra logg:
![image](https://user-images.githubusercontent.com/43232700/124567857-a60dd980-de44-11eb-99a1-f73f9a9a13b5.png)
{
  "insertId": "000000-74062d99-046b-4d4e-bd5d-faa945d5fd67",
  "jsonPayload": {
    "application": "fdk-portal",
    "location": "https://data.norge.no/search-all",
    "message": "Cannot read property '0' of null",
    "name": "TypeError",
    "image": "1e8c176c973098a45f7ab60e300fc15089216fe5",
    "trace": "\n    at i (https://data.norge.no/main.51855b35.02c3ed72efbac7c8e6ab.js:1:7079)\n    at div\n    at _ (https://data.norge.no/main.vendor.styled-components.bundle.js:1:14587)\n    at i (https://data.norge.no/main.8a003484.961a98da28b243efdf67.js:1:4054)\n    at div\n    at _ (https://data.norge.no/main.vendor.styled-components.bundle.js:1:14587)\n    at section\n    at _ (https://data.norge.no/main.vendor.styled-components.bundle.js:1:14587)\n    at p (https://data.norge.no/main.8a003484.961a98da28b243efdf67.js:1:5764)\n    at div\n    at H (https://data.norge.no/main.51855b35.02c3ed72efbac7c8e6ab.js:1:12529)\n    at w (https://data.norge.no/main.vendor.react-redux.b422d2cc.69fe4f019fb58ad66325.js:1:2358)\n    at ErrorBoundary (https://data.norge.no/main.1eb98410.75631a4b662400e9fbcb.js:1:16128)\n    at w (https://data.norge.no/main.vendor.react-redux.b422d2cc.69fe4f019fb58ad66325.js:1:2358)\n    at t (https://data.norge.no/main.vendor.react-resolver.bundle.js:1:1566)\n    at s (https://data.norge.no/main.vendor.react-resolver.bundle.js:1:12006)\n    at n (https://data.norge.no/main.vendor.react-router.bundle.js:1:3330)\n    at n (https://data.norge.no/main.vendor.react-router.bundle.js:1:3956)\n    at div\n    at k (https://data.norge.no/main.9f4db315.a1422501eadef36c6eae.js:1:490)\n    at ErrorBoundary (https://data.norge.no/main.1eb98410.75631a4b662400e9fbcb.js:1:16128)\n    at w (https://data.norge.no/main.vendor.react-redux.b422d2cc.69fe4f019fb58ad66325.js:1:2358)\n    at n (https://data.norge.no/main.vendor.react-router.bundle.js:1:3330)\n    at n (https://data.norge.no/main.vendor.react-router.bundle.js:1:673)\n    at t (https://data.norge.no/main.vendor.react-router-dom.bundle.js:1:413)\n    at n.Z (https://data.norge.no/main.vendor.react-redux.b422d2cc.69fe4f019fb58ad66325.js:1:308)\n    at f (https://data.norge.no/main.4e69d7e4.d1b54e20f23e57046804.js:1:1661)\n    at Tt (https://data.norge.no/main.vendor.styled-components.bundle.js:1:12668)\n    at J (https://data.norge.no/main.vendor.fellesdatakatalog.bundle.js:1:34281)",
    "namespace": "prod"
  },
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "digdir-cloud-functions",
      "function_name": "cloud-logging",
      "region": "europe-west1"
    }
  },
  "timestamp": "2021-07-06T07:20:27.519Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "5jv2krf1zmld"
  },
  "logName": "projects/digdir-cloud-functions/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/digdir-cloud-functions/traces/a6382ed90de0e64fd06936652d505beb",
  "receiveTimestamp": "2021-07-06T07:20:38.483749874Z"
}

https://console.cloud.google.com/logs/query;cursorTimestamp=2021-07-06T07:20:27.519Z;query=jsonPayload.namespace%3D%22prod%22%0Aseverity%3DERROR%0Aresource.type%3D%22cloud_function%22%20resource.labels.function_name%3D%22cloud-logging%22%0Atimestamp%3D%222021-07-06T07:20:27.519Z%22%0AinsertId%3D%22000000-74062d99-046b-4d4e-bd5d-faa945d5fd67%22;timeRange=2021-07-06T07:17:22.000Z%2F2021-07-06T07:24:52.000Z?project=digdir-cloud-functions

**Comment by jeffreiffers** [comment]
Vi er ikke 100% sikkert om dette løser problemet men @matsjs har gjort en del forbedringer i https://github.com/Informasjonsforvaltning/fdk-portal/issues/974

**Comment by shenluna** [comment]
Denne har ikke vært observert på ca en måned, rundt tiden Mats sine forbedringer ble prodsatt. Jeg lukker derfor saken. Vi ser nærmere på dette hvis det skulle oppstå igjen.
