### ISSUE TITLE
Endre logo i demomiljø publiseringsportal

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#380]
I demomiljø skal logo skiftes ut med denne, slik at det er synlig hvilket miljø man er inne i. Gjelder også alle "undersider" av publiseringsportal.

![Felles datakatalog - publisering demo.svg](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/8ef79d5c-9501-4016-918d-fe98ee7b007f)

**Comment by frederik-ronnevig** [comment]
Issue moved to [Informasjonsforvaltning/fdk-portal #1028](https://github.com/Informasjonsforvaltning/fdk-portal/issues/1028) via [**ZenHub**](https://www.zenhub.com/)
