### ISSUE TITLE
legg inn tittel på informasjon i starten av HTML-rapporter

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#382]
I bolk "Kontaktinformasjon" er det tittel på følgende felt:

- Navn på behandlingsansvarliges representant
- Virksomhetens postadresse
- Virksomhetens e-post
- Virksomhetens telefon

I bolk "Personvernombud" er det tittel på følgende felt:

- Navn 
- Postadresse
- E-post
- Telefon

![image](https://user-images.githubusercontent.com/32771488/124740463-1c7d0b00-df1b-11eb-829a-65906830d7d7.png)

Disse tittelfeltene mangler i HTML-rapportene "Behandlingsoversikt" og "Protokoll". Titlene må derfor inn i begge rapportene slik at det er tydelig hva informasjonen innebærer. Her er samme informasjon fra rapport hvor det er markert med gult hvor tittel på feltene mangler:
![image](https://user-images.githubusercontent.com/32771488/124741412-f441dc00-df1b-11eb-9a1b-45e3e17420bd.png)

**Comment by shenluna** [comment]
@LeneSundsbo Kan du ta en titt på hvordan dette bør vises?

**Comment by joachim-me** [comment]
Flyttet til behandlingsoversikt: https://github.com/behandlingsoversikt/records-of-processing-activities-gui/issues/305
