### ISSUE TITLE
Detaljside begrep - endre overskrift fra beskrivelse til definisjon

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#383]
Overskriften beskrivelse skal endres til definisjon, slik at vi er i henhold til begrepsstandarden:
![image](https://user-images.githubusercontent.com/46488929/124907132-17d25880-dfe8-11eb-8cf0-fd8026114790.png)

Husk å endre for alle språk + venstremeny.

**Comment by shenluna** [comment]
Testet OK
![image](https://user-images.githubusercontent.com/73637969/128679697-28b54917-40d3-4426-b764-4e8a39f41ce6.png)

**Comment by shenluna** [comment]
Verifisert OK
