### ISSUE TITLE
Detaljside modell - skrivefeil: Enkeltype skal skrives med en "l"

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#384]
I dag står det "Enkelttype". Skal rettes til Enkeltype.

![image](https://user-images.githubusercontent.com/46488929/124907737-cd051080-dfe8-11eb-877a-7b2a49add286.png)

**Comment by shenluna** [comment]
Testet og verifisert OK
