### ISSUE TITLE
Antall «Tjenester og hendelser» er ikke tatt med i det totale antallet i arkfanen «Alle»

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#385]
Antallet i arkfanen «Alle»  inneholder ikke antall tjenester og hendelser, kun totalsummen av antall Datasett, API-er, Begreper og Informasjonsmodeller.

![image](https://user-images.githubusercontent.com/43232700/125927000-c580d2d4-da97-403a-a351-66216936ed94.png)

Datasett 1587 + API-er 168 +Begreper 5203 + Informasjonsmodeller 153 + Tjenester og hendelser 34 = 7145

**Comment by oyvindis** [comment]
Det ble tidligere sagt at antallet fra Tjenester ikke skulle inkluderes i totalen på Alle-fanen så lenge Tjenester er i Beta.
Men vi kan endre dette til en feature og legge til ;-)

**Comment by joachim-me** [comment]
Avventer til vi har annet enn eksempeldata.

**Comment by KjerstiSteien** [comment]
Lukker saken, da vi ikke viser et total-tall på tvers av ressurser lenger.
