### ISSUE TITLE
Ved søk så vises ikke antall treff for Tjenester og hendelser i teksten over søkefeltet

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#387]
Eks.:
![image](https://user-images.githubusercontent.com/43232700/125931616-e302ea78-0754-4dbd-b958-baa9c6759e7c.png)

**Comment by joachim-me** [comment]
Avventer til vi har reelle data

**Comment by KjerstiSteien** [comment]
Vil vi kunne vise riktige tall i denne teksten når vi kommer over 10 000 treff?
