### ISSUE TITLE
Bilder vises ikke på enkelte av informasjonssidene

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#388]
Bilder vises ikke på disse informasjonssidene i FDK:

- https://data.norge.no/publishing/about-registration (Hjelp til å registrere)
- https://data.norge.no/publishing/about-harvesting (Hjelp til å høste dataendepunkter)

Ser at bilde vises hvis det i cms-et er lagt inn bilde i «modul Bilde» (som f.eks. bildet fra Altinn i Hjelp til å registrere). Men hvis bildet er lagt til i modulen Brødtekst i cms-et så vises det ikke i FDK. Dette var i orden, i hvert fall på siden «Hjelp til å høste dataendepunkter», i juni. (Tror det var i uke 25 jeg så det sist).

Sammenligning mellom FDK og CMS
FDK:
![image](https://user-images.githubusercontent.com/43232700/125940081-3732c078-0c6d-49b2-bfb4-94b9935bd9f3.png)

CMS:
![image](https://user-images.githubusercontent.com/43232700/125940275-95fdfd8e-f936-4895-86b1-722712988e07.png)

FDK:
![image](https://user-images.githubusercontent.com/43232700/125940403-48d6e724-88d2-40c8-85da-40a4cbf59254.png)

CMS:
![image](https://user-images.githubusercontent.com/43232700/125940570-22333af9-05c5-4e5a-a242-f88abb0cbb47.png)

**Comment by joachim-me** [comment]
Testet ok.
