### ISSUE TITLE
Informasjonsmodeller - navnløse objekttyper

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#390]
Fikk en tilbakemelding på at det manglet tittel på en objekttype for følgende modell:
![image](https://user-images.githubusercontent.com/17720749/128145224-56c9f97b-c3db-4a97-8139-08b836255aa7.png)

Denne er generert på bakgrunn av Open API specification. Når jeg ser på json-filen, så mangler dette objektet et navn. Så det er ikke noe feil med mappingen til ModellDCAT-AP-NO. Jeg synes heller ikke at vi skal generere noe navn i denne sammenhengen, for vi vil jo gjenspeile det faktiske forholdet.

Som man ser i json-filen har ikke objektet et navn: 
![image](https://user-images.githubusercontent.com/17720749/128146020-54b4a4da-0a6f-4d4f-9dff-38a3638d042e.png)

Forslag:
I slike tilfeller presenterer vi objekttypen, evt. andre modellelementer/egenskaper uten tittel, med tittel _(uten tittel)_ i strukturvisningen (NB! De skal ikke tildeles tittel ved mapping fra json til RDF-serialiseringer, kun visning).  
![image](https://user-images.githubusercontent.com/17720749/128148612-43445533-9997-4d6e-8814-d6e5c815efc8.png)

Denne tittelen vises også når man refererer til de navnløse modellelementene (f.eks. roller og komposisjoner):
![image](https://user-images.githubusercontent.com/17720749/128148049-47fea850-528d-4bd5-8d4e-5f3f973ad027.png)

**Comment by ToHelland** [comment]
@stigbd @matsjs Fint om dere kunne uttale dere om dette.

**Comment by stigbd** [comment]
Dette kan vere ein bug av oss. Eg er ikkje sikker på at eg forventar at det skal opprettast ein ny type i slike allof konstruksjonar.

Sjekk feks korleis det ser ut i editor.swagger.io når du paster spekken inn der. Der finn du ikkje tilsvarande "blanke" node.

**Comment by ToHelland** [comment]
@stigbd @matsjs Det var interessant  å se det i swagger-editoren. Der presenteres ikke objekttypen som du sier. På den andre siden tilfører den navneløse objekttypen ingen ting slik det er nå i spesifikasjonsfilen. Men man kunne tenke seg at forekomsten (multiplisiteten) av objektet var påkrevd, mens propertiene hadde en annen forekomst. Det kan hende at det likevel er det beste å behandle disse blanke nodene ved at vi "flytter" opp propertiene til den overordnede objekttypen, i dette tilfellet PagedLegalEntityResults. Men jeg forstår det slik at noen responser kan kun bestå av et navneløst objekt med egenskaper. Men disse objektene vil da være definert i forbindelse med responsen, ikke under schemas).  Men du vil da ikke kunne kjøre reverse engineering, fra informasjonsmodell til Json S hvis dette skulle være aktuelt, f.eks. i forbindelse med Altinn.

**Comment by ToHelland** [comment]
Vi behandler slike tilfeller som en blank node. 
Json-uttrykket:
#Json
#"PagedLegalEntityResults": {
    #    "description": "The result of searching for legal entities.",
    #    "allOf": [
    #      {
    #        "$ref": "#/components/schemas/LegalEntityResults"
    #      },
    #      {
      #      "type": "object",
      #      "description": "The result of searching for legal entities.",
      #      "additionalProperties": false,
      #      "properties": {
        #      "page": {
        #        "type": "integer",
        #        "description": "The page number returned.",
          #      "format": "int32"
          #    },
          #    "total": {
          #      "type": "integer",
            #    "description": "The total number of legal entities that match the query.",
            #    "format": "int32"
            #  }
            #}
          #}
        #]
      #},

Mappes da til:
#Turtle
ex-blankNode:PagedLegalEntityResult   a     modelldcatno:ObjectType ;
        dct:title             "PagedLegalEntityResult"@en ;
        modelldcatno:hasProperty ex-blankNode:legalEntityResults , ex-blankNode:page , ex-blankNode:total .
ex-blankNode:legalEntityResults   a         modelldcatno:Composition ; #kompososjon, tar navn etter objektet det refererer til.
        dct:title             "legalEntityResults"@en ;
        xsd:minOccurs         "0" ;
        xsd:maxOccurs         "1" ;
        modelldcatno:contains ex-blankNode:LegalEntityResults .
ex-blankNode:page              a       modelldcatno:Attribute ; #Attributt
        dct:title             "page"@en ;
        xsd:minOccurs         "0" ;
        xsd:maxOccurs         "1" ;
        modelldcatno:hasSimpleType  ex-blankNode:int32 .
  ex-blankNode:int32        a         modelldcatno:SimpleType ;
        dct:title             "int32"@en ;
        modelldcatno:typeDefinitionReference "https://swagger.io/specification/#data-types"^^xsd:anyURI .

**Comment by jeffreiffers** [comment]
Ser ut som måten vi håndterer dette i RDF er riktig (slå sammen skjema som ligger i allOf. Ser ut at Swagger gjør det samme.

![image](https://user-images.githubusercontent.com/430997/190067429-228de540-ca11-408d-a2d9-35cdb16416c2.png)
