### ISSUE TITLE
Informasjonsmodeller - manglende objekttyper og egenskaper

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#391]
Se modell https://data.norge.no/informationmodels/4eca6c1c-5efc-3cea-87a3-342ba8e240ab.

Dette er en modell som er høstet fra Open API specification.

Alle objekttypene og egenskapene er ikke høstet. Vises ikke i portalen og er ikke med i RDF-serialiseringene (kun referanser).

Json-fil (https://api.finanstilsynet.no/registry/v1/openapi.json)

Objektene i gult viser hvilke som er høstet. Jeg har ikke kontollert alle egenskaper, men bildet under viser også hvilke egenskaper som mangler for objektet License.

![image](https://user-images.githubusercontent.com/17720749/128495070-feea3de8-92e3-4e9d-8b81-9e7259146b51.png)

Dette gjelder også modell https://data.norge.no/informationmodels/5afdd2af-b48b-3a8a-b65e-f04d9227c537, hvor f.eks. egenskaper mangler under objekttypen Enhet og objekttype Organisasjonsformer mangler jf. API-spesifikasjon, https://raw.githubusercontent.com/brreg/openAPI/master/specs/enhetsregisteret.json.

**Comment by ToHelland** [comment]
@shenluna Fint om denne kan prioriteres.

**Comment by matsjs** [comment]
@ToHelland 
Det er flere (muligens alle feilene) i eksempelet over som har typen `oneOf`, der ser det ut til at det er en bug med at Model-Publisher forventer `items:{ oneOf: [{}, {} ...] }` mens `oneOf` skal opptre uten `items`. Dette fikses i Informasjonsforvaltning/jsonschematordf
