### ISSUE TITLE
Oppdatere datasettbeskrivelser med tidligere formatering

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#398]
- [x] Hente ut datasettbeskrivelser med formatering fra gamle data.norge
- [x] Oppdatere formatering manuelt

Ønsker å fikse formatering på blant annet datasettene her:
https://data.norge.no/datasets?organizationNumber=985399077

**Comment by AinaEngen** [comment]
@oystein-asnes - er dette ok?

**Comment by oystein-asnes** [comment]
OK
