### ISSUE TITLE
Ny flyt på begrepsregistrering

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#399]
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/387

Se konseptflyt her: https://eggedosis.github.io/fdk-design/redirects/register/other/register-save-publish.html

**Comment by stigbd** [comment]
_Forslag_

Ved opprettelse av nytt begrep (status=utkast):
- POST begreper/ -> backend gjør create av begrep, tildeler ny intern id og  setter på versjonsnr = "0.0.1" og resten av metadata (sist-endret-av etc)
- PATCH begreper/id: backend patcher ved å oppdatere dokumentet. (altså ingen sporing av endringer på begreper i utkast)

Ved endring på eksisterande begrep som er publisert:
- PATCH begreper/id: backend oppretter nytt dokument, ny intern id, bumper patch-versjon opp, og lagrer endrede egenskaper i det nye dokumentet, setter status=utkast.

Ved henting av liste over begreper:
- GET /begreper -> skal vise alle begreper og versjoner, gruppert slik som skissene viser

Ved henting av spesifik versjon av begrep:
- GET /begreper/id -> backend henter den publiserte versjonen og patcher representasjonen on-the-fly med innholdet i versjonen..
