### ISSUE TITLE
API-katalog: URL til detaljside endrer seg når jeg klikker "Publiser" i registreringsløsningen for API

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/fdk-issue-tracker#4]
Gjorde endringer i en API-beskrivelse i registreringsløsningen, klikket "publiser" og da jeg refreshet detaljsiden i portalen, var siden tom. Gikk tilbake til søk og fant den samme API-beskrivelsen, klikket og fant detaljside med den riktige, oppdaterte teksten, men siden hadde en ny URL enn den gamle.

Ustabile URL-er på denne måten gjør at det å henvise til detaljsider FDK er umulig i epost eller blogger eller lignende, som f.eks. Lånekassens henvisning til FDKs oppføring av saldo-apiet, her https://blogg.lanekassen.no/slik-dukker-studielanet-ditt-opp-i-nettbanken/
Ustabile URL-er reduserer sannsynligvis sjansen for at FDKs innhold blir prioritert i søkemotorenes søketreff.

Side med opprinnelig URL etter URL-en er blitt endret:
![image](https://user-images.githubusercontent.com/5012227/93438639-e0b27f80-f8cd-11ea-8c98-bda07a2d69ed.png)

Side etter at URL er blitt endret og jeg har funnet frem samme API-beskrivelse vha søk:
![image](https://user-images.githubusercontent.com/5012227/93438960-4272e980-f8ce-11ea-9d48-f4b17a84dacf.png)

**Comment by lillelars** [comment]
Dette bør fungere nå. URL'ene endres ikke ved publisering eller endring.
