### ISSUE TITLE
Informasjonsmodeller - knytning mellom API og informasjonsmodeller vises ikke lenger

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#400]
Portalen skal vises koblinger mellom API-beskrivelser og tilhørende informasjonsmodeller og det skal være mulig å navigere mellom API-beskrivelser og modeller.

Disse koblingene vises ikke lenger.

Eksempel:
API: https://data.norge.no/dataservices/4bd5dd61-350e-3110-b7c3-4b640b90b6af

Tilhørende modell:
https://data.norge.no/informationmodels/9103e2a8-19a3-36ed-9b24-bc1152ef352c

**Comment by stigbd** [comment]
I utgangspunktet skal portalen vise dei relasjonene som er spesifisert i dei ulike spesifikasjonane. Så her må vi vite to ting:
- kva for property i api er det snakk om?
- kva for propert i mdodell er det evt snakk om?

Og om relasjonane er symmetriske.

**Comment by ToHelland** [comment]
@stigbd Dette er en løsning som har fungert veldig lenge, men av en eller annen grunn ikke nå. Egenskapen som skal brukes på API (DataService) er dct:conformsTo med range dct:Standard. modelldcatno:InformationModel er definert som en subklasse av dct:Standard. Den er ikke symmetrisk, men portalen har vist koblingen begge veier som for andre katalogressurser.

**Comment by shenluna** [comment]
@ToHelland @stigbd Dette skyldes mest sannsynlig en bug i høsteren som ble fikset forrige uke, men det gjorde slik at id-ene til informasjonsmodellene fra fdk-model-publisher ble endret. APIene peker nå mot gammel uri, som er grunnen til at man nå ikke ser disse koblingene. Det må derfor kjøres en ETL på dette, @NilsOveTen og @valosnah er klar over saken og ser på det.
