### ISSUE TITLE
Informasjonsmodeller - begreper vises ikke lenger på egenskaper

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-issue-tracker#405]
Tidligere har begreper vistes på attributter som har referanser til begreper i begrepskatalogen. De vises fortsatt for objekttyper og datatyper, men ikke på alle attributtene (regner det gjelder også andre egenskaper som roller, komposisjoner m.m.).

Se f.eks. modell: https://data.norge.no/informationmodels/8bfa055a-9b0c-40df-a7c2-2e58173eb2e0
F.eks. har attributtet fødested en referanse til begrepet fødested i begrepskatalogen.

RDF turtle
![image](https://user-images.githubusercontent.com/17720749/131658653-20acd290-4925-4a00-a09b-9e27e18bca5d.png)

Dette vises ikke i portalvisningen:
![image](https://user-images.githubusercontent.com/17720749/131659996-d083d92f-80ff-427a-bbbe-184d113fd9f3.png)

Som man ser av bilde, vises imidlertid begrepet for attributtet fulltNavn.

Jeg ser ikke noe mønster i hvorfor noen attributter vises eller ikke. Det virker som om URI'ene  til begrepene det vises til er riktige, for hvis du går til begrepet fødested i begrepskatalogen vises det at begrepet er knyttet til modellen.

Men som nevnt, dette har virket tidligere

**Comment by shenluna** [comment]
Fødested viser nå begrepet
![image](https://user-images.githubusercontent.com/73637969/133735381-b03f8228-2904-46e5-afc1-de92aa911f5f.png)

@ToHelland Kan du ta en sjekk at alt stemmer nå?

**Comment by ToHelland** [comment]
@shenluna 
Har testet. Begreper på attributter vises. Fant imidlertid  at begreper ikke vises på kodeelementer.
Eksempel, Fellesmodell Person og Enhet:
![image](https://user-images.githubusercontent.com/17720749/133743903-bf50c8bf-e2b3-48f3-bd26-11f4b5b52fff.png)

I Turtle så ser man at disse kodeelementene har dct:subject, f.eks.:
![image](https://user-images.githubusercontent.com/17720749/133744573-cd388931-fbea-47cd-ab60-5135cda7cc40.png)

Ser at en del modellelementer (objekttype, kodeliste, enkeltyper, datatyper) mangler "Se detaljer". De kan virke som om dette er modellelementer som ikke har relasjoner til begreper (dct:subject). Selv om det er ikke noen relasjon skal Se detaljer vises og når du åpner så skal du se elementets identifikator.

Se f.eks. objekttypen Enhet i Fellesmodellen for Person og Enhet:
![image](https://user-images.githubusercontent.com/17720749/133747341-3b57c4db-0da3-4123-916e-2a4ca660c146.png)

**Comment by matsjs** [comment]
> @shenluna
> Har testet. Begreper på attributter vises. Fant imidlertid at begreper ikke vises på kodeelementer, bare identifikatorer.
> Eksempel, Fellesmodell Person og Enhet:
> ![image](https://user-images.githubusercontent.com/17720749/133743903-bf50c8bf-e2b3-48f3-bd26-11f4b5b52fff.png)
> 
> I Turtle så ser man at disse kodeelementene har dct:subject, f.eks.:
> ![image](https://user-images.githubusercontent.com/17720749/133744573-cd388931-fbea-47cd-ab60-5135cda7cc40.png)
> 
> Ser at en del modellelementer (objekttype, kodeliste, enkeltyper, datatyper) mangler "Se detaljer". De kan virke som om dette er modellelementer som ikke har relasjoner til begreper (dct:subject). Selv om de ikke har noen begrepsrelasjon så skal "Se detaljer" vises, og når du åpner så skal du se elementets identifikator.
> 
> Se f.eks. objekttypen Enhet i Fellesmodellen for Person og Enhet:
> ![image](https://user-images.githubusercontent.com/17720749/133747341-3b57c4db-0da3-4123-916e-2a4ca660c146.png)

For begreper brukt i modell:
Her ser det ut som informasjonsmodellen sitt `containsSubjects` felt ikke omfatter alle begreper brukt i modellen. Skal undersøke RDF parsing.

For "Se detaljer":
Grunnen til at denne ikke vises for noen elementer her er at de ikke har nødvendige data. Ser at Enhet i dette eksempelet har en `uri`, men ikke en identifikator. Vi kan eventuelt si at `uri` skal brukes om ikke identifikator er tilgjengelig, men dette vil da gjelde for alle elementer. Er et ønskelig @ToHelland ?

**Comment by ToHelland** [comment]
@matsjs Nei, det er ikke ønskelig. Dette vil etter hvert løses av issue #347.
