### ISSUE TITLE
Endring av tekst i advarselsboksen som vises når bruksvilkår ikke er godkjent av en virksomhet

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#407]
I dag vises dette varselet:
![image](https://user-images.githubusercontent.com/43232700/131998587-0c699f7e-9aa9-4549-b713-a3ade6dbcf2f.png)

Men det er ikke alle som skjønner at de må klikke på det første ordet i varslet (Bruksvilkår) for å lese og akseptere vilkårene. Noen lurer også på hva som ligger i begrepet "bemyndiget person" - altså hvem anser vi som bemyndiget person. I tillegg kommer dette varslet i utgangspunktet kun første gang noen logger seg inn på vegne av en virksomhet for første gang. Teksten kan kanskje derfor være litt mildere?

Forslag til tekst:
Alle virksomheter må godta bruksvilkår før de kan registrere data i Felles datakatalog.
Les mer om bruksvilkårene og aksepter her: [Bruksvilkår](url)

**Comment by shenluna** [comment]
Tekst oppdatert
![image](https://user-images.githubusercontent.com/73637969/133440649-a1fa06c7-85c0-4420-846f-b2baff6bba22.png)
