### ISSUE TITLE
Forbedre søk og filter på data.norge

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#411]
https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/415

Se behov: https://github.com/datadeling/behov-issue-tracker/issues/84

**Comment by KjerstiSteien** [comment]
Lukker denne, da behovet er godt nok beskrevet i behovssaken det er lenket til. Denne saken gir ikke noe ekstra.
