### ISSUE TITLE
Hjelpetekster datasettregistrering

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#414]
Format - fjern markert tekst:
![image](https://user-images.githubusercontent.com/46488929/133217559-f5ecf05f-7c0c-49af-9197-09c26de24398.png)

Geografisk avgrensning - endre markert tekst til:
**Søk etter geografisk område fra Administrative enheter (Kartverket) og velg fra nedtrekksliste.**
![image](https://user-images.githubusercontent.com/46488929/133218450-85c2f306-b203-43b9-815f-bcfad7342165.png)

**Comment by shenluna** [comment]
![image](https://user-images.githubusercontent.com/73637969/133262414-2d2555e9-743d-4d06-b08e-f4c338b16b99.png)
![image](https://user-images.githubusercontent.com/73637969/133262443-d22d8cea-0ab9-4531-a21e-d32af9fc312b.png)
