### ISSUE TITLE
Forbedringer på søk

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-issue-tracker#415]
- Bruk søkeboksen til informasjon
- Gi forslag
- Koble til tittel for datasett, begreper, kilde
- Skru på autofullfør
- Skru på autokorrigering
- Skru på funksjon for å gi treff ved skrivefeil, ufullstendige søk etc.
- Sett inn et eksempel på søk i søkeboksen (må avklares WCAG-messig)

**Comment by terjesyl** [comment]
Krever endringer i portal, fulltext-search og muligens elasticsearch.
Søkefeltet er aktuelt å gjenbruke.

@jeffreiffers Kan du bryte ned og opprette issues for hvert punkt med beskrivelse?
