### ISSUE TITLE
Avvik mellom rapportsiden og søkesiden til portalen når det gjelder visning/filtrering av tilbydere av API

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#418]
I søkesiden til portalen vises det at det er 113 private tilbydere av API-er. Mens på rapportsiden finnes det ingen private tilbydere av API. Disse 113 API-ene er lagt til Digdir. Årsaken til avviket er at filteret til søkesiden viser tilbyderne av API-ene, mens filteret på rapportsiden viser eiere av katalogene som API-ene er publisert i fra. Digdir har jo publisert de 113 bankapi-ene fra sin katalog.

Rapportsiden må for API-er endres til å vise hvem det er som tilbyr API-ene slik at dette blir likt med portalen.

Fra søkesiden:
![image](https://user-images.githubusercontent.com/43232700/133777196-a0ae4b36-f3ff-4ed0-8caa-c360d07b0c97.png)

Fra rapportsiden:
![image](https://user-images.githubusercontent.com/43232700/133777049-7184b1fb-4ebb-48c3-ac21-91a55cddc01e.png)

**Comment by KurtStian** [comment]
Meldt av bruker, se: https://teams.microsoft.com/l/message/19:7b65dffa9a134cca89355f418ad9de6a@thread.tacv2/1631872975363?tenantId=008e560f-08af-4cec-a056-b35447503991&groupId=47529ac3-12da-40d3-ba0f-947e6d4cec62&parentMessageId=1631872975363&teamName=FDK%20Utviklingsteam&channelName=Servicedesk&createdTime=1631872975363

**Comment by shenluna** [comment]
Rapportsiden er nå oppdatert med tilbyderne av API-ene
![image](https://user-images.githubusercontent.com/73637969/134638535-cffcbd3e-22b0-4a9e-9c08-98fbe201ce32.png)
