### ISSUE TITLE
feil i hjelpetekst for "Kategorier av registrerte og kategorier av personopplysninger"

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#43]
- [x] Hjelpetekst i kortform er vist to ganger. Den gulmerkede teksten skal slettes:
![image](https://user-images.githubusercontent.com/32771488/96112250-a3e4a300-0ee2-11eb-9d62-94e6da3b7a7a.png)

- [x] Siste setning i utvidet hjelpetekst skal også slettes:
![image](https://user-images.githubusercontent.com/32771488/96112464-eefeb600-0ee2-11eb-9c17-94bbfd6828a0.png)

Se også hjelpetekstfil https://docs.google.com/document/d/1B55vGWVdezos4lotFd5SMGuZfx8n0pyVNnNQd0mklv0/edit#

**Comment by lillelars** [comment]
Da er denne også ute i demo. Lukker saken. @RogerSOlsen
