### ISSUE TITLE
Begrepstabellen i en begrepskatalog er ikke toppjustert

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#439]
Hvis man åpner begrepskatalogen til en virksomhet som har registrert ingen eller få begreper ser man at tabellen inkl. overskrift presenteres langt ned på siden. Jo flere begrep jo lengre opp flyttes tabellen og overskriften. Ved ca. 7 begrep så er tabellen og overskriften så langt opp som den kan komme og etter dette så utvides siden nedover. Hvis man logger inn med lestilgang blir det enda mer åpenrom ovenfor da knapperaden er borte.

Begrepstabellen inkl. overskift må våre toppjustert slik f.eks. tabellen for datasett og datatjeneste.

![image](https://user-images.githubusercontent.com/43232700/139068458-6b473e92-030e-49c7-a9f8-150b7ad96617.png)
![image](https://user-images.githubusercontent.com/43232700/139068596-04b70485-2b12-4128-93ce-1cefe4d5feff.png)
![image](https://user-images.githubusercontent.com/43232700/139068924-4dfc9d31-5c6b-4c16-ac69-4f606484b73c.png)

**Comment by shenluna** [comment]
Testet ok
