### ISSUE TITLE
Søk med fraser

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/fdk-issue-tracker#446]
Ser ikkje ut til at ein kan søke med fraser ved å omslutte fleire termar med hermeteikn.
Eksempel: https://data.norge.no/search-all?q=%22h%C3%B8yere%20utdanning%22
Dette gjer det svært vanskeleg å finne spesifikke oppføringar. I dette tilfelle prøvde eg å finne database for statistikk for høyere utdanning (DBH).

PS. Ønskjer meg ei side som dokumenterer søke-syntaks.

**Comment by livarb** [comment]
Ser det er plasshaldar for å dokumentere søk og filter her: 
![image](https://user-images.githubusercontent.com/3617256/147207280-5a31fc6d-cea8-4d71-b68b-618f34dea2b9.png)
https://informasjonsforvaltning.github.io/felles-datakatalog/s%C3%B8k_og_filter/

**Comment by livarb** [comment]
Eksempel på dokumentasjon av søk hos Finn.no:
https://hjelpesenter.finn.no/hc/no/articles/303324-Tips-om-friteksts%C3%B8k-og-ord-i-annonsen-
![image](https://user-images.githubusercontent.com/3617256/148502812-ee93e119-20ab-4b16-9f32-886d4cdc7960.png)

**Comment by livarb** [comment]
La inn dokumentasjon av søk (i Datafabrikken) som separat sak: https://github.com/datadeling/behov-issue-tracker/issues/137

**Comment by KjerstiSteien** [comment]
Regnes som løst, da vi har byttet boolsk søkeoperator fra OR til AND ved søk på flere ord.
