### ISSUE TITLE
Feil i HTML-rapport og CSV-rapport for tema om tredjeland/internasjonale organisasjoner og DPIA

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#449]
Problem: 
- det vises verdier i HTML-rapport og CSV-rapporter som ikke er registrert i registreringsløsning. 
- det mangler felt  rapporter

Kilde ved testing: Behandlingsoversikt i demoløsning
Behandlingsansvarlig: Høgskolen for IT og arkitektur
Testet med to Behandlingsaktiviteter: 
- "test 6" som er en uferdig/ikke godkjent behandlingsaktivitet. Den har data kun i det første feltet "Behandlingen gjelder". 
Innhold i test 6 skal kun fremgå i HTML og CSV rapportene for Behandlingsoversikt ettersom denne behandlingsaktiviteten ikke er godkjent.
- "Flaskepost",  som er en godkjent behandlingsaktivitet hvor alle obligatoriske felt har fått en verdi eller data. Alle felt i behandlingsaktiviteten skal vises i CSV og HTML-rapport for Behandlingsoversikt. 
De obligatoriske feltene i denne behandlingsaktiviteten skal fremgå i CSV og HTML rapportene for Protokoll.

1) **Tema "Er mottakerne tredjeland eller internasjonale organisasjoner?"**:  
I registeringsløsningen kan man angi Nei eller Ja på spørsmålet eller la være å angi noe. Dersom man vil godkjenne behandlingsaktiviteten og generere rapport Protokoll må man angi Ja eller Nei.
I test 6 er det ikke angitt verdi i registreringsløsning (test 6 kan derfor kun vises i rapport Behandlingsoversikt):
![image](https://user-images.githubusercontent.com/32771488/141970937-7f7b0555-e23b-44cf-b16f-02e0206db383.png)
For test 6 vises verdi "Nei" allikevel i HTML-rapport og CSV-rapport "Behandlingsoversikt". Her skulle det ikke vært noen verdi (feltene skulle vært uten innhold).
I HTML-rapport vises test 6 slik:
![image](https://user-images.githubusercontent.com/32771488/141979814-39d8a916-f8c2-4613-af48-850de60891d4.png)

I CSV-rapport vises test 6 slik:
![image](https://user-images.githubusercontent.com/32771488/141971324-793dd0ae-e65e-4dc3-9344-c89aeed6179a.png)

NB! Test 6 inngår ikke i HTML og CSV rapport Protokoll  fordi denne behandlingsaktiviteten har status Utkast. 

Flaskepost: 
her er det i registreringsløsning valgt "ja" og tekst "Danmark, Verdens helseorganisasjon" i fritekstfeltet "Tredjeland eller internasjonale organisasjoner" i registreringsløsningen (dette feltet vises dersom man har svart Ja på "Er mottakerne tredjeland eller internasjonale organisasjoner?"):
![image](https://user-images.githubusercontent.com/32771488/141971682-5823c35c-fdc8-47de-939f-8741ecfa8856.png)
I HTML og CSV-rapport Behandlingsoversikt vises innholdet fra registreringsløsningen med riktig innhold for Flaskepost:
![image](https://user-images.githubusercontent.com/32771488/141972286-6a876855-f0e8-4d6c-b6da-edb03dc6b3cd.png)
![image](https://user-images.githubusercontent.com/32771488/141972860-cb857263-123c-41a9-a018-dff56b77e69e.png)

2) **Tema "Er det gjennomført vurdering av personvernkonsekvenser (DPIA)"**
I registeringsløsningen kan man angi Nei eller Ja på spørsmålet eller la være å angi noe. Dette er ikke et obligatorisk felt. Man kan derfor godkjenne behandlingsaktiviteten uten å registrert Ja eller Nei her. 
Temaet skal komme med i rapport Behandlingsoversikt, men ikke i Protokoll ettersom dette ikke er et obligatorisk tema:
![image](https://user-images.githubusercontent.com/32771488/141975669-34ff8b4c-f3c5-446d-8cba-50bd3eb04980.png)
Dersom man velger å svare Ja, kan man fylle ut feltet "Sak-/arkivreferanse eller lenke til vurdering av personvernkonsekvenser (DPIA)":
![image](https://user-images.githubusercontent.com/32771488/141975812-6cb62d3c-463e-4b81-889e-a2bbabf4af6a.png)

I test 6 er det IKKE angitt Ja eller Nei på "Er det gjennomført vurdering av personvernkonsekvenser (DPIA)". 
I HTML-rapport Behandlingsoversikt vises dette feltet i test 6 med verdien "Neise risikovurdering":
![image](https://user-images.githubusercontent.com/32771488/141976374-1618ce59-ddcd-4aed-8b13-1837da56bc0c.png)
"Neise risikovurdering" skal altså ikke fremgå her for test 6 (jeg vet ikke hvor den kommer fra). 
Videre burde det her vært et felt som heter "Er det gjennomført vurdering av personvernkonsekvenser (DPIA)" med verdi Ja, Nei eller ingen verdi. 

I CSV-rapporten for Behandlingsoversikt vises test 6 uten verdi for "Er det gjennomført DPIA og "Referanse til DPIA", som er riktig visning:
![image](https://user-images.githubusercontent.com/32771488/141977664-ade80e47-ed27-494f-bfa1-ffc91cc8386c.png)

I Flaskepost er det i registreringsløsning angitt verdi Ja for "Er det gjennomført vurdering av personvernkonsekvenser (DPIA)?", samt teksten "sak nr 1 i arkivet" under "Sak-/arkivreferanse eller lenke til vurdering av personvernkonsekvenser (DPIA)":
![image](https://user-images.githubusercontent.com/32771488/141978584-eb6c7268-e7a9-4fe9-b1ae-85f2a57d1071.png)
I HTML-rapport for Flaskepost i Behandlingsoversikt mangler visning av feltet "Sak-/arkivreferanse eller lenke til vurdering av personvernkonsekvenser (DPIA)":
![image](https://user-images.githubusercontent.com/32771488/141978760-5a27c57f-d899-4d8a-8fcc-1087bf8f9950.png)
I CSV-rapport Behandlingsoversikt vises verdi for begge felt slik for Flaskepost:
![image](https://user-images.githubusercontent.com/32771488/141979042-4d7a76f0-e386-45a5-8bd2-441d7556d56a.png)

**Comment by RogerSOlsen** [comment]
Testing 23.11.2021:

![image](https://user-images.githubusercontent.com/32771488/143037615-6fffa3c0-b5cb-4625-927b-5d2cefe4de82.png)

**Comment by NilsOveTen** [comment]
> Testing 23.11.2021:

@RogerSOlsen Jeg klarer ikke å gjenskape problemet du fant med HTML-rapporten, hvilken nettleser var du på?

**Comment by RogerSOlsen** [comment]
> > Testing 23.11.2021:
> 
> @RogerSOlsen Jeg klarer ikke å gjenskape problemet du fant med HTML-rapporten, hvilken nettleser var du på?

@NilsOveTen jeg klarer heller ikke å gjenskape feil under "Vurdering av personvernkonsekvenser (DPIA)". Foreslår derfor at saken lukkes
