### ISSUE TITLE
Trigge at skattetaten skin blir valgt v/ innlogging

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#45]
Når en bruker med epost @skattetaten.no logger seg på registreringsløsningen skal skatteetaten skin-tema vises.

**Comment by oyvindis** [comment]
Vi legger også på en mulighet for å sette "skeProfile" fra localstorage på samme måte som vi har for Transportportal i fdk-portal (napProfile). Det gjør det enkelt å teste profilen i alle miljøer.

**Comment by lillelars** [comment]
Dette fungerer nå som forventet. Testet i staging, demo og prod med skattetetaten orgnr :) lukker saken.
