### ISSUE TITLE
Gå over til GitHub Packages

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#450]
I dag dytter vi alle bygg til et eget registry-prosjekt i GCP (digdir-fdk-infra).
For å løse knytningen til GCP er det fordelaktig å heller bruke GitHubs Container registry.

- [x] Endre workflows til å autentisere mot ghcr.io
- [x] Endre image-path fra eu.gcr.io/digdir-fdk-infra/(*) til ghcr.io/(*)

**Comment by KjerstiSteien** [comment]
@valosnah Fortsatt relevant?

**Comment by valosnah** [comment]
@KjerstiSteien 
Ja. Vi er fortsatt i Google Container Registry, som nå er deprekert, og vil bli skrudd av i mai 2025.
Det nye heter Google Artifact Registry, som jeg mistenker vil koste oss mer penger å bruke (GCR ≈ 1000NOK/mnd)
Anbefaler fortsatt å bytte over til GitHub, som for oss i tillegg er helt gratis.

**Comment by KjerstiSteien** [comment]
@KurtStian Dette burde vi vurdere å få på planen.

**Comment by valosnah** [comment]
Henter frem denne fra backlog.
Testet ut GitHub Packages ifm Hackathon, og det er _særdeles enkelt_ å bytte

**Comment by valosnah** [comment]
Workflows har blitt endret, repoene må gjøre noen små endringer for at de skal virke skikkelig. Se oppskrift på confluence
