### ISSUE TITLE
"Legg til datatjeneste"-knapp er tilgjengelig for lesebruker

### ISSUE THREAD

**Issue by joachim-me** [Informasjonsforvaltning/fdk-issue-tracker#452]
"Legg til datatjeneste"-knapp er tilgjengelig for lesebruker:

![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/c3886d73-cd4e-4c4b-a4f4-96034291a2c0)

**Comment by KurtStian** [comment]
Mer utfyllende informasjon:

Feilen oppstår når man logger inn med den nye Altinntjenesten «Felles datakatalog - alle kataloger - lesetilgang».
Det finnes ikke lesevariant til høsteløsningen slik at brukeren skal få beskjed om at hen ikke har tilgang. Dette får man i dag hvis man bruker Felles brukerhåndering og kun har tilgangen «subscriber». Lesetilgangsrettigheter via Altinn og Felles brukerhåndtering bør gi de samme rettighetene.

**Comment by KjerstiSteien** [comment]
@KurtStian er dette fortsatt relevant?

**Comment by KurtStian** [comment]
Denne er løst. Brukere som kun har lesetilgang får samme beskjed om at de ikke ha tilgang uavhenging om de logger inn via Id-porten/Altinn eller Felles brukerhåndtering.

Skjermbilde ved innlogging via Id-porten/Altinn med bruker som kun har lesetilgang:
![image](https://user-images.githubusercontent.com/43232700/231723626-5cdc3b7b-9140-4fdc-abac-5e550c1063e6.png)
