### ISSUE TITLE
TilgangsURL i portalen for datasett vises ikke slik den er blitt registrert i registreringsløsningen

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#454]
Lenker som er registrert via feltet «Tilgangslenke» i registreringsløsningen får omgjort store bokstaver til små bokstaver når lenke vises i feltet «TilgangsURL». Hvis man klikker på lenken så vil opprinnelig lenke som inneholder store bokstaver følges, men hvis man kopier lenken så vil man få feilmelding.

Eksempel fra registreringsløsningen:
![image](https://user-images.githubusercontent.com/43232700/142415035-210fd377-c3a0-48d6-8acb-643fae468cce.png)

Eksempel fra portalen:
![image](https://user-images.githubusercontent.com/43232700/142415184-c9a7ae48-c585-41b0-a864-c581a60c496d.png)

Det bør også sjekkes at ikke tilsvarende endringer blir gjort for andre lenker som kan publiseres i portalen

**Comment by valosnah** [comment]
Spesifisering: I portalen er det korrekt lenke som skjuler seg TilgangsURL'en, men selve teksten som blir vist har fått små bokstaver. [eksempel](EKSEMPEL)
