### ISSUE TITLE
Oppdatere sertifikat

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#457]
- [x] Oppdatere sertifikat

**Comment by valosnah** [comment]
Nye sertifikat mottatt, legger inn i løpet av mandag 29.11

**Comment by valosnah** [comment]
Nye sertifikater lagt inn.
Men vi ser at vi nå har problemer med dataservice-publisher.digdir.no
Denne skal omdøpes til dataservice-publisher.fellesdatakatalog.digdir.no enn så lenge, krever noe endring i kode, issue opprettes i respektivt repo.

**Comment by valosnah** [comment]
Sertifikat mottatt og lagt inn for data.transportportal.no

![image](https://user-images.githubusercontent.com/8625716/145212226-705a4dfb-7d3d-496b-ad75-114bf59c2341.png)

**Comment by valosnah** [comment]
For ordens skyld, FDK-sertifikatene også:
![image](https://user-images.githubusercontent.com/8625716/145212341-0b4e0261-17dd-442b-9117-ed0e952773eb.png)
![image](https://user-images.githubusercontent.com/8625716/145213213-2ab84daa-e2f6-4df6-8d8d-4225d09144b7.png)

**Comment by valosnah** [comment]
Har også oppdatert dokumentasjonen i Teams relatert til å legge inn transportportal-sertifikatet, da det er litt annerledes enn med Buypass

**Comment by shenluna** [comment]
Lukker denne da alle sertifikater er blitt lagt inn.
