### ISSUE TITLE
Endre navn på datakilde og katalog for tjeneste- og hendelsekatalog i data-source

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#461]
Da det høstes både tjeneste- og hendelsebeskrivelser må navnet på datakilden og katalogen gjenspeile dette.
I dag heter datakilden «Tjenestekatalog». Den må endres til «Tjeneste- og hendelsekatalog».
I skjemaet «Registrer ny datakilde» i nedtrekkslisten «Katalog» heter Tjeneste- og hendelsekatalogen kun «Tjeneste». Den må endres «Tjeneste og hendelse».

**Comment by KjerstiSteien** [comment]
@KurtStian er dette fortsatt relevant?

**Comment by KurtStian** [comment]
@KjerstiSteien  Ja :-)

![image](https://user-images.githubusercontent.com/43232700/231712460-d9cfd668-90cd-46cc-9ed8-88636ade5c84.png)
![image](https://user-images.githubusercontent.com/43232700/231712715-00016ebf-cf6e-4552-84e2-8388144671dc.png)
