### ISSUE TITLE
Endre tittel på "andre som relaterer til dette datasettet"

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/fdk-issue-tracker#468]
Endre overskriften til:
"Andre ressurser med relasjoner til dette datasettet" @nb
"Andre ressursar med relasjonar til dette datasettet" @nn 
 "Other resources with relations to this dataset @en

**Comment by shenluna** [comment]
Dette er prodsatt, eksempel fra enhetsregisteret:
![image](https://user-images.githubusercontent.com/73637969/149151295-035609ae-d83e-4ac7-a7fa-2cff05556e76.png)
