### ISSUE TITLE
Det skal alltid vises en tittel på en hjemmel

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#470]
I utgangspunktet skal tittel hentes fra dct:title i beskrivelsen som høstes. Men hvis dct:title ikke finnes (siden den ikke er obligatorisk) i beskrivelsen skal tittel hentes fra kilden (f.eks. fra feltet «Title» i Lovdata). Og er ikke dette mulig skal URL-en til hjemmelen vises.

(Foreløpig finnes ikke dct:title for klassen eli:LegalResource i CPSV-AP-NO eller DCAT-AP-NO, men vi ønsker å legge dette til)

Eksempelvis burde tittel hentes i fra Lovdata for tjenesten til KF (ev. vise URL):

Fra portalen:
![image](https://user-images.githubusercontent.com/43232700/145413054-5a86f8f2-d5f3-4ad2-823e-c08d011ff9a5.png)

Fra beskrivelsen som blir høstet:
![image](https://user-images.githubusercontent.com/43232700/145413367-6a8aed85-84a6-4b78-af6e-878295590453.png)

**Comment by KurtStian** [comment]
Behovet for å kunne ha en tittel knyttet til eli:LegalResource er lagt inn her: https://github.com/Informasjonsforvaltning/cpsv-ap-no/issues/17. Vil komme i 0.9 versjonen av CPSV-AP-NO.

**Comment by shenluna** [comment]
Testet OK
