### ISSUE TITLE
Veldig tregt søk i portal

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#477]
Søker på f.eks. «kommune organisasjonsnummer» og velger «Datasett». Får 530 treff.
Når jeg så blar fra en side til en annen så kommer man tilsynelatende til ny side (man kommer øverst på siden og sidenr endres i adressefeltet), men det er innholdet på den forrige siden som vises. Først etter 1-2 sekunder så oppdateres til innholdet. Så for brukeren blir siden oppfrisket to ganger.

Hvis man blar mellom sidene uten å ha utført søk så vises innholdet på ny side mer eller mindre med det samme du blar til den nye siden.

Er det mulig å få til bedre ytelse slik at sidene oppdateres tilsvarende de gjør når det ikke er utført søk? Som bruker synes jeg også det er uheldig at løsningen fremstår som den har oppdatert siden når den fremdeles vises den gamle siden. Man tror at man har fått en ny side med nytt innhold og begynner så å skrolle ned for å lete og så oppfriskes siden en gang til. Veldig irriterende.

Ser også at det er avvik mellom sidenr som vises i adressefeltet i nettleseren og det som vises i menyen i løsningen. Når det .feks. vises «page=1» i adressefeltet så har bruker valgt side «2» i menyen.

**Comment by oyvindis** [comment]
@jeffreiffers Det er lagt til mapping i runtime i fulltext, jeg tror det kan bidra til at søk tar vesentlig lengre tid nå?

@shenluna kanskje format-aggregering bør fjernes midlertidig siden det går så utover ytelse?

**Comment by shenluna** [comment]
@oyvindis Hva vil det si for løsningen om vi fjerner format-aggregering? Er det snakk om format filteret?

**Comment by joebrreg** [comment]
Søket tar veldig lang tid ved velge et autovalg:

1. Står på "Alle"-fanen (eller framsiden)
2. Skriver inn kompensasjonso
3. Velger datasetttet "Kompensasjonsordningen for innreisekarantene"
4. Tar over 5 sek før søkeresultat vises

**Comment by shenluna** [comment]
Dette er fikset og prodsatt, lukker dermed saken
