### ISSUE TITLE
Skifte logo i portal

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#48]
Digdir har fått ny visuell identitet. Det smitter over på oss:

https://www.figma.com/proto/tkHD7njZcjSNJIAPDnyN4d/Portal?node-id=349%3A2611&viewport=-1643%2C-2536%2C0.743359386920929&scaling=min-zoom

Logo: https://web.tresorit.com/l/VE3Vs#glUQIt5Pz5gOWZmeY40Nug&3CbmUZplwBliarino6VMmB2nkqhiWgUZ
(gå ned til: Felles datakatalog.svg )

Favikon: https://web.tresorit.com/l/VE3Vs#glUQIt5Pz5gOWZmeY40Nug&sA1BtIal17pc0ZAY6zen6kbZb6PQz1lD

- [x] endre logo i portal

- [x] endre favikon

**Comment by lillelars** [comment]
Denne er da levert. Testet i chrome, edge og på mobil - prodsatt. Lukker saken.
