### ISSUE TITLE
Avvik mellom rapportsiden og søkesiden til portalen når det gjelder visning/filtrering av ansvarlige for informasjonsmodeller

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#481]
På rapportsiden fremgår det at Helsedirektoratet er ansvarlig for 147 informsjonsmodeller, men har egentlig ikke noen. I tillegg står det at Digdir kun er ansvarlig for 2. På søkesiden vises det korrekt med bl.a. 113 banker, se skjermdump.

Rapporter:
![image](https://user-images.githubusercontent.com/43232700/146186352-f1e16bd1-24fa-4b21-b671-c45e54b74bc3.png)

Portalen:
![image](https://user-images.githubusercontent.com/43232700/146186562-533f7d6d-f23c-4ab1-b182-7d8f5d4fcb73.png)

**Comment by shenluna** [comment]
Testet OK, lukker saken
