### ISSUE TITLE
FEIL: ikke mulig å registrere tilknyttet datasettbeskrivelse i Behandlingsoversikt

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#483]
det er ikke lenger mulig å søke opp datasettbeskrivelser i feltet "Tilhørende datasett" i Behandlingsoversikt, hverken i demo-miljøet eller i produksjonsmiljøet. 
Har prøvd å søke opp datasettbeskrivelsen "Norge.no - tjenesteeiere. Statlige virksomheter, kommuner og fylkeskommuner"  som er en av Digdir sine datasettbreskrivelser i produksjon, og som i portalen har lenke https://data.norge.no/datasets/2a9fb39c-47ca-48b9-85b4-a3747e00a477, ved å skrive "Norge" i feltet "Tilhørende datasett" i registreringsløsningen i Behandlingsoversikt i produksjon, men får ingen respons. Det ligger minst to datasettbeskrivelser under Digdir i prod. med navn som starter med "Norge", så det burde være mulig å få vist minst to alternativer i registreringsløsningen når man skriver "Norge". 
Det er derfor ikke lenger mulig å knytte en behandlingsaktivitet til en datasettbeskrivelse.

**Comment by oyvindis** [comment]
@valosnah Kan du sjekke at miljøvariabel i staging, demo og prod peker riktig:
DATASET_CATALOG_API: 'https://registrering.staging.fellesdatakatalog.digdir.no'

Ser ut som den nå feilaktig peker på 'https://registrering-protokoll.staging.fellesdatakatalog.digdir.no'
