### ISSUE TITLE
Oppdatere tilgangsnivåer i datasett

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#484]
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/634

**Comment by NilsOveTen** [comment]
Vi får en liste av labels for hver type tilgangsnivå fra reference-data, problemet er at vi bruker gammel reference-data til dette.

Så tror dette blir todelt:
1. Oppdatere new-reference-data med nye norskel labels, den har atm kun engelske
2. Gå over til å bruke new-reference-data for access-rights i portal

**Comment by oystein-asnes** [comment]
@NilsOveTen Jeg tror at dette handler om å flytte alle datasett med en eller annen verdi i feltet `skjermingshjemmel`  OG som har verdien "restricted" flyttes til "non-public" 
I versjon 2.x av dcat er dette `cpsv:follows`. I versjon 1.x det `dcatno:accessRightsComment`

**Comment by NilsOveTen** [comment]
> @NilsOveTen Jeg tror at dette handler om å flytte alle datasett med en eller annen verdi i feltet `skjermingshjemmel` OG som har verdien `restricted` flyttes til `non-public` I versjon 2.x av dcat er dette `cpsv:follows`. I versjon 1.x det `dcatno:accessRightsComment`

Vil det si at datasettene som har minst en av `ruleForDataProcessing`, `ruleForNonDisclosure` og `ruleForDisclosure`, eller kun de som har `ruleForNonDisclosure` i `cpsv:follows`?

**Comment by oystein-asnes** [comment]
> Vil det si at datasettene som har minst en av `ruleForDataProcessing`, `ruleForNonDisclosure` og `ruleForDisclosure`, eller kun de som har `ruleForNonDisclosure` i `cpsv:follows`?

Spot on @NilsOveTen. Det skal i teorien være nok med `ruleForNonDisclosure`, men det kan hende du fanger flere ved å ta med de to andre også.

**Comment by shenluna** [comment]
Verifisert ok.
