### ISSUE TITLE
Lag plugin for apache atlas som gjør den dcat-capable

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#485]
Med "dcat-capable" meiner vi at man i en apache atlas instans/eller på et anna service skal kunne eksponere et endpunkt der dataset-katalogen i atlas blir eksponert som en dcat-catalog + datasets ihht til dcat-ap-no v2.

**Comment by jeffreiffers** [comment]
Jeg har sett litt på atlas og addons og det er fullt mulig å lage en addon til dcat. Sånn jeg ser det må vi bruke atlas sitt REST API for å få det til. Hva menes det med dcat-capable? Kunne importere dcat-ap entiteter eller kunne eksportere entiteter som dcat-ap?

**Comment by stigbd** [comment]
Bra! (Eg har lagt inn litt i description over.)
