### ISSUE TITLE
får ikke generert HTML-rapporter for Behandlingsoversikt i demo-miljøet

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#489]
Jeg får ikke generert HTML-rapporter i Behandlingsoversikt i demo-miljøet. Får kun en blank side på rapport "Behandlingsoversikt" og rapport "Protokoll". 
Det går til orientering greit å generere CSV-rapporter for Behandlingsoversikt" og rapport "Protokoll" i demo-miljøet. 
Dette går også greit å generere HTML-rapporter i Behandlingsoversikt i produksjons-miljøet.

**Comment by oyvindis** [comment]
Får ikke gjenskapt feilen, mulig rettet allerede?

Hvis fortsatt feil, fint om du gir med hvilken organisasjon man er pålogget som.

**Comment by RogerSOlsen** [comment]
> Får ikke gjenskapt feilen, mulig rettet allerede?
> 
> Hvis fortsatt feil, fint om du gir med hvilken organisasjon man er pålogget som.

@oyvindis Jeg får generert rapportene Behandlingsoversikt og Protokoll (begge HTML) nå. Har testet på org.nr 555111290 og så vidt jeg husker var det dette org.nummeret feilen oppstod i. Siden det funker nå, lukker jeg saken
