### ISSUE TITLE
Feil i titler på lenker

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#49]
![image](https://user-images.githubusercontent.com/46488929/97283236-dde96980-183f-11eb-9992-3b04cd5b13f6.png)

Det skal stå:
- "Standard for beskrivelse av datasett"
- "Veileder for tilgjengeliggjøring av åpne data"

**Comment by lillelars** [comment]
Dette er nå fikset. Lukker saken. Testet i staging i chrome.
