### ISSUE TITLE
Gjere lenker i postar i Datalandsbyen i Datafabrikken synlege

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/fdk-issue-tracker#491]
I ein post, er lenker nesten usynlege, så brukarane blir ikkje klar over at det finst lenker på tekst. Bør vere mogeleg å sjå visuelt.

Eksempel:
https://datafabrikken.norge.no/datalandsbyen/3/m%C3%B8ter-og-arrangementer/127/open-data-challenge-27-01-2022
Nederst i posten:
![image.png](https://images.zenhubusercontent.com/6156b64dc26db0798c7faadf/70af84a8-25af-4d84-80ab-4959ef4a5b9f)

Samme post i Datalandsbyen:
https://datalandsbyen.norge.no/topic/127/open-data-challenge-27-01-2022
![image.png](https://images.zenhubusercontent.com/6156b64dc26db0798c7faadf/aef793ff-5369-415f-a17b-978c6b0d7de5)

**Comment by livarb** [comment]
@LeneSundsbo : kan du ta ein titt på denne?

**Comment by livarb** [comment]
Kudos for kjapp levering! :)

![image](https://user-images.githubusercontent.com/3617256/149091307-4d6be808-975d-4fb6-a4d9-0fea70a0acac.png)

**Comment by shenluna** [comment]
Lukker dermed saken :)
