### ISSUE TITLE
FEIL Registreringsfelt for "Kategorier av registrerte og kategorier av personopplysninger" lagrer ikke/er forskjøvet

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#493]
Om jeg skriver noe i feltet "Kategorier av registrerte", skal teksten vises som et sort felt med hvit tekst under registreringsfeltet. Nå skjer det ingenting når jeg trykker enter etter teksten. 
Når jeg skriver i registreringsfeltet for "Kategorier av personopplysninger tilknyttet den registrerte", får jeg lagret når jeg trykker enter, men registreringsfeltet står feil plassert:
![image](https://user-images.githubusercontent.com/32771488/149198897-4dbc9c26-faf3-45ca-8a99-09bf97b78c2a.png)

**Comment by joebrreg** [comment]
Feltet "Kategorier av registrerte" er et normalt inputfelt. Det skal ikke være mulig å legge inn flere verdier her: 
![image](https://user-images.githubusercontent.com/46488929/149284168-2f7ab08d-0766-44a8-ae77-6bb88f7039ae.png)
Når det gjelder plassering av inputfelt for "Kategorier av personopplysninger..." er det helt klart feil plassert.

**Comment by shenluna** [comment]
Testet og verifisert ok
