### ISSUE TITLE
Feil i ledetekst for Kategori av registrerte

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#494]
Overskrift "Kategorier av registrerte" skal endres til "Kategori av registrerte" slik at overskriften viser kategori i entall:

![image](https://user-images.githubusercontent.com/32771488/151782390-b1097b06-3eb3-46d4-8565-748c57054f4e.png)

**Comment by shenluna** [comment]
Testet ok 
![image](https://user-images.githubusercontent.com/73637969/155323500-ee98fd2c-8808-4bf3-a708-22e548f1cd1c.png)
