### ISSUE TITLE
ETL for datasett med skjermingshjemmel

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-issue-tracker#495]
Alle datasett med en eller annen verdi i feltet skjermingshjemmel OG som har verdien restricted flyttes til non-public
I versjon 2.x av dcat er dette cpsv:follows. I versjon 1.x det dcatno:accessRightsComment

**Comment by valosnah** [comment]
Tatt en extract i prod.
Følgende titler vil berøres:
(merk at dette er fra dataset-catalog, så noen kan være draft/duplikat)

`{
    "4aee4ef0-e112-4675-acc7-08a9a4559ce8": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Kontakt- og reservasjonsregisteret",
            "en": "Norwegian Digital Contact Information Register"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/forskrift/2004-06-25-988/§29",
                "prefLabel": {
                    "nb": "eForvaltningsforskriften § 29 andre ledd"
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    },
    "c76c5699-1c4e-4894-b3ea-c66f5b7ac48f": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {
                "nb": "Begrenset",
                "nn": "Begrenset",
                "en": "Restricted"
            }
        },
        "title": {
            "nb": "Arbeidsgiver- og arbeidstakerregisteret",
            "en": "State Register of Employers and Employees (Aa-registeret)"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://www.nav.no/no/bedrift/tjenester-og-skjemaer/aa-registeret-og-a-meldingen/tilgang-til-aa-registret_kap",
                "prefLabel": {
                    "nb": "Tilgang til Aa-registeret"
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    },
    "8437f0bf-254f-434a-a4c8-2c02838a065d": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Dødsårsaksregisteret ",
            "en": "Norwegian Cause of Death Registry"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/dokument/SF/forskrift/2001-12-21-1476?q=d%C3%B8ds%C3%A5rsaksregisterforskriften",
                "prefLabel": {
                    "nb": "Pårørendes innsynsrett §5.1."
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    },
    "eca29f6e-d016-4093-aff9-f832614f754a": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Gjeldsregisteret"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/lov/2017-06-16-47/§12",
                "prefLabel": {
                    "nb": "Lov om gjeldsinformasjon ved kredittvurdering av privatpersoner (gjeldsinformasjonsloven)"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/lov/2017-06-16-47/§12",
                "prefLabel": {
                    "nb": "Lov om gjeldsinformasjon ved kredittvurdering av privatpersoner (gjeldsinformasjonsloven)"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/lov/2017-06-16-47/§12",
                "prefLabel": {
                    "nb": "Lov om gjeldsinformasjon ved kredittvurdering av privatpersoner (gjeldsinformasjonsloven)"
                }
            }
        ]
    },
    "ae084118-ce5b-44e9-898b-1e6b697da81a": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Gjeldsregisteret"
        },
        "legalBasisForRestriction": [],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/lov/2017-06-16-47/§12",
                "prefLabel": {
                    "nb": "Lov om gjeldsinformasjon ved kredittvurdering av privatpersoner (gjeldsinformasjonsloven)"
                }
            }
        ]
    },
    "c6e862a0-9155-43af-9f1e-0d08d155f30f": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {
                "nb": "Begrenset",
                "nn": "Begrenset",
                "en": "Restricted"
            }
        },
        "title": {
            "nb": "A-melding per inntektsmottaker"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/lov/2012-06-22-43/§7",
                "prefLabel": {
                    "nb": "Taushetsplikt ved drift og forvaltning"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/lov/2012-06-22-43/§6",
                "prefLabel": {
                    "nb": "Ansvar for fellestjenester og behandlingsansvar"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/lov/2012-06-22-43/§8",
                "prefLabel": {
                    "nb": "Tilgang til opplysningene"
                }
            }
        ]
    },
    "4810857f-3cd1-474d-80ab-7d12bd9f4795": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {
                "nb": "Begrenset",
                "nn": "Begrenset",
                "en": "Restricted"
            }
        },
        "title": {
            "nb": "Valutaregisteret"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/NL/lov/2016-05-27-14/§3-1",
                "prefLabel": {
                    "nb": "Skatteforvaltningsloven §3-1"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/NL/lov/2004-05-28-29/§3",
                "prefLabel": {
                    "nb": "Valutaregisterloven §§ 3 til 7 "
                }
            },
            {
                "uri": "https://lovdata.no/NL/lov/2004-05-28-29/§9",
                "prefLabel": {
                    "nb": "Valutaregisterloven §9"
                }
            },
            {
                "uri": "https://lovdata.no/pro/#document/SF/forskrift/2004-12-06-1573/%C2%A73",
                "prefLabel": {
                    "nb": "Valutaregisterforskriften §§ 1 til 13"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/NL/lov/2016-05-27-14/§3-3",
                "prefLabel": {
                    "nb": "Skatteforvaltningsloven §§ 3-3 til 3-9"
                }
            }
        ]
    },
    "ea29742f-d7ab-4de0-93f2-f1be891325cb": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {
                "nb": "Begrenset",
                "nn": "Begrenset",
                "en": "Restricted"
            }
        },
        "title": {
            "nb": "A-meldingen"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/lov/2012-06-22-43/§7",
                "prefLabel": {
                    "nb": "Taushetsplikt ved drift og forvaltning"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/lov/2012-06-22-43/§6",
                "prefLabel": {
                    "nb": "Ansvar for fellestjenester og behandlingsansvar"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/lov/2012-06-22-43/§8",
                "prefLabel": {
                    "nb": "Tilgang til opplysningene"
                }
            }
        ]
    },
    "d9096b50-6b4e-41bb-ba10-d4a07e8c023d": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Akvakulturregisteret"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/forskrift/2005-12-28-1706/§17",
                "prefLabel": {
                    "nb": "Forskrift om Akvakulturregisteret §17"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/lov/2005-06-17-79/§18",
                "prefLabel": {
                    "nb": "Lov om akvakultur §18"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2005-12-28-1706/§6",
                "prefLabel": {
                    "nb": "Forskrift om Akvakulturregisteret §6"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/forskrift/2005-12-28-1706/§16",
                "prefLabel": {
                    "nb": "Forskrift om Akvakulturregisteret §16"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2005-12-28-1706/§17",
                "prefLabel": {
                    "nb": "Forskrift om Akvakulturregisteret §17"
                }
            }
        ]
    },
    "738d67e0-da45-4535-b006-66402eaf371f": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Konkursregisteret"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/forskrift/1993-08-23-824/§10",
                "prefLabel": {
                    "nb": "Forskrift om Konkursregisteret og om kunngjøringer etter konkursloven §10"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/1993-08-23-824/§11",
                "prefLabel": {
                    "nb": "Forskrift om Konkursregisteret og om kunngjøringer etter konkursloven §11"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/1993-08-23-824/§12",
                "prefLabel": {
                    "nb": "Forskrift om Konkursregisteret og om kunngjøringer etter konkursloven §12"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/forskrift/1993-08-23-824/§3",
                "prefLabel": {
                    "nb": "Forskrift om Konkursregisteret og om kunngjøringer etter konkursloven §3"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§13",
                "prefLabel": {
                    "nb": "Forskrift om gebyr til Brønnøysundregistrene §13"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/1993-08-23-824/§9",
                "prefLabel": {
                    "nb": "Forskrift om Konkursregisteret og om kunngjøringer etter konkursloven §9"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/1993-08-23-824/§18",
                "prefLabel": {
                    "nb": "Forskrift om Konkursregisteret og om kunngjøringer etter konkursloven §18"
                }
            }
        ]
    },
    "82cc57e2-c094-4517-961a-947a249ad059": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Gjeldsordningsregisteret"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§13",
                "prefLabel": {
                    "nb": "Forskrift om gebyr til Brønnøysundregistrene §13"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§7",
                "prefLabel": {
                    "nb": "Forskrift om gebyr til Brønnøysundregistrene §7"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§6",
                "prefLabel": {
                    "nb": "Forskrift om gebyr til Brønnøysundregistrene §6"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/1995-11-03-875/§18",
                "prefLabel": {
                    "nb": "Forskrift om tinglysing §18"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/lov/1992-07-17-99/§7-1",
                "prefLabel": {
                    "nb": "Gjeldsordningsloven §7-1"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§13",
                "prefLabel": {
                    "nb": "Forskrift om gebyr til Brønnøysundregistrene §13"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§7",
                "prefLabel": {
                    "nb": "Forskrift om gebyr til Brønnøysundregistrene §7"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§6",
                "prefLabel": {
                    "nb": "Forskrift om gebyr til Brønnøysundregistrene §6"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/1995-11-03-875/§18",
                "prefLabel": {
                    "nb": "Forskrift om tinglysing §18"
                }
            }
        ]
    },
    "1ffcb9e4-008b-4333-a372-268f50d01482": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Reservasjonsregisteret"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/forskrift/2009-06-05-598/§3",
                "prefLabel": {
                    "nb": "Forskrift om Reservasjonsregisteret §3"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/forskrift/2009-06-05-598/§3",
                "prefLabel": {
                    "nb": "Forskrift om Reservasjonsregisteret §3"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/forskrift/2009-06-05-598/§3",
                "prefLabel": {
                    "nb": "Forskrift om Reservasjonsregisteret §3"
                }
            }
        ]
    },
    "c50854ed-e754-462b-9cfc-9d1df0cb57fd": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {
                "en": "Public",
                "nb": "Offentlig",
                "nn": "Offentlig"
            }
        },
        "title": {
            "nb": "Partiregisteret"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/LTI/forskrift/2005-11-24-1433/§2",
                "prefLabel": {
                    "nb": "Forskrift om registrering av politiske partier"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/LTI/forskrift/2005-11-24-1433/§2",
                "prefLabel": {
                    "nb": "Forskrift om registrering av politiske partier"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/lov/1994-06-03-15/§22",
                "prefLabel": {
                    "nb": "Lov om Enhetsregisteret"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§6",
                "prefLabel": {
                    "nb": "Forskrift om gebyr til Brønnøysundregistrene"
                }
            },
            {
                "uri": "https://lovdata.no/LTI/forskrift/2005-11-24-1433/§7",
                "prefLabel": {
                    "nb": "Forskrift om registrering av politiske partier"
                }
            }
        ]
    },
    "c0d24886-2075-421e-ae36-9d2c3d9c2c86": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Tilda tilsynsrapport"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/lov/2006-05-19-16/§13",
                "prefLabel": {
                    "nb": "Offentleglova § 13"
                }
            },
            {
                "uri": "https://lovdata.no/lov/1967-02-10/§13",
                "prefLabel": {
                    "nb": "Forvaltningsloven § 13"
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    },
    "4bc631c1-0b58-41d1-8d49-9271ddca04ff": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Løsøreregisteret"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§7",
                "prefLabel": {
                    "nb": "Forskrift om gebyr til Brønnøysundregistrene §7"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§13",
                "prefLabel": {
                    "nb": "Forskrift om gebyr til Brønnøysundregistrene §13"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/forskrift/1995-11-03-875/§16",
                "prefLabel": {
                    "nb": "Forskrift om tinglysing §16"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§7",
                "prefLabel": {
                    "nb": "Forskrift om gebyr for Brønnøysundregistrene §7"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2015-12-11-1668/§13",
                "prefLabel": {
                    "nb": "Forskrift om gebyr for Brønnøysundregistrene §13"
                }
            }
        ]
    },
    "d8e4d37d-f9d0-409b-a62e-c37e10174ebd": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Tilsynsrapport"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/lov/2006-05-19-16/%C2%A713",
                "prefLabel": {
                    "nb": "Offentleglova § 13"
                }
            },
            {
                "uri": "https://lovdata.no/lov/1967-02-10/%C2%A713",
                "prefLabel": {
                    "nb": "Forvaltningsloven § 13"
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    },
    "cdca9b17-4e6c-4784-975b-be094c0dafa9": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Tilda tilsynskoordinering"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/lov/2006-05-19-16/§13",
                "prefLabel": {
                    "nb": "Offentleglova § 13"
                }
            },
            {
                "uri": "https://lovdata.no/lov/1967-02-10/§13",
                "prefLabel": {
                    "nb": "Forvaltningsloven § 13"
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    },
    "6bbc58cd-fd1b-4b02-a542-e25cb7047120": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Akvakulturregisteret"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/forskrift/2005-12-28-1706/§16",
                "prefLabel": {
                    "nb": "Forskrift om Akvakulturregisteret § 16"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2005-12-28-1706/§17",
                "prefLabel": {
                    "nb": "Forskrift om Akvakulturregisteret § 17"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2005-12-28-1706/§20",
                "prefLabel": {
                    "nb": "Forskrift om Akvakulturregisteret § 20"
                }
            }
        ],
        "legalBasisForProcessing": [
            {
                "uri": "https://lovdata.no/forskrift/2005-12-28-1706/§5",
                "prefLabel": {
                    "nb": "Forskrift om Akvakulturregisteret § 5"
                }
            },
            {
                "uri": "https://lovdata.no/lov/2005-06-17-79/§18",
                "prefLabel": {
                    "nb": "Lov om akvakultur § 18"
                }
            }
        ],
        "legalBasisForAccess": [
            {
                "uri": "https://lovdata.no/forskrift/2005-12-28-1706/§16",
                "prefLabel": {
                    "nb": "Forskrift om Akvakulturregisteret § 16"
                }
            },
            {
                "uri": "https://lovdata.no/forskrift/2005-12-28-1706/§17",
                "prefLabel": {
                    "nb": "Forskrift om Akvakulturregisteret § 17"
                }
            }
        ]
    },
    "47163698-67de-41e2-a37a-3bcd52675b73": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Tilda trender"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/lov/2006-05-19-16/§13",
                "prefLabel": {
                    "nb": "Offentleglova § 13"
                }
            },
            {
                "uri": "https://lovdata.no/lov/1967-02-10/§13",
                "prefLabel": {
                    "nb": "Forvaltningsloven § 13"
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    },
    "fa079d2e-2f86-45cc-8b97-f5bc6fdb70cd": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Tilda melding til annen myndighet"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/lov/2006-05-19-16/§13",
                "prefLabel": {
                    "nb": "Offentleglova § 13"
                }
            },
            {
                "uri": "https://lovdata.no/lov/1967-02-10/§13",
                "prefLabel": {
                    "nb": "Forvaltningsloven § 13"
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    },
    "caa0ae52-7859-4eae-878d-12c55795279f": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Tilda tilsynsrapport"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/dokument/NL/lov/2006-05-19-16?q=offentleglova",
                "prefLabel": {
                    "nb": "Offentleglova § 13 "
                }
            },
            {
                "uri": "https://lovdata.no/dokument/NL/lov/1967-02-10?q=forvaltningsloven",
                "prefLabel": {
                    "nb": "Forvaltningsloven § 13"
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    },
    "e74b46ec-a091-4046-8326-39f8508acc4f": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Tilda tilsynskoordinering"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/dokument/NL/lov/2006-05-19-16?q=offentleglova",
                "prefLabel": {
                    "nb": "offentleglova § 13 "
                }
            },
            {
                "uri": "https://lovdata.no/dokument/NL/lov/1967-02-10?q=forvaltningsloven",
                "prefLabel": {
                    "nb": "forvaltningsloven § 13"
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    },
    "1e02e682-159f-4efc-b518-15bc33f3cbbf": {
        "accessRights": {
            "uri": "http://publications.europa.eu/resource/authority/access-right/RESTRICTED",
            "prefLabel": {}
        },
        "title": {
            "nb": "Tilda trender"
        },
        "legalBasisForRestriction": [
            {
                "uri": "https://lovdata.no/dokument/NL/lov/2006-05-19-16/KAPITTEL_3#%C2%A713",
                "prefLabel": {
                    "nb": "offentleglova § 13"
                }
            },
            {
                "uri": "https://lovdata.no/dokument/NL/lov/1967-02-10/KAPITTEL_3#%C2%A713",
                "prefLabel": {
                    "nb": "forvaltningsloven § 13"
                }
            }
        ],
        "legalBasisForProcessing": [],
        "legalBasisForAccess": []
    }
}`
