### ISSUE TITLE
Får opp innlogging til Oslo kommune i produksjonsmiljøet på bruker som ikke har noe knytning til virksomheten

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#497]
Får opp innloggingen til Oslo kommune i produksjonsmiljøet på en bruker som ikke skal ha noe knytning til denne virksomheten.

Fremgangsmåte:

Jeg hadde en bruker i Felles brukerhåndtering som ikke var knyttet til FDK. Registrerte en ny bruker i Felles brukerhåndtering med tilgang til FDK som ikke finnes fra før i Felles brukerhåndtering. Logget så inn på user.difi.no på den brukeren som ikke var knyttet til FDK. Endrer e-postadressen/brukernavnet til denne brukeren til den samme som jeg hadde registrert med tilgang til FDK. Forsøker så å logge inn med denne brukeren i FDK via Felles brukerhåndtering. Etter å ha verifisert e-postadressen så får jeg dette bildet:

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/43232700/149520434-ae4cdaee-fb9e-4c7e-a310-0c23d644aaed.png)

Velger "Add to existing account". Får innloggingsvindu på nytt og trykker Logg inn via Felles brukerhåndtering. Da får jeg dette vinduet:

![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/43232700/149520542-1f1aebc5-ae10-47fb-b291-3b10c58879a5.png)

**Comment by joachim-me** [comment]
Gjelder denne fortsatt?

**Comment by joachim-me** [comment]
Ikke lenger aktuell.
