### ISSUE TITLE
Fjerne staging og demo fra søkeindex

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#5]
Man kan idag få opp både demo og staging når man søker på felles datakatalog

- [x] Sette opp robots.txt i fdk-nginx-search, evt oppdatere med noindex-direktiv

**Comment by valosnah** [comment]
Noindex er lagt inn, venter i spenning på at google skal reindeksere (fjerne) sidene.
For ordens skyld: for å få opp staging/demo, må man spesifikt søke på dette.

**Comment by lillelars** [comment]
Denne er løst. PR håndteres via annen issue. Lukker saken.
