### ISSUE TITLE
Det blir opprettet mange dublettbrukere i datalandsbyen

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#505]
Det blir opprettet mange dublettbrukere i datalandsbyen.Brukere som blir opprettet får 2 brukere med samme e-postadresse og navn, der systemet legger til «- 1» i navnet på den ene brukeren. Eks.:
![image](https://user-images.githubusercontent.com/43232700/151129024-5dd027c5-732a-47fb-9dd6-50c756fbd151.png)

**Comment by KurtStian** [comment]
Jeg fikk også dublettbruker da jeg testet å opprett ny bruker (kurtstia). Jeg hadde denne brukeren i datalandsbyen og felles brukerhåndtering fra før. Jeg slettet brukeren i datalandsbyen (via users) og felles brukerhåndtering via user.difi.no. Valgte så logg inn/registrere via datalandsbyen. Registrerte så brukeren på nytt.

**Comment by valosnah** [comment]
Dette ble oppdaget da det ble meldt inn at brukere opplevde å få 403 ved registrering. Kan virke som noen brukere ikke blir gjenkjent og må registrere seg på nytt.

Kallene ser slik ut:
https://datalandsbyen.norge.no/register/complete/?_csrf=fkTdsx4q-WtRk3YNwMCub-63-u--BE7cEk2Y
Det virker som de blir avvist pga ugyldig csrf-token.

Hovedandelen av dublettbrukere ser ut til å være fra rundt nyttår eller nyere, men vii ser dubletter i databasen helt tilbake til september 2021, så dette kan ha vært et problem lenge.

**Comment by jeffreiffers** [comment]
Har lagt inn en fix på duplikater ved å gjøre en ekstra sjekk akkurat før man oppretter en bruker med tilpasset brukernavn. Dette løser ikke 403 + csrf.
