### ISSUE TITLE
Cloud Armor blokkerer innlegg i Datalandsbyen med SQL-kode

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/fdk-issue-tracker#507]
Dette innlegget får ein 403-feilmelding på ved posting:
https://datalandsbyen.norge.no/topic/130/nedlasting-av-data-om-kj%C3%B8ret%C3%B8y/7

Midlertidig løysing her er å legge koden inn som skjermbilder.

Tre problemstillingar:

1. Må vere tillete å legge inn slike koder.

2. I front-end får brukar kun varsel om "error". Kan vi gje meir tilbakemelding til brukaren?

3. Følgjer vi med på slike feilmeldingar og følger dei opp fortløpande?
Det er nok ikkje alle brukarar som støter på slike problem som gir beskjed.

Dei linjene som gjer at posten blir blokkert frå innlegging.

```
q -C readwrite -H -O --delimiter=\; "SELECT COUNT(*) FROM kjoretoy.csv WHERE tekn_merkenavn = 'BMW'"
```

```
q -C read -H -O --delimiter=\; "SELECT * FROM kjoretoy.csv WHERE tekn_merkenavn = 'BMW'" > kjoretoy_bmw.csv
```

**Comment by KurtStian** [comment]
Kodesnutter som legges inn i Datalandsbyen bør skrives om slik at de ikke kan kjøres.
Hans Olav sjekker hva som er mulig i Cloud Armor.

**Comment by livarb** [comment]
Kommentar på denne spesifikke problemet i beskrivelsen.
Meinar å hugse det vart løyst for dei spesifikke kodane. Fekk til slutt lagt dei inn.

Utfordringa er at ved litt andre kodar får ein kanskje samme problemet på nytt.
Vil tippe NodeBB har nokon mekanismer som gjer at ein ikkje kan injisjere JavaScript-kode i postar, men det veit eg ikkje.

**Comment by livarb** [comment]
Trur ikkje det er så stort omfang på dette.
Tenker det viktigaste vi kan gjere er å få varsel dersom det skjer igjen (forsøk på å legge inn post blir stoppa), og så kan vi heller følgje opp om det blir eit problem.

**Comment by KurtStian** [comment]
Mulig løsning kan være å sette opp et loggfilter i GCP som sender ut melding til slack for disse feiltypene.

**Comment by KjerstiSteien** [comment]
@KurtStian @livarb skal vi gjøre noe med dette, eller bare lukke den og vente til det eventuelt skjer igjen?

**Comment by livarb** [comment]
Foreslår vi berre lukkar saka for no, og så tar vi det dersom problemet oppstår igjen.
