### ISSUE TITLE
Datasett registrering lisens uri

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#509]
Ved registrering av lisens i registreringskatalogen blir data.norge satt
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/e203fd71-2b74-4ca9-b1af-73b6c757c2a3)

Denne skal settes til lisens uri fra EU
http://publications.europa.eu/resource/authority/licence/NLOD_1_0
http://publications.europa.eu/resource/authority/licence/NLOD_2_0

**Comment by NilsOveTen** [comment]
@shenluna Må vi også kjøre en ETL for å endre de som er satt til data.norge.no/nlod til eu-versjonen?

**Comment by shenluna** [comment]
@NilsOveTen Jeg tror nok det er ønskelig, men jeg kaster spørsmålet videre til @stigbd

**Comment by stigbd** [comment]
Ja, det meiner eg. Noverande praksis er feil og validerer ikkje.

**Comment by NilsOveTen** [comment]
Registrering henter listen med åpne lisenser fra reference-data, vi bør først fikse det der. Tenker dette er et ba tidspunkt å få inn åpne lisenser i `new-reference-data`, forslag til kjøreplan:

1. Legg til åpne lisenser fra EU i new-reference-data
2. Endre henting av åpne lisenser i `dataset-catalog-gui` fra `reference-data` til `new-reference-data`
3. Endre henting av åpne lisenser i `fdk-rdf-parser` fra `reference-data` til `new-reference-data`
4. ETL for `dataset-catalog` hvor lisenser blir oppdatert til å bruke EU-lisenser

**Comment by NilsOveTen** [comment]
Sitat Øystein:
> Vi treng 3 lisensar frå http://publications.europa.eu/resource/authority/licence : NLOD v.2.0, CC0 og CC-BY 4.0

Så reduserer åpne lisenser i reference-data til disse 3 og kjører tilhørende ETL
