### ISSUE TITLE
Bruker får ikke opprettet ny behandlingsaktivitet dersom det ikke er opprettet noe data på virksomheten fra før

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#51]
- [x] Bruker får ikke opprettet nye behandlingsaktiviteter DERSOM det ikke er opprettet noen data på virksomheten fra før(?)

Jeg har får ikke opprettet ny behandlingsaktivitet  i demomiljøet, uten at en datasettbeskrivelse er registrert og godkjent først.   

Resultat fra  "Norsk forening for tur- og tidsspørsmål" i demo:
Bruksvilkår er akseptert for virksomheten, men det var ikke registrert noe annet i Behandlingsoversikt eller i Datasettkatalogen, Begrepskatalogen eller API-katalogen. Jeg  sjekket at jeg ikke var innlogget i skrivebruker ved å klikke på feltet for "Navn på behandlingsansvarliges representant" hvor jeg da fikk tilgang til å skrive.

Dajeg klikket på knappen "Legg til behandlingsaktivitet", fikk jeg ikke tilgang til bolkene og registreringsfeltene hvor jeg lagrer informasjon om ny behandlingskaitivitet:

![image](https://user-images.githubusercontent.com/32771488/97799130-50858b00-1c2c-11eb-9501-5084521fa54e.png)

Jeg fikk da dette resultatet: 

![image](https://user-images.githubusercontent.com/32771488/97799148-71e67700-1c2c-11eb-96c4-d940afd8bf6c.png)

Jeg gjorde flere forsøk på å gå inn og ut av behandlingsaktiviteter og fikk samme resultat hver gang. 

Deretter opprettet jeg en datasettbeskrivelse i "Norsk forening for tur- og tidsspørsmål" med kun obligatoriske felt utfylt og ga den status "Godkjent".   Da jeg åpnet "Behandlingsoversikt" på nytt, fikk jeg opprettet en ny Behandlingsaktivitet. Det kan derfor se ut som at man må ha registrert en datasettbeskrivelse for å kunne registrere en datasettbeskrivelse i løsningen. Det er i så fall en feil.

**Comment by lillelars** [comment]
@RogerSOlsen - denne feilen du beskrev er rettet. Testet og verifisert at det fungerer i demo-miljøet, i chrome.
