### ISSUE TITLE
Feil på dct:identifier for skos:Concept

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#510]
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/b7bb1da3-cb33-4fc0-a544-248b0aea2b30)

https://www.w3.org/TR/vocab-dcat-2/#Property:resource_identifier
https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-identifikator

**Comment by NilsOveTen** [comment]
Er blokkert av: https://github.com/Informasjonsforvaltning/skos-ap-no-begrep/issues/127

- [ ] concept-catalog
- [ ] ConceptBuilder i skos-ap-no-tools
- [ ] org-type og org-status i organization-catalogue

**Comment by jimjyang** [comment]
> Er blokkert av: [Informasjonsforvaltning/skos-ap-no-begrep#127](https://github.com/Informasjonsforvaltning/skos-ap-no-begrep/issues/127)

@NilsOveTen shacl er endret, kan du se om blokkeringen er løst?
