### ISSUE TITLE
Feil/endringsønske: navn på Datasettbeskrivelse(r) i rapportene "Behandlingsoversikt HTML og CSV er ikke forståelig

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#514]
Rapportene Behandlingsoversikt" (HTML) og Behandlingsoversikt CSV skal vise tilhørende datasett dersom det er knyttet datasettbeskrivelser til behandlingsaktiviteten. Nå viser de ikke navnet på behandlingsaktiviteter. De viser kun en uforståelig kode og må endres slik at de i stedet viser navnet på datasettbeskrivelsen.
Eksempel fra registreringsløsning:
![image](https://user-images.githubusercontent.com/32771488/151789445-1de29d5b-6ba9-45b3-8fd7-61b6990a5dd8.png)
Samme datasettbeskrivelser vises slik i rapport Behandlingsoversikt (HTML):
![image](https://user-images.githubusercontent.com/32771488/151789565-c7a17143-fb00-43f2-b930-b904603deeb2.png)
og vises slik i rapport Behandlingsoversikt CSV:
![image](https://user-images.githubusercontent.com/32771488/151790034-cdeb19e3-f079-4bb9-9d8c-4cb921e7ae3f.png)

**Comment by shenluna** [comment]
Testet ok

**Comment by shenluna** [comment]
Verifisert ok
