### ISSUE TITLE
Feil: får ikke sortert behandlingsaktiviteter etter "Navn/tittel" eller "Daglig behandlingsansvarlig

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#515]
Piltastene for sortering av behandlingsaktiviteter etter "Navn/tittel" eller "Daglig behandlingsansvar" virker ikke:

![image](https://user-images.githubusercontent.com/32771488/151807569-6732f77a-8980-4167-b7c8-565f7d8ea05a.png)
 Det går greit å sortere etter "Status"

**Comment by shenluna** [comment]
Testet ok
![image](https://user-images.githubusercontent.com/73637969/155324243-bfe4edbb-e6d6-424e-b21a-076e0d4e0056.png)

**Comment by shenluna** [comment]
Verifisert ok
