### ISSUE TITLE
Feil i sparql

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#517]
Når man går inn på sparql-spørring ser siden slik ut
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/fa0fe75d-78a3-4372-b309-e475151ae7c6)

**Comment by matsjs** [comment]
Lukket av https://github.com/Informasjonsforvaltning/fdk-portal/pull/1156
