### ISSUE TITLE
Feltet «endepunktbeskrivelse» blir ved en feil satt som et obligatorisk felt i sjekken om utfylte felt i registreringsløsningen for API

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#518]
Feltet «endepunktbeskrivelse» blir ved en feil satt som et obligatorisk felt i sjekken om utfylte felt i registreringsløsningen for API. I spesifikasjonen er dette et anbefalt felt: https://data.norge.no/specification/dcat-ap-no/#Datatjeneste-endepunktsbeskrivelse

Eks.:
![image](https://user-images.githubusercontent.com/43232700/152160349-14cef170-19dd-414a-b3ba-b0e9c3fa068b.png)

**Comment by shenluna** [comment]
Testet ok
