### ISSUE TITLE
Lage en visning/rapport som viser hvor i skyen (Europa) tjenestene kjører

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#519]
Vi ønsker å ha det dokumentert  at alle tjenester vi bruker ligger i Europa (zone europe-north1 eller europe-west1).

Et dashboard? Rapport? Et bilde?

**Comment by valosnah** [comment]
Løst

https://digdir.sharepoint.com/:w:/r/sites/FDKUtviklingsteam/Delte%20dokumenter/IT%20Infrastruktur/FDK%20cloud%20location.docx?d=w83d4c5c8aa9b4dfab2b48e55b929ccca&csf=1&web=1&e=WbHpjd
