### ISSUE TITLE
Slette-ETL (ryddejobb) for samtlige høstere

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#525]
Det forekommer relativt hyppig at det oppstår duplikater i høsterne (pga retting av skrivefeil, osv)
Det er en smal sak å fjerne søkbarheten for duplikatene, men de eksisterer fortsatt, og er mulige å nå via direktelenken.

Vi trenger å opprette en ETL som gjør følgende:

Sammenlikne innhold i fs.files (1) med catalogMeta (2) og <datatype>Meta (3).
Slett innhold fra fs.files og fs.chunks som ikke eksisterer i 2 & 3.

**Comment by KjerstiSteien** [comment]
@valosnah Fortsatt relevant etter refaktorering av høsteløpet?

**Comment by valosnah** [comment]
@KjerstiSteien 
Ja, absolutt.

**Comment by NilsOveTen** [comment]
det kan være vi bør se på flere situasjoner som kan oppstå, er kanskje ikke nøyaktig samme fremgangsmåte som er best hver gang:

- En ressurs har fått ny URI i høstekilden
  - Den har allerede blitt høstet og er listet 2 ganger på Data.norge.no
  - Den har ikke blitt høstet enda, men neste høsting vil resultere i at den listes 2 ganger
- En ressurs skal fjernes fra Data.norge.no
  - Er det ok at den beholder dyplenking?
- Alle ressurser fra en katalog skal fjernes fra Data.norge.no
- En ressurs har blitt fjernet fra søket i Data.norge.no, men skal nå også fjernes fra dyplenking

**Comment by NilsOveTen** [comment]
- [Endepunkt for å fjerne json-dyplenking](https://github.com/Informasjonsforvaltning/fdk-resource-service/issues/45)
- Endepunkt for å fjerne ressurser fra Data.norge.no:
  - datasett
  - begreper
  - datatjenester
  - informasjonsmodeller
  - tjenester
  - hendelser
- Endepunkt for å endre IRI for eksisterende ressurser i Data.norge.no:
  - datasett
  - begreper
  - datatjenester
  - informasjonsmodeller
  - tjenester
  - hendelser
- Fjerning av RDF-dyplenking bør tas som ETL'er
- Skal vi legge til støtte for sletting av hele kataloger og/eller alle ressurser fra en høstekilde?
