### ISSUE TITLE
Varsle om feil når vi ikke klarer å høste

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#526]
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/684

I dagens løsning får man opp en liten melding om at man har sendt en høste forespørsel vel å klikke på høst.
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/48675d9e-6f41-4a47-82ac-e94173cf383b)

Man får da inntrykket av at det man har lagt inn skal bli høstet og etterhvert skal vises i portal. Når det vi prøver å høster ikke går igjennom høsteprosessen, kommer det ikke ut i portal, og brukeren får ingen tilbakemelding om at noe er galt.

Vi ønsker derfor å varsle om feil ved fremtidig høsting. 

Ting som skal løses:
Sende varsel
Vise loggen

**Comment by NilsOveTen** [comment]
Løst av https://github.com/Informasjonsforvaltning/fdk-admin-gui/pull/128
