### ISSUE TITLE
Dokumentere søk

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#527]
Se behov: https://github.com/datadeling/behov-issue-tracker/issues/137

Vi har i dag en side som skal forklare søk og filter, denne har per dags dato ikke innhold.
Vi ønsker å fylle ut denne med informasjon om dagens søkeløsning.

**Comment by KjerstiSteien** [comment]
Oppgave i refinement: Bli enige om hvem som skal være med på å bygge denne dokumentasjonen og hva den bør inneholde.

**Comment by KjerstiSteien** [comment]
@NilsOveTen tar du denne som del av skrivejobben på informasjonsforvaltning.github.io?
