### ISSUE TITLE
Modellkatalog: engelsk navn brukes/vises ikke under Contact information 

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/fdk-issue-tracker#528]
Se f.eks. https://data.norge.no/informationmodels/8bfa055a-9b0c-40df-a7c2-2e58173eb2e0

Selv om vcard:hasOrganizationName har tekst med lang-tag "en", vises ikke det engelske navnet under Contact information når engelsk er valgt som språket for FDK-GUI. 

<img width="504" alt="image" src="https://user-images.githubusercontent.com/46558821/153880759-d550bf99-38b9-47ca-a428-fdce2e0ca8a4.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/46558821/153880557-74cb9174-d513-4b5c-90ff-2a5e68a72aa8.png">

**Comment by stigbd** [comment]
Dette gjeld også :digdir-contact-point triplet:
```
:digdir-contact-point
        rdf:type                   vcard:Organization ;
        vcard:hasEmail             "mailto:informasjonsforvaltning@digdir.no" ;
        vcard:hasOrganizationName  "Norwegian digitalisation agency"@en , "Digitaliseringsdirektoratet"@nb , "Digitaliseringsdirektoratet"@nn ;
        vcard:hasURL               <https://digdir.no> .
```

**Comment by stigbd** [comment]
Eg gjettar på at årsaka er at informasjon om navn på andre språk ikkje er med i json-representasjonen som front-end brukar:
```
contactPoint: [{,…}]
0: {,…}
email: "informasjonsforvaltning@digdir.no"
fullname: null
hasTelephone: null
hasURL: "https://digdir.no"
organizationName: "Digitaliseringsdirektoratet"
organizationUnit: null
uri: "https://raw.githubusercontent.com/Informasjonsforvaltning/model-publisher/master/src/model/catalog-of-models-for-specifications.ttl#digdir-contact-point"
```
Eksempel på request:
```
curl -H "Accept: application/json" https://www.fellesdatakatalog.digdir.no/information-models/f4c2ff8d-3137-36a9-b762-3513fb1da5e8
```

https://www.fellesdatakatalog.digdir.no/information-models/f4c2ff8d-3137-36a9-b762-3513fb1da5e8

**Comment by NilsOveTen** [comment]
Det er `fdk-rdf-parser` som ikke tar hensyn til at `vcard:hasOrganizationName` kan ha flere språk, kan gjøre en oppdatering der for det. Skal også `vcard:organization-unit` støtte flere språk?

**Comment by jimjyang** [comment]
> Skal også `vcard:organization-unit` støtte flere språk?
Ja

**Comment by shenluna** [comment]
Testet og prodsatt
![image](https://user-images.githubusercontent.com/73637969/171613016-a753fac1-a07e-47f5-8ae5-0a6a5cd5ede6.png)
