### ISSUE TITLE
RDF-visning av tjeneste

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#531]
Skal fungere på samme måte som for datasett, api og begrep. Når ein går til detaljsida for tjeneste, skal ein kunne få rdf content dersom ein angir dette i accept-header. Eksempel:
https://data.norge.no/public-services-and-events/536bfa22-0126-3032-b31a-af8d05b7b0ae

Evt 406 viss det ikkje går.

**Comment by valosnah** [comment]
Blocked by https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/537
