### ISSUE TITLE
RDF-visning av hendelse

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#532]
Skal fungere på samme måte som for datasett, api og begrep. Når ein går til detaljsida for hendelse, skal ein kunne få rdf content dersom ein angir dette i accept-header. Eksempel:
https://data.norge.no/events/92bf30ca-9fc1-35c7-ac7e-88b0188a2dc9

Evt 406 viss det ikkje går.

**Comment by valosnah** [comment]
Blocked by #537
