### ISSUE TITLE
Datakatalog: I dct:Standard skal rdfs:seeAlso brukes istedenfor dct:source

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/fdk-issue-tracker#535]
I henhold til [DCAT-AP-NO](https://data.norge.no/specification/dcat-ap-no/#Standard-harReferanse) skal `rdfs:seeAlso` brukes i klassen `dct:Standard`, til å referere til selve standarden. Nå er det `dct:source` som brukes.

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/dataset-catalog/commit/59062786d20a50e74f01db7bcf6db9d5dea80710
