### ISSUE TITLE
Registrering: dct:license skal EU-listen når lisensen finnes på listen

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/fdk-issue-tracker#536]
I henhold til [DCAT-AP-NO](https://data.norge.no/specification/dcat-ap-no/#Skal-brukes-for-license), _skal_ dct:license ha verdi som er fra EUs liste over lisenser _når_ lisensen som brukes finnes på listen. 

For CC0 som kan velges i registreringsløsning og som finnes på EU-listen, _skal_ `dct:license` peke EU sin `http://publications.europa.eu/resource/authority/licence/CC0` (nå peker den til  `https://creativecommons.org/publicdomain/zero/1.0/`). 

Jeg har ikke sjekket de andre lisenstypene som kan velges i registreringsløsningen.

**Comment by joachim-me** [comment]
Testet ok.
