### ISSUE TITLE
[Epic] fdk-portal skal hente detalj-visning frå fdk-x-harvester (via bffs)

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#537]
Dette er allereie gjort for informasjonsmodeller.
Gjenstår for:
 - [x] datasets
 - [x] dataservices
 - [x] concepts
 - [x] information-models
 - [x] events
 - [x] public-service *

\* her må url i portal endres til `https://data.norge.no/public-services/62966d9d-a547-3a66-a588-3fdf0f97d885`

**Comment by stigbd** [comment]
Avhenger av #538

**Comment by terjesyl** [comment]
Var ferdigstilt
