### ISSUE TITLE
Utfasing av fdk-dataset-api

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#54]
Vi har fortsatt sju paths i fdk-nginx-search som peker til fdk-dataset-api. Det må bestemmes hva som skal gjøres med disse.

- [x] Møte avtalt
- [x] Hans Olav og Stig møte
- [x] Endringer på nginx basert på resultat av møtet

/api/publishers - ingen trafikk
/search - noe trafikk, men samtlige ser ut til å være crawlerbots
/publisher - mye trafikk både eksternt og av oss selv -> både "https://kommunalt-rapporteringsregister.brreg.no/" og oss selv (/concepts/{id}) som referer i loggen.
/publishers - ingen trafikk
/catalogs - noe trafikk, kan se ut som bare crawlerbots
/datasets.atom - mye trafikk
/datasets.rss - mye trafikk

**Comment by valosnah** [comment]
Denne er sperret inntil https://github.com/informasjonsforvaltning/fdk-issue-tracker/issues/12 blir løst.
Vi kan ikke prodsette før .atom og .rss blir håndtert.

**Comment by valosnah** [comment]
Oppdatert med omdirigering av .rss og .atom

**Comment by valosnah** [comment]
Brreg må opplyses om at /publisher ikke lenger kan brukes (alternativ: organization-catalogue)

**Comment by valosnah** [comment]
Alle endepunkt (bortsett fra /publisher) fjernet fra fdk-nginx-search
rss & atom endepunktene peker nå til fdk-fulltext-search

**Comment by lillelars** [comment]
avventer fortsatt brreg før vi kan lukke denne.

**Comment by stigbd** [comment]
Det er to issues som må løses:
https://github.com/Informasjonsforvaltning/organization-catalogue/issues/85
https://github.com/Informasjonsforvaltning/organization-catalogue/issues/84

**Comment by lillelars** [comment]
@stigbd kan vi nå lukke denne ettersom disse to er løst
Informasjonsforvaltning/organization-catalogue#85
Informasjonsforvaltning/organization-catalogue#84

**Comment by valosnah** [comment]
Endepunkt sjekket, ingen trafikk registrert siste måneden.
BRREG varslet om at vi stenger /publisher onsdag 10.03

**Comment by valosnah** [comment]
/publisher fjernet fra fdk-nginx-search, fdk-dataset-api scalet ned (slettes i løpet av uken)

**Comment by shenluna** [comment]
fdk-dataset-api er slettet. Lukker saken.
