### ISSUE TITLE
Begrepskatalogen: Flyktig feil: Relasjoner mellom begrep vises i katalogen, men vi har ikke lagt dem inn

### ISSUE THREAD

**Issue by hildea** [Informasjonsforvaltning/fdk-issue-tracker#541]
Jeg har registrert en del begreper i begrepskatalogen, via registerløsninga. For noen av dem dukket det opp relasjoner som jeg ikke hadde lagt inn. Jeg gikk inn i registreringsløsninga for å sjekke hva jeg hadde gjort, bekreftet at relasjonene ikke var der, og når jeg gikk tilbake til visninga i begrepskatalogen var de borte.

(En annen person så de samme relasjonene, så det er ikke bare jeg som ser syner :)

Feilen har forsvunnet nå, så det er ikke noe som trenger å gjøres, men jeg logger det i tilfelle det er noe som kan dukke opp igjen.

Begrepet det gjaldt var [understellsnummer](https://data.norge.no/concepts/8e9883c4-5acf-3bed-ba07-5ab1ad9040c2) som i noen timer hadde relasjon til [kontrollfrist periodisk kjøretøykontroll](https://data.norge.no/concepts/d179ecd9-b80a-35bb-b09f-30dfafc13ca6) og [dato for siste godkjenning periodisk kjøretøykontroll](https://data.norge.no/concepts/8778a5d4-8fdd-3f5f-b04e-45ac7681c229). Jeg la inn relasjon fra periodisk kjøretøykontroll til de to siste i samme arbeidsøkt som jeg la inn understellsnummer, så jeg antar et eller annet har blitt duplisert på en eller annen måte mens jeg holdt på.

**Comment by shenluna** [comment]
Hei @hildea
Vi har for øyeblikket en bug hvor informasjon fra tidligere besøkte ressurser henger igjen slik at det ser ut som om de tilhører den du står i. Dette blir borte når du laster siden på nytt. Ut fra beskrivelsen din regner jeg med at det du har opplevd gjelder samme feil. Vi jobber med å rette feilen.
Ref https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/508

**Comment by shenluna** [comment]
Dette skal nå være fikset, lukker dermed saken. Men si gjerne ifra hvis det skulle skje igjen.
