### ISSUE TITLE
Begrepskatalogen: Bare en tillatt og frarådet term vises, selv om jeg legger inn flere

### ISSUE THREAD

**Issue by hildea** [Informasjonsforvaltning/fdk-issue-tracker#542]
Jeg har lagt inn flere tillatte og frarådede termer for et begrep i begrepskatalogen, men bare ett av dem vises.

Eksempel [kjennemerke](https://data.norge.no/concepts/4bd4c9f0-20d4-31a0-9541-d7ecdbddfe77), der jeg har lagt inn registreringsnummer og skilt som tillatte termer, og bilnummer, nummerskilt og bilskilt som frarådede termer, men bare den første av hver av dem vises.
![kjennemerke registrering](https://user-images.githubusercontent.com/6659191/155499544-bd3255d9-7ad8-40b2-a775-784d542ad3b6.jpg)
![kjennemerke visning](https://user-images.githubusercontent.com/6659191/155499545-4ff8864b-404b-4072-aa5f-c99458053c20.jpg)

**Comment by shenluna** [comment]
@hildea Dette er nå fikset.
