### ISSUE TITLE
Feil: rapport Behandlingsoversikt CSV mangler informasjon om status

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#546]
rapport Behandlingsoversikt CSV mangler informasjon om status, dvs om en behandlingsaktivitet har status Utkast eller Godkjent.  Slik informasjon finnes i rapport Behandlingsoversikt HTML

**Comment by terjesyl** [comment]
Er denne fikset? (csv-rapport generert fra demo-miljøet)

![bilde](https://user-images.githubusercontent.com/108797958/183601543-1885115b-dfef-4161-874e-4c875dfc50ea.png)

**Comment by RogerSOlsen** [comment]
Saken er løst.
