### ISSUE TITLE
Oppdatere demo med logo

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#549]
Se behov: Informasjonsforvaltning/tmp_behandlingsoversikt_behov#3

- [x] https://demo.fellesdatakatalog.digdir.no/
- [x] https://demo.fellesdatakatalog.digdir.no/publishing
- [ ] https://sso.demo.fellesdatakatalog.digdir.no/
- [x] https://registrering.demo.fellesdatakatalog.digdir.no/
- [x] https://registrering.demo.fellesdatakatalog.digdir.no/ - Datasett
- [x] https://registrering.demo.fellesdatakatalog.digdir.no/ - API
- [x] https://registrering.demo.fellesdatakatalog.digdir.no/ - Begrep
- [x] https://registrering.demo.fellesdatakatalog.digdir.no/ - Behandlingsoversikt

**Comment by joachim-me** [comment]
https://sso.demo.fellesdatakatalog.digdir.no/ gjenstår. Er det vrient eller bare glemt?
