### ISSUE TITLE
Oppdatere ikoner i Datalandsbyen

### ISSUE THREAD

**Issue by LeneSundsbo** [Informasjonsforvaltning/fdk-issue-tracker#550]
Alle ikoner for kategorier i Datalandsbyen er oppdatert.
Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/community/community-default-d.html

[Lenke til ikoner.](https://drive.google.com/drive/folders/1q4ialddr9NarrXXPXcZixS0IS0tlJv-0?usp=sharing)
Følgende skal benyttes:

- icon-community-comments-lg.svg
- icon-community-dataset-api-lg.svg
- icon-community-events-lg.svg
- icon-community-examples-lg.svg
- icon-community-feedback-lg.svg
- icon-community-law-lg.svg
- icon-community-projects-lg.svg (ny kategori)
- icon-community-tips-lg.svg
- icon-community-transportportal-lg.svg

**Comment by shenluna** [comment]
Disse er oppdatert, lukker dermed saken.
