### ISSUE TITLE
Videreutvikling av Tjeneste og hendelseskatalog

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#553]
Se spesifikasjon: https://informasjonsforvaltning.github.io/cpsv-ap-no/

Eksempler på klassene i tjeneste og hendelseskatalogen: https://github.com/Informasjonsforvaltning/cpsv-ap-no/tree/develop/examples

- [ ] Aktor
- [ ] Åpningstid
- [ ] Åpningstid Resepsjon
- [ ] Åpningstid Telefon
- [ ] Deltagelse Datatilbyder
- [ ] Deltagelse Tjenestemottaker
- [ ] Deltagelse Tjenestetilbyder
- [ ] Dokumentasjon
- [ ] Dokument referanse
- [ ] Gebyr
- [ ] Helligdager åpningstid
- [ ] Helligdager stengt
- [ ] Hendelse
- [ ] Kontakt punkt
- [ ] Livshendelse
- [ ] Offentlig organisasjon
- [ ] Offentlig tjeneste
- [ ] Regel
- [ ] Regulativ ressurs
- [ ] Tidsrom
- [ ] Tjenestekanal epost
- [ ] Tjenestekanal online
- [ ] Tjenestekanal telefon
- [ ] Tjenestekanal kontor
- [ ] Tjenesteresultat
- [ ] Vilkår
- [ ] Virksomhetshendelse

**Comment by KjerstiSteien** [comment]
@KurtStian @LeneSundsbo Er dette et duplikat? Kan det slettes?
