### ISSUE TITLE
Navnet til eier av katalog i registreringsløsningen blir ikke oppdatert i oversikten over alle kataloger og datasettkatalogen

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#554]
Virksomheten UNIT - DIREKTORATET FOR IKT OG FELLESTJENESTER I HØYERE UTDANNING OG FORSKNING  har etter en sammenslåing endret navn til [SIKT - KUNNSKAPSSEKTORENS TJENESTELEVERANDØR](https://data.norge.no/organizations/919477822).

I portalen er navnet blitt oppdatert, samt i registreringsløsningen for begrep og behandlingsoversikt (navn på virksomhet er ikke oppgitt i API-katalogen) og i høsteløsningen. (Har manuelt oppdatert beskrivelsen for datasettkatalogen og høsteløsningen med det nye navnet.) Men i oversikten over alle kataloger og for Datasettkatalogen henger det igjen den gamle navnet på virksomheten.

Antar at det er en bugg i løsningen som gjør at navnet ikke automatisk blir oppdatert.

E-post fra eier av katalogen: [Oppdatere tilknytning til datasett pga omorganisering.pdf](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/files/8252211/Oppdatere.tilknytning.til.datasett.pga.omorganisering.pdf)

**Comment by stigbd** [comment]
> oversikten over alle kataloger og for Datasettkatalogen henger det igjen den gamle navnet på virksomheten.

Kunne du oppgitt dei to lenkene til dei sidende dette er feil, ver så snill?

**Comment by stigbd** [comment]
Takker. Eg forstår det dermed slik:
1. Dette issuet er begrensa til Registreringsløsninga.
2. Issuet fins ikkje i data.norge.no

**Comment by valosnah** [comment]
Collections catalog og datasets oppdatert med korrekt navn i mongoDB.

**Comment by KurtStian** [comment]
Testet OK.

![image](https://user-images.githubusercontent.com/43232700/158571163-30785301-beeb-435b-bc05-d23b23d7e6c0.png)
![image](https://user-images.githubusercontent.com/43232700/158571259-39e961b9-8f55-43a2-945b-466720aba172.png)
