### ISSUE TITLE
Oppdatere virksomhetssertifikat i staging

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#556]
Virksomhetssertifikatet har gått ut. Vi har til nå brukt et som vi fikk av Altinn-gjengen via backchannel.
Det er bedre at vi bestiller vårt eget, slik at vi har litt mer kontroll

- [x] Bestill test-virksomhetssertifikat fra Drift
- [x] Legg inn i GCP

**Comment by shenluna** [comment]
Får nå logget inn i staging med ID-porten, lukker dermed saken
