### ISSUE TITLE
Bytte eierskap på datasett - NSD -> HK-dir

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#559]
Eier av datasettet **API mot NSD sin Database for statistikk om høgre utdanning (DBH)** (https://data.norge.no/datasets/9efe2de1-1093-4662-a8cb-fd7907bae9bc) må endres fra [NSD - Norsk senter for forskningsdata AS](https://data.norge.no/organizations/985321884) til [Direktoratet for høyere utdanning og kompetanse (HK-dir)](https://data.norge.no/organizations/974788985), organisasjonsnummer 974 788 985

NSD er nå en del av Sikt - Kunnskapssektorens tjenesteleverandør og virksomheten er under avvikling hos Foretaksregisteret: https://w2.brreg.no/enhet/sok/detalj.jsp?orgnr=985321884

Bestilling fra "ny" eier av datasettene:
[API mot NSD sin Database for statistikk om høgre utdanning (DBH).pdf](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/files/8340501/API.mot.NSD.sin.Database.for.statistikk.om.hogre.utdanning.DBH.pdf)

**Comment by KurtStian** [comment]
Så plutselig denne. Servicedesken har først forsøkt å svare på henvendelsen. I tilbakemeldingen på svaret ber han om flytting av eierskapet:
[RE_ Din sak er behandlet  - [Altinn SD4957601]_ API mot NSD sin Database for statistikk om høgre utdanning (DBH).pdf](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/files/8341443/RE_.Din.sak.er.behandlet.-.Altinn.SD4957601._.API.mot.NSD.sin.Database.for.statistikk.om.hogre.utdanning.DBH.pdf)

**Comment by valosnah** [comment]
Har overført eierskap til [Direktoratet for høyere utdanning og kompetanse (HK-dir)](https://data.norge.no/organizations/974788985)
https://data.norge.no/datasets/9efe2de1-1093-4662-a8cb-fd7907bae9bc

**Comment by KurtStian** [comment]
Testet OK 😊
