### ISSUE TITLE
feil i hjelpetekst for “Nødvendige garantier ved overføring til tredjeland eller internasjonale organisasjoner”

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#56]
"artikkel 49" i hjelpetekst for “Nødvendige garantier ved overføring til tredjeland eller internasjonale organisasjoner” skal endres til "artikkel 46" slik at teksten blir slik: 

Ved overføring som nevnt i GDPR artikkel 46 nr. 1, 2. ledd , skal dokumentasjon på nødvendige garantier angis.

Nå er det slik:
![image](https://user-images.githubusercontent.com/32771488/98348438-0a0fa200-2019-11eb-9097-a4795c60d3e5.png)

**Comment by lillelars** [comment]
Denne er nå fikset. Lukker saken. @RogerSOlsen
