### ISSUE TITLE
Navnet til eier av katalog i registreringsløsningen blir ikke oppdatert i oversikten over alle kataloger og datasettkatalogen - 974 788 985

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#560]
Virksomheten [Direktoratet for høyere utdanning og kompetanse](https://data.norge.no/organizations/974788985) har tidligere hatt navnet Kompetanse Norge.

Navnet er ikke blitt oppdatert i registreringsløsningen for oversikten over alle kataloger og for datasettkatalogen. Dette er tilsvarende feil som ble meldt i https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/554
![image](https://user-images.githubusercontent.com/43232700/159897657-a18797b4-cff1-48a8-9a44-6d221b136618.png)
![image](https://user-images.githubusercontent.com/43232700/159897846-40f8e54f-16fd-4714-a459-453b244efb55.png)
![image](https://user-images.githubusercontent.com/43232700/159897961-9f01e83f-1029-431e-9213-6b320641fc51.png)

**Comment by valosnah** [comment]
Fikset

**Comment by KurtStian** [comment]
Testet OK.
