### ISSUE TITLE
Navnet til eier av katalog i registreringsløsningen blir ikke oppdatert i oversikten over alle kataloger og datasettkatalogen - 974 760 665

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#561]
Virksomheten [STATSFORVALTAREN I VESTLAND](https://data.norge.no/organizations/974760665) har tidligere hatt navnet FYLKESMANNEN I VESTLAND.

Navnet er ikke blitt oppdatert i registreringsløsningen for oversikten over alle kataloger og for datasettkatalogen. Dette er tilsvarende feil som ble meldt i https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/560

![image](https://user-images.githubusercontent.com/43232700/159912693-c70d599a-4839-45f6-84a8-a762049c94c3.png)

![image](https://user-images.githubusercontent.com/43232700/159912858-1ef26413-87d0-4c2d-ab3a-d181bd67c1dd.png)

![image](https://user-images.githubusercontent.com/43232700/159912936-49b0c4b2-01da-4c4e-9b81-3aaa4c94debc.png)

**Comment by valosnah** [comment]
Fikset

**Comment by KurtStian** [comment]
Testet OK 👍
