### ISSUE TITLE
feil: Henvisning til annet hjemmelsgrunnlag i artikkel 9 blir ikke vist i lesevisning

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#562]
Tekst som legges inn i feltet "Henvisning til annet hjemmelsgrunnlag" i artikkel 9, vises ikke i lesevisning. 
Her er eksempel fra behandlingsaktivitet "Flaskepost" i demo-miljø (https://registrering-protokoll.demo.fellesdatakatalog.digdir.no/555111290/records/c880579c-d414-442c-bc00-1a3a8cc2cb52 ) fra registreringsløsning:

![image](https://user-images.githubusercontent.com/32771488/159962180-49c3d00c-1f5b-49b8-8529-c6e841b66ba0.png)

Her er samme felt fra demo-løsningen (skjermdump er tatt ca en halv time senere. Har logget ut og inn igjen i både skriveløsning og leseløsning i mellomtiden i tilfelle det hadde betydning for resultatet):

![image](https://user-images.githubusercontent.com/32771488/159962641-26c667c4-084c-4b35-a93c-08f4d72a1738.png)

**Comment by oyvindis** [comment]
I tillegg endrer font-weight til vanlig tekst i lesemodus.

**Comment by shenluna** [comment]
Testet ok
![image](https://user-images.githubusercontent.com/73637969/160828993-aac87411-1054-406c-93c3-c7c415facc69.png)
