### ISSUE TITLE
Mangler visning av flere kilder

### ISSUE THREAD

**Issue by yngvep** [Informasjonsforvaltning/fdk-issue-tracker#563]
Har registrert flere kilder på et begrep men det vises kun ett, som regel det sist, i visningen

**Comment by NilsOveTen** [comment]
> Nå vises første kilde som er lagt inn (i stedet for siste), men fortsatt kun en av flere kilder

Endringen er ikke klar i produksjon enda, vi er i gang med å den prossessen atm

**Comment by shenluna** [comment]
Hei @yngvep, nå skal det være på plass.

**Comment by yngvep** [comment]
Supert

**Comment by yngvep** [comment]
Er det noen spesiell grunn til at rekkefølgen på kilder ikke er i overenstemmelse med slik det er lagt inn? Når vi registrerer begrep settes den viktigste kilden først, osv. Bør være slik i visningsmodus også.

**Comment by stigbd** [comment]
Det er ingen måte i registreringsskjermbildet å angi viktighet av kilder. Den underliggande datamodellen har heller ingen støtte for dette. Derfor fins det ingen garantier for at ting kjem ut i rekkefølgend dei er registrert.

Merk at data.norge.no ("visningsmodus") og registreringsløysinga er to ulike tjenester. 

For at det skal vere mulig å sikre rekkefølge, må vi sjå om den underliggande spesifikasjonen kan utvidast med denne type informasjon. Eg skal ta dette vidare med spesifikasjonen.

**Comment by stigbd** [comment]
Spesifikasjonen det er snakk om er denne: https://data.norge.no/specification/skos-ap-no-begrep/

**Comment by stigbd** [comment]
Tar dette vidare i spesifikasjonen på følgande issue
https://github.com/Informasjonsforvaltning/skos-ap-no-begrep/issues/132

Lukker derfor denne.
