### ISSUE TITLE
endring av informasjon i Behandlingsoversikt

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#564]
Gjøre informasjon om hvem som er Behandlingsansvarlig mer tydelig. Nå er denne informasjonen lite synlig i skjermbildet:
![image](https://user-images.githubusercontent.com/32771488/161553609-090fb35e-a270-4037-a46a-debffadf9f1b.png)

Endre overskrifter for "Kontaktinformasjon" og "Personvenombud" (rød tekst = ny tekst)
![image](https://user-images.githubusercontent.com/32771488/161553261-1621a2f6-a81d-48a5-8f92-bc94eb27c3a8.png)

Endre overskrifter:
![image](https://user-images.githubusercontent.com/32771488/161555234-f9884080-8544-493c-96cd-5a8dc2606982.png)

**Comment by joachim-me** [comment]
Flyttet til Behandlingsoversiktrepoet: https://github.com/behandlingsoversikt/issue-tracker/issues/11
