### ISSUE TITLE
mangel i hjelpetekst i felt "Generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak"

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#57]
forkortelsen "GDPR" mangler i hjelpetekst i feltet Generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak. 
Det skal stå:
Som nevnt i GDPR artikkel 32. nr 1, dersom mulig.

Nå står det slik:
![image](https://user-images.githubusercontent.com/32771488/98349347-295aff00-201a-11eb-8dbc-2a5561ebcd91.png)

**Comment by lillelars** [comment]
Denne er nå fikset. Lukker saken @RogerSOlsen
