### ISSUE TITLE
Opprette infrastruktur for behandlingsoversikt

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#570]
- [x] Opprette nye prosjekter i GCP
- [x] Opprette networks i shared-vpc prosjekt
- [x] Opprette dev Kubernetes serviceaccount
- [x] Opprette dev-cluster
- [x] Opprette prod Kubernetes serviceaccount
- [x] Opprette prod-cluster

- [ ] Opprette cloud-armor (dev)
- [ ] Opprette cloud-armor (prod)

- [x] Opprette mongodb-disk (staging) 
- [ ] legge inn databasedump fra fdk-staging
- [x] Opprette mongodb-disk (demo)
- [ ] legge inn databasedump fra fdk-demo
- [x] Opprette mongodb-disk (prod)
- [ ] legge inn databasedump fra fdk-prod

- [ ] Opprette CI/CD for aktuelle repo i /behandlingsoversikt
- [ ] Sette opp IP-adresser i dev
- [ ] Sette opp IP-adresser i prod
- [ ] Bestille DNS og sertifikat

**Comment by KjerstiSteien** [comment]
Lukker denne, da behandlingsoversikt er vedtatt nedlagt.
