### ISSUE TITLE
Gå over til å bruke codecov-action

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#574]
Se eksempelvis fdk-reports-bff

**Comment by KjerstiSteien** [comment]
@valosnah fortsatt relevant?

**Comment by valosnah** [comment]
@KjerstiSteien 
Denne er løst (alle repoer bruker https://github.com/Informasjonsforvaltning/workflows, der alle codecov-relaterte flows bruker codecov-action ifm upload av resultat)
