### ISSUE TITLE
Rettelser begrepsrelasjoner

### ISSUE THREAD

**Issue by oyvindis** [Informasjonsforvaltning/fdk-issue-tracker#576]
Når man velger overordnet/underordnet under generisk relasjon så vises det motsatte i portal

Endre navnet "Type relasjon" til "Nivå" i registrering

Det ser ikke ut som den teller alle relasjoner, tipper erstatter ikke blir telt?

**Comment by shenluna** [comment]
Testet ok, og prodsatt
