### ISSUE TITLE
Lenke til datafabrikken gir feilmelding

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-issue-tracker#581]
Følgende lenke fungerer ikke lenger. Urler til nyhetsartikler har blitt endret og må oppdateres hos Facebook.

[https://l.facebook.com/l.php?u=https%3A%2F%2Fdatafabrikken.norge.no%2Fsiste-nytt%2F82e96caf-c23e-4581-b166-1127a4fff7d3%3Ffbclid%3DIwAR2BMwP4PDz9S3nSWgqhxqhqQAplX9zAQg_YcJ4Vo2-FW3NCW-wkZlJNZkM&h=AT0mdtHl2k-9tydgfVxyzi3mL1EvwZPgUp4q9r4kMS1YWgRtw4NLf-DQA_rzvl0JYqDrM9lm_2NvOPnuqT_f47_k4kCgu-QfPrXjm2iTLmXyvSoeQhWXKevCJJX1PCiMu_ZRgx7P0JdsOWPNRAFBFrGhzQvBBJoDPmrcbbVuB9GHwIiMbRylcvQKUulvhZFfOY6e9fg7k6FY4w-FRmpKCvP5gGV9fDjeNL_9CMumeH2Y5MrG-IWG5AvfuLUc7vqD4cdTxRnvvpna_erU2XkitzpZqg&__tn__=H-R&c[0]=AT0VBFuWaU9syfD6KUV062T_xCoIio9ahSMIGBEU2KIufOasBUUzYAjts6lhLP_l2KkWgZEOYVsXBL2zPPABhnhpZ5LU63RTqQLOcFTnokrag7RI56A2BkGVZmLpLYur8s_yBAWNsmmJdkidxkIPw8HvQF_pkUyptVVtx3slbh69X6-7jNELamNZkDoj2AqnVrpSG0IsbK51UeiDOAbcC6sez-VnxBKelDkllc8XZQMyKFUB0G4tUjoOPTGsRyyOQVftlht3bebQCfjejwQdfYRUJFxf-TiMFlvMarPMwpESxcU31OWU-i-DOhpoRIkC2goz-bFh](https://l.facebook.com/l.php?u=https%3A%2F%2Fdatafabrikken.norge.no%2Fsiste-nytt%2F82e96caf-c23e-4581-b166-1127a4fff7d3%3Ffbclid%3DIwAR2BMwP4PDz9S3nSWgqhxqhqQAplX9zAQg_YcJ4Vo2-FW3NCW-wkZlJNZkM&h=AT0mdtHl2k-9tydgfVxyzi3mL1EvwZPgUp4q9r4kMS1YWgRtw4NLf-DQA_rzvl0JYqDrM9lm_2NvOPnuqT_f47_k4kCgu-QfPrXjm2iTLmXyvSoeQhWXKevCJJX1PCiMu_ZRgx7P0JdsOWPNRAFBFrGhzQvBBJoDPmrcbbVuB9GHwIiMbRylcvQKUulvhZFfOY6e9fg7k6FY4w-FRmpKCvP5gGV9fDjeNL_9CMumeH2Y5MrG-IWG5AvfuLUc7vqD4cdTxRnvvpna_erU2XkitzpZqg&__tn__=H-R&c[0]=AT0VBFuWaU9syfD6KUV062T_xCoIio9ahSMIGBEU2KIufOasBUUzYAjts6lhLP_l2KkWgZEOYVsXBL2zPPABhnhpZ5LU63RTqQLOcFTnokrag7RI56A2BkGVZmLpLYur8s_yBAWNsmmJdkidxkIPw8HvQF_pkUyptVVtx3slbh69X6-7jNELamNZkDoj2AqnVrpSG0IsbK51UeiDOAbcC6sez-VnxBKelDkllc8XZQMyKFUB0G4tUjoOPTGsRyyOQVftlht3bebQCfjejwQdfYRUJFxf-TiMFlvMarPMwpESxcU31OWU-i-DOhpoRIkC2goz-bFh)

**Comment by jeffreiffers** [comment]
Her finner man alle nyhetsartikler: https://datafabrikken.norge.no/siste-nytt

**Comment by palunanue** [comment]
Jeg har pinget Luna om vi kan sette opp en permanent redirect fra gammel URL til ny. Dersom ikke, må vi gi nye URLer på alle gamle pekere til disse sidene.

**Comment by palunanue** [comment]
Digital Norway-folkene oppdaterer lenkene hos Facebook, for å være føre var.
