### ISSUE TITLE
Symbol for dropdown i menyen

### ISSUE THREAD

**Issue by LeneSundsbo** [Informasjonsforvaltning/fdk-issue-tracker#587]
Ønsker caret / pil ned-symbol for menyvalgene som har undermenyer. Altså markere at dette er dropdowns, slik vi har gjort for språk-menyen.

**Comment by pooriamehregan** [comment]
Hei! Bare lurte på: Er det disse to menyene i bilde nedenfor som skal ha dette ikonet? :) 

![image](https://user-images.githubusercontent.com/50879748/210741213-72202e24-ad9b-413c-95e3-af7a01fffdd5.png)

![image](https://user-images.githubusercontent.com/50879748/210741307-a27af084-ece7-4c2d-b5cf-a45a415b5500.png)

**Comment by LeneSundsbo** [comment]
Jepp, de bør ha ikonet som heter _chevron-down-stroke.svg_.

**Comment by pooriamehregan** [comment]
OK. Skal fikse det!

**Comment by terjesyl** [comment]
Er det mulig å få til at den veksler mellom caret-down og caret-up avhengig av om nedfallsmenyen er åpnet eller ikke?

**Comment by pooriamehregan** [comment]
@terjesyl Jepp. Skal ordne det.

**Comment by hegeaal** [comment]
Slik det er nå så kan man ikke klikke på menyvalgene, men de åpner seg når man hovrer. Da gir det kanskje mest mening å bare alltid ha caret-down og ikke at det veksler?

**Comment by pooriamehregan** [comment]
> Slik det er nå så kan man ikke klikke på menyvalgene, men de åpner seg når man hovrer. Da gir det kanskje mest mening å bare alltid ha caret-down og ikke at det veksler?

stemmer for! 👍
