### ISSUE TITLE
endre overskrift: "Formålene med behandlingen"

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#59]
endre overskrift "Formålene med behandlingen" til "Formål med behandlingen":

![image](https://user-images.githubusercontent.com/32771488/98541342-91664b00-228f-11eb-94b0-725259a9b2fc.png)

**Comment by lillelars** [comment]
Denne er nå fikset. Lukker saken @RogerSOlsen
