### ISSUE TITLE
Forbedringer på helm-chart repo

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#590]
- [ ] Sette opp Chart releaser action (https://helm.sh/docs/howto/chart_releaser_action/)
- [ ] Branch names
- [ ] Branch protection rules

**Comment by KjerstiSteien** [comment]
@valosnah fortsatt relevant?

**Comment by valosnah** [comment]
Nei, https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/769 vil medføre at vi går vekk fra å bruke helm-chart repoet.

**Comment by valosnah** [comment]
Lukker denne, da helm-chart repoet vil bli overflødig når vi har gått helt over til kustomize
