### ISSUE TITLE
Tjeneste-detaljside

### ISSUE THREAD

**Issue by oyvindis** [Informasjonsforvaltning/fdk-issue-tracker#592]
Oppdatere iht. nytt design:

Figma: https://www.figma.com/proto/N5yRmXN2WW6sv6J3ILiav7/Portal-%E2%80%93-Detail-(d)?page-id=3212%3A49591&node-id=3876%3A94573&viewport=328%2C48%2C1.54&scaling=min-zoom&starting-point-node-id=3876%3A94573&hide-ui=1

**Comment by shenluna** [comment]
1. Menyen på venstre side følger ikke siden
![image](https://user-images.githubusercontent.com/73637969/175294216-f31c1f90-565a-4009-874d-2c0d6a87b28a.png)

2. Under beskrivelse har "Vis beskrivelsen" og "Skjul beskrivelsen" en litt mørkere bakgrunnsfarge enn resten, er dette meningen?
![image](https://user-images.githubusercontent.com/73637969/175294036-fec7c70b-935f-4e0a-b0cc-8d46df99f5c8.png)

**Comment by oyvindis** [comment]
Endret:

Tekst på detaljside er plassert i hvite bokser.
Overskrifter mindre font.
Ventstremeny er endret design (men designet i skissene er oppdatert en gang til så må endres på nytt)
