### ISSUE TITLE
Opprette informasjonssider til katalogene

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#595]
Se design for meny-struktur:  https://www.figma.com/proto/pnrNm7VYrlPv5cCrurdWLj/Min-FDK?page-id=0%3A1&node-id=602%3A136546&viewport=-5808%2C-1415%2C0.5&scaling=scale-down&starting-point-node-id=602%3A136546&show-proto-sidebar=1

Se design av informasjonssidene: https://www.figma.com/proto/pnrNm7VYrlPv5cCrurdWLj/Min-FDK?page-id=0%3A1&node-id=719%3A117626&viewport=-632%2C-383%2C0.06&scaling=scale-down-width&starting-point-node-id=706%3A101040&show-proto-sidebar=1

**Comment by joachim-me** [comment]
Noen justeringer:

1. For lite luft mellom avsnitt og overskrifter (se skisser)
2. Overskrifter og tekst må venstrejusteres
3. Ikke mulig å velge siste menyvalg i nedtrekksmenyen under "Om felles datakatalog"

Design ligger her: https://www.figma.com/proto/wmZga2U7gUwUK0jdgbTIqA/Portal-%E2%80%93%C2%A0About-(d)?page-id=124%3A1260&node-id=124%3A10195&viewport=-721%2C306%2C0.26&scaling=min-zoom&starting-point-node-id=124%3A10195&show-proto-sidebar=1&hide-ui=1

**Comment by joachim-me** [comment]
Fant et par ting til @pooriamehregan:

1. Bilder vises ikke: https://data.norge.no/om-begrepskatalogen
2. Skrivefeil i nedtrekksmeny - bare en l i Veiledning

**Comment by pooriamehregan** [comment]
@joachim-me 
Jeg fiksa skrivefeilen. 
Var det disse bildene i _om begrepskatalogen_ du tenkte på?  https://www.figma.com/proto/pnrNm7VYrlPv5cCrurdWLj/Min-FDK?page-id=0%3A1&node-id=719%3A117626&viewport=-632%2C-383%2C0.06&scaling=scale-down-width&starting-point-node-id=706%3A101040&show-proto-sidebar=1

**Comment by jeffreiffers** [comment]
Bilder vises ikke siden containeren var satt opp med feil persistent volume (kubernetes). Bildene er dessverre borte så må lastes opp i strapi på nytt. 

Disse bilder må lages på nytt:

### Articles
#### Digdir lanserer et åpent nettforum for alle som er interesserte i data

- clay_banks_no2blv_V_Yo_Jw_unsplash_4d4c28ee67.jpg

### Fancy Articles
#### Om begrepskatalogen

- Begrep_sammenligning_06f1277866.jpg
- Begrep_brukt_datasett_f303bbe480.jpg
- Begrep_brukt_informasjonsmodell_67d1de3158.jpg

**Comment by joachim-me** [comment]
Testet ok.
