### ISSUE TITLE
Tjenestekatalog - frontend

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#60]
- [x] Opprette ny fane

- [ ]

**Comment by shenluna** [comment]
Testet i staging, ny fane med 'tjeneste' er synlig med toggel.
@oyvindis, kan du endre navnet fra 'tjeneste' til 'tjenester' slik at den er lik som de andre. (ble nevnt i behovsmøte)
cc @lillelars

**Comment by shenluna** [comment]
Tested i staging.
