### ISSUE TITLE
Feil dato for "Gyldig" for informasjonsmodellbeskrivelse for "Felles informasjonsmodell for Person og Enhet"

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#604]
I feltet "Gyldig" i informasjonsmodellbeskrivelse for "Felles informasjonsmodell for Person og Enhet" (https://data.norge.no/informationmodels/8bfa055a-9b0c-40df-a7c2-2e58173eb2e0) står det "fra 11.02.2016". 
Det skal i stedet stå "fra 02.11.2016". 

Endring må derfor gjøres i model-catalog.ttl (https://github.com/Informasjonsforvaltning/model-publisher/blob/master/src/model/model-catalog.ttl ) på 
digdir:Tidsintervall  a    dct:PeriodOfTime ;
        dcat:startDate  "2016-**02-11**T00:00:00+01:00"^^xsd:dateTime .
før filen høstes og publiseres på nytt. 

### Årsak
I følge @jimjyang finnes det en versjon 0,9 av wordfil for Person og enhet dataert 08. augsut 2016, samt en Google-docs-fil sist modifisert av Geir Myrind (som ledet gruppen) 21. september 2016. Det er derfor sannsynlig at dato for "Gyldig fra" skal være etter disse datoene. 

Dato for "Utgitt" for informasjonsmodellbeskrivelse for "Felles informasjonsmodell for Person og Enhet" er 02.11.2016. 
Det er derfor sannsynlig at dato for "Gyldig" skal være samme dato som for "Utgitt", altså 02.11.2016.

**Comment by joachim-me** [comment]
Testet ok @RogerSOlsen
