### ISSUE TITLE
Toppmeny - Feil gjør at meny legger seg bak teksten på siden

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#611]
Hva gjorde jeg? 
* Gikk inn på https://data.norge.no/om-datasettkatalogen
* Trykket på Om datakatalogen i toppmenyen. 

Hva forventet jeg? 
* Jeg forventet å se menyen foran teksten på siden. 

Hva skjedde? 
* Menyen la seg bak overskriften på siden. 

Konsekvens: 
Jeg kan ikke lese alle menypunktene når jeg er inne på siden om datasettkatalogen. 
![Feil med visning av meny](https://user-images.githubusercontent.com/110605570/184308864-72bd4e72-db22-4af9-b566-180b38fb9257.png)

**Comment by terjesyl** [comment]
Duplikat av https://github.com/informasjonsforvaltning/fdk-portal/issues/1266

Fikses av https://github.com/Informasjonsforvaltning/fdk-portal/pull/1273
