### ISSUE TITLE
Bug: Informasjonsmodeller - enkelttyper med lange navn ser rare ut

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#618]
Enkelttyper med lange navn (over 18 tegn) vises ikke som forventet. Se vedlagte bilde. 

Dette er feil:
* Teksten som vises over to linjer er vanskelig å lese, ser ut som to ord.
* Multiplisitet (eks. "0..1") vises over to linjer. Skal vises på én linje. 

<img width="375" alt="image" src="https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/110605570/e837374d-91d5-4cfa-ad6e-74d9711a87df">

Eksempelet er hentet fra: https://data.norge.no/informationmodels/8bfa055a-9b0c-40df-a7c2-2e58173eb2e0 

## Ønsker at: 
* Ord som deles over flere linjer henger sammen visuelt, slik at det blir lettere å lese. F. eks. vha bindestrek. 
* Multiplisitet alltid vises på én linje.

**Comment by KjerstiSteien** [comment]
@jeffreiffers er dette noe du jobber med nå, eller skal jeg flytte den tilbake til ready/backlog?

**Comment by terjesyl** [comment]
Er denne løst nå? @KjerstiSteien

**Comment by Lillebo** [comment]
Det er forsåvidt en enkel fiks å legge på et par `white-space: nowrap` regler for å tvinge disse teksene til å holde seg på en enkelt linje.

Men løsningen har også noen tilgjengelighets-utfordringer, f.eks. når skjermen blir enda mindre:

<img width="371" alt="Screenshot 2024-05-06 at 09 24 00" src="https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/74510/a82221c0-faeb-4d88-bddf-f773b327273a">


Er redd dette bryter med [WCAG 1.4.10 Reflow](https://www.w3.org/TR/WCAG22/#reflow):

>Content can be presented without loss of information or functionality, and without requiring scrolling in two dimensions for vertical scrolling content at a width equivalent to 320 CSS pixels.

Disse listene blir heller ikke opplest som lister når man bruker skjermleser for å navigere innholdet.

Jeg lurer på om det kanskje hadde vært best å forsøke å skrive om denne markupen til å være rene HTML-tabeller i stedet. Da kan vi bruke horisontal scrolling når det blir trangt om plassen (som 1.4.10 tillater for tabeller), og unngå at tekstene brytes på rare måter. Men dette forutsetter en litt større omskriving av disse modulene.

**Comment by Lillebo** [comment]
Lager en [PR for quick-fix](https://github.com/Informasjonsforvaltning/fdk-portal/pull/2039) med `whitespace:nowrap` for å lukke denne saken, men oppretter et nytt issue (#941) på en eventuell omskriving til tabeller og fikse WCAG-brudd.
