### ISSUE TITLE
Oppdatere logoen til Folkehelseinstituttet på virksomhetsiden

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#619]
Mottatt henvendelse fra Folkehelseinstituttet om oppdatering av logen deres på virksomhetsiden (SD5410913):

Fra: @fhi.no> 
Sendt: mandag 22. august 2022 11:43
Til: fellesdatakatalog@digdir.no
Emne: Endre logo for Folkehelseinstituttet

[ Ekstern e-post ] 
Hei,

Ber om at logoen på informasjonssiden om Folkehelseinstituttet i Felles datakatalog endres til den nåværende logoen (den som ligger der nå er mange år gammel). På forhånd takk.
https://data.norge.no/organizations/983744516

![image](https://user-images.githubusercontent.com/43232700/185905207-fe79aa80-5fad-4550-941a-2ba22f5f58c8.png)

**Comment by stigbd** [comment]
I dag henter vi logoen frå eit difi-api:
https://orglogo.difi.no/api/logo/org/983744516

Så det beste er om orglogo-løysinga får den korrekte logoen. Eg er usikker på om dette api framleis er supportert. Sjekker.

**Comment by KurtStian** [comment]
Har sendt henvendelse til de som vedlikeholder Orglogo-løsningen og bedt de om å oppdatere logoen.

**Comment by KurtStian** [comment]
Logoen er nå oppdatert i Orglogo-løsningen og den oppdaterte logoen vises i FDK:

![image](https://user-images.githubusercontent.com/43232700/186134239-06a2a537-d429-4f73-97c0-72432daf2bfe.png)
