### ISSUE TITLE
Tjenester - støtte for feature-toggle

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#62]
- [x] Eksludere fra "Alle-fanen" i første omgang (for backend) (sjekk om dette finnes i fulltext-search)
- isolere til fanen "tjenester" som har feature toggle

- [x] Eksludere fra re-sent endepunkt (siste innslag)

- [x] Feature toggle i portal

**Comment by shenluna** [comment]
Testet og verifisert i staging
