### ISSUE TITLE
Skrivefeil i menyfelt under menyen «Om Felles datakatalog»

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#623]
Menyfeltet «Veiledning» under «Om Felles datakatalog» har fått en «l» for mye.

![image](https://user-images.githubusercontent.com/43232700/186167008-a212998e-de12-4587-86df-4af76e870b89.png)

**Comment by pooriamehregan** [comment]
resolved by: https://github.com/Informasjonsforvaltning/fdk-portal/pull/1277

**Comment by KurtStian** [comment]
Feilen er rettet og saken lukkes derfor.
