### ISSUE TITLE
Underenheter som det er gitt skrive-/lesetilgang via Altinn vises ikke i registreringensløsningen

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#633]
I Altinn så arver underenhetene rettighetene som er gitt på en hovedenhet, dvs. at hvis man får skrivetilgang til en hovedenhet så får man også automatisk skrivetilgang til underenhetene. I tillegg kan man få tilgang direkte til underenheter uten å ha tilgang til hovedenhet.

I FDK vises ikke underenheter man har fått tilgang til (direkte eller via arv) via Altinn selv om organisasjonsnumrene er whitelistet, kun hovedenheter vises. Derimot hvis man bruker Felles brukerhåndtering så vises underenhetene i FDK, hvis man har fått tilgang til dem og de er whitelistet.

Altinn har bekreftet at dette virker for andre som bruker løsningen så vi har sannsynligvis en feil i vår løsning.

**Comment by NilsOveTen** [comment]
Vi har to whitelists, organisasjonsform og organisasjonsnummer, hvordan skal logikken rundt de to fungere mtp underenheter?

Regner med at underenheten skal godtas hvis den ligger i organisasjonsnummerlisten, men hvis den ikke ligger der men har en organisasjonsform som godtas, hva skal skje da?

**Comment by KurtStian** [comment]
Det finnes kun org.formene BEDR og AAFY for underenheter. [org.former](https://www.brreg.no/en/business-2/types-of-organisation/?nocache=1663764308170) AAFY brukers på underenheter til ikke-næringsdrivende virksomheter og vil neppe noen gang være aktuell. 

Jeg mener at underenheter kun skal vises når org.nummeret til denne er whitelistet, uavhengig om hovedenheten har en org.form som er godkjent eller ikke. Hvis vi automatisk åpnet for underenheter som hadde en hovedenhet med en godkjent org.form er jeg redd at det hadde blitt mye støy og forvirring da det ikke er alle som har noe forhold til underenheten(e).

**Comment by KurtStian** [comment]
Har teste i staging den 20.09.2022:

- En bruker får skrivetilgang til hovedenheten via Altinn - resultat i FDK: skrivetilgang til hovedenhet og underenhet - OK
- En bruker får lesetilgang til hovedenheten via Altinn - resultat i FDK: lesetilgang til hovedenhet og underenhet - OK
- En bruker kun har fått skrivetilgang til en underenhet via Altinn - resultat i FDK: kun underenhet vises, og man har skrivetilgang - OK
- En bruker har fått lesetilgang til hovedenhet og skrivetilgang til en underenhet via Altinn - resultat i FDK: lesetilgang til hovedenhet og skrivetilgang til underenhet - OK)

- Det er ikke mulig i Altinn å gi skrivetilgang til hovedenheten og kun lesetilgang til en eller flere underenheter (Pga. arving fra hovedenheten vil alle som har skrivetilgang til hovedenheten også få skrivetilgang til underenhetene når de whitelistes hos oss). Kan teoretisk kanskje løses ved å opprette flere lenketjenester (tilganger) som skiller på hovedenhet og underenhet, hvis dette blir et behov.
- Det er ikke mulig å gi en person skrivetilgang til hovedenheten og en underenhet, samt å gi en annen person skrivetilgang til samme hovenhenhet og en annen underenhet (Pga. arvingen fra hovedenheten vil de begge få tilgang til begge underenhetene når de whitelistes hos oss.). Kan teoretisk kanskje løses ved å opprette flere lenketjenester (tilganger) som skiller på hovedenhet og underenhet, hvis dette blir et behov.

Har ikke testet med flere underenheter da jeg har ikke testperson som har tilgang til hovedenhet med flere underenheter.
