### ISSUE TITLE
Side for teknisk feil: Oppdatere design

### ISSUE THREAD

**Issue by LeneSundsbo** [Informasjonsforvaltning/fdk-issue-tracker#636]
Følgende oppdateringer er ønskelig:
- All brødtekst på én og samme linje.
- Fjerne dekorstripene nederst i skjermbildet.
- Erstatte stripene øverst med ny fil (vedlagt)

[Designskisser for mobil](https://eggedosis.github.io/fdk-design/redirects/portal/other/500-m.html)
[Designskisser for desktop](https://eggedosis.github.io/fdk-design/redirects/portal/other/500.html)

![illustration-lines-corner.svg](https://images.zenhubusercontent.com/5d5bd38ecce8ee0649bb1a75/6f5e7482-9ec5-45f2-bc25-66328505b29d)

**Comment by tenstad** [comment]
Issue moved to [Informasjonsforvaltning/fdk-portal #1320](https://github.com/Informasjonsforvaltning/fdk-portal/issues/1320) via [**Zenhub**](https://www.zenhub.com/)
