### ISSUE TITLE
feil: ikke mulig å bruke tab-tasten for å hoppe mellom ja/nei radioknapp

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#64]
Dersom man flytter markøren nedover i registreringsfeltene for behandlingsaktivitet ved hjelp av tab-tasten, hopper markøren over Ja-alternativet dersom:
- det ikke allerede er valgt noen verdi ("ja" eller "nei")
- dersom Nei er valgt fra før.

Dersom Ja er valgt fra før, hopper markøren over Nei-alternativet. 

Markøren bør gå innom alle mulige ja og nei-valg felt slik at man kan aktivere Ja eller nei med space-tast, eller aktivere valget ved klikke på det med muspekeren når feltet er merket.

Feilen oppstår i:
- bolk Kontaktinformasjon", felt "Er behandlingsansvarlig etablert utenfor EU/EØS"
- bolk "Overføring av personopplysningene", felt "Er mottakerne tredjeland eller internasjonale organisasjoner"
- bolk Sikkerhetstiltak og DPIA", felt "Er det gjennomført vurdering av personvernkonsekvensene"

Eksempel: 
markøren står i feltet "Mottakere eller kategori av mottakere.
![image](https://user-images.githubusercontent.com/32771488/98640757-e1462000-232a-11eb-8673-342480a733cd.png)

Dersom jeg trykker på tab-tasten, hopper den til nei-knappen
Dersom jeg trykker tab-tasten på nytt, hopper den over Ja-knappen og går direkte til "Generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak:
![image](https://user-images.githubusercontent.com/32771488/98640351-5e24ca00-232a-11eb-8c36-eebc25ef43bb.png)

Det samme skjer dersom jeg manøvrer nedover med tab-tasten, og passerer et Nei/Ja-valg hvor Nei er valgt tidligere:
![image](https://user-images.githubusercontent.com/32771488/98640986-5285d300-232b-11eb-89ac-6d3ff387f246.png)

Dersom Ja var valgt tidligere, hopper markøren over Nei-knappen når man manøvrer nedover med tab-tasten:
![image](https://user-images.githubusercontent.com/32771488/98641125-9082f700-232b-11eb-867e-e64173e9345b.png)

**Comment by shenluna** [comment]
I følge w3c skal man kun hoppe til radioknapp gruppen ved tab, ikke navigere innad i gruppen, da må man ta i bruk piltaster. Lukker dermed saken.
