### ISSUE TITLE
Knytte begreper i FDK til datasett i FDK

### ISSUE THREAD

**Issue by S138659** [Informasjonsforvaltning/fdk-issue-tracker#643]
Hei! NAV publiserer både datasett og begreper til Felles datakatalog. Vi tror det er en god idé å bruke FDK til å knytte begreper til datasett. Kunne FDK tilby en løsning for dette? I så fall tror vi at også andre etater vil benytte den muligheten.

**Comment by KurtStian** [comment]
Endring/oppgaver:
Endre til å kjøre søk på uri i stedet for identifier for dct:subject
Endre rdf-produksjon i dataset-catalog til kun å legge til uri

Kan krevet en liten etl i databasen til registreringsløsning etter at oppdateringen av portalen er gjort.
