### ISSUE TITLE
Feature: Legge til script for SiteImprove på data.norge.no, Datalandsbyen og Datafabrikken

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#657]
### Feature beskrivelse

Legg til script for SiteImprove på data.norge.no, Datalandsbyen og datafabrikken. 
OBS! Script for Google analytics skal beholdes inntil videre, for å kunne se på forholdet mellom tallene i de to løsningene. 

### Hvorfor trenger vi det?

Dette er et første steg for å bli kvitt Google Analytics for godt. Det gjør det lettere for oss å forsvare analysene vi gjør og vil forhåpentligvis få domstolene til å publisere i katalogene våre. SiteImprove vil i tillegg gjøre det lettere for oss å fylle ut tilgjengelighetserklæringen.

### Definisjon av ferdig

Script er lagt til i alle tre løsningene.
Det er verifisert at data hentes inn til SiteImprove. 
Det er verifisert at data fortsatt hentes inn til Google Analytics.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
@terjesyl aner ikke. @jeffreiffers vet du?

**Comment by jeffreiffers** [comment]
Denne er utført ja. Er gjort i februar.

**Comment by pooriamehregan** [comment]
Stemmer fra chatten at denne er fullført? Skal denne lukkes og fjernes fra Blocked?
