### ISSUE TITLE
Statistikk FDK - ustabile tall begreper

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/fdk-issue-tracker#658]
Det skjer fortløpende endringer i tallene som inngår i grafene for rapportsiden til FDK - https://data.norge.no/reports
og disse endringene har tilbakevirkende kraft.

Dvs at selv om det er normale endringer fra dag til dag blir det som var riktige tall på et tidligere tidspunkt ikke lagret - altså slik at historiske tall som er brukt i tidligere rapporteringer ikke kan gjenfinnes i grafene som vises

Se også issue #555

**Comment by NilsOveTen** [comment]
Dette krever en del fra resten av stacken, liste av relevante issues:
- https://github.com/Informasjonsforvaltning/fdk-concept-harvester/issues/121
- https://github.com/Informasjonsforvaltning/fdk-dataset-event-publisher/issues/15
- https://github.com/Informasjonsforvaltning/fdk-rdf-postman/issues/18
- https://github.com/Informasjonsforvaltning/rdf-diff-store/issues/27
- https://github.com/Informasjonsforvaltning/rdf-diff-store/issues/28
- https://github.com/Informasjonsforvaltning/fdk-reports-bff/issues/115

**Comment by KjerstiSteien** [comment]
@NilsOveTen kan denne lukkes? Ser ut som alle oppgavene er utført.

**Comment by NilsOveTen** [comment]
Ja, denne er kun for begrep. Det er utført, lukker
