### ISSUE TITLE
BUG: filtre fungerer ikke på tvers av kataloger.

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#659]
## 🐛 Bug rapport

Filtre ser ikke ut til å påvirke katalogene på data.norge.no på tvers.

### Nåværende oppførsel

* Når jeg bruker filter inne i en katalog, oppdateres kun antallet for denne katalogen. 

![image](https://user-images.githubusercontent.com/110605570/210387207-1c24ebd7-9557-4ba2-9edc-ed4242c5fb87.png)

### Forventet oppførsel

* Når jeg bruker filter inne i en katalog, forventer jeg at antallet oppdateres for alle katalogene. 
* Når jeg bytter katalog forventer jeg at filtervalgene jeg har gjort blir med videre. 
Forventer at filtre har lignende oppførsel som fritekstsøk: 

![image](https://user-images.githubusercontent.com/110605570/210387368-50901ed4-f8b3-4698-9e98-7444fc7a656f.png)

### Hvordan reprodusere?

* Gå inn på data.norge.no
* Velg "Vis kun datasett"
* Filtrer på tema "Natur, klima og miljø"

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by hegeaal** [comment]
Not a bug, but how the filter is set up.
