### ISSUE TITLE
feil: mangler demo-merke flere steder i demo-miljø

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#66]
når man kommer inn i demo-miljøet, mangler demo-merket som angir at man nå er i demo og ikke i produksjon. Merket mangler når man kommer inn etter innlogging, og i datasettkatalogen og i begrepskatalogen: 

![image](https://user-images.githubusercontent.com/32771488/98808130-f8b10600-241b-11eb-94a0-736229efe171.png)

![image](https://user-images.githubusercontent.com/32771488/98808400-56455280-241c-11eb-8688-8c8ae5ecc99b.png)

![image](https://user-images.githubusercontent.com/32771488/98808512-85f45a80-241c-11eb-8e51-fc1297126cc0.png)

![image](https://user-images.githubusercontent.com/32771488/98808326-3746c080-241c-11eb-8e5b-f0a4b0b47c0d.png)

![image](https://user-images.githubusercontent.com/32771488/98808563-a02e3880-241c-11eb-9dc2-6731cfb75f7b.png)

**Comment by joachim-me** [comment]
testet ok
