### ISSUE TITLE
Epic: Tilgjengelighet

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-issue-tracker#661]
- [x] #662
 - [x] #663
 - [x] #666
 - [x] #668
 - [x] #670
 - [x] #671
 - [x] #673
 - [x] #674
 - [x] #675
 - [x] #677
 - [x] #678
 - [x] #680
 - [x] #682

**Comment by KjerstiSteien** [comment]
Flyttet ut de sakene som ikke var løst. Lukker saken som løst.
