### ISSUE TITLE
Text is clipped when resized

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-issue-tracker#664]
[Text is clipped when resized - Issues - Accessibility NextGen - Accessibility.pdf](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/files/10402005/Text.is.clipped.when.resized.-.Issues.-.Accessibility.NextGen.-.Accessibility.pdf)

Dette kravet skal dekke både zoom opp til 200%, samt at man har stor tekst i browser.
Zoom er ok, men ikke stor tekst. Se kommentar (testet i prod)

**Comment by AinaEngen** [comment]
Zoom opp til 200% fungerer bra.

Men, ved endring av tekststørrelse i browser, ser det ikke bra ut (eks. Edge : Innstillinger => utseende => skrifter (sette den til ekstra stor)
Se eksempler - zoom er her 100% (blir enda verre hvis høyere zoom)
Testet med normal laptop skjermstørrelse + litt større ekstern skjerm

1) Fanene forsvinner ut av skjermen - ikke mulig å se fanen Alle eller hele fanen Tjeneste og Hendelseskatalog
(ikke mulig å pile eller skrolle for å finne fanene heller)

![Image](https://user-images.githubusercontent.com/49443711/212862256-0f623a08-85d1-4e4b-8db1-376d6e6ec636.png)

2) Teksten er for stor for boksen

![Image](https://user-images.githubusercontent.com/49443711/212863543-9f397267-8de1-4fb0-86f2-2099b67c0a99.png)

3) Bokstaver kuttes litt på toppen (ringen over "å" og toppen av "f" bl.a.)

![Image](https://user-images.githubusercontent.com/49443711/212863740-444b6a86-9a9e-437d-b647-58b4c5b3648e.png)

4) Toppmenyen ser ikke helt pen ut

![Image](https://user-images.githubusercontent.com/49443711/212863880-ccaca421-10ef-4f4e-87a4-d9c56600cd9b.png)

**Comment by AinaEngen** [comment]
@pooriamehregan @jeffreiffers - har oppdatert denne bug'en. Jeff testet at zoom 200% var ok, så da trengte vi ikke gjøre noe med denne akkurat nå. Men, som jeg skrev i kommentaren over, så ser det ikke bra ut når man forstørrer teksten i browser. Iflg. kravet til wcag skal det være mulig

**Comment by pooriamehregan** [comment]
Ja, enig i at det ikke ser bra ut.  😬

**Comment by AinaEngen** [comment]
Testet i staging, og punkt 3 ser ut til å være løst. bokstavene kuttes ikke der, så det er mulig det er en annen fiks som har løst dette

**Comment by pooriamehregan** [comment]
Tror line-height fiksen (AAA) løste dette.

**Comment by KjerstiSteien** [comment]
@AinaEngen @pooriamehregan hva er status på denne saken?

**Comment by pooriamehregan** [comment]
@AinaEngen Dette er løst. Lukker saken
