### ISSUE TITLE
Empty headings

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-issue-tracker#667]
[Empty headings - Issues - Accessibility NextGen - Accessibility.pdf](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/files/10402080/Empty.headings.-.Issues.-.Accessibility.NextGen.-.Accessibility.pdf

Saken gjelder tomme headere som vi mistenker at kommer via Strapi. Eks: [https://data.norge.no/guidance](https://data.norge.no/guidance)

**Comment by pooriamehregan** [comment]
Fant ikke h2 taggen den peker mot i:  https://data.norge.no/about-registration .
Mistenker at den kommer fra ekstern kilde (Strapi?).

**Comment by pooriamehregan** [comment]
Denne er fikset av @hegeaal : https://data.norge.no/public-services/a0db7475-6f3a-3cc5-ab9d-287433589a00

**Comment by pooriamehregan** [comment]
Ble fikset: https://data.norge.no/datasets/b0921286-e778-43c2-83ed-b0b1cdf35294

**Comment by KjerstiSteien** [comment]
@pooriamehregan hva er status i denne saken?

**Comment by pooriamehregan** [comment]
tror jeg assignet denne til meg selv og fikset feilene som vi hadde i portal (tomme html headere). Men det er en del tomme hendere på sidene som jeg limet inn ovenfor. Jeg finner dem ikke lokalt i repoet, mistenker at disse html taggene kommer inn med strapi. Derfor laget issuet for det. 

Hvis du f.eks. går på denne siden https://data.norge.no/guidance så kan du fange opp den tomme hederen som ble fanget opp av SiteImprove.

![Screenshot from 2023-02-02 21-16-43](https://user-images.githubusercontent.com/50879748/216440551-95827e51-57ec-4d37-b661-bb4f03d8c5b6.png)

**Comment by KjerstiSteien** [comment]
Jeg finner ikke denne siden i Strapi. Er vi sikre på at den ikke er hardkodet? Kan dere hjelpe meg med å finne den i Strapi hvis den ligger der?

**Comment by pooriamehregan** [comment]
Kan være at den kommer fra Drupal. For vi har fortsatt sider som får innhold av Drupal. 

Tror ikke de er hardkoda, men for kvalitetsikringsskyld er det fint hvis noen andre tar også en liten sjekk. Ellers kan vi se på det sammen når jeg er tilbake. :)

**Comment by KjerstiSteien** [comment]
Sjekkes når sider er flyttet til Strapi

**Comment by KjerstiSteien** [comment]
Løst ved overgang fra drupal til strapi.
