### ISSUE TITLE
Bytte eierskap på datasett

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#67]
Eier av datasettene **Utdanningsbeskrivelser fra utdanning.no** (https://data.norge.no/datasets/eff568d2-8409-48f6-824c-cd93f42fa3ac) og **Yrkesbeskrivelser fra utdanning.no** (https://data.norge.no/datasets/7a1a0217-1f46-4e26-b207-75bd2e54f647) må endres fra Utdanningsdirektoratet til Kompetanse Norge, organisasjonsnummer 974 788 985.

Bestilling fra ny eier av datasettene:
[Datasett fra utdanning.no.pdf](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/files/5524208/Datasett.fra.utdanning.no.pdf)

**Comment by valosnah** [comment]
Datasettene flyttet over til ny eier. Merk at ny eier burde oppdatere kontaktinfo

**Comment by valosnah** [comment]
Eier oppdatert av Kurt Stian, lukker denne.
