### ISSUE TITLE
Får feil (gammelt) søkeresultat ved søk på datasettbeskrivelse

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#683]
Ved søk på datasettbeskrivelse vises gammel versjon av datasettbeskrivelsen. 
Eksempel: Brønnøysundregistrene varslet 16.01.2023 om at de hadde oppdatert datasettbeskrivelsen "Enhetsregisteret" (https://data.norge.no/datasets/68d08f28-a16d-4fab-a953-ed4ab08ce2e2). De fortalte at de hadde lagt til 11 nye begrepsbeskrivelser og en ny distribusjon til datasettbeskrivelsen. Datasettbeskrivelsen skulle derfor vise 12 tilknyttede begrepsbeskrivelser og 7 distribusjoner etter at oppdateringen ble publisert. 
Ved søk i Chrome og Edge, etter at jeg mottok meldingen fra Brønnøysundregistrene, viste søkeresultatet kun ett begrep og 6 distribusjoner. Jeg gjentok søket flere ganger i Chrome og Edge, blant annet i morges (17.01.2023) og fikk fortsatt samme resultat. 
Ved søk på samme datasettbeskrivelse via Firefox fikk jeg riktig resultat, det vil si at jeg fikk vist navn på  12 tilknyttede begrepsbeskrivelser og 7 distribusjoner

**Comment by KurtStian** [comment]
@RogerSOlsen Kan du teste denne? Ser ut som alt er OK nå. Det er registrert 6 distribusjoner + 2 API-er som relaterer til datasettet.

**Comment by KjerstiSteien** [comment]
Regner denne som løst.
