### ISSUE TITLE
Potensielt nginx-issue ved utskifting av høster

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#7]
Se slakcmld fra #prodfeil

- [x] Gjennomføre en tegne WS på gw9 - @valosnah 

- [x] Hans Olav følger opp

- [x] Lag modeller for AS-IS, TO-BE

Løsning for foreløpig og målbildeoppgradering av fdk-nginx-search bestemt
(Ny pod skal ta over på sikt, fdk-nginx-portal)

P.g.a. en feil i FDK ligger vår åpne data-løsning for Kommunalt rapporteringsregister nede. Kan du melde denne feilen internt i FDK slik at den kan rettes snarest mulig?
Denne requesten feiler:
GET https://data.norge.no/api/datasets/11b748f7-3a67-326f-8038-b76504341d50
Accept:application/json
Dette er feilmeldingen vi får:
{
    "timestamp": "2020-09-22T07:42:25.630+00:00",
    "status": 406,
    "error": "Not Acceptable",
    "message": "",
    "path": "/datasets/11b748f7-3a67-326f-8038-b76504341d50"
}
Eg anar ikkje kvar den lenka kjem frå og kvifor dei forsøker å sende denne spørringa. Er det eit nginx-issue?

**Comment by valosnah** [comment]
api/datasets peker igjen på fdk-dataset-api, men denne tjenesten blir ikke oppdatert med ny data. 
Fdk-dataset-harvester kan betjene disse kallene, men med text/turtle, ikke application/json. Det var omruting i fdk-nginx-search, der fdk-dataset-api ble byttet til fdk-dataset-harveser som var utslagsgivende for prodfeilen.

/datasets, /datasets/ og /datasets/{id} skal peke til ny tjeneste: fdk-harvester-bff

**Comment by lillelars** [comment]
Ferdigstilt - lukker denne saken i samsvar med Hans Olav.
