### ISSUE TITLE
Rapportsiden viser 0 API

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/fdk-issue-tracker#70]
På rapportsiden for API, https://data.norge.no/reports, vises bare 0.
![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/b6382403-c694-44af-a806-8d30716b387e)

Klikk på en 0, og du blir tatt til rett filter.

Feilen er bare i prod. Funker i staging og demo!

**Comment by lillelars** [comment]
Denne er nå fikset. Testet i chrome, i staging og prod. Lukker saken.
