### ISSUE TITLE
BUG: Oppdatere PROD OG DEMOMILJØ og fjerne 'obligatorisk' på relasjoner

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/fdk-issue-tracker#701]
### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by KurtStian** [comment]
@marittor Har nettopp testet på demo og det er kun term og definisjon som er obligatorisk: https://demo.fellesdatakatalog.digdir.no/concepts/c4a2933a-9631-3a3b-bef7-5fae32b17f0c
Kanskje det har vært en midlertidig feil. Kan du teste på nytt?

**Comment by marittor** [comment]
Testet nå og nå var det ikke obligatorisk, men da jeg trykket inn på legg til relasjon ble det obligatiorisk-trekant selv om jeg ikke hadde valgt noe mer. Men det er vel slik siden man nå legge til et begrep i relasjonsenden/ og at standarden sier noe om obligatoriske inndelingskriterer e.l. Men da er det ok.
