### ISSUE TITLE
BUG: Det lenkes nå til RDF-ressurser i registreringsløsningen istedenfor publiserte RDF-ressurser

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/fdk-issue-tracker#702]
### Nåværende oppførsel

Med datasettet Enhetsregisteret som eksempel (https://data.norge.no/datasets/68d08f28-a16d-4fab-a953-ed4ab08ce2e2). F.eks. linjenr. 214 i Turtle-filen peker til en API-beskrivelse med URL https://dataservice-catalog.fellesdatakatalog.digdir.no/data-services/63fdde652b4c3e56b419af60 og man møter påloggingssiden til registreringsløsning med den URLen.   

NB! Dette er kun et eksempel, det kan med andre ord hende at det er flere slike URLer som er bak påloggingen til registreringsløsningen. 

### Forventet oppførsel

Det skal peke til selve API-beskrivelsen som er publisert, maskinlesbart og uten pålogging, altså URLen https://data.norge.no/dataservices/1c55423c-8fd2-3610-8176-c8671d0c8cb6 

### Hvordan reprodusere?

Bruk https://dataservice-catalog.fellesdatakatalog.digdir.no/data-services/63fdde652b4c3e56b419af60 i en nettleser, eller curl på den URLen.

### Forslag/Løsning [Valgfritt]

Det skal peke til den publiserte ressursen, dvs. URLen https://data.norge.no/dataservices/1c55423c-8fd2-3610-8176-c8671d0c8cb6

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by jimjyang** [comment]
I GUIen i FDK er det lenket til den publiserte versjonen av API-beskrivelsen (i feltet "Datatjeneste") og det er riktig, men ikke i Turtle-filen bak GUIen. Hvis GUIen ikke er en representasjon av RDF-ressursen bak, er også en feil.

**Comment by jimjyang** [comment]
Etter en prat med @KurtStian, må jeg presisere og korrigere ... 

**Presisering**: Dette gjelder URIer som vi (ev. på vegne av andre) genererer og eier, i dette tilfelle URIer som registreringsløsningen vår genererer. [Ansvaret for å dereference URIer som andre genererer og eier, ligger hos andre]

**Problemstilling**: "If a URI identifies an information resource, the URI owner SHOULD provide representations of that resource." ([Ref. W3C Dereferencing HTTP URIs](https://www.w3.org/2001/tag/doc/httpRange-14/2007-05-31/HttpRange-14)). Ettersom det vi snakker om her er åpne data/metadata, bør ikke "representasjonen" ligge bak en påloggingsside. 

**Løsningsforslag**: Vi dereference enhver URI som vår registreringsløsning genererer, til den tilsvarende ressursen som er åpent tilgjengelig i FDK, slik at enhver ressurs som er registrert ved bruk av vår registreringsløsning er tilgjengelig for både mennesket og maskinen uten pålogging. 

**Eksempel**: Med den ovennevnte API-beskrivelsen som eksempel:
* URIen https://dataservice-catalog.fellesdatakatalog.digdir.no/data-services/63fdde652b4c3e56b419af60 dereference's til
* URLen/representasjonen(e) https://data.norge.no/dataservices/1c55423c-8fd2-3610-8176-c8671d0c8cb6.

**Comment by NilsOveTen** [comment]
Det er registreringsløsningen som er den publiserte katalogen, hvis det er noe som er feil med endepunktet der bør vi fikse det der.

Det er ikke nødvendig å logge seg på for å hente rdf fra registreringskatalogene, men det er json som er default og den krever pålogging. Er mulig å endre oppsettet der om det er forvirrende

**Comment by jimjyang** [comment]
Lukker dette, siden kjernen av problemstillingen nå er dekket av et nytt issue, #724.
