### ISSUE TITLE
Brukerfeil: utilsiktede instanser i modellkatalogen

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/fdk-issue-tracker#712]
### Nåværende oppførsel

Mange av modellene er tilsynelatende duplisert. Dette skjedde fordi jeg rettet opp en "skrivefeil" i URIen til disse modellene, og de ble derfor (helt korrekt) oppfattet som nye instanser og dermed duplisert. F.eks. for DCAT-AP-NO er det to instanser: 
* https://data.norge.no/informationmodels/87242133-a014-3d5b-a8db-881ec1490d01
* https://data.norge.no/informationmodels/e9c0c652-4d50-30ee-95cb-36376616eeec

### Forventet oppførsel

Bare en instans skal vises i mdoellkatalogen. Alle med `spesifications` i URIen skal slettes fra basen (URIen skal isteden inneholde `specifications`). Følgende skal altså slettes: 
* Informasjonsmodell for ModellDCAT-AP-NO, https://data.norge.no/informationmodels/cb8da202-1c19-3131-ba5f-80a8f7a4e2c9
* Informasjonsmodell for begrepsbeskrivelser, https://data.norge.no/informationmodels/624e167f-c87c-33ad-b462-03b0f8b73253
* Informasjonsmodell for XKOS-AP-NO, https://data.norge.no/informationmodels/22230f97-8dba-3fc6-9227-d67115c5e1b0
* Informasjonsmodell for DCAT-AP-NO, https://data.norge.no/informationmodels/e9c0c652-4d50-30ee-95cb-36376616eeec
* Informasjonsmodell for CPSV-AP-NO, https://data.norge.no/informationmodels/229cf035-a9af-3e24-9ee9-9d6ce6ee492a
* Informasjonsmodell for DQV-AP-NO, https://data.norge.no/informationmodels/a9367612-aeed-3bd9-be90-63bfe0b61bf3

### Hvordan reprodusere?

Ved f.eks. å søke på "DCAT-AP-NO" i mdoellkatalogen.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Klarer ikke å gjenskape. Vurderer denne som løst.
