### ISSUE TITLE
BUG: Kan ikke velge xml som format i distribusjon i registreringsløsningen

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/fdk-issue-tracker#716]
### Nåværende oppførsel
Prøver å velje «xml» som format, men lista er ikkje lang nok til å vise det. Antar eg.

![image](https://user-images.githubusercontent.com/3617256/227203698-22225f26-3d7a-4e38-9b6f-19eee5c9404f.png)

### Forventet oppførsel
At det er mogeleg å velje «xml» som format.

### Hvordan reprodusere?
Gå inn i registreringsskjema, under Distribusjon og prøvd å skrive inn «xml» i feltet Format.

### Forslag/Løsning [Valgfritt]
Endre GUI så drop-down-lista kan vise heile lista.

Super-løysing: dei mest vanlege formata kjem øverst i drop-down-lista.
Kan generere liste over vanlege format ut frå kva som er i datasett-katalogen.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Løst gjennom andre saker som gjaldt støtte av riktig vokabular for dct:format på datatjenester.
