### ISSUE TITLE
BUG: Registrering av dct:conformsTo ikke i henhold til DCAT-AP-NO

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/fdk-issue-tracker#722]
## 🐛 Bug rapport

Når man i registreringsløsningen registrerer en standard som f.eks. et datasett er i samsvar med (`dct:conformsTo`), blir det opprettet en blank kode med en del egenskaper. En av egenskapene i den blanke noden er `dct:source`, som ikke er i henhold til DCAT-AP-NO. 

Dette gjelder i hvert fall også registrering av standard som en distribusjon eller et API er i samsvar med. 

### Nåværende oppførsel

Den blanke noden som opprettes inneholder nå egenskap `dct:source`:
1.  [DCAT-AP-NO](https://data.norge.no/specification/dcat-ap-no#Standard-harReferanse) sier at det er `rdfs:seeAlso` som skal brukes (og ikke `dct:source`). 
2. I henhold til DCAT-AP-NO skal egenskapen referere til en instans av `rdfs:Resource`, altså verdien skal være en URI mens den nå er en Litereal. 

### Forventet oppførsel

Som sagt skal egenskapsURIen være `rdfs:seeAlso` og verdien skal være en URI, eller `literal typed as xsd:anyURI`. 

### Hvordan reprodusere?

Se f.eks. den blanke noden https://registrering.fellesdatakatalog.digdir.no/catalogs/986128433/datasets/7eada976-4188-4bc9-9323-77e0eae3d10e/.well-known/skolem/4e773112-b6f8-3305-b75c-bcdf8f499b0f i datasettet https://data.norge.no/datasets/5f41f578-2841-3c74-92dc-6a3db859ec16 

### Forslag/Løsning [Valgfritt]

Det bør være: 
`````
<>
   rdfs:seeAlso ""^^xsd:anyURI ; . 
`````

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
Må først støtte rdfs:seeAlso i høsteprosessen, så blokkeres av denne: https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/318
