### ISSUE TITLE
BUG: Relasjonene «partitiv» og «generisk» mellom begrep vises ikke i portalen

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#729]
### Nåværende oppførsel
Relasjonene «Partitiv - Omfatter» og «Partitiv - er en del av» samt «Generisk - Overordnet» vises ikke i portalen. «Generisk - Underordnet», «Assosiativ» og «Se også» vises i portalen. Men overskriften "Relaterte begreper» viser rett antall relasjoner.

Eks. fra demo:
![image](https://user-images.githubusercontent.com/43232700/234894599-d0a3c38a-a7c0-4f55-9bb8-8e84079ec2e0.png)
![image](https://user-images.githubusercontent.com/43232700/234894891-db218ea5-34ee-4503-adc5-51532936ce68.png)

Eks. fra prod:
![image](https://user-images.githubusercontent.com/43232700/234852166-70dc6d1f-24fd-4b73-ba3d-69607c46e8ad.png)
![image](https://user-images.githubusercontent.com/43232700/234852328-8cd2705d-2268-4319-8ca3-cf07941a871a.png)

### Forventet oppførsel

Relasjonene partitiv og generisk skal også vises.

### Hvordan reprodusere?

Demomiljø: https://demo.fellesdatakatalog.digdir.no/concepts/75343653-b38a-37f2-849b-016d9f71fbf8
Prodmiljø: https://data.norge.no/concepts/39b5379a-c289-3dce-bf89-ec2ebea222b8

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by terjesyl** [comment]
Merk at eksempelet i produksjon (Forsyningssikkerhet) kun har partitiv relasjon satt i Turtle-responsen. Viser seg også i JSON-responsen (se bildet). Er den registrert med generisk(e) og assosiativ(e) relasjon(er) også, @KurtStian ?
![bilde](https://user-images.githubusercontent.com/108797958/234859791-e67452d2-9212-42e3-bbb9-4f21dbea8fe7.png)

**Comment by terjesyl** [comment]
Demo-eksempelet har verdier på alle tre JSON-feltene. Ligger feilen i frontend? Eller gjør vi oppslag mot fulltext-search som kan feile/gir manglende respons?
![bilde](https://user-images.githubusercontent.com/108797958/234860529-bfa06e53-97ae-429a-a295-371fde4b80d2.png)

**Comment by KurtStian** [comment]
**Feil i reg. løsning** (@Te-Bert registrerer eget issue):
Det er ikke mulig å finne egne begreper når det valgt «Partitiv - er en del av« eller «Generisk - Underordnet».

**Portal:**
* Det vises ikke relasjonen «Generisk - Overordnet»
* Det vises ikke relasjonene «Partitiv - Omfatter» og «Partitiv - er en del av».

**Følgende er testet:**

* Partitiv - er en del av - relasjon til eget begrep (workaround i reg.løsning: først velge «omfatter» og så «er en del av» for å kunne velge begrepet)
* «Partitiv - er en del av» - relasjon til andres begrep
* «Partitiv - omfatter» - relasjon til eget begrep 

* «Generisk - Underordnet» - relasjon til eget begrep (workaround i reg.løsning: først velge "Overordnet" og så "Underordnet" for å kunne velge begrepet)
* «Generisk - Underordnet» - relasjon til andres begrep
* «Generisk - Overordnet» - relasjon til eget begrep

**Comment by KurtStian** [comment]
![image](https://user-images.githubusercontent.com/43232700/234898575-8771cab0-9b5b-46fb-9ab1-87be24347b9d.png)
@terjesyl Begrepet "forsyningssikkerhet" er registrert med relasjonen «Partitiv - omfatter» mot 3 andre begreper som virksomheten har publisert. De har ikke registrert andre relasjoner på dette begrepet.

**Comment by Te-Bert** [comment]
Jeg har testet at det nå er mulig å legge til partitiv relasjon, både "del av" og "omfatter", og at dette vises i portalen. Det samme gjelder generisk overordnet (selv om denne fortsatt er begrenset til egne begreper)

Ledeteksten "Inndelingskriterium" mangler i portalen (som forklaring til hva som er beskrevet)
