### ISSUE TITLE
Feature: migrering av data til virksomhetsintern begrepskatalog

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#731]
### Feature beskrivelse
Tilrettelegge for migrering av dataene til virksomhetsintern begrepskatalog til demo.
Se testfiler fra Skatt og Brreg. 

### Hvorfor trenger vi det?
For å kunne teste reelt i demo ønsker vi å hente inn begrepene som finnes i Skatt og Brreg sine begrepskataloger i dag. 

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by AinaEngen** [comment]
@KjerstiSteien - har du mer informasjon her? Kan du ta et møte med Nils Ove og Hans Olav?

**Comment by KjerstiSteien** [comment]
@valosnah @NilsOveTen vurder om denne trenger å refines mer - hvis ikke: fjern label refinement og legg til planning.

**Comment by KjerstiSteien** [comment]
@NilsOveTen @valosnah kan jeg lukke denne, siden dere har sak for både br og skatt?

**Comment by valosnah** [comment]
Migrering utført for både Brreg og Skatt
