### ISSUE TITLE
BUG: Svart stripe over bunnmeny på innloggingsside registreringsløsning

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#735]
### Nåværende oppførsel
Det ligger en svart stripe over bunnmenyen på innloggingssiden i registreringsløsningen. Dette gjør at teksten om tilgang blir vanskelig å lese.

### Forventet oppførsel
Det skal ikke være en svart stripe over bunnmenyen.

### Hvordan reprodusere?
* Gå til https://sso.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/auth?client_id=fdk-registration-public&redirect_uri=https%3A%2F%2Fregistrering.fellesdatakatalog.digdir.no%2F&state=c5dc9f56-edb9-4762-863a-3d40b6ec4dfd&response_mode=fragment&response_type=code&scope=openid&nonce=d85cb7f4-9d91-4387-83ab-3749e582fa7c
* Scroll ned til teksten "Trenger du eller andre tilgang?" 
* Du ser nå en sort stripe som dekker halve teksten om tilgang. 

<img width="830" alt="image" src="https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/110605570/b1a700db-bd80-482e-b90a-06f5ef6c96a9">

### Forslag/Løsning [Valgfritt]
* Fjern den sorte linjen. 

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by jeffreiffers** [comment]
Jeg får ikke opp denne teksten. Er du sikker det ikke er noe på din pc (plugin/extension)?

**Comment by NilsOveTen** [comment]
Den mørke stripa standardbakgrunnen til keycloak som titter frem, bunnmeny og den hvite bakgrunnen dekker tydeligvis ikke 100% av bakgrunnen i alle tilfeller

**Comment by AinaEngen** [comment]
@jeffreiffers  @KjerstiSteien 
Jeg får den svarte stripa over teksten "Trenger du eller andre tilgang", slik som Kjersti. Ser at det ser litt forskjellig ut i Edge og Chrome. Den svarte stripa forsvinner hvis jeg reduserer skjermstørrelsen (Edge - 90%, Chrome - 67%).
Ser slik ut i Edge: 
<img width="821" alt="image" src="https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/49443711/a75247d4-12c6-4c14-8412-5101653e436f">

Chrome:
<img width="805" alt="image" src="https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/49443711/561f3ff9-d451-4c4a-9532-b50ab5545085">

**Comment by terjesyl** [comment]
Som Nils Ove sier, det er bakgrunnsimaget som ikke scaler skikkelig, fyller ikke hele bakgrunnen når man zoomer inn, da vises den svarte keycloak-defaultbakgrunnen. Er på saken.
