### ISSUE TITLE
BUG: static-rdf-server håndterer relativ URI feil

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/fdk-issue-tracker#737]
## 🐛 Bug rapport

I asciidoc-kildekoden bruker vi/jeg ofte relativ URI, og det ser ut til at `../` (et hakk opp) blir håndtert av static-rdf-server dit hen at det blir helt opp til data.norge.no, istedenfor ett hakk opp. 

### Nåværende oppførsel

Se dette skjermbildet
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/46558821/76775697-e266-4050-996f-517d071da8ad)

### Forventet oppførsel

Som sagt at `../` skal bare ett hakk oppover i "mappestrukturen" uansett hvor man er, og ikke helt opp til rota "data.norge.no"

### Hvordan reprodusere?

Se f.eks. [data.norge.no/showroom/skos-ap-no](https://data.norge.no/showroom/skos-ap-no) og klikk på den aller nederste linken som p.t. gir feil fordi det er en relativ URI bak som ikke blir håndtert korrekt. 

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by terjesyl** [comment]
Kom over [dette StackOverflow-svaret](https://stackoverflow.com/questions/24028561/relative-path-in-html) om pathing i HTML.
Har du prøvd med `./../overview/#overview` (merk `./` i starten)?

**Comment by jimjyang** [comment]
@terjesyl 

Har nå forsøkt med `./../overview/#overview`, og resultatet ble det samme (og at det er helt riktig håndtert i Github Pages)
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/46558821/47414882-244d-472a-8593-75f9f2dde539)

**Comment by jimjyang** [comment]
Nå har jeg løst dette problemet ved å oppgi rota (uten domene) i URLene f.eks. `/showroom/overview/`, som heldigvis er håndtert likt av Github Pages og data.norge.no, slik at jeg kan bruke samme asciidoc-kildekoder for begge.  

BORTSETT FRA at src-angivelse for bilder fremdeles ikke blir håndtert korrekt av data.norge.no. Jeg valgte å duplisere bildene i hver sin undermappe slik at for å unngå å måtte gå oppover i mappestrukturen. Dermed er også dette løst.  

Jeg lukker derfor dette Issuet.
