### ISSUE TITLE
BUG: får ikke registrert og sett på datasettbeskrivelse 

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#741]
### Nåværende oppførsel
Jeg får ikke åpnet registreringsbilde for ny datasettbeskrivelse eller åpnet påbegynt/eksisterende datasettbeskrivelse. 
Dette gjelder både demo og prod og i ulike nettlesere. 

@KurtStian  har testet med pålogging via Altinn og Felles brukerhåndtering og det ser ut til at feilen er knytta til rollen org-admin. 
Ved bruk av ID-porten/Altinn feiler det. Der er vel skrivebruker koplet til org-admin-rettighet/rolle.
Ved bruk av Felles brukerhåndtering så feiler det når man bruker Author som er koplet til org-admin, mens ved bruk av editor, som er sys-admin og contributor (skrivebruker), så kommer registreringsskjema for ny datasettbeskrivelse og gammel datasettbeskrivelse opp. 

Registreringsskjema for datasettserie åpnes i både demo og prod

### Forventet oppførsel
Skulle fått åpnet nye datasettbeskrivelser og eksisterende datasettbeskrivelser når jeg har rollen author i Felles brukerhåndtering eller skrivetilgang via ID-porten/Altinn

### Hvordan reprodusere?
prøve å åpne et nytt datasett eller eksisterende datasett når man har rollen author i Felles brukerhåndtering

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/dataset-catalog-gui-old/pull/48
