### ISSUE TITLE
Feature: Endre tilgangsnivå for importer begrep

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#743]
## 🚀 Feature forespørsel

Bør vente til nye roller for begrepskatalogen er tatt i bruk, slik at vi ikke hindrer eksisterende brukere i å importere begrep. 

### Feature beskrivelse
VI ønsker vi å begrense denne tilgangen til lokal administrator og høyere tilgangsnivå. Skrivebruker skal dermed ikke ha tilgang til denne funksjonen. 

### Hvorfor trenger vi det?
Fordi import av begrep fører til store endringer i begrepskatalogen og antall brukere som har tilgang til funksjonen bør begrenses.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KurtStian** [comment]
Testet OK på staging. Vi har nå rollene/rettighetene lesetilgang, skrivetilgang og virksomhetadministrator i FDK, og man må ha rettigheten «Felles datakatalog - alle kataloger - virksomhetsadministrator» i Altinn eller «author» i Felles brukerhåndtering for å kunne importere begrep.
Obs. den nye rettigheten er ikke p.t. tilgjengelig i Altinn produksjon, men produksjonssettes i forbindelse med lansering.

**Comment by jeffreiffers** [comment]
Dette er vel allerede implementert i https://github.com/Informasjonsforvaltning/concept-catalog/pull/270 ?

**Comment by KurtStian** [comment]
@jeffreiffers Ja, som jeg skriver lengre opp så har jeg testet denne og den er OK :-)
