### ISSUE TITLE
BUG: Tomme begrep blir opprettet hvis man ikke lagrer

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#744]
### Nåværende oppførsel
Hvis man velger "Nytt begrep" og så forlater registreringssiden uten å trykke på lagre så blir det opprettet et tomt begrep (også selv man f.eks. har lagt til term).

### Forventet oppførsel
Hvis man velger "Nytt begrep" og så forlater registreringssiden uten å trykke på lagre så skal det ikke opprettes et nytt begrep.

### Hvordan reprodusere?
I staging: Velg "Nytt begrep". Når registreringssiden er åpen går du tilbake til begrepskatalogen uten å lagre.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

Relatert til: https://github.com/Informasjonsforvaltning/behov/issues/930

**Comment by jeffreiffers** [comment]
Denne er vel ikke aktuelt lenger? Viktig å nevne at man må opprette nytt begrep via nye begrepskatalogen og ikke den gamle.

**Comment by KurtStian** [comment]
Denne gjaldt den nye begrepskatalogen, men den er blitt løst. Lukker saken.
