### ISSUE TITLE
Gjøre det nye behovsprosjektet i Github public

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#747]
Som produkteier for FDK ønsker jeg at prosjektet for Behov skal være åpent tilgjengelig og mulig for eksterne å legge til saker i, slik at vi kan få inn innspill utenfor Digdir.

Behovsprosjektet: https://github.com/orgs/Informasjonsforvaltning/projects/12

**Comment by KurtStian** [comment]
@KjerstiSteien Har endret prosjektets synlighet fra private til public.
