### ISSUE TITLE
Feature: vise redaksjonelle sider på Transportportalen

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#749]
### Feature beskrivelse
Flytte redaksjonelle sider for Transportportal.no til data.transportportal.no

### Hvorfor trenger vi det?
For at løsningen skal være sammenhengende nok til at vi ikke bryter med WCAG-krav. 

### Definisjon av ferdig

- [x] Overføre sidene til produksjon (om mulig)
- [x] Lage visning for sidene i portal (forslag til url: data.transportportal.no/about)
- [x] #750
- [x] Legge til embedding av Youtube-videoer
- [x] Verifisere at de som legger inn innhold på vegne av Transportportal får lagt inn bilder,
- [x] Bytte lenke i toppmenyen (Om Transportportal.no) til å vise til de nye sidene. (Gjøres når Transportportal-gjengen er fornøyde med de nye sidene. 
- [x] Vi redirecter data.transportportal.no til transportportal.no (Gjøres når punktet over er løst) (https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/865)
- [x] Endre lenke i "logoen" til Transportportal i toppmenyen, slik at den viser til data.transportportal.no

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by valosnah** [comment]
Siste punkt utført, kan lukkes?
