### ISSUE TITLE
Sidemeny

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#750]
### Sidemenyen i rekkefølge med overskrifter:

| Overordnet menypunkt | Tekst på norsk bokmål | Tekst på nynorsk | Tekst på Engelsk | Siden det lenkes til i transportportal i dag|
| --- | --- | --- | --- | --- |
| N/A | Generell informasjon | N/A | General information | N/A |
| Generell informasjon | Roller og ansvar |N/A| Roles and Responsibilities |https://transportportal.atlas.vegvesen.no/en/gen/roles/
| Generell informasjon | ITS direktivet og forordninger | N/A | ITS Directive and Delegated Regulations | https://transportportal.atlas.vegvesen.no/en/gen/its/|
| Generell informasjon | Informasjon om portalen | N/A | Information about the portal | https://transportportal.atlas.vegvesen.no/en/gen/about/ |
| N/A | For databrukere | N/A | For users of data | N/A |
| For databrukere | Nyhetsbrev | N/A | N/A | https://transportportal.atlas.vegvesen.no/no/read/news/
| For databrukere | Hvor finner jeg data | N/A | Where do I find the data? | https://transportportal.atlas.vegvesen.no/en/read/what/
| For databrukere | Hva finnes av data | N/A | N/A | https://transportportal.atlas.vegvesen.no/no/read/data/ |
| For databrukere | Data i NAP  | N/A | Data in NAP | https://transportportal.atlas.vegvesen.no/en/read/data/ |
| N/A | For datatilbydere | N/A | For data providers | N/A |
| For datatilbydere | Tilby data | N/A | Add data | https://transportportal.atlas.vegvesen.no/en/write/add-data/ |
| For datatilbydere | Samsvarserklæring | N/A | Declaration of Compliance | https://transportportal.atlas.vegvesen.no/en/write/conform/ |

**Comment by jeffreiffers** [comment]
### Forslag til urler
https://data.transportportal.no/transport/general
https://data.transportportal.no/transport/general/roles-and-responsibilities
https://data.transportportal.no/transport/general/its-directive-and-delegated-regulations
https://data.transportportal.no/transport/general/information-about-the-portal
https://data.transportportal.no/transport/users
https://data.transportportal.no/transport/users/news
https://data.transportportal.no/transport/users/where-do-i-find-the-data
https://data.transportportal.no/transport/users/what-data-is-available
https://data.transportportal.no/transport/users/data-in-nap
https://data.transportportal.no/transport/providers
https://data.transportportal.no/transport/providers/add-data
https://data.transportportal.no/transport/providers/declaration-of-compliance
