### ISSUE TITLE
BUG: Registrer data/Høste data i toppmenyen i publiseringsportalen tar bruker til innlogging i prodmiljø når bruker er i staging/demo 

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#751]
### Nåværende oppførsel
Er på demomiljøet og velger "Logg inn for å registrere".  Når bildet for å velge type innlogging vises så velger jeg toppmenylenken Høste data. Innlogging for høsteadmin vises, men miljøet er blitt endret til prod. Tilsvarende skjer også hvis man velger toppmenylenken "Registrer data" og hvis man først velger "Logg inn for å administrere høsting" og så velger toppmenylenken "Registrere data"/"Høste data".

Den samme feilen gjelder også for stagingmiljøet.

### Forventet oppførsel
Toppmenylenkene skal ta bruker til innlogging i samme miljø som brukeren allerede er i.

### Hvordan reprodusere?
Gå inn på: https://demo.fellesdatakatalog.digdir.no/publishing / https://staging.fellesdatakatalog.digdir.no/publishing
Klikk på "Logg inn for å registrere"
Klikk så på f.eks. toppmenylenken "Høste data".
Se at URL-en i adressefeltet nå går mot prod.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
Dette kommer av at sida du da er inne på er bygd vha ftl-filene i keycloak. Det er nok mulig å fikse, men vi tok valget for noen år siden å bare la det være linker til prod siden all jobbing med de sidene tok ekstremt lang tid.

Vil tippe vi må lage egne sider for hvert miljø og bygge egne docker-image for hvert miljø, som har sine egne problem.

Hvis det er noe vi skal prioritere så må det tas med i beregningen at alle som hadde erfaring med å jobbe med dette har slutta i teamet, så det bør settes av en god del tid...

**Comment by terjesyl** [comment]
Akkurat nå er vi ganske begrenset av hvordan Keycloak oppretter HTML-siden som setter disse URL-ene. Foreslår vi ser dette issuet i sammenheng med overgang til ny versjon av KeyCloak hvor vi forhåpentligvis kan løse dette.

**Comment by KurtStian** [comment]
Relatert: https://github.com/Informasjonsforvaltning/sso/issues/135

**Comment by terjesyl** [comment]
@NilsOveTen @hegeaal har vi fortsatt samme problem som tidligere, eller kan dette løses nå?
