### ISSUE TITLE
BUG: Kobling av datasett til datasettserie medfører at datasettet ikke lenger er tilgjengelig i portal

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#755]
### Nåværende oppførsel
Når et datasett kobles/relateres til en datasettserie via registreringsløsningen så er ikke datasettet lenger tilgjengelig for søk i portalen. Og på datasettserien vil det kun vises at det er tilknyttet et datasett og ikke noen mulighet til å se informasjon om datasettet.
Eks.:

I reg.løsning: 
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/304748c6-84c3-49f2-a107-ae0d7b4288b9)

Portal:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/2e1f9e07-63dc-427c-b718-cbe76a727bb6)
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/dcd79993-280e-4411-8f5f-7b818fa53092)

https://demo.fellesdatakatalog.digdir.no/datasets/9f63b43c-9c71-3054-a697-617781289bc5

Dette datasettet forsvinner fra søket: https://demo.fellesdatakatalog.digdir.no/datasets/c48b7d1b-1dd2-36d2-9d8b-368ce0f93d8f

Har testet høsting utenfor reg.løsning ved å høste filen: https://raw.githubusercontent.com/Informasjonsforvaltning/dcat-ap-no/develop/examples/test.ttl Da forsvinner ikke datasettet.
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/929855cb-541b-4c62-8539-20c41aec3ae0)
https://demo.fellesdatakatalog.digdir.no/datasets/deead2b7-e50c-3285-9f38-807f8f816dac

![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/687225a9-4eaa-48c8-9dc7-ea8182d15c0f)
https://demo.fellesdatakatalog.digdir.no/datasets/7c5a0af9-e275-3d85-9871-5495f42530d8

### Forventet oppførsel

Forventet oppførsel er beskrevet her: https://github.com/Informasjonsforvaltning/behov/issues/694

### Forslag/Løsning [Valgfritt]

En midlertidig løsning i første omgang til man får prioritert opp jobben med datasettserier kan være å fikse løsningen slik at datasett som er lagt til en datasettserie via registreringsløsningen ikke forsvinner fra søket i portalen. Alternativt kan man skjule feltene i registreringsløsningen der man legger til relasjon mellom datasett og datasettserie.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
Er en del som kan ha feila her, mine 4 hovedmistenkte er:
- dataset-catalog dropper å legge til datasettet når den produserer rdf
- dataset-harvester ignorerer triplene til et datasett i en serie
- reasoning-service ignorerer datasett i en serie
- rdf-parser ignorerer datasett i en serie

**Comment by KurtStian** [comment]
Testet OK. Datasett som er lagt til en datasettserie via registreringsløsningen forsvinner ikke fra søket i portalen.
