### ISSUE TITLE
Validere dataset-catalog

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#76]
Validere at høste-endepunktet er i henhold til dcat-ap-no 2.0
EU validator: https://www.itb.ec.europa.eu/shacl/bregdcat-ap/upload
Vår:
```
curl -H "Content-Type: text/turtle" \
  -X POST \
  --data-binary @<filnavn.ttl> \
  https://validator.staging.fellesdatakatalog.digdir.no/validator```

**Comment by matsjs** [comment]
Forskjeller i RDF

*Bugs*
- [ ] - Kataloger får ikke lagt på seg datasett uri
- [ ] - Blir publishers delt i to? Forskjell på dataset publisher og catalog publisher?
- [ ] - publisher mangler dct:Identifier i nye :: muligens utdatetert
- [ ] - tomme objectives kommer med på datasett i nye

*Features*
- dqv:inDimension currentness er http://iso.org/25012/2008/dataquality/Currentness i gamle, http://www.w3.org/ns/dqvNS#Currentness i nye
- nye dataset-catalog har et endepunkt for å hente _alle_ kataloger i RDF
- dct:issued er dateTime i gamle, date i nye
- catalog dct:publisher sine urier er nå: https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/{orgnr} var før https://data.brreg.no/enhetsregisteret/api/enheter/{orgnr} :: ønskelig endring?
- Ugyldige URL'er kommer ikke med, f.eks i contactPoint->hasURL: bjornafjorden.kommune.no
