### ISSUE TITLE
BUG: Kilde "egendefinert" på definisjon vises ikke

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#760]
### Nåværende oppførsel

Legger til kilde "Egendefinert" på definisjon. Kilden vises ikke på detaljesiden til begrepet. Vet ikke om den også skulle vises på søkesiden slik det gjør i portalen. 

**Fra begrepskatalogen:**

![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/e21e3cc8-2b48-455c-ad8e-0bcf551d09bd)
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/ac40707c-bbe3-49fe-b0f4-f192711096e1)

**Fra portal:**

![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/3822ef7d-dd69-4742-976a-aab53fe53257)
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/f4f27e1d-9903-4937-b4b2-ddb547236aab)

### Forventet oppførsel

Kilde "Egendefinert" skal vises når dette er registrert. 

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by jeffreiffers** [comment]
@KurtStian  Kilde til definisjonen vises ikke i søkeresultatene (ikke designet i hvertfall).

**Comment by KurtStian** [comment]
@jeffreiffers Ja, "Kilde til definisjon" vises ikke i søkeresulatet til begrepskatalogen, men gjør det i portalen. Er den ikke tatt med i designet så skal den kanskje ikke være med, eller så er den glemt. 
@KjerstiSteien Skal "kilde til definisjon" være med i søkeresulatet til begrepskatalogen?

**Comment by KjerstiSteien** [comment]
Kilde skal ikke med i søkeresultatet. Vi kan eventuelt ta det opp senere, dersom noen etterlyser det.

**Comment by jeffreiffers** [comment]
Kjersti har svart at den ikke skal med. Kan jeg lukke saken?

**Comment by KurtStian** [comment]
@jeffreiffers Er det fikset slik at kilde "egendefinert" vises på detaljesiden til begrepet? Hvis ja, så kan den lukkes.
At den ikke vises i søkeresultatet var bare en tilleggskommentar.

**Comment by jeffreiffers** [comment]
Det har alltid vært der.


![Image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/430997/88e7fa71-76cd-411f-beed-eeb22caa6a03)
