### ISSUE TITLE
Mer robust tilkobling til meldingstjeneste (Rabbit/Kafka)

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#773]
# Robust tilkobling til meldingstjeneste
## Hva
Sørge for mer robust konfigurering av tilkoblinger til meldingsutveksler. Gjelder ihvertfall Rabbit, muligens Kafka.

## Hvorfor
Appene som er avhengig av Rabbit kræsjer og klarer ikke restarte om Rabbit går ned.

GCP restarter tjenestene i ny og ne (omtrent en gang i måneden), inkludert Rabbit/meldingstjenesten. Med andre ord risikerer vi at stacken vår går ned med jevne mellomrom.

## Annet
Hvis dette problemet ikke gjelder Kafka, eller løses enklere med Kafka bør dette issuet ses i sammenheng med issuet om å erstatte RabbitMQ med Kafka.

## Todo:
- [ ] Undersøke om problemet også gjelder tjenestene som bruker Kafka.
- [ ] Undersøke konfigurering som løser problemet.

**Comment by KjerstiSteien** [comment]
@NilsOveTen @jeffreiffers er dette issuet fortsatt relevant?

**Comment by jeffreiffers** [comment]
Virker ikke veldig konkret beskrevet. Kan for min del lukkes.

**Comment by NilsOveTen** [comment]
Tror fortsatt vi har en del applikasjoner som ikke håndterer at rabbitmq restartes, men planen er vel å gå helt bort fra rabbit og bruke kafka i alle ledd. Vi kan kanskje lukke denne og peke til et issue som beskriver hva som skal til for å kunne fjerne rabbitmq fra stacken

**Comment by NilsOveTen** [comment]
løses av: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/691
