### ISSUE TITLE
Relasjoner til datasett

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#78]
Datasett kan ha relasjoner til informasjonsmodeller. Denne relasjonen ønsker vi å vise på informasjonsmodellen også.
F.eks har dette datasettet en relasjon til flere informasjonsmodeller:
https://demo.fellesdatakatalog.digdir.no/datasets/dacf5020-867f-372d-842f-4a814f987809

De ønsker vi å vise på informasjonsmodellen sin detaljeside også under "relatert til datasett"
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/infomodel/detail-structure-default.html

**Comment by shenluna** [comment]
Testet i staging
https://www.staging.fellesdatakatalog.digdir.no/informationmodels/60ecfff8-9ea3-41ee-92cc-7e791d73dac0
