### ISSUE TITLE
Refaktorere fdk-model-publisher

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#781]
## Beskrivelse av dagens situasjon: 
denne dør i ny og ne pga bruk av mye minne. 

## Forslag til løsning: 
Tror vi kan gå over til å bruke kafka events slik at den kun trigger oppdateringer av enkelte datatjenester, og ikke kjører for alle høstede datatjenester hver gang det skjer en høsting)

##Mulig relevante issues: 
- [ ] https://github.com/Informasjonsforvaltning/behov/issues/736

**Comment by KjerstiSteien** [comment]
@jeffreiffers @NilsOveTen er denne fortsatt relevant, ellerhar vi skrudd av fdk-model-publisher?

**Comment by jeffreiffers** [comment]
Fdk-model-publisher er arkivert og kjøres ikke lenger. Usikker om det skal bygges noe nytt eller om saken kan lukkes. @NilsOveTen kan svare på det.

**Comment by NilsOveTen** [comment]
Det var for mye problem med en tjeneste som automatisk produserte informasjonsmodeller ut fra openapi-speccen til alle datatjenestene vi høster, så denne er ikke relevant. Lukker

Hvis noen savner at dette skjedde så kan vi potensielt gjenbruke noe av koden her til å publisere noe ala [oastodcat](https://github.com/Informasjonsforvaltning/oastodcat)
