### ISSUE TITLE
Forenkle oppdatering av dataservice-publisher, dvs DSOP (Det er komplisert i dag)

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#782]

**Comment by pooriamehregan** [comment]
har sammenheng med: 
https://github.com/orgs/Informasjonsforvaltning/projects/11/views/3?pane=issue&itemId=40983433

**Comment by KjerstiSteien** [comment]
Lukker denne saken, da data.altinn.no vil ta over DSOP-biten. Vi vil forenkle beskrivelsen på data.norge.no, slik at vi ikke lenger trenger en slik tjeneste. Når vi er klare for å legge ned tjenesten vil dette beskrives i egen sak.
