### ISSUE TITLE
BUG: Definisjonene for målgruppe allmennheten/spesialister vises ikke på detaljesiden i portalen

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#795]
### Nåværende oppførsel

Det vises kun en definisjon på detaljesiden i portalen selv om alle tre definisjonene er lagt til. I tillegg vil det variere hvilken definisjon som vises.
I eksemplet nedenfor vises definisjon for allmennheten selv om definisjon også er lagt til. Ser ut som definisjon for allmennheten vises pga. at det lagt til tittel/lenke til kilde.

![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/381ec513-29bf-4b77-9321-fce4e4beef0a)
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/eb246a69-f89f-458a-ba02-2319e0a6c365)

For samme begrep på søkesiden i portalen vises definisjonen. Lager egen sak på hva som skal vises på søkesiden.
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/510afeb3-21be-4000-bc2d-792e3aaf6975)

### Forventet oppførsel

Alle definisjonene  (definisjon, definisjon - målguppe for allmennheten og definsjon - målgruppe for spesialister) skal vises på detaljesiden til begrepet i portalen når disse finnes.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Sjekket i staging. Alle definisjoner vises i portal nå. Regner derfor bugen som løst. Lager en feature som beskriver endret visning av de ulike definisjonene.

**Comment by KjerstiSteien** [comment]
Restanse beskrevet i denne saken: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/972
