### ISSUE TITLE
BUG: Mangler prioritering på hvilken definisjon som skal vises på søkesiden for et begrep når det finnes flere definisjoner

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#796]
### Nåværende oppførsel

Det virker tilfeldig hvilken definisjon som vises på søkesiden for begrepet når det er registrert flere definisjoner (definisjon, definisjon - målguppe for allmennheten og definsjon - målgruppe for spesialister) på begrepet. Bl.a. ser det ut som angivelse av  kilde til definisjon kan påvirke hva som vises.

Eks.:
Søkeside:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/98c71e74-7e27-4dbb-8cc7-bd3cf30b0cd5)
Detaljeside:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/e8bcae92-40bf-42c3-9966-f77ae79082b9)

### Forventet oppførsel

Definisjon skal vises uavhengig av kilde og prioritert etter:
1. Definisjon - uten målgruppe
2. Definisjon - målgruppe for allmennheten
3. Definisjon - målgruppe for spesialister

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
Dette er en bug som kommer fra fdk-rdf-parser og at den støtter maks 1 definisjon, etter prat med @KurtStian lander vi på denne løsningen:

- henter ut alle definisjoner i et nytt json-felt, som kan skilles fra hverandre vha audience-verdi
- beholder det gamle `definition`-feltet for å være bakoverkompatible, men det er bare definisjonen uten audience som legges til her, i stedet for en tilfeldig som nå

**Comment by KjerstiSteien** [comment]
Tilknyttet sak: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/795
