### ISSUE TITLE
Performance issue ved førstegangsåpning av data.norge.no

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#8]
Nå tar det nesten 6-7 sekunder å laste inn data.norge.no første gang bruker er på siden.

Vi ønsker å forbedre performance her og se hva vi kan gjøre for at dette blir bedre.

Forslag:
Se på dette på infrastrukturnivå:
- Potensiell løsning: benytte http2 ? <- laster inn flere av filene samtidig
- Kan evnt få inn en hjelpeside som ser bra ut i mens bruker venter (???)

**Comment by valosnah** [comment]
Det viser seg at vi alltid har støttet http/2. Sjekk av staging og demo, samt våre egne sider i prod viser at vi bruker http/2. Dette er standard i GCP.
Issuet er at loadbalanceren til portalteamet ikke gjør det, så all trafikk via data.norge.no går på http/1.1 

Har snakket med Sture, som har identifisert hva som burde gjøres. 
Vi må legge inn en bestilling hos helpdesk, og de må rulle ut nytt oppsett. 
Tar en prat om dette med Stig i løpet av møtet vårt onsdag 04.11, og oppretter bestilling.

**Comment by valosnah** [comment]
Bestilling sendt til helpdesk.
Bedt om at de deployer endringen til demo.difi.no først (som peker på vårt demo-miljø), hvis mulig.
Utrulling i prod: mellom kl 17-18, så snart som mulig.
Det er uansett antatt at endringen ikke vil føre til noen problemer i prod.

**Comment by valosnah** [comment]
Http/2 er nå aktivert i portalteamets loadbalancer, og data.norge.no laster som forventet langt raskere (~1s)
