### ISSUE TITLE
Lenke til Catalog Admin under nedtrekksliste i header

### ISSUE THREAD

**Issue by AinaEngen** [Informasjonsforvaltning/fdk-issue-tracker#817]
Skal fungere fra:

Prioritert rekkefølge:

- [x] - [registration-portal](https://github.com/Informasjonsforvaltning/registration-portal)
- [x] - [catalog-frontend](https://github.com/Informasjonsforvaltning/catalog-frontend)
- [x] - [concept-catalog-gui](https://github.com/Informasjonsforvaltning/concept-catalog-gui)
- [x] - [dataset-catalog-gui](https://github.com/Informasjonsforvaltning/dataset-catalog-gui)
- [x] - [dataservice-catalog-gui](https://github.com/Informasjonsforvaltning/dataservice-catalog-gui)
- [x] - [dataset-catalog-gui-old](https://github.com/Informasjonsforvaltning/dataset-catalog-gui-old)
- [x] - [records-of-processing-activities-gui](https://github.com/behandlingsoversikt/records-of-processing-activities-gui)
- [x] - [terms-and-conditions-gui](https://github.com/Informasjonsforvaltning/terms-and-conditions-gui)

Skal ligge ved Logg ut:
![Screenshot from 2023-10-25 12-20-39](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/50194012/99637d52-d02e-4e99-a08f-8aaa0277c89f)

**Comment by hegeaal** [comment]
Hvordan skal man vite hvilken katalog man skal linke til?
