### ISSUE TITLE
BUG: potensiel prodfeil

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-issue-tracker#819]
## 🐛 Bug rapport
Tekniske problemer ved import/legge til nye begrep i begrepskatalogen. Brukeren skriver "I dag har jeg prøvd å importere en .csv fil med begrep (to begreper, se også vedlegget). Jeg får en feilmelding som ser sånn ut:" 

![278607604-bc1f5549-df28-42fc-9e5d-b8566a90ddbf](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/50879748/d91fcb9f-7c1b-45bc-9921-742ff1c2784c)

videre skriver brukeren: "I tillegg kan jeg ikke legge til et nytt begrep via knappen; når jeg trykker «Legg til nytt begrep» reagerer systemet ikke.".

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
@KurtStian dette er fikset nå?

**Comment by KurtStian** [comment]
@KjerstiSteien Ja, denne er løst. Mal er blitt oppdatert og import er testet OK både for csv og json.
