### ISSUE TITLE
Opprette flere demobrukere

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#82]
Det begynner å bli tynt med tilgjengelige demobrukere.

- [x] Vurdere om demobrukere skal/kan/burde benytte seg av Felles brukerhåndtering istedet? (Vi fortsetter med mock-brukere)
- [x] Opprette 20-ish nye demobrukere

**Comment by valosnah** [comment]
Vi har pdd 5 demobrukere til overs

**Comment by valosnah** [comment]
pdd 1 ledig demobruker

**Comment by valosnah** [comment]
24 nye demobrukere opprettet

**Comment by shenluna** [comment]
Demobrukere opprettet, lukker saken
