### ISSUE TITLE
BUG: Lenken administrer katalogene vises for datasettkatalog som bruker kun har skrivetilgang til når han samtidig har admin rettighet til annen datasettkatalog

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#821]
### Nåværende oppførsel
Logger inn med en bruker som både har virksomhetsadministratortilgang til katalogene til en virksomhet og kun skrivetilgang til katalogene til en annen virksomhet.
Åpner datasettkatalogen til virksomheten brukeren kun har skrivetilgang til og ser at lenke "Administrer katalogene" vises. (Ser ut som det er riktig for begrep - lenken vises ikke)

### Forventet oppførsel
Lenken "Administrere katalogene" skal kun vises på katalognivå for katalogene brukeren har administratortilgang til. 

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Må vurdere beste flyt her. Kanskje høre med andre designere, @matfuru ?
