### ISSUE TITLE
Feature: legge ned Drupal

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#824]
### Feature beskrivelse
Vi ønsker å legge ned drupal for data.norge.no og gå fullt over til Strapi. 

### Hvorfor trenger vi det?
Fordi vi ønsker å forenkle porteføljen vår, og fjerne rester av systemer vi har brukt tidligere

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
@jeffreiffers Har vi lagt ned drupal nå? Mener å huske at vi kan ha blitt ferdig med dette. Har du mulighet til å sjekke?

**Comment by jeffreiffers** [comment]
@KjerstiSteien ja den er ikke i bruk lenger
