### ISSUE TITLE
BUG: catalog-view-api - feil knyttet til å hente ut beskrivelse til interne felt

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#834]
### Nåværende oppførsel
Det hentes ikke ut beskrivelse til kodeliste. Feltet i json-filen er tom.
Det er ikke mulig å registrere beskrivelse til feltene «Kort tekst», «Lang tekst» og «Bolsk verdi» i administrasjonsgrensesnittet til katalogene, men det vises som tomme felt i json-filen.

![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/74ac4f15-5558-4845-9226-fa2c0bb1cecb)
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/f6a3d9dd-2a49-4c08-93cf-2d9779833a21)
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/7cb21f79-bf61-4e2c-a91a-9abd171ef11d)

### Forventet oppførsel
Beskrivelse til kodeliste blir med i json-filen når dette er registrert.
Feltet description fjernes/deaktiveres i json-fil for feltene «Kort tekst», «Lang tekst» og «Bolsk verdi» da dette  ikke er mulig å registrere p.t.

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
Jeg la til `description`-feltet siden interne felt har et `description`-felt i backend, men jeg ser nå at det ikke er mulig å registrere data der i frontend-skjemaet. Gir det kanskje mest mening å bare fjerne feltet helt fra catalog-view? Og så heller legge det til igjen hvis vi legger til støtte for å registrere beskrivelse av interne felt?

Jeg føler ikke nytteverdien er helt der for å vise beskrivelsen fra en kodeliste

**Comment by KurtStian** [comment]
Ja, feltene kan fjernes til vi ev. legger inn støtte for å registrere beskrivelser av interne felt.

**Comment by KurtStian** [comment]
Testet OK på staging.
