### ISSUE TITLE
BUG: catalog-view-api henter ikke ut opplysninger registrert i det interne feltet «Merkelapp»

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#835]
### Nåværende oppførsel

Opplysninger registrert i det interne feltet «Merkelapp» blir ikke med i json-filen som kommer ved API-kallet.

### Forventet oppførsel

Uthenting av merkelapp/er skal også støttes.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
@KurtStian Har du et eksempel på et begrep hvor dette intreffer?

**Comment by KurtStian** [comment]
Eksempel:

{
    "id": "18b8a2b4-de2c-4450-ba79-bb725e074fe6",
    "idOfOriginalVersion": "18b8a2b4-de2c-4450-ba79-bb725e074fe6",
    "version": {
        "major": 0,
        "minor": 1,
        "patch": 0
    },
    "isPublished": false,
    "publisher": "991825827",
    "status": "http://publications.europa.eu/resource/authority/concept-status/DRAFT",
    "preferredTerm": {
        "nb": "Anbefalt term 1 - nb",
        "nn": "Anbefalt term 1 - nn",
        "en": "Anbefalt term 1 - en"

**Comment by KurtStian** [comment]
Testet OK:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/153dcf47-b9dd-45b4-b1bc-cd34a2c86055)
