### ISSUE TITLE
Task: Fjerne visning av antall treff i søkefanene i portalen

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#842]
### Nåværende oppførsel

Visning av antall treff i overskriften for hver søkefane støtter kun maks 10000 treff. Dette overstiges nå ved høsting av hele Geonorge for søkefanen "Alle".
Eks:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/7e139050-fb2e-4253-acd4-7112e3d563b1)

### Forslag/Løsning

Antall treff fjernes fra søkefanene, jf. kommentar: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/842#issuecomment-1911734318

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Sjekket med teamet "Data som ressurs". Vi fjerner antall treff i stedet for å løse dette. Ny sak kommer.

**Comment by NilsOveTen** [comment]
siden dette skal løses skikkelig senere, kan vi bruke dette issuet for å gjøre en kjapp løsning? Dvs vise `10000+` i stedet for `10000`?

**Comment by KurtStian** [comment]
> siden dette skal løses skikkelig senere, kan vi bruke dette issuet for å gjøre en kjapp løsning? Dvs vise `10000+` i stedet for `10000`?

Ja, det kan vi.

**Comment by KjerstiSteien** [comment]
Har fått svar fra Øystein sitt team om at antall treff kan fjernes fra disse fanene.

**Comment by KurtStian** [comment]
> Har fått svar fra Øystein sitt team om at antall treff kan fjernes fra disse fanene. Saken må skrives om eller lukkes og erstattes med ny sak.

@KjerstiSteien Ja, men da må vi vel også implementere en annen måte å vise antall treff når noen gjør et søk? Eller mener du at vi skal ha et søk uten antall treff.

**Comment by KurtStian** [comment]
Nå som vi ikke lenger har en betaversjon av tjenestekatalogen og vi skal fjerne antall treff i søkefanene, bør denne prioriteres: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/387

**Comment by KjerstiSteien** [comment]
Bør løses i sammenheng med https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/387
