### ISSUE TITLE
BUG: Samme format vises flere ganger i søkeresultatet når et datasett har flere distribusjoner med samme format

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#846]
### Nåværende oppførsel
Hvis et datasett har flere distribusjoner med samme format (filetype/mediaType) så vises formatene tilsvarende mange ganger som filter i søkeresultatet på datasettet.
Eks: ![image (19)](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/830e1402-11db-4698-8b81-a8ae7a6f17f7)

### Forventet oppførsel
I søkeresultatet på datasett skal det kun vises unike format.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by NilsOveTen** [comment]
listen er bygd opp ved å slå sammen `fdkFormat` for samtlige distribusjoner i datasettet, vi trenger en filtrering av unike verdier for denne visningen
