### ISSUE TITLE
behov for å samordne begrepsbruk i registreringsløsning og portal om API og datatjeneste

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#85]
Det virker som at det er behov for å samordne begrepsbruk om "API" og "datatjeneste" i registreringsløsning, portal og på github, samt at "datatjeneste" bør defineres i begrepskatalogen. 

Fra oversiktsbildet:
![image](https://user-images.githubusercontent.com/32771488/100089544-22255500-2e52-11eb-9e93-cb3509f8e286.png)

Inne i katalogen:
![image](https://user-images.githubusercontent.com/32771488/100089620-42edaa80-2e52-11eb-8a5e-c7d3a9d4e85f.png)

Inn i katalogen er det nå knapp og overskrift hvor vi bruker begrepet "datatjenestebeskrivelse" (ref de to nederste gule tekstene i bildet over her), men ute i portalen bruker vi begrepet "API":
![image](https://user-images.githubusercontent.com/32771488/100089901-b42d5d80-2e52-11eb-8ef7-c2672d19bf07.png)

Portal:
![image](https://user-images.githubusercontent.com/32771488/100090268-387fe080-2e53-11eb-8b9d-c578a87bd9f7.png)

https://informasjonsforvaltning.github.io/ :
![image](https://user-images.githubusercontent.com/32771488/100090438-77ae3180-2e53-11eb-82c0-9422558234ab.png)

Digdir har en definisjon av API i Felles datakatalog, men vi har ingen definisjon på datatjeneste der.

Vi må også ta stilling til om navnet på datasettbeskrivelsen "API-katalog i Felles datakatalog" skal endres til "Datatjenestekatalog i Felles datakatalog", samt om begrepsbruk under "Beskrivelse", Formål" og "Distribusjon" skal endres, samt om datasettbeskrivelser som har relasjon til denne datasettbeskrivelsen må endre relasjonshenvisning

Nederst på https://data.norge.no/ ligger det en lenke som heter "Søk i datatjenester". Den leder nå til https://data.norge.no/apis . Se issue ""Søk i datatjeneste" i portalen leder ikke til side som viser datatjenester #87

**Comment by joachim-me** [comment]
Issue må beskrive endringene vi ønsker før utviklingsteamet kan ta tak i det. @RogerSOlsen

**Comment by KjerstiSteien** [comment]
Dette blir ryddet opp i i registreringsløsning nå. 
Foreslår at vi brukertester begrepene før vi gjør endringer i portal og dokumentasjon.

**Comment by KjerstiSteien** [comment]
Lukker saken, da vi følger opp dette i egne prosesser.
