### ISSUE TITLE
Kafka-event publishers

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#853]
# Kafka-event publishers
## Beskrivelse:
For informationmodels, events og services.
Har blitt gjort før.

**Comment by jeffreiffers** [comment]
- https://github.com/Informasjonsforvaltning/fdk-kafka-event-publisher/blob/main/src/bin/fdk-event-event-publisher.rs
- https://github.com/Informasjonsforvaltning/fdk-kafka-event-publisher/blob/main/src/bin/fdk-service-event-publisher.rs
- https://github.com/Informasjonsforvaltning/fdk-kafka-event-publisher/blob/main/src/bin/fdk-information-model-event-publisher.rs
