### ISSUE TITLE
fdk-rdf-parser-service lytter til kafka-meldinger

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#854]
# fdk-rdf-parser-service lytter til kafka-meldinger
## Beskrivelse: 
Lytter til "reasoned”-meldinger i Kafka fra publishers.

## Avhengigheter:
Krever at informationmodels, events og services sender Kafka-melding.

**Comment by terjesyl** [comment]
Erstattes av https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/854 , fdk-rdf-parser-service skrives om til å være et REST-API som tar inn RDF og returnerer JSON.
