### ISSUE TITLE
Overta transportportal.no

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#865]
~Vi avventer foreløpig klargjøring fra SVV om hvilke adresser som skal peke til hva, etc
Før SVV foretar seg noe må vi:~

Vi endte opp med at Digdir overtok domenet transportportal.no
Idag peker transportportal.no på SVVs løsning. 
Denne adressen skal fremover gå til vår portal, og data.transportportal.no skal omdirigeres til transportportal.no

- [x] Bestille nytt multisertifikat for transportportal.no, www.transportportal.no og data.transportportal.no
- [x] #948
- [x] #946
- [x] #947
- [x] #945

- [x] ~Få SVV til å bestille A og AAAA record til våre IP'er for de relevante adressene.~

Ellers; gjøre nødvendige endringer i fdk-portal (se https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/749)

**Comment by valosnah** [comment]
Det må også bli klarhet i om Digdir vil ta over eierskapet til domenene, Kjersti i dialog med KOM

**Comment by AinaEngen** [comment]
@KjerstiSteien - vet du noe mer her?

**Comment by KjerstiSteien** [comment]
Epost sendt til SVV med bekreftelse om at vi kan ta over eierskapet for domenet. Blokkert frem til vi får svar fra SVV.

**Comment by valosnah** [comment]
Svar mottatt, i kontakt med Drift for å høre hvordan vi fortsetter mtp domeneovertakelse, DNS og sertifikatbestilling.

**Comment by valosnah** [comment]
Bestilling av sertifikat: det er visst noe trøbbel med å autorisere domenet, drift har en support-sak hos Buypass gående

**Comment by valosnah** [comment]
Alle oppgaver utført
