### ISSUE TITLE
BUG: Får meldingen "Sign in with Keycloak" når jeg går fra begrepskatalog til tjenestekatalog

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#867]
### Nåværende oppførsel

Er innlogg og har vært i begrepskatalogen og gjort endring i skjema. Går til "alle kataloger" og velger så "Tjenestekatalog". Får meldingen nedenfor:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/71980044-f2c5-4266-967d-ac1c59b1e036)

Ved å klikke på meldingen så kommer jeg inn i tjenestekatalogen.

Det er også tilfeller at jeg får denne meldingen når jeg bruker brødsmulelisten i begrepskatalogen for å gå til "alle kataloger":
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/26a077fc-1ad7-4b95-9d9d-3fce171a6b2f)

### Forventet oppførsel

Siden jeg allereder er innlogget med rette tilganger skal jeg kunne navigere mellom katalogene uten å få melding om å logge inn eller andre feilmeldinger.

**Comment by jeffreiffers** [comment]
Har ikke klart å reprodusere denne "feilen"/oppførsel.
