### ISSUE TITLE
lenke "Søk i datatjeneste" i portalen leder ikke til side som viser datatjenester

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#87]
Nederst på https://data.norge.no/ ligger det en lenke som heter "Søk i datatjenester". Den leder nå til https://data.norge.no/apis som gir dette resultatet:

![image](https://user-images.githubusercontent.com/32771488/100346058-8af00700-2fe3-11eb-98ba-40078192c599.png)

**Comment by terjesyl** [comment]
Ser ut til å være fikset. "Søk i datatjenester" leder nå til https://data.norge.no/dataservices (se bilde)

![bilde](https://user-images.githubusercontent.com/108797958/183584776-3f5bc6f5-501a-4e7c-907e-1fc48bcb210d.png)

**Comment by RogerSOlsen** [comment]
Sak løst!
