### ISSUE TITLE
Feature: Legge ut melding i datafabrikken om nedleggelse

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#870]
### Feature beskrivelse
Legge ut melding i datafabrikken om nedleggelse og overgang til data.norge.no

### Hvorfor trenger vi det?
For å varsle brukerne av Datafabrikken om at løsningen vil legges ned og slås sammen med data.norge.no

### Forslag/løsning [Valgfritt]
Banner eller bilde på forsiden av datafabrikken med lenke til data.norge.no

[Design](https://www.figma.com/proto/vNYsWsl4TbLU0Bo7aE1bmH/Datafabrikken-%E2%80%93-Publisert?page-id=1604%3A78873&type=design&node-id=1604-78874&viewport=756%2C2153%2C0.96&t=nkl6eujztrAjS8NW-1&scaling=scale-down-width&mode=design):

<img width="867" alt="image" src="https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/110605570/f37f6f6f-2fc0-4592-a4ea-cd88ee7fa2e3">

Tekst: Datafabrikken vil legges ned 30. april 2024. Datafabrikken og data.norge.no fyller samme behov i dag.  Ved å samle ressursene rundt data.norge.no vil vi få større kraft til å lage en bedre løsning som dekker både næringslivets og offentlig sektors behov. Du vil fortsatt finne datasettbeskrivelser på data.norge.no.  Ønsker du å bidra til at data.norge.no blir bedre? Ta kontakt med oss på fellesdatakatalog@digdir.no.

**Comment by matfuru** [comment]
https://www.figma.com/proto/vNYsWsl4TbLU0Bo7aE1bmH/Datafabrikken-%E2%80%93-Publisert?page-id=1604%3A78873&type=design&node-id=1604-78874&viewport=756%2C2153%2C0.96&t=nkl6eujztrAjS8NW-1&scaling=scale-down-width&mode=design
