### ISSUE TITLE
BUG: Kodeelmentene i nyopprettet kodeliste vises ikke i registreringsskjema for begrep

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#872]
### Nåværende oppførsel
Feltet "Fagområde" viser ikke kodelisten som er lagt til i administrasjonsgrensesnittet. Feltet vises fortsatt som fritekstfelt.
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/57f158fd-d4ea-4e43-9a8d-6198ebadc61f)

Internt felt der det er valgt at dette skal være en kodeliste viser ikke kodelisten som er lagt til. Søkefeltet "Søk etter kode" vises.
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/6907759e-efaf-49db-a72b-63abe883a621)

### Forventet oppførsel
Kodelisten skal vises og kodelementer skal kunne velges i feltet Fagområde.

Kodelisten skal vises og kodelement skal kunne velges i det opprettede interne feltet. 

### Hvordan reprodusere?
Opprett en ny kodeliste.
Opprett internt felt type "kodeliste" og velger den opprettede kodelisten.
Velg også den samme kodelisten i editerbare felt (Fagområde).

**Comment by NilsOveTen** [comment]
Det ser ut til å være dropdown for å velge fagområde-kodeliste i admin-grensesnittet som er problemet.

Den takler ikke null-verdi, så den velger automatisk øverste kodeliste som valgt liste. Men den er ikke lagret og skjemaet krever en endring før den prøver å lagre. Siden det bare er 1 liste tilgjengelig så er det ikke mulig å gjøre noen endringer slik at det er mulig å lagre.
