### ISSUE TITLE
Feature: Rate-limiting på alle api

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#873]
## 🚀 Feature forespørsel

Rate-limiting i form av tak på antall requests eller mengde nedlastet data over tid.

Per nå er vi sårbare for at brukere av catalog-view-api henter ut store mengder data, som fører til økte kostnader for oss.

Kan innføres enten i catalog-view-api-ingressen (litt begrenset med valg), eller i en egen nginx-tjeneste (veldig fleksibel)

### Definisjon av ferdig: 
En feilkode 429 hvis man sender for mange requests i løpet av definert tid, eller mengde data over tidsrom

- [x] fdk-nginx-community
- [x] fdk-nginx-dataservices
- [x] fdk-nginx-organization-bff
- [x] ~fdk-nginx-records~
- [x] fdk-nginx-registration
- [x] fdk-nginx-sparql
- [x] nginx-harvester
- [x] høsterne (nginx-harvester)
- [x] catalog-view-api (ny nginx)
- [x] ai-project-service
- [ ] catalog-admin-frontend
- [x] catalog-admin-service
- [x] catalog-history-service
- [ ] catalog-portal-frontend
- [x] ~concept-catalog-frontend~
- [x] ~data-service-catalog-frontend~
- [x] ~dataset-catalog-frontend~
- [x] fdk-harvest-admin
- [x] fdk-llm-search-service
- [x] ~fdk-reports-bff~
- [x] fdk-resource-service
- [x] fdk-search-service
- [ ] karma
- [ ] prometheus
- [ ] grafana
- [ ] thanos
- [ ] thanos-store
- [ ] service-catalog
- [ ] service-catalog-frontend

**Comment by valosnah** [comment]
Trenger avklaring:

- [ ] Hvilke grenser skal vi sette? (Antall requests, datamengde etc), hva kommer til å stå i avtalen til Skatt?

**Comment by KurtStian** [comment]
Vi må også sette rate-limiting på alle de andre åpne API-ene vi har.

**Comment by KjerstiSteien** [comment]
@valosnah @KurtStian venter vi på noe fra Skatt her?

**Comment by KurtStian** [comment]
> @valosnah @KurtStian venter vi på noe fra Skatt her?

@KjerstiSteien Nei, vi har hatt møte med SKD og har det vi trenger. Må bare prioriteres.

**Comment by valosnah** [comment]
Alle relevante API er satt bak rate-limit, lukker denne.
