### ISSUE TITLE
Task: oppdatere monsido-script på transportportal

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#876]
### Task beskrivelse
Monsido-scriptet på transportportal må oppdateres til 

<script type="text/javascript">
    window._monsido = window._monsido || {
        token: "H7pMv_I-KwnWIR1nkiCXuw",
        statistics: {
            enabled: true,
            cookieLessTracking: false,
            documentTracking: {
                enabled: false,
                documentCls: "monsido_download",
                documentIgnoreCls: "monsido_ignore_download",
                documentExt: ["pdf","doc","ppt","docx","pptx"],
            },
        },
        heatmap: {
            enabled: true,
        },
    };
</script>
<script type="text/javascript" async src="https://app-script.monsido.com/v2/monsido-script.js"></script>

### Hvorfor trenger vi det?
For å få analyticsfunksjonen for denne siden til å fungere i monsido.

**Comment by jeffreiffers** [comment]
Er utført!
