### ISSUE TITLE
Doc: Installasjon og tips og triks for verktøy og tech-stack

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-issue-tracker#877]

**Comment by KjerstiSteien** [comment]
@terjesyl legger du til en beskrivelse av oppgaven?

**Comment by KjerstiSteien** [comment]
Jeg tror @NilsOveTen har forsøkt å dekke en del av dette her: https://informasjonsforvaltning.github.io/developers_handbook/tools_and_software/ Er det mer vi burde gjøre for å dekke denne oppgaven?

**Comment by terjesyl** [comment]
Tror det skal være greit. Vi kan legge til mer senere, ved behov:)
