### ISSUE TITLE
Oversikt over repoer

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-issue-tracker#878]
En oversikt over repoer og tjenester og relasjonene mellom disse. 
Beskrivelse av hva repoene er i Github så det gir mening. 
Kategorisere repoene på en måte som gir bedre oversikt? (biblioteker etc)

**Comment by KjerstiSteien** [comment]
Sjekke om dette er gjort.

**Comment by pooriamehregan** [comment]
Vi har disse: 
- https://digdir.sharepoint.com/sites/FDKUtviklingsteam/SitePages/Github-repositories.aspx
- https://digdir.sharepoint.com/sites/FDKUtviklingsteam/SitePages/API.aspx?csf=1&web=1&e=vIyMUt

I tillegg var det en en tom Repositories side under Architecture, som nå inneholder en lenke til den første lenken som er listet over: https://digdir.sharepoint.com/sites/FDKUtviklingsteam/SitePages/Repositories.aspx?csf=1&web=1&e=l3eEZk

**Comment by pooriamehregan** [comment]
Det som mangler per nå er:
- relasjonene mellom repoene
- sjekke om repoene har oppdatert Readme i Github
- Og kanskje lage en bedre oversikt over repoer, hvor de repoene som hører sammen er gruppert osv.

**Comment by KjerstiSteien** [comment]
Flytter denne tilbake til ready, så noen kan se på punktene som gjenstår, ref Poorias liste.

**Comment by terjesyl** [comment]
Er litt usikker på verdien av denne. Vi risikerer å duplisere masse informasjon som egentlig burde stå i README-ene i repoene. Og et større dokument med oversikt over alle repoene blir vanskelig å holde ved like etterhvert som repoene endrer seg.

Forslag:
- Vi lager et ikke-komplett diagram over de viktigste repoene i løsningen, hvilke tjenester som befinner seg i repoet og ev. vise sammenhengen mellom de tjenestene. Gir et overordnet innblikk for nye.
- Gå gjennom de viktigste repoene og sørge for at README-ene er oppdatert (hvilke skal i så fall prioriteres?)
- Gå gjennom de viktigste/alle repoene og sørge for at de har en god "About"-seksjon/beskrivelse.
- Merke alle viktige repoer med topics. Være konsekvent med merking av repoer.

Hva tenker dere @KurtStian @AinaEngen

**Comment by AinaEngen** [comment]
@terjesyl Tenker at vi ikke skal duplisere informasjon. Synes forslaget ditt er bra. Hva om (noen av) dere utviklere + Kurt Stian tar et lite arbeidsmøte for å diskutere dette. Da får vi bestemt hvilke repo som skal prioriteres. Selve oppdateringen av readme/about kan jo teamet dele på å gjøre.  Så tenker jeg at det kan være bra nok for nå.
@KurtStian

**Comment by terjesyl** [comment]
# Repo-oversikt

Forslag til topics å tagge repoer med:

- Frontend
- Backend
- Infra
- Høsting
- Registrering
- Bibliotek

Merk: noen repoer vil få flere topics (eks: Backend + Registrering)

Forslag til viktige repoer å trekke frem:

## Infra

|  Navn      |  Lenke | Type |  Merknad |
| ---------- | ------ | ---- | -------- |
| fdk-infra  |        |      |          |
| helm-chart |        |      |          |

## data.norge.no

## Frontend

|  Navn         |  Lenke                                                               | Type     |  Merknad                          |
| ------------- | -------------------------------------------------------------------- | -------- | --------------------------------- |
| fdk-frontend  | [GitHub ->](https://github.com/Informasjonsforvaltning/fdk-frontend) | Monorepo | Erstatter gradvis fdk-portal      |
| fdk-portal    | [GitHub ->](https://github.com/Informasjonsforvaltning/fdk-portal)   |          | Erstattes gradvis av fdk-frontend |
| fdk-admin-gui | [GitHub ->]()                                                        |          |                                   |

## Backend/Høsteløp

|  Navn                          |  Lenke | Type |  Merknad |
| ------------------------------ | ------ | ---- | -------- |
| fdk-concept-harvester          |        |      |          |
| fdk-dataset-harvester          |        |      |          |
| fdk-public-service-harvester   |        |      |          |
| fdk-informationmodel-harvester |        |      |          |
| fdk-dataservice-harvester      |        |      |          |
| fdk-sparql-service             |        |      |          |
| fdk-reference-data             |        |      |          |
| fdk-rdf-parser-service         |        |      |          |
| fdk-search-service             |        |      |          |

## Bibliotek

|  Navn          |  Lenke | Type |  Merknad |
| -------------- | ------ | ---- | -------- |
| fdk-rdf-parser |        |      |          |

## Registreringsløsning

## Frontend

|  Navn                   |  Lenke | Type |  Merknad |
| ----------------------- | ------ | ---- | -------- |
| catalog-frontend        |        |      |          |
| concept-catalog-gui     |        |      |          |
| dataset-catalog-gui-old |        |      |          |
| dataset-catalog-gui     |        |      |          |
| dataservice-catalog-gui |        |      |          |

## Backend

|  Navn               |  Lenke | Type |  Merknad |
| ------------------- | ------ | ---- | -------- |
| concept-catalog     |        |      |          |
| dataset-catalog     |        |      |          |
| dataservice-catalog |        |      |          |
| dataservice-catalog |        |      |          |

## Annet

I tillegg fins

- eget oppsett av mikrotjenester for vurdering av metadatakvalitet (MQA) som inngår i høsteløpet.
- Datalandsbyen (kjører på NodeBB)

## Se også

(TODO: pek til andre Sharepoint- og github.io-sider)

**Comment by terjesyl** [comment]
Oversikt er lagt ut i Sharepoint.
Har laget eget issue for å beskrive de prioriterte repoene i Informasjonsforvaltning-organisasjonen: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1006

Lukker denne saken etter avtale med @KurtStian
