### ISSUE TITLE
BUG: Relasjon til begrep fra datasettet Regnskapsregisteret og Partiregisteret feiler pga feil URI

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#891]
### Nåværende oppførsel

Er inne på datasettet med tittel "Regnskapsregisteret": https://data.norge.no/datasets/7c87f169-2520-4e56-ba2a-b7a3cc7de2e9

I datasettet er det relasjoner til en god del begreper. URI-en til disse begrepene går til feil adresse, eks. begrepet "regnskapsprinsipper" har URI https://fellesdatakatalog.brreg.no/api/concepts/d98b3fc3-884d-4ec6-9ad6-c411d221345b i datasettet, men skulle ha hatt URI https://data.norge.no/concepts/d98b3fc3-884d-4ec6-9ad6-c411d221345b
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/147aec02-1fd0-44dd-bddf-eda882fccf6e)
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/21d894d3-1b46-486b-9a43-1431c52452fa)
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/67958ebb-f7c8-4e6e-926e-c082d94f45be)

Tilsvarnde feil gjelder for datasettet "Partiregisteret": https://data.norge.no/datasets/a04b50eb-4233-4b92-9ef1-71b3aa82f2f6

### Forventet oppførsel
URI-ene til de respektive begrepene som brukes i portalen skal brukes i relasjonen slik at man har fått åpnet begrepbeskrivelsene i portalen.

**Comment by pooriamehregan** [comment]
Trenger ETL på relasjonene mellom begrepene til Brreg og ressurser i andre kataloger.

**Comment by valosnah** [comment]
Det er fortsatt total

**Comment by valosnah** [comment]
Gjenstående problematikk tas i https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/980
