### ISSUE TITLE
BUG: Relasjon til begrep fra datasettet Enhetsregisteret og Foretaksregisteret går ikke til portal

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#892]
### Nåværende oppførsel

Er inne på datasettet med tittel "Enhetsregisteret": https://data.norge.no/datasets/68d08f28-a16d-4fab-a953-ed4ab08ce2e2

Alle relasjonene til begrep som er lagt inn på datasettet bruker URI som går mot https://concepts.fellesdatakatalog.digdir.no/) i stedet for portalen https://data.norge.no/:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/f20e53b0-dcf9-45f5-b04e-d30bce308203)
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/ddbb82a5-5291-4d5d-aff4-0c012d4e9128)

Tilsvarende gjelder for datasettet "Foretaksregisteret": https://data.norge.no/datasets/ae335ad2-0f3d-4eb1-98ce-87882776a123

### Forventet oppførsel

Det skal brukes URI-ene som begrepene har i portalen slik at man har fått åpnet begrepbeskrivelsene i portalen (og som html).

Det er f.eks. i orden for datasettet "Smilefjestilsyn på serveringssteder": https://data.norge.no/datasets/288aa74c-e3d3-492e-9ede-e71503b3bfd9

**Comment by pooriamehregan** [comment]
Trenger ETL på relasjonene mellom begrepene til Brreg og ressurser i andre kataloger.
