### ISSUE TITLE
BUG: rapportene Behandlingsoversikt CSV og Protokoll CSV mangler data i demo- og produksjonsmiljøet

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#893]
## 🐛 Bug rapport
rapportene Behandlingsovrsikt CSV og Protokoll CSV mangler data i demo- og produksjonsmiljøet. Det står "undefined" i alle kolonner og rader i CSV-rapporter. 

Disse rapportene er viktige å kunne generere dersom virksomheter ønsker å ta data ut av Behandlingsoversikt på en maskinlesbar form. Rapportene vil være særdeles viktig å kunne gjennomføre dersom Behandlingsoversikt må avvikles

### Nåværende oppførsel
Eksempel fra rapport Behandlingsoversikt CSV for Direktoratet for forvandling og KTI i demo:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/32771488/3b57b668-29d4-44b5-97e3-64339cc84dcd)

Eksempel fra rapport Protokoll CSV for Direktoratet for forvandling og KTI i demo:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/32771488/6224b175-16e7-4f42-a7da-ab41c5306583)

Antall rader som vises i rapportene er imidlertid riktig.

### Forventet oppførsel
At verdier vises i celler der noe er utfylt i registreringsløsningen, og at felt som det ikke er registrert noe i, i registreringsløsningen er blanke

### Hvordan reprodusere?
Ved å generere rapporter på nytt

**Comment by KurtStian** [comment]
@jeffreiffers  Testet OK i staging. 
Alle utfylte felt kommer med og har data i behandlingsoversikt CSV. Og alle utfylte godkjente felt kommer med og har data i protokoll CSV. Dvs. jeg ser at det er avvik mellom html-visning av protokoll og CSV-visning (html viser mer informasjon knyttet til avsnittet "Felles behandlingsansvar"), men jeg antar at dette avviket er kjent. Og man får jo ut alle dataene når man henter ut dataene via behandlingsoversikt CSV.
