### ISSUE TITLE
BUG: Navn på en rekke organisasjoner er ikke oppdatert på siden "Alle kataloger i registreringsløsningen

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#894]
### Nåværende oppførsel

En rekke organisasjoner har fått endret navn, men det gamle navnet vises fortsatt på siden "Alle kataloger" i registreringsløsningen. Dette gjelder for:

| Organisasjonsnummer | Gammelt navn | Gjeldende navn |
| :---:  | :--- | :---  |
| 971 527 412 | Norsk kulturråd | Kulturdirektoratet |
| 977 161 630 | Olje- og energidepartementet | Engergidepartementet |
| 984 661 185 | Posten Norge AS | Posten Bring AS |
| 971 273 003 | KA Arbeidsgiverirganisasjon for kirkelig virksomheter | Hovedorganisasjonen KA |
| 974 761 122 | Statens legemiddelverk | Direktoratet for medisinske produkter |
| 972 417 858 | Kommunal- og moderniseringsdepartementet | Kommunal- og distriktsdepartementet |
| 972 417 866 | Kulturdepartementet | Kultur- og likestillingsdepartementet |
| 986 174 613 | Petroleumstilsynet | Havindustritilsynet |
| 921 693 230 | Viken fylkeskommune | Viken fylkeskommune under sletting fra 01.01.2024 |
| 915 933 149 | Direktoratet for e-helse | Direkotratet for e-helse meldt til opphør |

### Forventet oppførsel

Siden "Alle kataloger" skal inneholde oppdatert navn fra Enhetsregisteret.

### Forslag/Løsning [Valgfritt]

Oppdatere navn i MongoDB.

**Comment by NilsOveTen** [comment]
Er dette fortsatt et problem? Tjenesten prøver å oppdatere disse navnene automatisk minst en gang i måneden, det ser ut til å ha skjedd for disse eksemplene

**Comment by KurtStian** [comment]
@NilsOveTen 
Dette er fremdeles feil.
Eks.:
Katalogoversiktsiden
![image](https://github.com/user-attachments/assets/22def791-5602-4c8a-99ff-bdf17f4ce0fe)

Datasettkatalog for samme virksomhet:
![image](https://github.com/user-attachments/assets/d2ba71db-e513-40ca-9d2e-60f761b0c61c)

Nøkkelopplysninger fra ER:
![image](https://github.com/user-attachments/assets/de57def2-a2b0-4bdc-971d-48609d09edcf)

**Comment by NilsOveTen** [comment]
> @NilsOveTen Dette er fremdeles feil. 

Aha, ja. Det er spesifikkt i katalogoversikten. Dette er en gammel kjent feil. Navnet som vises i katalogoversikten til registrering er basert på navnet i katalogen i dataset-catalog. Har tidligere fiksa dette via oppdatering i databasen, men det er kanskje på tide å fikse det i koden?

@KurtStian Fikse dette i koden til [registration-portal](https://github.com/Informasjonsforvaltning/registration-portal) eller skal jeg få Hans Olav til å fikse det i databasen?

**Comment by KurtStian** [comment]
@NilsOveTen Det er best å fikse dette i koden ellers vil det stadig dukke opp slike. Å fikse det i databasen er nødløsningen.
Jeg antar at dette ikke er en stor jobb?
