### ISSUE TITLE
Manglande oversettinger av "Felles datakatalog" når språk settes til engelsk.

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#90]
(Opprinneleg rapportert av SSB i e-post.)
ref https://data.norge.no/dataservices/4c525f0a-f10d-3bcc-a67e-ee3fbbfd6ccc

Felles datatalog skal erstattes med The National Data Catalog når språk byttes til engelsk
StatBank Norway API from Statistics Norway (PxWebApi)
Data service description published in Felles datakatalog on 18.11.2020

**Comment by lillelars** [comment]
@stigbd Tenker du her også på logo eller på teksten "Published in Felles datakatalog" ?

**Comment by stigbd** [comment]
Tenker på teksten. Det burdet stått "Published in National Data Catalog" når visningsspråk er engelsk. (Logo er eit anna issue, slik eg ser det.)

**Comment by jeffreiffers** [comment]
Ser ut at denne er fikset allerede.
