### ISSUE TITLE
BUG: Felt som har kombinasjon med komma/bindestrek og "and" feiler

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#903]
### Nåværende oppførsel
Meldt av bruker:

«Jeg har lagt inn den engelske termen «Desserts excluding products covered in categories 1, 3 and 4»

Den feiler, og det som trigger feilen er «and». Jeg byttet den ut med «og», og da feilet det ikke. Det samme med komma eller bindestrek. »

Har testet og ser at denne feilen også gjelder for andre felt som f.eks. definisjon.

### Forventet oppførsel

Felt som har kombinasjon med komma/binnestrek og "and" må takles i feltene slik at det er mulig å ha engelske termer og definisjoner med en slik kombinasjon.

**Comment by jeffreiffers** [comment]
@KurtStian Kan ikke gjenskapes. Lukker saken.

**Comment by KurtStian** [comment]
Feilen oppstår i prod og ikke i staging.
Eksempel på feil i prod:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/8c1f9abb-f098-4982-bbaf-d4eae72dd7ea)

Ser at oppdateringen blir stoppet av cloud armor.

**Comment by jeffreiffers** [comment]
Kan du sjekke igjen. Skal være rettet.

**Comment by KurtStian** [comment]
Test OK i prod. Testet både med komma, binnestrek og "and", samt kombinasjoner av disse.
