### ISSUE TITLE
Engelsk institusjonsnavn for engelsk språk i FDK.

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#91]
(Opprinneleg inmeldt av SSB i e-post.)
Det hadde også vært fint å kunne registrere engelsk institusjonsnavn for engelsk versjon.

Ref https://data.norge.no/dataservices/4c525f0a-f10d-3bcc-a67e-ee3fbbfd6ccc

**Comment by lillelars** [comment]
@stigbd - kan ta dette med Lene først.

**Comment by stigbd** [comment]
Det er vel kun snakk om å hente evt engelsk namn frå organization-catalogue og vise dette i staden for det norske. Trenger ikkje design for dette.
