### ISSUE TITLE
DOC: Dokumentasjon av høsteløpet

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-issue-tracker#912]
## 📖 Dokumentasjon

**To do:**

- [ ] Oppdatere fdk/portal tegning m/nytt høsteløp
- [ ] Lage en tekstlig beskrivelse av høsteløpet (se det Terje sendte i chatten)
- [ ] Sjekk openAPI-spec for fdk-search-service, fdl-resource-service og fdk-parser-service

Ikke relatert til høsteløpet: (Lag egne issues på dette)
- [ ] Beskrivelse av AI-api'et (KI) + datasettbeskrivelse
- [ ] Flytt denne siden til FDK Wiki, og oppdater tekst og tegning https://informasjonsforvaltning.github.io/felles-datakatalog/metadatakvalitet/, oversett til engelsk

### Hvem er dokumentasjon for
[Team/Utviklere/Eksterne/Annet]

### Huskeliste for dokumentasjon
- Beskrivelse av tjeneste
  - Hvis relevant: Er det en utvidelse, forbedring eller ny løsning?
- Beskrivelse av API
- Bakgrunn for valg av teknologi
- Ev. arkitektur og hvordan løsningen inngår i nåværende arkitektur
- Ev. tegninger
- Ev. OpenAPI-spesifikasjon

**Comment by KjerstiSteien** [comment]
@NilsOveTen kan du se over om alt i denne saken er løst?

**Comment by NilsOveTen** [comment]
Er løst av dokumentasjonen som er lagt til her: https://informasjonsforvaltning.github.io/felles-datakatalog/harvesting/
