### ISSUE TITLE
Feature: Endre på viste ID-felt i begrepskatalog

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#913]
Skatteetaten ønsker å gjøre det enklere for deres brukere å kopiere den varige ID-en for begrepet (heretter kalt BegrepsID. Dette er for å unngå feil når man bruker ID-en til begrepet i Skatteetatens systemer, når man ikke ønsker å vise til en spesifikk versjon. 

I dag viser vi kun den spesifikke versjonens ID (heretter kalt VersjonsID på detaljsiden. Vi ønsker at begge ID-ene skal vises, og at BegrepsID skal være mer fremtrendende enn VersjonsID. 

Oppgaver: 
1: Endre Id-en som vises i høyre kolonne til den varige ID-en for begrepet og endre ledeteksten til Begreps-ID. 

![Image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/110605570/5726790b-15b5-4ec4-aeda-0a95dcdab1a2)

2: Legg til versjons-ID til hver versjon under fanen "Versjoner"

![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/110605570/2c95e3c1-9a06-4510-96fb-d0b7985b33fb)

**Comment by KjerstiSteien** [comment]
Avklaring etter møte med Skatt, Brreg og UDI: Vi ønsker ikke å ha den med i høyremargen foreløpig. Alle er enige om at det hadde vært fint, men brukerne skjønner ikke hva det er, eller hva som er forskjellen på det og begrepsid. Vi velger derfor å kun ha versjons-id under versjoner foreløpig. Og kun begreps-id i høyremargen.
