### ISSUE TITLE
Rydde i data: Flytte all info fra vår registreringsløsning fra "assosiativ relasjon - beskrivelse" til "assosiativ relasjon - relasjonsrolle"

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-issue-tracker#919]
- [ ] Legg til feltet `relationRole` i datamodell `BegrepRelasjon` i concept-catalog. 
- [ ] Bruk nytt `relationRole`-felt i produksjon av rdf for assosiativRelasjon isteden for gammel `beskrivelse`-felt. 
- [ ] concept-catalog-gui må oppdateres til å bruke nytt `relationRole`-felt isteden for gammelt `beskrivelse`-felt i registreringsskjemaet.
- [ ] ETL som trekker ut alt av assosiativRelasjon og flytter data gammel `beskrivelse`-felte til nye `relationRole`-felt.

**Comment by hegeaal** [comment]
Vurderer å ha et generisk tekstfelt knyttet til relasjonene, dette må diskuteres nærmere.

**Comment by KjerstiSteien** [comment]
Vi gjør ikke dette nå, men sparer diskusjonen til en større refaktorering av databasen til concept catalog.
