### ISSUE TITLE
BUG: flere tjeneste mangler tilbyder i trefflisten

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-issue-tracker#920]
## 🐛 Bug rapport
Flere tjenster og hendelser mangler tilbyder i trefflisten.  
Hypotese: Feil med mapping i fdk-search-service med tjenester som har competentAuthoroty. Mangler organization-data i responsen. 

![Uploading image.png…]()

**Comment by terjesyl** [comment]
Er en skrivefeil i Service-objektet i fdk-search-service: `hasCompetentAuthority`. Mulig at denne fører til at PublicService-instanser (som har competentAuthority) mangler organization-informasjonen.

**Comment by terjesyl** [comment]
Løst i new.staging
