### ISSUE TITLE
BUG: mediaType viser kode isteden for navn

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-issue-tracker#923]
## 🐛 Bug rapport
<img width="332" alt="image" src="https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/48259307/9ff4c773-2c98-4f4c-887e-cb1392bf3520">

Burdet stått bare f.eks. "json". 

Foreslått løsning:
Laste ned mediaType kodeliste fra reference-data.

**Comment by NilsOveTen** [comment]
Splitt code på / og bruk siste del av det som visningsnavn
