### ISSUE TITLE
BUG: Avvik på tekst på knytingen til Datalandbyen på detaljesiden

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#928]
### Nåværende oppførsel

New.staging mangler teksten: «Denne informasjonsmodellen er ikke omtalt i» samt «informasjonsmodellen». Se skjembilder:

new.staging
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/cc141211-1051-4357-b3aa-8151a41ec94e)

staging:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/3cbb41ad-259a-42ef-88ec-85bc953b09a0)

### Forventet oppførsel
Skal vises som for staging.

**Comment by KjerstiSteien** [comment]
Løses av https://github.com/Informasjonsforvaltning/fdk-portal/issues/2014
