### ISSUE TITLE
BUG: avvik mellom antall begrep for brreg i registreringsløsning og portal

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#931]
### Nåværende oppførsel
Antall publiserte begrep i Brønnøysundsregistrenes katalog i registreringsløsning: 510
Antall begrep med Brønnøysundsregistrene som eier i portal: 502

### Forventet oppførsel
Forventer samme tall. 

### Forslag/Løsning [Valgfritt]
Finn ut hvilke publiserte begrep som ikke vises i portal. 
Meld fra hvilke begrep det gjelder til Brønnøysundsregistrene, slik at de kan vurdere hva vi skal gjøre med begrepene.

**Comment by NilsOveTen** [comment]
Noen begrep hadde endt opp med samme fdk-id ila migreringa, som gjorde at disse ble overskrevet av hverandre i fdk. Fikk generert opp ny id for disse og alt ser nå ok ut i portal 👍
