### ISSUE TITLE
BUG: Det vises skolem-uri som spatial på GML-innhold på datasett

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#933]
### Nåværende oppførsel

Kartverket har flere datasett der de har lagt inn dct:spatial med GML-innhold, noe som ikke støttes av FDK (og heller ikke DCAT-AP-NO).
Dette vises i dag som skolem-uri på detaljesiden til datasettet i portalen.

Eksempel: https://data.norge.no/datasets/57b64f5d-7f6f-3eb1-bac3-5773cb078b4d

Html i portal:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/a56f8ef9-f617-4a55-80cc-4e336541c6e9)

Turtelfil i portal:
 dcterms:spatial "https://data.geonorge.no/administrativeEnheter/nasjon/id/173163";
 dcterms:spatial <https://kartkatalog.geonorge.no/Metadata/uuid/9c72cd67-3e71-426d-9914-f29a43dd28c4/.well-known/skolem/a56c106a-3535-37a9-915f-6131ffa44252>;

<https://kartkatalog.geonorge.no/Metadata/uuid/9c72cd67-3e71-426d-9914-f29a43dd28c4/.well-known/skolem/a56c106a-3535-37a9-915f-6131ffa44252>
        locn:geometry  "<gml:Envelope srsName=\"http://www.opengis.net/def/crs/OGC/1.3/CRS84\"><gml:lowerCorner>2,00 57,00</gml:lowerCorner><gml:upperCorner>33,00 72,00</gml:upperCorner></gml:Envelope>"^^<http://www.opengis.net/ont/geosparql#gmlLiteral> .

Fra fil til kartverket:
<dct:spatial>https://data.geonorge.no/administrativeEnheter/nasjon/id/173163</dct:spatial>
<dct:spatial parseType="Resource"><locn:geometry datatype="http://www.opengis.net/ont/geosparql#gmlLiteral"><![CDATA[<gml:Envelope srsName="http://www.opengis.net/def/crs/OGC/1.3/CRS84"><gml:lowerCorner>2,00 57,00</gml:lowerCorner><gml:upperCorner>33,00 72,00</gml:upperCorner></gml:Envelope>]]></locn:geometry></dct:spatial>

### Forventet oppførsel

I første omgang ikke vises noe i portalen da GML ikke er definet som lovlige vokabular i DCAT-AP-NO.

I neste omgang eventuelt vurdere om FDK skal støtte visning av GML selv om dette ikke inngår i DCAT-AP-NO.

**Comment by NilsOveTen** [comment]
Dette er et resultat av tre ting:
- Egenskapene kartverket bruker for å legge til gml er ikke noe vi støtter
- Vi viser uri som backup når vi ikke har noe annet og vise
- Vi skolemiserer alle blanke noder

Dette vil også bli et problem for alle andre blanke noder, så jeg løser dette nå ved å ignorere alle urier som inneholder `/.well-known/skolem/`

Hvis vi skal støtte gml fra locn:geometry så tar vi det i et annet feature-issue

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/fdk-rdf-parser/pull/316
