### ISSUE TITLE
BUG: Relasjonen seOgså vises ikke på detaljesiden i registreringsløsningen for begrep

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#935]
### Nåværende oppførsel

Relasjonen seOgså vises ikke på detaljesiden i registreringsløsningen for begrep. Relasjonen vises på data.norge.

Eks. fra data.norge:
https://data.norge.no/concepts/89e42702-a514-3cea-ac32-63500329be7c
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/1aad6540-9fdc-49f9-a8d9-a9bc53c6efa2)

Begrepet har ID 20b2e32f-9fe1-11e5-a9f8-e4115b280940 i registreringsløsningen.

### Forventet oppførsel

Relasjonen seOgså skal vises på detaljeside i registreringsløsningen for begrep når denne relasjonen er registrert.

**Comment by KjerstiSteien** [comment]
Oppdatering: Ser ut til å gjelde alle typer relasjoner. Se Høgskolen for it og arkitektur i demo. Begrepet test relasjon mellom begrep viser ingen begrep.

**Comment by NilsOveTen** [comment]
@jeffreiffers er dette kanskje at catalog-frontend fortsatt prøver å bruke fulltext?

**Comment by jeffreiffers** [comment]
Det ser sånn ut. Oppretter issue.
