### ISSUE TITLE
BUG: Relasjon til publisert begrep fra detaljsiden i registreringsløsning for begrep fører til error.

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#936]
### Nåværende oppførsel
For å beskrive feilen må relasjoner først vises på detaljsiden igjen. https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/935

**Comment by hegeaal** [comment]
@KjerstiSteien #935 er løst så er det mulig å beskrive feilen nå?

**Comment by KjerstiSteien** [comment]
Klarer ikke å gjenskape feilen. Regner denne som løst.
