### ISSUE TITLE
BUG: får ikke treff på begrep når jeg forsøker å legge til relasjoner i Demo

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#937]
### Nåværende oppførsel
Når jeg søker etter begrep å relatere til i demo, får jeg ikke treff på begrep, selv om de vises som publisert i på detaljsiden. 

### Forventet oppførsel
Forventer å få treff i egen katalog i tillegg til andres når jeg søker etter begrep å relatere til. 

### Hvordan reprodusere?
Logg inn som Stein Eidem i demo. 
Gå inn på et begrep. Søk opp Eplesyre eller test relasjon mellom begrep. Får ingen treff.

**Comment by hegeaal** [comment]
Jeg lurer på om dette egentlig bare er en design/frontend-bug. Når man trykker på relatert begrep så står det "no options", men dersom man begynner å skrive noe får man treff. Dette er kjent fra tidligere, mener det skal finnes et issue på det allerede. Var det dette du mente @KjerstiSteien ?


![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/48259307/3578255e-c390-4c89-a303-ce2937473e64)

![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/48259307/075aa351-be63-4546-ac79-2a864e634b7e)

![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/48259307/68e82757-7354-4aad-977d-e44711926819)

**Comment by hegeaal** [comment]
Ser ut til å kun være et problem for noen begreper. Mistenker at det har noe med ETL som ble utført når vi splittet status-felt fra publiserings-tilstand å gjøre. Virker som at det kun gjelder demo. @valosnah

**Comment by valosnah** [comment]
Observerte også at begrepet eplesyre ikke eksisterte i portalen.
Kikket på databasen i demo, og kunne ikke finne noe åpenbart galt der. 
Kjørte en forced harvest (høsteknappen i admin-grensesnittet), og da dukket begrepet opp i portalen, og det er også nå søkbart i relasjoner.

**Comment by valosnah** [comment]
Det kan være problemet kommer av endringer/publiseringer utført i løpet av en tidsperiode da vi utviklet den nye begrepskatalogen. Kan ikke helt utelukke at produksjon ikke har blitt berørt, og har for sikkerhets skyld kjørt en høsting av alle fdk-begrepskataloger i prod.

**Comment by jeffreiffers** [comment]
Testet og fungerer fint i demo. Lukker saken.
