### ISSUE TITLE
BUG: Opprettet-dato settes til dagens dato ved redigering av begrep

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#938]
### Nåværende oppførsel
Når jeg redigerer et publisert begrep endres opprettet-dato til dagens dato. 

### Forventet oppførsel
Forventer at datoen som vises for opprettet-dato viser til første gang begrepet ble opprettet, altså opprettet-dato for første versjon av begrepet. 

### Hvordan reprodusere?
Gå inn på et publisert begrep i begrepskatalogen.
Rediger begrepet
Sjekk opprettelsesdato.

**Comment by NilsOveTen** [comment]
Vil tro dette er backend som forholder seg til opprettelse-dato for revisjonen, burde være en enkel fiks. Men for å fikse for samtlige må vi kjøre en ETL-jobb. @valosnah Har du tid til å bli med og se på dette?

**Comment by valosnah** [comment]
ETL testet ok i staging
