### ISSUE TITLE
Håndtere ønsket oppførsel i fdk-portal

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-issue-tracker#945]
- [x] legge til transportportal.no i NAP_HOST (støtter commaseparert liste)
- [x] hoved siden blir mainPage istedenfor datasets
- [x] søk går til datasets istedenfor search-all
- [x] rydde opp i konfigurasjonslogikken
- [x] fjerne hvit border på headeren

**Comment by valosnah** [comment]
Oppdatert NAP_HOST
