### ISSUE TITLE
BUG: Monsido statistikk

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-issue-tracker#951]
### Nåværende oppførsel
Etter implementasjon av statistikksporing i Monsido, ble noen rader med teststatistikk igjen. Rader som er gyldige per nå har prefiksene `PROD-`, `DEMO-`, `STAG-`, and `LOCAL-`. andre rader skal fjernes.

### Forventet oppførsel
At det er kun en rad med PROD- under "Arrangementer" (venstre sidemeny etter at du har valgt fanen statistikk).

**Comment by KjerstiSteien** [comment]
Lukker denne, davi mister tilgang til Monsido i august.
