### ISSUE TITLE
BUG: relasjoner mellom begreper er knyttet til spesifikk versjon

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#955]
## 🐛 Bug rapport
Meldt inn av skatteetaten

### Nåværende oppførsel
Vi har oppdaget flere utfordringer knyttet til versjoner og relasjoner. Det virker som om relasjonene er knyttet til spesifikke versjoner av et begrep, noe som kan oppleves som klønete. For eksempel, når man ser på relasjonen mellom "anleggsmiddel" og "omløpsmiddel" og klikker på "omløpsmiddel", kan man ende opp med å se en tidligere versjon av dette begrepet. Dette kan virke forvirrende, spesielt når begrepet ikke er foreldet. Dette vil kreve masse forvaltning fra brukerne, som ikke er realistisk for oss. 

### Forventet oppførsel
Vi trenger at relasjonene peker til selve begrepet/begrepsidentifikator (typisk siste versjon), ikke en spesifikk versjon/versjonsidentifikator.

**Comment by NilsOveTen** [comment]
@KjerstiSteien dette er et resultat av at vi ikke har prioritert denne enda: https://github.com/Informasjonsforvaltning/concept-catalog/issues/316

Jeg starter på den

**Comment by NilsOveTen** [comment]
> @KjerstiSteien dette er et resultat av at vi ikke har prioritert denne enda: [Informasjonsforvaltning/concept-catalog#316](https://github.com/Informasjonsforvaltning/concept-catalog/issues/316)
> 
> Jeg starter på den

Rettelse: Dete er to forskjellige bugs som kan være årsaken til dette. Det kan enten være interne relasjoner som ikke flyttes, som jeg linka til. Eller så kan det være relasjoner som hentes fra FDK som deretter gjenkjennes som interne. Da vil den bruke id fra urien til å linke internt. Men den IDen er alltid id til første versjon av begrepet, lagde dette issuet i catalog-frontend: https://github.com/Informasjonsforvaltning/catalog-frontend/issues/685

**Comment by KjerstiSteien** [comment]
Testet i demo. 
Viser nå til nyeste publiserte versjon. Jeg melder tilbake til skatt at vi mener å ha løst problemet. Dersom de forventer at relasjon viser til nyeste versjon uavhengig av publisering, oppretter jeg ny sak. Mistenker at det vil kreve en lengre diskusjon.
