### ISSUE TITLE
BUG: virksomhetsside og organisasjonsside viser 0 ressurser for alle virksomheter

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#957]
### Nåværende oppførsel
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/110605570/8d8bf516-03b2-4eba-b140-678b31271ab5)

![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/110605570/0f551d07-75b0-4802-91c4-6c875a833af6)

### Forventet oppførsel
Forventer å se reelle tall. I overkant av 7000 datasett for kartverket. 

### Hvordan reprodusere?
https://data.norge.no/organizations
https://data.norge.no/organizations/971040238

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/fdk-nginx-sparql/pull/12
