### ISSUE TITLE
Problemer ved åpning av enkelte informasjonsmodeller

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-issue-tracker#96]
https://staging.fellesdatakatalog.digdir.no/informationmodels/5b15202c-ae33-35a5-aeaa-2692b9a75ec6

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/9d7c4124-4f12-4c4e-b57e-97a57577de9a)

I staging med chrome

**Comment by lillelars** [comment]
@shenluna er denne fortsatt et issue?

**Comment by shenluna** [comment]
Ikke lenger et issue, nå kommer man inn på siden uten problemer
