### ISSUE TITLE
BUG: Får ikke logget inn og kommentert på transportportal-datasett

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#961]
## 🐛 Bug rapport
Detaljsidene for datasett tillater ikke å logge inn for å skrive kommentarer

### Nåværende oppførsel
Tenker det har å gjøre med tillatte redirect-urier hos SSO
Hvis man trykker på logg inn, ender man opp her:
![bilde](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/8625716/66385173-660e-4f09-a668-6f2d17984685)

### Forventet oppførsel
Slik som den ordinære portalen mht datalandsby og kommentarfelt

### Hvordan reprodusere?
Gå inn på et vilkårlig transportportal-datasett og klikk på "Logg inn for å kommentere"

**Comment by NilsOveTen** [comment]
har oppdatert klienten i keycloak, fungerer nå
