### ISSUE TITLE
BUG: logout fungerer ikke alltid for next-applikasjoner

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-issue-tracker#962]
Merk at det kun gjelder hvis noen logger inn med en annen bruker fra samme nettleser kort tid etter at utlogging ble utført, ikke er inkognito og ikke har deaktivert cache fra devtools.

Feilen gjelder alle next-applikasjoner.

Hvordan reprodusere for begrepskatalogen:
1. Logg inn i registrering-portal: registrering.staging.fellesdatakatalog.digdir.no
2. Gå inn i begrepskatalogen: begrepskatalog.staging.fellesdatakatalog.digdir.no/{orgnr}
3. Gå tilbake til registrering-portal: registrering.staging.fellesdatakatalog.digdir.no
4. Logg ut
5. Logg inn med ny bruker
6. Åpne begrepskatalogen: begrepskatalog.staging.fellesdatakatalog.digdir.no/{orgnr}
7. Du er nå logget inn som den første brukeren

Dette gjelder fortsatt hvis steg 3 byttes ut med hvilken som helst annen applikasjon, også andre next-applikasjoner.
-> Hvis steg 3 byttes ut med hvilken som helst av disse så vil resultatet fortsatt være at du er innlogget med feil bruker i begrepskatalogen
> 3. Åpne registreringsskjema for begrepskatalogen: registrering-begrep.staging.fellesdatakatalog.digdir.no/{orgnr}/{begrep-id}

> 3. Åpne katalogadministrering: catalog-admin.staging.fellesdatakatalog.digdir.no/catalogs/{orgnr}

> 3. Åpne tjenestekatalogen: service-catalog.staging.fellesdatakatalog.digdir.no/catalogs/{orgnr}/services

**Comment by NilsOveTen** [comment]
All informasjon om sesjonene i next-applikasjonene holdes lokalt hos brukeren, burde være mulig å få next-applikasjonene i samme mono-repo til å bruke samme session-store eller at de klarer å invalidere session-store for de andre applikasjonene

**Comment by jeffreiffers** [comment]
Har forsøkt å bruke Frontchannel logout. Alle våre applikasjonene kan logges ut ved bruke av /api/auth/logout. Det ser ikke ut at Keycloak faktisk kaller urlen. Fant denne kommentaren på Github:

https://github.com/keycloak/keycloak/issues/25234
![bilde](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/430997/f94a3333-d766-4f14-b367-de15b60963d6)

**Comment by NilsOveTen** [comment]
> Har forsøkt å bruke Frontchannel logout. Alle våre applikasjonene kan logges ut ved bruke av /api/auth/logout. Det ser ikke ut at Keycloak faktisk kaller urlen. Fant denne kommentaren på Github:

Det ser ut til at de har merga en fix og at den er med på versjon 24.0.6, vi kjører 24.0.5 så er nok uproblematisk å oppgradere til 24.0.6 når den kommer 👍

Tror den er med i 25.0.1 som kom for en uke siden. Det er sannsynligvis også uproblematisk å oppgradere til den, men kanskje avvente til etter sommeren med en major-oppdatering?

**Comment by jeffreiffers** [comment]
Vi har gått for å polle Keycloak istedenfor. Dokumentasjon ligger i sharepoint.
