### ISSUE TITLE
BUG: Enkelte datasett har begrepsrelasjon som ikke lenger eksisterer

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#980]
## 🐛 Bug rapport
Enkelte datasett peker til begrepsrelasjoner som ikke lenger eksisterer, som fører til lenker som ikke virker under.

### Nåværende oppførsel
Eksempel:
https://data.norge.no/datasets/7c87f169-2520-4e56-ba2a-b7a3cc7de2e9
![bilde](https://github.com/user-attachments/assets/ba3375d9-614b-408e-93b0-9a4d8c6e7010)

### Forventet oppførsel
Alle lenker skal ta deg til detaljsiden for begrepet.

### Forslag/Løsning [Valgfritt]
Det aller enkleste er om eier av datasettet fikser på feltene i registreringsløsningen.

**Comment by KurtStian** [comment]
Har sendt til e-post til BR (Marit/Synne) og spurt om de kan få noen til å oppdatere datasettet.

**Comment by KurtStian** [comment]
BR (v/Synne) har oppdatert begrepsrelasjonene i datasettene Regnskapsregisteret og Løsøreregisteret slik at alle relasjoner til begrep for disse datasettene er nå OK.
