### ISSUE TITLE
BUG: Endringer i datasett som er blitt høstes vises ikke i portal

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-issue-tracker#990]
### Nåværende oppførsel

Gjelder datasett: https://data.norge.no/datasets/e4c67aa2-af5a-36c2-b5c2-96b571ddd850

Høsting feilet først pga. whitespace i URL. Etter oppdatering ble høsting gjenomført (jf. logg), men datasettet er ikke blitt oppdatert i portalen.

Eksempel på to URL-er som er oppdatert i reg.løsningen men som ikke er oppdatert i portal:
![image](https://github.com/user-attachments/assets/ca5e212b-e96b-4c83-a16c-8e9f63abdb35)

### Forventet oppførsel

Datasettet i portalen blir oppdatert med de nye endringene.

**Comment by jeffreiffers** [comment]
Dette var pga det var opprettet et Kafka skjema med samme id som medførte at meldingen ble ignorert. Har fjernet skjemaet.
