### ISSUE TITLE
BUG: Tema "Tilgangsnivå" er merket "Obligatorisk", men skal være merket "Anbefalt"

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/fdk-issue-tracker#996]
## 🐛Digdir forvalter "Standard for beskrivelse av datasett, datatjenester og datakataloger (DCAT-AP-NO)". Som forvalter av standarden bør vi sikre at Digdir sine løsninger eri henhold til standard. 
Tema "Tilgangsnivå" i datasettkatalogen i registreringsløsningen er merket "Obligatorisk", men har kravsnivå "Anbefalt" i DCAT-AP-NO, ref https://data.norge.no/specification/dcat-ap-no#Datasett-tilgangsniv%C3%A5

### Nåværende oppførsel
Tema Tilgangsnivå er merket "Obligatorisk". Dette gir brukeren inntrykk av at man må oppgi tilgangsnivå for å kunne få godkjent og publisert datasettbeskrivelser. Det er imidlertid mulig å godkjenne og publisere uten å ha fylt ut noe under Tilgangsnivå. At det er mulig å godkjenne uten at man har registrert noe under tilgangsnivå, kan vi ikke forvente at brukerne skal forstå. 

### Forventet oppførsel
Oppførsel skal være nåværende oppførsel. Funksjonalitet skal ikke endres. Det er kun merking som bør endres til "Anbefalt" slik som for øvrige tema som er merket "Anbefalt" om løsningen skal være i henhold til DCAT-AP-NO. 

### Hvordan reprodusere?
Ved å åpne datasettkatalogen og prøve å publisere en datasettbeskrivelse uten å registrere noe i tilgangsnivå, får man både sett merking og sjekket om det er mulig å godkjenne og publisere uten å ha registrert noe under tilgangsnivå

### Forslag/Løsning [Valgfritt]
Bytte merking "Obligatorisk" med "Anbefalt" og fjerne symbol med trekantskilt utropstegn.

**Comment by KjerstiSteien** [comment]
Dette vil løses som del av flytting av skjema til ny løsning. Lukker derfor denne saken.
